// Training data for Baby category
// Consolidated from babyChildToys.ts and babybaby.ts
// Singapore-specific baby and child products

export const babyTrainingData = [
  // Baby feeding
  { text: 'baby formula', label: 'baby' },
  { text: 'infant formula', label: 'baby' },
  { text: 'milk powder', label: 'baby' },
  { text: 'baby milk', label: 'baby' },
  { text: 'follow on milk', label: 'baby' },
  { text: 'toddler milk', label: 'baby' },
  { text: 'growing up milk', label: 'baby' },
  { text: 'baby cereal', label: 'baby' },
  { text: 'baby food', label: 'baby' },
  { text: 'baby puree', label: 'baby' },
  { text: 'baby porridge', label: 'baby' },
  { text: 'baby snacks', label: 'baby' },
  { text: 'baby biscuits', label: 'baby' },
  { text: 'teething biscuits', label: 'baby' },
  { text: 'baby crackers', label: 'baby' },
  { text: 'baby juice', label: 'baby' },
  { text: 'baby water', label: 'baby' },
  { text: 'baby drinks', label: 'baby' },
  { text: 'organic baby food', label: 'baby' },
  { text: 'stage 1 baby food', label: 'baby' },
  { text: 'stage 2 baby food', label: 'baby' },
  { text: 'stage 3 baby food', label: 'baby' },

  // Baby bottles and feeding accessories
  { text: 'baby bottles', label: 'baby' },
  { text: 'baby bottle', label: 'baby' },
  { text: 'feeding bottles', label: 'baby' },
  { text: 'milk bottles', label: 'baby' },
  { text: 'bottle nipples', label: 'baby' },
  { text: 'bottle teats', label: 'baby' },
  { text: 'sippy cups', label: 'baby' },
  { text: 'sippy cup', label: 'baby' },
  { text: 'training cups', label: 'baby' },
  { text: 'baby cups', label: 'baby' },
  { text: 'baby spoons', label: 'baby' },
  { text: 'baby spoon', label: 'baby' },
  { text: 'baby forks', label: 'baby' },
  { text: 'baby bowls', label: 'baby' },
  { text: 'baby bowl', label: 'baby' },
  { text: 'baby plates', label: 'baby' },
  { text: 'baby utensils', label: 'baby' },
  { text: 'high chair', label: 'baby' },
  { text: 'booster seat', label: 'baby' },
  { text: 'baby chair', label: 'baby' },
  { text: 'feeding chair', label: 'baby' },
  { text: 'bottle warmer', label: 'baby' },
  { text: 'bottle sterilizer', label: 'baby' },
  { text: 'sterilizer', label: 'baby' },
  { text: 'baby food maker', label: 'baby' },
  { text: 'baby blender', label: 'baby' },
  { text: 'bib', label: 'baby' },
  { text: 'feeding bib', label: 'baby' },
  { text: 'breast pump', label: 'baby' },
  { text: 'nursing pads', label: 'baby' },

  // Baby care and hygiene
  { text: 'baby diapers', label: 'baby' },
  { text: 'diapers', label: 'baby' },
  { text: 'nappies', label: 'baby' },
  { text: 'newborn diapers', label: 'baby' },
  { text: 'disposable diapers', label: 'baby' },
  { text: 'cloth diapers', label: 'baby' },
  { text: 'diaper inserts', label: 'baby' },
  { text: 'diaper covers', label: 'baby' },
  { text: 'training pants', label: 'baby' },
  { text: 'pull ups', label: 'baby' },
  { text: 'baby wipes', label: 'baby' },
  { text: 'wet wipes', label: 'baby' },
  { text: 'diaper cream', label: 'baby' },
  { text: 'diaper rash cream', label: 'baby' },
  { text: 'baby powder', label: 'baby' },
  { text: 'baby oil', label: 'baby' },
  { text: 'baby lotion', label: 'baby' },
  { text: 'baby shampoo', label: 'baby' },
  { text: 'baby soap', label: 'baby' },
  { text: 'baby wash', label: 'baby' },
  { text: 'baby bath', label: 'baby' },
  { text: 'baby bubble bath', label: 'baby' },
  { text: 'baby moisturizer', label: 'baby' },
  { text: 'baby sunscreen', label: 'baby' },
  { text: 'baby toothpaste', label: 'baby' },
  { text: 'baby toothbrush', label: 'baby' },
  { text: 'baby towel', label: 'baby' },
  { text: 'baby washcloth', label: 'baby' },
  { text: 'changing mat', label: 'baby' },
  { text: 'baby thermometer', label: 'baby' },
  { text: 'nasal aspirator', label: 'baby' },
  { text: 'baby nail clipper', label: 'baby' },
  { text: 'baby brush', label: 'baby' },

  // Baby clothing
  { text: 'baby clothes', label: 'baby' },
  { text: 'baby clothing', label: 'baby' },
  { text: 'baby romper', label: 'baby' },
  { text: 'romper', label: 'baby' },
  { text: 'baby onesie', label: 'baby' },
  { text: 'onesie', label: 'baby' },
  { text: 'baby bodysuit', label: 'baby' },
  { text: 'baby sleepsuit', label: 'baby' },
  { text: 'baby pajamas', label: 'baby' },
  { text: 'baby sleepwear', label: 'baby' },
  { text: 'baby shirt', label: 'baby' },
  { text: 'baby pants', label: 'baby' },
  { text: 'baby shorts', label: 'baby' },
  { text: 'baby dress', label: 'baby' },
  { text: 'baby skirt', label: 'baby' },
  { text: 'baby jacket', label: 'baby' },
  { text: 'baby sweater', label: 'baby' },
  { text: 'baby cardigan', label: 'baby' },
  { text: 'baby hat', label: 'baby' },
  { text: 'baby cap', label: 'baby' },
  { text: 'baby socks', label: 'baby' },
  { text: 'baby shoes', label: 'baby' },
  { text: 'baby booties', label: 'baby' },
  { text: 'baby mittens', label: 'baby' },
  { text: 'baby gloves', label: 'baby' },
  { text: 'baby blanket', label: 'baby' },
  { text: 'swaddle', label: 'baby' },
  { text: 'sleep sack', label: 'baby' },

  // Baby gear and furniture
  { text: 'baby stroller', label: 'baby' },
  { text: 'stroller', label: 'baby' },
  { text: 'pram', label: 'baby' },
  { text: 'pushchair', label: 'baby' },
  { text: 'baby carrier', label: 'baby' },
  { text: 'baby sling', label: 'baby' },
  { text: 'baby wrap', label: 'baby' },
  { text: 'car seat', label: 'baby' },
  { text: 'baby car seat', label: 'baby' },
  { text: 'infant car seat', label: 'baby' },
  { text: 'convertible car seat', label: 'baby' },
  { text: 'booster car seat', label: 'baby' },
  { text: 'baby crib', label: 'baby' },
  { text: 'baby cot', label: 'baby' },
  { text: 'crib', label: 'baby' },
  { text: 'baby bed', label: 'baby' },
  { text: 'bassinet', label: 'baby' },
  { text: 'moses basket', label: 'baby' },
  { text: 'baby mattress', label: 'baby' },
  { text: 'crib mattress', label: 'baby' },
  { text: 'baby bedding', label: 'baby' },
  { text: 'crib sheets', label: 'baby' },
  { text: 'baby pillow', label: 'baby' },
  { text: 'changing table', label: 'baby' },
  { text: 'baby monitor', label: 'baby' },
  { text: 'video monitor', label: 'baby' },
  { text: 'audio monitor', label: 'baby' },
  { text: 'night light', label: 'baby' },

  // Baby safety
  { text: 'baby gate', label: 'baby' },
  { text: 'safety gate', label: 'baby' },
  { text: 'baby fence', label: 'baby' },
  { text: 'playpen', label: 'baby' },
  { text: 'baby playpen', label: 'baby' },
  { text: 'play yard', label: 'baby' },
  { text: 'baby swing', label: 'baby' },
  { text: 'baby rocker', label: 'baby' },
  { text: 'bouncer', label: 'baby' },
  { text: 'baby bouncer', label: 'baby' },
  { text: 'jumper', label: 'baby' },
  { text: 'baby jumper', label: 'baby' },
  { text: 'walker', label: 'baby' },
  { text: 'baby walker', label: 'baby' },
  { text: 'baby safety', label: 'baby' },
  { text: 'child safety', label: 'baby' },
  { text: 'safety locks', label: 'baby' },
  { text: 'cabinet locks', label: 'baby' },
  { text: 'drawer locks', label: 'baby' },
  { text: 'door knob covers', label: 'baby' },
  { text: 'outlet covers', label: 'baby' },
  { text: 'plug covers', label: 'baby' },
  { text: 'corner guards', label: 'baby' },
  { text: 'edge guards', label: 'baby' },
  { text: 'table corner protectors', label: 'baby' },
  { text: 'toilet locks', label: 'baby' },
  { text: 'toilet lock', label: 'baby' },
  { text: 'refrigerator locks', label: 'baby' },
  { text: 'oven locks', label: 'baby' },
  { text: 'stove knob covers', label: 'baby' },
  { text: 'window guards', label: 'baby' },
  { text: 'window stops', label: 'baby' },
  { text: 'blind cord wraps', label: 'baby' },
  { text: 'door knob locks', label: 'baby' },
  { text: 'sliding door locks', label: 'baby' },
  { text: 'appliance locks', label: 'baby' },
  { text: 'safety harness', label: 'baby' },

  // Baby toys and entertainment
  { text: 'baby toys', label: 'baby' },
  { text: 'infant toys', label: 'baby' },
  { text: 'newborn toys', label: 'baby' },
  { text: 'soft toys', label: 'baby' },
  { text: 'soft toy', label: 'baby' },
  { text: 'plush toys', label: 'baby' },
  { text: 'stuffed animals', label: 'baby' },
  { text: 'stuffed animal', label: 'baby' },
  { text: 'teddy bear', label: 'baby' },
  { text: 'baby doll', label: 'baby' },
  { text: 'rattle', label: 'baby' },
  { text: 'baby rattle', label: 'baby' },
  { text: 'shaker toy', label: 'baby' },
  { text: 'musical toy', label: 'baby' },
  { text: 'music box', label: 'baby' },
  { text: 'mobile', label: 'baby' },
  { text: 'crib mobile', label: 'baby' },
  { text: 'activity gym', label: 'baby' },
  { text: 'play gym', label: 'baby' },
  { text: 'play mat', label: 'baby' },
  { text: 'activity mat', label: 'baby' },
  { text: 'tummy time mat', label: 'baby' },
  { text: 'sensory toy', label: 'baby' },
  { text: 'textured toy', label: 'baby' },
  { text: 'crinkle toy', label: 'baby' },
  { text: 'squeaky toy', label: 'baby' },
  { text: 'pacifier', label: 'baby' },
  { text: 'dummy', label: 'baby' },
  { text: 'soother', label: 'baby' },
  { text: 'teether', label: 'baby' },
  { text: 'teething ring', label: 'baby' },
  { text: 'teething toy', label: 'baby' },
  { text: 'stacking toy', label: 'baby' },
  { text: 'shape sorter', label: 'baby' },
  { text: 'baby blocks', label: 'baby' },
  { text: 'push toy', label: 'baby' },
  { text: 'ride on toy', label: 'baby' },

  // Bath toys
  { text: 'bath toys', label: 'baby' },
  { text: 'rubber duck', label: 'baby' },
  { text: 'bath book', label: 'baby' },
  { text: 'floating toys', label: 'baby' },
  { text: 'water toys', label: 'baby' },

  // Educational toys
  { text: 'educational toys', label: 'baby' },
  { text: 'learning toys', label: 'baby' },
  { text: 'alphabet toys', label: 'baby' },
  { text: 'number toys', label: 'baby' },
  { text: 'counting toys', label: 'baby' },
  { text: 'stacking toys', label: 'baby' },
  { text: 'nesting toys', label: 'baby' },
  { text: 'building blocks', label: 'baby' },
  { text: 'wooden blocks', label: 'baby' },
  { text: 'soft blocks', label: 'baby' },
  { text: 'foam blocks', label: 'baby' },
  { text: 'puzzle', label: 'baby' },
  { text: 'jigsaw puzzle', label: 'baby' },
  { text: 'wooden puzzle', label: 'baby' },
  { text: 'floor puzzle', label: 'baby' },
  { text: 'chunky puzzle', label: 'baby' },
  { text: 'peg puzzle', label: 'baby' },
  { text: 'magnetic toys', label: 'baby' },
  { text: 'magnetic letters', label: 'baby' },
  { text: 'magnetic numbers', label: 'baby' },
  { text: 'flash cards', label: 'baby' },
  { text: 'picture cards', label: 'baby' },
  { text: 'memory game', label: 'baby' },
  { text: 'matching game', label: 'baby' },

  // Books
  { text: 'baby books', label: 'baby' },
  { text: 'baby book', label: 'baby' },
  { text: 'board books', label: 'baby' },
  { text: 'picture books', label: 'baby' },
  { text: 'cloth books', label: 'baby' },
  { text: 'soft books', label: 'baby' },
  { text: 'touch and feel books', label: 'baby' },
  { text: 'interactive books', label: 'baby' },
  { text: 'sound books', label: 'baby' },
  { text: 'musical books', label: 'baby' },
  { text: 'pop up books', label: 'baby' },
  { text: 'lift the flap books', label: 'baby' },
  { text: 'bedtime stories', label: 'baby' },
  { text: 'nursery rhymes', label: 'baby' },
  { text: 'fairy tales', label: 'baby' },
  { text: 'children books', label: 'baby' },
  { text: 'story books', label: 'baby' },
  { text: 'reading books', label: 'baby' },
  { text: 'learning books', label: 'baby' },
  { text: 'activity books', label: 'baby' },
  { text: 'coloring books', label: 'baby' },
  { text: 'sticker books', label: 'baby' },

    // Toys and games
  { text: 'lego', label: 'baby' },
  { text: 'lego blocks', label: 'baby' },
  { text: 'lego sets', label: 'baby' },
  { text: 'building blocks', label: 'baby' },
  { text: 'duplo', label: 'baby' },
  { text: 'playmobil', label: 'baby' },
  { text: 'action figures', label: 'baby' },
  { text: 'dolls', label: 'baby' },
  { text: 'barbie', label: 'baby' },
  { text: 'barbie doll', label: 'baby' },
  { text: 'toy cars', label: 'baby' },
  { text: 'hot wheels', label: 'baby' },
  { text: 'matchbox cars', label: 'baby' },
  { text: 'remote control car', label: 'baby' },
  { text: 'rc car', label: 'baby' },
  { text: 'toy train', label: 'baby' },
  { text: 'train set', label: 'baby' },
  { text: 'thomas the tank engine', label: 'baby' },
  { text: 'puzzle', label: 'baby' },
  { text: 'jigsaw puzzle', label: 'baby' },
  { text: 'board games', label: 'baby' },
  { text: 'card games', label: 'baby' },
  { text: 'monopoly', label: 'baby' },
  { text: 'scrabble', label: 'baby' },
  { text: 'uno', label: 'baby' },
  { text: 'chess', label: 'baby' },
  { text: 'checkers', label: 'baby' },
  { text: 'connect four', label: 'baby' },
  { text: 'jenga', label: 'baby' },
  { text: 'twister', label: 'baby' },
  { text: 'pictionary', label: 'baby' },
  { text: 'charades', label: 'baby' },
  { text: 'video games', label: 'baby' },
  { text: 'nintendo', label: 'baby' },
  { text: 'nintendo switch', label: 'baby' },
  { text: 'playstation', label: 'baby' },
  { text: 'xbox', label: 'baby' },
  { text: 'gaming console', label: 'baby' },
  { text: 'handheld games', label: 'baby' },
  { text: 'electronic games', label: 'baby' },
  { text: 'educational games', label: 'baby' },
  { text: 'learning games', label: 'baby' },
  { text: 'memory games', label: 'baby' },
  { text: 'brain games', label: 'baby' },
  { text: 'strategy games', label: 'baby' },
  { text: 'role playing games', label: 'baby' },
  { text: 'fantasy games', label: 'baby' },
  { text: 'adventure games', label: 'baby' },
  { text: 'simulation games', label: 'baby' },
  { text: 'racing games', label: 'baby' },
  { text: 'sports games', label: 'baby' },
  { text: 'fighting games', label: 'baby' },
  { text: 'shooting games', label: 'baby' },
  { text: 'puzzle games', label: 'baby' },
  { text: 'arcade games', label: 'baby' },
  { text: 'retro games', label: 'baby' },
  { text: 'classic games', label: 'baby' },
  { text: 'party games', label: 'baby' },
  { text: 'family games', label: 'baby' },
  { text: 'cooperative games', label: 'baby' },
  { text: 'competitive games', label: 'baby' },
  { text: 'outdoor games', label: 'baby' },
  { text: 'indoor games', label: 'baby' },
  { text: 'travel games', label: 'baby' },
  { text: 'portable games', label: 'baby' },
  { text: 'magnetic games', label: 'baby' },
  { text: 'wooden games', label: 'baby' },
  { text: 'plastic games', label: 'baby' },
  { text: 'electronic toys', label: 'baby' },
  { text: 'interactive toys', label: 'baby' },
  { text: 'talking toys', label: 'baby' },
  { text: 'musical toys', label: 'baby' },
  { text: 'light up toys', label: 'baby' },
  { text: 'sound toys', label: 'baby' },
  { text: 'motion toys', label: 'baby' },
  { text: 'robotic toys', label: 'baby' },
  { text: 'programmable toys', label: 'baby' },
  { text: 'coding toys', label: 'baby' },
  { text: 'stem toys', label: 'baby' },
  { text: 'science toys', label: 'baby' },
  { text: 'chemistry set', label: 'baby' },
  { text: 'microscope', label: 'baby' },
  { text: 'telescope', label: 'baby' },
  { text: 'binoculars', label: 'baby' },
  { text: 'magnifying glass', label: 'baby' },
  { text: 'experiment kit', label: 'baby' },
  { text: 'lab kit', label: 'baby' },
  { text: 'discovery kit', label: 'baby' },
  { text: 'exploration kit', label: 'baby' },
  { text: 'nature kit', label: 'baby' },
  { text: 'bug catching kit', label: 'baby' },
  { text: 'fossil kit', label: 'baby' },
  { text: 'rock collection', label: 'baby' },
  { text: 'mineral kit', label: 'baby' },
  { text: 'crystal growing kit', label: 'baby' },
  { text: 'volcano kit', label: 'baby' },
  { text: 'solar system model', label: 'baby' }
];

export default babyTrainingData;