export const babyChildToysData = [
  { text: 'baby formula', label: 'Baby, Child & Toys' },
  { text: 'infant formula', label: 'Baby, Child & Toys' },
  { text: 'baby food', label: 'Baby, Child & Toys' },
  { text: 'baby cereal', label: 'Baby, Child & Toys' },
  { text: 'baby puree', label: 'Baby, Child & Toys' },
  { text: 'baby snacks', label: 'Baby, Child & Toys' },
  { text: 'teething biscuits', label: 'Baby, Child & Toys' },
  { text: 'baby bottle', label: 'Baby, Child & Toys' },
  { text: 'sippy cup', label: 'Baby, Child & Toys' },
  { text: 'baby spoon', label: 'Baby, Child & Toys' },
  { text: 'baby fork', label: 'Baby, Child & Toys' },
  { text: 'high chair', label: 'Baby, Child & Toys' },
  { text: 'booster seat', label: 'Baby, Child & Toys' },
  { text: 'baby bib', label: 'Baby, Child & Toys' },
  { text: 'burp cloth', label: 'Baby, Child & Toys' },
  { text: 'diapers', label: 'Baby, Child & Toys' },
  { text: 'nappies', label: 'Baby, Child & Toys' },
  { text: 'baby wipes', label: 'Baby, Child & Toys' },
  { text: 'diaper cream', label: 'Baby, Child & Toys' },
  { text: 'baby powder', label: 'Baby, Child & Toys' },
  { text: 'baby lotion', label: 'Baby, Child & Toys' },
  { text: 'baby shampoo', label: 'Baby, Child & Toys' },
  { text: 'baby soap', label: 'Baby, Child & Toys' },
  { text: 'baby oil', label: 'Baby, Child & Toys' },
  { text: 'pacifier', label: 'Baby, Child & Toys' },
  { text: 'dummy', label: 'Baby, Child & Toys' },
  { text: 'teether', label: 'Baby, Child & Toys' },
  { text: 'rattle', label: 'Baby, Child & Toys' },
  { text: 'baby toy', label: 'Baby, Child & Toys' },
  { text: 'stuffed animal', label: 'Baby, Child & Toys' },
  { text: 'plush toy', label: 'Baby, Child & Toys' },
  { text: 'teddy bear', label: 'Baby, Child & Toys' },
  { text: 'doll', label: 'Baby, Child & Toys' },
  { text: 'action figure', label: 'Baby, Child & Toys' },
  { text: 'toy car', label: 'Baby, Child & Toys' },
  { text: 'toy truck', label: 'Baby, Child & Toys' },
  { text: 'toy train', label: 'Baby, Child & Toys' },
  { text: 'toy plane', label: 'Baby, Child & Toys' },
  { text: 'building blocks', label: 'Baby, Child & Toys' },
  { text: 'lego', label: 'Baby, Child & Toys' },
  { text: 'puzzle', label: 'Baby, Child & Toys' },
  { text: 'board game', label: 'Baby, Child & Toys' },
  { text: 'card game', label: 'Baby, Child & Toys' },
  { text: 'educational toy', label: 'Baby, Child & Toys' },
  { text: 'learning toy', label: 'Baby, Child & Toys' },
  { text: 'musical toy', label: 'Baby, Child & Toys' },
  { text: 'toy piano', label: 'Baby, Child & Toys' },
  { text: 'toy guitar', label: 'Baby, Child & Toys' },
  { text: 'toy drum', label: 'Baby, Child & Toys' },
  { text: 'art supplies', label: 'Baby, Child & Toys' },
  { text: 'crayons', label: 'Baby, Child & Toys' },
  { text: 'colored pencils', label: 'Baby, Child & Toys' },
  { text: 'markers', label: 'Baby, Child & Toys' },
  { text: 'paint set', label: 'Baby, Child & Toys' },
  { text: 'coloring book', label: 'Baby, Child & Toys' },
  { text: 'sticker book', label: 'Baby, Child & Toys' },
  { text: 'activity book', label: 'Baby, Child & Toys' },
  { text: 'picture book', label: 'Baby, Child & Toys' },
  { text: 'story book', label: 'Baby, Child & Toys' },
  { text: 'children book', label: 'Baby, Child & Toys' },
  { text: 'baby book', label: 'Baby, Child & Toys' },
  { text: 'nursery rhyme book', label: 'Baby, Child & Toys' },
  { text: 'baby clothes', label: 'Baby, Child & Toys' },
  { text: 'baby onesie', label: 'Baby, Child & Toys' },
  { text: 'baby romper', label: 'Baby, Child & Toys' },
  { text: 'baby sleeper', label: 'Baby, Child & Toys' },
  { text: 'baby pajamas', label: 'Baby, Child & Toys' },
  { text: 'baby socks', label: 'Baby, Child & Toys' },
  { text: 'baby shoes', label: 'Baby, Child & Toys' },
  { text: 'baby hat', label: 'Baby, Child & Toys' },
  { text: 'baby mittens', label: 'Baby, Child & Toys' },
  { text: 'baby blanket', label: 'Baby, Child & Toys' },
  { text: 'swaddle', label: 'Baby, Child & Toys' },
  { text: 'baby towel', label: 'Baby, Child & Toys' },
  { text: 'baby washcloth', label: 'Baby, Child & Toys' },
  { text: 'baby carrier', label: 'Baby, Child & Toys' },
  { text: 'baby sling', label: 'Baby, Child & Toys' },
  { text: 'stroller', label: 'Baby, Child & Toys' },
  { text: 'pram', label: 'Baby, Child & Toys' },
  { text: 'car seat', label: 'Baby, Child & Toys' },
  { text: 'baby gate', label: 'Baby, Child & Toys' },
  { text: 'baby monitor', label: 'Baby, Child & Toys' },
  { text: 'night light', label: 'Baby, Child & Toys' },
  { text: 'mobile', label: 'Baby, Child & Toys' },
  { text: 'play mat', label: 'Baby, Child & Toys' },
  { text: 'activity mat', label: 'Baby, Child & Toys' },
  { text: 'bouncer', label: 'Baby, Child & Toys' },
  { text: 'swing', label: 'Baby, Child & Toys' },
  { text: 'walker', label: 'Baby, Child & Toys' },
  { text: 'jumper', label: 'Baby, Child & Toys' },
  { text: 'playpen', label: 'Baby, Child & Toys' },
  { text: 'crib', label: 'Baby, Child & Toys' },
  { text: 'bassinet', label: 'Baby, Child & Toys' },
  { text: 'changing pad', label: 'Baby, Child & Toys' },
  { text: 'diaper bag', label: 'Baby, Child & Toys' },
  { text: 'baby thermometer', label: 'Baby, Child & Toys' },
  { text: 'baby nail clippers', label: 'Baby, Child & Toys' },
  { text: 'baby brush', label: 'Baby, Child & Toys' },
  { text: 'baby comb', label: 'Baby, Child & Toys' },
  { text: 'baby toothbrush', label: 'Baby, Child & Toys' },
  { text: 'training pants', label: 'Baby, Child & Toys' },
  { text: 'potty', label: 'Baby, Child & Toys' },
  { text: 'toilet seat', label: 'Baby, Child & Toys' },
  { text: 'step stool', label: 'Baby, Child & Toys' },
  { text: 'child safety lock', label: 'Baby, Child & Toys' },
  { text: 'outlet cover', label: 'Baby, Child & Toys' },
  { text: 'corner guard', label: 'Baby, Child & Toys' },
  { text: 'toy robot', label: 'Baby, Child & Toys' },
  { text: 'remote control car', label: 'Baby, Child & Toys' },
  { text: 'toy helicopter', label: 'Baby, Child & Toys' },
  { text: 'toy boat', label: 'Baby, Child & Toys' },
  { text: 'toy dinosaur', label: 'Baby, Child & Toys' },
  { text: 'toy kitchen', label: 'Baby, Child & Toys' },
  { text: 'play food', label: 'Baby, Child & Toys' },
  { text: 'toy tools', label: 'Baby, Child & Toys' },
  { text: 'doctor kit', label: 'Baby, Child & Toys' },
  { text: 'dress up clothes', label: 'Baby, Child & Toys' },
  { text: 'costume', label: 'Baby, Child & Toys' },
  { text: 'superhero cape', label: 'Baby, Child & Toys' },
  { text: 'princess dress', label: 'Baby, Child & Toys' },
  { text: 'toy sword', label: 'Baby, Child & Toys' },
  { text: 'toy shield', label: 'Baby, Child & Toys' },
  { text: 'water gun', label: 'Baby, Child & Toys' },
  { text: 'bubble maker', label: 'Baby, Child & Toys' },
  { text: 'sandbox toys', label: 'Baby, Child & Toys' },
  { text: 'beach toys', label: 'Baby, Child & Toys' },
  { text: 'sand bucket', label: 'Baby, Child & Toys' },
  { text: 'sand shovel', label: 'Baby, Child & Toys' },
  { text: 'kite', label: 'Baby, Child & Toys' },
  { text: 'frisbee', label: 'Baby, Child & Toys' },
  { text: 'jump rope', label: 'Baby, Child & Toys' },
  { text: 'hula hoop', label: 'Baby, Child & Toys' },
  { text: 'yo-yo', label: 'Baby, Child & Toys' },
  { text: 'spinning top', label: 'Baby, Child & Toys' },
  { text: 'kaleidoscope', label: 'Baby, Child & Toys' },
  { text: 'magic 8 ball', label: 'Baby, Child & Toys' },
  { text: 'slinky', label: 'Baby, Child & Toys' },
  { text: 'rubiks cube', label: 'Baby, Child & Toys' },
  { text: 'fidget spinner', label: 'Baby, Child & Toys' },
  { text: 'stress ball', label: 'Baby, Child & Toys' },
  { text: 'slime', label: 'Baby, Child & Toys' },
  { text: 'play dough', label: 'Baby, Child & Toys' },
  { text: 'modeling clay', label: 'Baby, Child & Toys' },
  { text: 'finger paints', label: 'Baby, Child & Toys' },
  { text: 'sidewalk chalk', label: 'Baby, Child & Toys' },
  { text: 'stickers', label: 'Baby, Child & Toys' },
  { text: 'temporary tattoos', label: 'Baby, Child & Toys' },
  { text: 'trading cards', label: 'Baby, Child & Toys' },
  { text: 'pokemon cards', label: 'Baby, Child & Toys' },
  { text: 'magic tricks', label: 'Baby, Child & Toys' },
  { text: 'science kit', label: 'Baby, Child & Toys' },
  { text: 'chemistry set', label: 'Baby, Child & Toys' },
  { text: 'microscope', label: 'Baby, Child & Toys' },
  { text: 'telescope', label: 'Baby, Child & Toys' },
  { text: 'binoculars', label: 'Baby, Child & Toys' },
  { text: 'magnifying glass', label: 'Baby, Child & Toys' },
  { text: 'compass', label: 'Baby, Child & Toys' },
  { text: 'walkie talkie', label: 'Baby, Child & Toys' },
  { text: 'toy phone', label: 'Baby, Child & Toys' },
  { text: 'toy computer', label: 'Baby, Child & Toys' },
  { text: 'electronic learning toy', label: 'Baby, Child & Toys' },
  { text: 'tablet for kids', label: 'Baby, Child & Toys' },
  { text: 'kids headphones', label: 'Baby, Child & Toys' },
  { text: 'karaoke machine', label: 'Baby, Child & Toys' },
  { text: 'toy microphone', label: 'Baby, Child & Toys' },
  { text: 'musical instruments', label: 'Baby, Child & Toys' },
  { text: 'xylophone', label: 'Baby, Child & Toys' },
  { text: 'tambourine', label: 'Baby, Child & Toys' },
  { text: 'maracas', label: 'Baby, Child & Toys' },
  { text: 'triangle', label: 'Baby, Child & Toys' },
  { text: 'harmonica', label: 'Baby, Child & Toys' },
  { text: 'recorder', label: 'Baby, Child & Toys' },
  { text: 'toy violin', label: 'Baby, Child & Toys' },
  { text: 'toy trumpet', label: 'Baby, Child & Toys' },
  { text: 'toy saxophone', label: 'Baby, Child & Toys' },
  { text: 'music box', label: 'Baby, Child & Toys' },
  { text: 'wind chimes', label: 'Baby, Child & Toys' },
  { text: 'baby mobile', label: 'Baby, Child & Toys' },
  { text: 'crib mobile', label: 'Baby, Child & Toys' },
  { text: 'baby swing', label: 'Baby, Child & Toys' },
  { text: 'baby rocker', label: 'Baby, Child & Toys' },
  { text: 'baby bouncer seat', label: 'Baby, Child & Toys' },
  { text: 'baby jumper seat', label: 'Baby, Child & Toys' },
  { text: 'baby walker', label: 'Baby, Child & Toys' },
  { text: 'push toy', label: 'Baby, Child & Toys' },
  { text: 'pull toy', label: 'Baby, Child & Toys' },
  { text: 'ride on toy', label: 'Baby, Child & Toys' },
  { text: 'rocking horse', label: 'Baby, Child & Toys' },
  { text: 'tricycle', label: 'Baby, Child & Toys' },
  { text: 'balance bike', label: 'Baby, Child & Toys' },
  { text: 'scooter', label: 'Baby, Child & Toys' },
  { text: 'skateboard', label: 'Baby, Child & Toys' },
  { text: 'roller skates', label: 'Baby, Child & Toys' },
  { text: 'ice skates', label: 'Baby, Child & Toys' },
  { text: 'helmet', label: 'Baby, Child & Toys' },
  { text: 'knee pads', label: 'Baby, Child & Toys' },
  { text: 'elbow pads', label: 'Baby, Child & Toys' },
  { text: 'wrist guards', label: 'Baby, Child & Toys' },
  { text: 'sports ball', label: 'Baby, Child & Toys' },
  { text: 'soccer ball', label: 'Baby, Child & Toys' },
  { text: 'basketball', label: 'Baby, Child & Toys' },
  { text: 'football', label: 'Baby, Child & Toys' },
  { text: 'tennis ball', label: 'Baby, Child & Toys' },
  { text: 'ping pong ball', label: 'Baby, Child & Toys' },
  { text: 'volleyball', label: 'Baby, Child & Toys' },
  { text: 'baseball', label: 'Baby, Child & Toys' },
  { text: 'softball', label: 'Baby, Child & Toys' },
  { text: 'golf ball', label: 'Baby, Child & Toys' },
  { text: 'bowling ball', label: 'Baby, Child & Toys' },
  { text: 'beach ball', label: 'Baby, Child & Toys' },
  { text: 'exercise ball', label: 'Baby, Child & Toys' },
  { text: 'medicine ball', label: 'Baby, Child & Toys' },
  { text: 'foam ball', label: 'Baby, Child & Toys' },
  { text: 'rubber ball', label: 'Baby, Child & Toys' },
  { text: 'bouncy ball', label: 'Baby, Child & Toys' },
  { text: 'stress relief ball', label: 'Baby, Child & Toys' },
  { text: 'sensory ball', label: 'Baby, Child & Toys' },
  { text: 'textured ball', label: 'Baby, Child & Toys' },
  { text: 'light up ball', label: 'Baby, Child & Toys' },
  { text: 'musical ball', label: 'Baby, Child & Toys' },
  { text: 'talking ball', label: 'Baby, Child & Toys' },
  { text: 'interactive ball', label: 'Baby, Child & Toys' },
  { text: 'smart ball', label: 'Baby, Child & Toys' },
  { text: 'electronic ball', label: 'Baby, Child & Toys' },
  { text: 'programmable toy', label: 'Baby, Child & Toys' },
  { text: 'coding toy', label: 'Baby, Child & Toys' },
  { text: 'robotics kit', label: 'Baby, Child & Toys' },
  { text: 'stem toy', label: 'Baby, Child & Toys' },
  { text: 'steam toy', label: 'Baby, Child & Toys' },
  { text: 'engineering toy', label: 'Baby, Child & Toys' },
  { text: 'construction toy', label: 'Baby, Child & Toys' },
  { text: 'building set', label: 'Baby, Child & Toys' },
  { text: 'magnetic tiles', label: 'Baby, Child & Toys' },
  { text: 'magnetic blocks', label: 'Baby, Child & Toys' },
  { text: 'wooden blocks', label: 'Baby, Child & Toys' },
  { text: 'foam blocks', label: 'Baby, Child & Toys' },
  { text: 'soft blocks', label: 'Baby, Child & Toys' },
  { text: 'stacking blocks', label: 'Baby, Child & Toys' },
  { text: 'nesting blocks', label: 'Baby, Child & Toys' },
  { text: 'sorting blocks', label: 'Baby, Child & Toys' },
  { text: 'shape sorter', label: 'Baby, Child & Toys' },
  { text: 'color sorter', label: 'Baby, Child & Toys' },
  { text: 'size sorter', label: 'Baby, Child & Toys' },
  { text: 'pattern sorter', label: 'Baby, Child & Toys' },
  { text: 'matching game', label: 'Baby, Child & Toys' },
  { text: 'memory game', label: 'Baby, Child & Toys' },
  { text: 'concentration game', label: 'Baby, Child & Toys' },
  { text: 'brain teaser', label: 'Baby, Child & Toys' },
  { text: 'logic puzzle', label: 'Baby, Child & Toys' },
  { text: 'word puzzle', label: 'Baby, Child & Toys' },
  { text: 'number puzzle', label: 'Baby, Child & Toys' },
  { text: 'alphabet puzzle', label: 'Baby, Child & Toys' },
  { text: 'geography puzzle', label: 'Baby, Child & Toys' },
  { text: 'world map puzzle', label: 'Baby, Child & Toys' },
  { text: 'animal puzzle', label: 'Baby, Child & Toys' },
  { text: 'vehicle puzzle', label: 'Baby, Child & Toys' },
  { text: 'dinosaur puzzle', label: 'Baby, Child & Toys' },
  { text: 'princess puzzle', label: 'Baby, Child & Toys' },
  { text: 'superhero puzzle', label: 'Baby, Child & Toys' },
  { text: 'cartoon puzzle', label: 'Baby, Child & Toys' },
  { text: 'movie puzzle', label: 'Baby, Child & Toys' },
  { text: 'tv show puzzle', label: 'Baby, Child & Toys' },
  { text: 'character puzzle', label: 'Baby, Child & Toys' },
  { text: 'licensed puzzle', label: 'Baby, Child & Toys' },
  { text: 'branded puzzle', label: 'Baby, Child & Toys' },
  { text: 'custom puzzle', label: 'Baby, Child & Toys' },
  { text: 'photo puzzle', label: 'Baby, Child & Toys' },
  { text: 'personalized puzzle', label: 'Baby, Child & Toys' },
  { text: 'name puzzle', label: 'Baby, Child & Toys' },
  { text: 'wooden puzzle', label: 'Baby, Child & Toys' },
  { text: 'cardboard puzzle', label: 'Baby, Child & Toys' },
  { text: 'foam puzzle', label: 'Baby, Child & Toys' },
  { text: 'magnetic puzzle', label: 'Baby, Child & Toys' },
  { text: '3d puzzle', label: 'Baby, Child & Toys' },
  { text: 'floor puzzle', label: 'Baby, Child & Toys' },
  { text: 'giant puzzle', label: 'Baby, Child & Toys' },
  { text: 'mini puzzle', label: 'Baby, Child & Toys' },
  { text: 'travel puzzle', label: 'Baby, Child & Toys' },
  { text: 'pocket puzzle', label: 'Baby, Child & Toys' },
  { text: 'electronic puzzle', label: 'Baby, Child & Toys' },
  { text: 'digital puzzle', label: 'Baby, Child & Toys' },
  { text: 'interactive puzzle', label: 'Baby, Child & Toys' },
  { text: 'talking puzzle', label: 'Baby, Child & Toys' },
  { text: 'musical puzzle', label: 'Baby, Child & Toys' },
  { text: 'sound puzzle', label: 'Baby, Child & Toys' },
  { text: 'light up puzzle', label: 'Baby, Child & Toys' },
  { text: 'glow in dark puzzle', label: 'Baby, Child & Toys' },
  { text: 'holographic puzzle', label: 'Baby, Child & Toys' },
  { text: 'lenticular puzzle', label: 'Baby, Child & Toys' },
  { text: 'changing image puzzle', label: 'Baby, Child & Toys' },
  { text: 'motion puzzle', label: 'Baby, Child & Toys' },
  { text: 'animated puzzle', label: 'Baby, Child & Toys' },
  { text: 'moving puzzle', label: 'Baby, Child & Toys' },
  { text: 'kinetic puzzle', label: 'Baby, Child & Toys' },
  { text: 'mechanical puzzle', label: 'Baby, Child & Toys' },
  { text: 'gear puzzle', label: 'Baby, Child & Toys' },
  { text: 'clockwork puzzle', label: 'Baby, Child & Toys' },
  { text: 'wind up puzzle', label: 'Baby, Child & Toys' },
  { text: 'spring loaded puzzle', label: 'Baby, Child & Toys' },
  { text: 'gravity puzzle', label: 'Baby, Child & Toys' },
  { text: 'balance puzzle', label: 'Baby, Child & Toys' },
  { text: 'physics puzzle', label: 'Baby, Child & Toys' },
  { text: 'engineering puzzle', label: 'Baby, Child & Toys' },
  { text: 'construction puzzle', label: 'Baby, Child & Toys' },
  { text: 'building puzzle', label: 'Baby, Child & Toys' },
  { text: 'assembly puzzle', label: 'Baby, Child & Toys' },
  { text: 'disassembly puzzle', label: 'Baby, Child & Toys' },
  { text: 'take apart puzzle', label: 'Baby, Child & Toys' },
  { text: 'put together puzzle', label: 'Baby, Child & Toys' },
  { text: 'combination puzzle', label: 'Baby, Child & Toys' },
  { text: 'sequential puzzle', label: 'Baby, Child & Toys' },
  { text: 'step by step puzzle', label: 'Baby, Child & Toys' },
  { text: 'progressive puzzle', label: 'Baby, Child & Toys' },
  { text: 'level puzzle', label: 'Baby, Child & Toys' },
  { text: 'difficulty puzzle', label: 'Baby, Child & Toys' },
  { text: 'challenge puzzle', label: 'Baby, Child & Toys' },
  { text: 'expert puzzle', label: 'Baby, Child & Toys' },
  { text: 'master puzzle', label: 'Baby, Child & Toys' },
  { text: 'advanced puzzle', label: 'Baby, Child & Toys' },
  { text: 'professional puzzle', label: 'Baby, Child & Toys' },
  { text: 'competition puzzle', label: 'Baby, Child & Toys' },
  { text: 'tournament puzzle', label: 'Baby, Child & Toys' },
  { text: 'championship puzzle', label: 'Baby, Child & Toys' },
  { text: 'world record puzzle', label: 'Baby, Child & Toys' },
  { text: 'speed puzzle', label: 'Baby, Child & Toys' },
  { text: 'timed puzzle', label: 'Baby, Child & Toys' },
  { text: 'race puzzle', label: 'Baby, Child & Toys' },
  { text: 'fast puzzle', label: 'Baby, Child & Toys' },
  { text: 'quick puzzle', label: 'Baby, Child & Toys' },
  { text: 'instant puzzle', label: 'Baby, Child & Toys' },
  { text: 'immediate puzzle', label: 'Baby, Child & Toys' },
  { text: 'rapid puzzle', label: 'Baby, Child & Toys' },
  { text: 'swift puzzle', label: 'Baby, Child & Toys' },
  { text: 'speedy puzzle', label: 'Baby, Child & Toys' },
  { text: 'lightning puzzle', label: 'Baby, Child & Toys' },
  { text: 'flash puzzle', label: 'Baby, Child & Toys' },
  { text: 'blitz puzzle', label: 'Baby, Child & Toys' },
  { text: 'turbo puzzle', label: 'Baby, Child & Toys' },
  { text: 'super puzzle', label: 'Baby, Child & Toys' },
  { text: 'mega puzzle', label: 'Baby, Child & Toys' },
  { text: 'ultra puzzle', label: 'Baby, Child & Toys' },
  { text: 'extreme puzzle', label: 'Baby, Child & Toys' },
  { text: 'maximum puzzle', label: 'Baby, Child & Toys' },
  { text: 'ultimate puzzle', label: 'Baby, Child & Toys' },
  { text: 'supreme puzzle', label: 'Baby, Child & Toys' },
  { text: 'premium puzzle', label: 'Baby, Child & Toys' },
  { text: 'deluxe puzzle', label: 'Baby, Child & Toys' },
  { text: 'luxury puzzle', label: 'Baby, Child & Toys' },
  { text: 'exclusive puzzle', label: 'Baby, Child & Toys' },
  { text: 'limited edition puzzle', label: 'Baby, Child & Toys' },
  { text: 'special edition puzzle', label: 'Baby, Child & Toys' },
  { text: 'collectors puzzle', label: 'Baby, Child & Toys' },
  { text: 'rare puzzle', label: 'Baby, Child & Toys' },
  { text: 'unique puzzle', label: 'Baby, Child & Toys' },
  { text: 'one of a kind puzzle', label: 'Baby, Child & Toys' },
  { text: 'handmade puzzle', label: 'Baby, Child & Toys' },
  { text: 'artisan puzzle', label: 'Baby, Child & Toys' },
  { text: 'craft puzzle', label: 'Baby, Child & Toys' },
  { text: 'artistic puzzle', label: 'Baby, Child & Toys' },
  { text: 'creative puzzle', label: 'Baby, Child & Toys' },
  { text: 'imaginative puzzle', label: 'Baby, Child & Toys' },
  { text: 'innovative puzzle', label: 'Baby, Child & Toys' },
  { text: 'original puzzle', label: 'Baby, Child & Toys' },
  { text: 'novel puzzle', label: 'Baby, Child & Toys' },
  { text: 'new puzzle', label: 'Baby, Child & Toys' },
  { text: 'fresh puzzle', label: 'Baby, Child & Toys' },
  { text: 'modern puzzle', label: 'Baby, Child & Toys' },
  { text: 'contemporary puzzle', label: 'Baby, Child & Toys' },
  { text: 'current puzzle', label: 'Baby, Child & Toys' },
  { text: 'latest puzzle', label: 'Baby, Child & Toys' },
  { text: 'newest puzzle', label: 'Baby, Child & Toys' },
  { text: 'recent puzzle', label: 'Baby, Child & Toys' },
  { text: 'updated puzzle', label: 'Baby, Child & Toys' },
  { text: 'revised puzzle', label: 'Baby, Child & Toys' },
  { text: 'improved puzzle', label: 'Baby, Child & Toys' },
  { text: 'enhanced puzzle', label: 'Baby, Child & Toys' },
  { text: 'upgraded puzzle', label: 'Baby, Child & Toys' },
  { text: 'advanced puzzle', label: 'Baby, Child & Toys' },
  { text: 'sophisticated puzzle', label: 'Baby, Child & Toys' },
  { text: 'complex puzzle', label: 'Baby, Child & Toys' },
  { text: 'complicated puzzle', label: 'Baby, Child & Toys' },
  { text: 'intricate puzzle', label: 'Baby, Child & Toys' },
  { text: 'detailed puzzle', label: 'Baby, Child & Toys' },
  { text: 'elaborate puzzle', label: 'Baby, Child & Toys' },
  { text: 'comprehensive puzzle', label: 'Baby, Child & Toys' },
  { text: 'complete puzzle', label: 'Baby, Child & Toys' },
  { text: 'full puzzle', label: 'Baby, Child & Toys' },
  { text: 'whole puzzle', label: 'Baby, Child & Toys' },
  { text: 'entire puzzle', label: 'Baby, Child & Toys' },
  { text: 'total puzzle', label: 'Baby, Child & Toys' },
  { text: 'all inclusive puzzle', label: 'Baby, Child & Toys' },
  { text: 'everything puzzle', label: 'Baby, Child & Toys' },
  { text: 'universal puzzle', label: 'Baby, Child & Toys' },
  { text: 'global puzzle', label: 'Baby, Child & Toys' },
  { text: 'worldwide puzzle', label: 'Baby, Child & Toys' },
  { text: 'international puzzle', label: 'Baby, Child & Toys' },
  { text: 'multicultural puzzle', label: 'Baby, Child & Toys' },
  { text: 'diverse puzzle', label: 'Baby, Child & Toys' },
  { text: 'varied puzzle', label: 'Baby, Child & Toys' },
  { text: 'assorted puzzle', label: 'Baby, Child & Toys' },
  { text: 'mixed puzzle', label: 'Baby, Child & Toys' },
  { text: 'combination puzzle', label: 'Baby, Child & Toys' },
  { text: 'hybrid puzzle', label: 'Baby, Child & Toys' },
  { text: 'fusion puzzle', label: 'Baby, Child & Toys' },
  { text: 'blend puzzle', label: 'Baby, Child & Toys' },
  { text: 'merge puzzle', label: 'Baby, Child & Toys' },
  { text: 'unite puzzle', label: 'Baby, Child & Toys' },
  { text: 'join puzzle', label: 'Baby, Child & Toys' },
  { text: 'connect puzzle', label: 'Baby, Child & Toys' },
  { text: 'link puzzle', label: 'Baby, Child & Toys' },
  { text: 'chain puzzle', label: 'Baby, Child & Toys' },
  { text: 'series puzzle', label: 'Baby, Child & Toys' },
  { text: 'sequence puzzle', label: 'Baby, Child & Toys' },
  { text: 'order puzzle', label: 'Baby, Child & Toys' },
  { text: 'arrangement puzzle', label: 'Baby, Child & Toys' },
  { text: 'organization puzzle', label: 'Baby, Child & Toys' },
  { text: 'structure puzzle', label: 'Baby, Child & Toys' },
  { text: 'system puzzle', label: 'Baby, Child & Toys' },
  { text: 'method puzzle', label: 'Baby, Child & Toys' },
  { text: 'process puzzle', label: 'Baby, Child & Toys' },
  { text: 'procedure puzzle', label: 'Baby, Child & Toys' },
  { text: 'technique puzzle', label: 'Baby, Child & Toys' },
  { text: 'approach puzzle', label: 'Baby, Child & Toys' },
  { text: 'strategy puzzle', label: 'Baby, Child & Toys' },
  { text: 'plan puzzle', label: 'Baby, Child & Toys' },
  { text: 'scheme puzzle', label: 'Baby, Child & Toys' },
  { text: 'design puzzle', label: 'Baby, Child & Toys' },
  { text: 'pattern puzzle', label: 'Baby, Child & Toys' },
  { text: 'template puzzle', label: 'Baby, Child & Toys' },
  { text: 'model puzzle', label: 'Baby, Child & Toys' },
  { text: 'example puzzle', label: 'Baby, Child & Toys' },
  { text: 'sample puzzle', label: 'Baby, Child & Toys' },
  { text: 'specimen puzzle', label: 'Baby, Child & Toys' },
  { text: 'instance puzzle', label: 'Baby, Child & Toys' },
  { text: 'case puzzle', label: 'Baby, Child & Toys' },
  { text: 'situation puzzle', label: 'Baby, Child & Toys' },
  { text: 'scenario puzzle', label: 'Baby, Child & Toys' },
  { text: 'circumstance puzzle', label: 'Baby, Child & Toys' },
  { text: 'condition puzzle', label: 'Baby, Child & Toys' },
  { text: 'state puzzle', label: 'Baby, Child & Toys' },
  { text: 'status puzzle', label: 'Baby, Child & Toys' },
  { text: 'position puzzle', label: 'Baby, Child & Toys' },
  { text: 'location puzzle', label: 'Baby, Child & Toys' },
  { text: 'place puzzle', label: 'Baby, Child & Toys' },
  { text: 'spot puzzle', label: 'Baby, Child & Toys' },
  { text: 'point puzzle', label: 'Baby, Child & Toys' },
  { text: 'area puzzle', label: 'Baby, Child & Toys' },
  { text: 'region puzzle', label: 'Baby, Child & Toys' },
  { text: 'zone puzzle', label: 'Baby, Child & Toys' },
  { text: 'sector puzzle', label: 'Baby, Child & Toys' },
  { text: 'section puzzle', label: 'Baby, Child & Toys' },
  { text: 'part puzzle', label: 'Baby, Child & Toys' },
  { text: 'piece puzzle', label: 'Baby, Child & Toys' },
  { text: 'component puzzle', label: 'Baby, Child & Toys' },
  { text: 'element puzzle', label: 'Baby, Child & Toys' },
  { text: 'factor puzzle', label: 'Baby, Child & Toys' },
  { text: 'aspect puzzle', label: 'Baby, Child & Toys' },
  { text: 'feature puzzle', label: 'Baby, Child & Toys' },
  { text: 'characteristic puzzle', label: 'Baby, Child & Toys' },
  { text: 'trait puzzle', label: 'Baby, Child & Toys' },
  { text: 'quality puzzle', label: 'Baby, Child & Toys' },
  { text: 'property puzzle', label: 'Baby, Child & Toys' },
  { text: 'attribute puzzle', label: 'Baby, Child & Toys' },
  { text: 'specification puzzle', label: 'Baby, Child & Toys' },
  { text: 'requirement puzzle', label: 'Baby, Child & Toys' },
  { text: 'standard puzzle', label: 'Baby, Child & Toys' },
  { text: 'criterion puzzle', label: 'Baby, Child & Toys' },
  { text: 'measure puzzle', label: 'Baby, Child & Toys' },
  { text: 'metric puzzle', label: 'Baby, Child & Toys' },
  { text: 'scale puzzle', label: 'Baby, Child & Toys' },
  { text: 'size puzzle', label: 'Baby, Child & Toys' },
  { text: 'dimension puzzle', label: 'Baby, Child & Toys' },
  { text: 'proportion puzzle', label: 'Baby, Child & Toys' },
  { text: 'ratio puzzle', label: 'Baby, Child & Toys' },
  { text: 'percentage puzzle', label: 'Baby, Child & Toys' },
  { text: 'fraction puzzle', label: 'Baby, Child & Toys' },
  { text: 'decimal puzzle', label: 'Baby, Child & Toys' },
  { text: 'number puzzle', label: 'Baby, Child & Toys' },
  { text: 'digit puzzle', label: 'Baby, Child & Toys' },
  { text: 'figure puzzle', label: 'Baby, Child & Toys' },
  { text: 'numeral puzzle', label: 'Baby, Child & Toys' },
  { text: 'integer puzzle', label: 'Baby, Child & Toys' },
  { text: 'whole number puzzle', label: 'Baby, Child & Toys' },
  { text: 'counting puzzle', label: 'Baby, Child & Toys' },
  { text: 'calculation puzzle', label: 'Baby, Child & Toys' },
  { text: 'computation puzzle', label: 'Baby, Child & Toys' },
  { text: 'arithmetic puzzle', label: 'Baby, Child & Toys' },
  { text: 'mathematics puzzle', label: 'Baby, Child & Toys' },
  { text: 'math puzzle', label: 'Baby, Child & Toys' },
  { text: 'algebra puzzle', label: 'Baby, Child & Toys' },
  { text: 'geometry puzzle', label: 'Baby, Child & Toys' },
  { text: 'trigonometry puzzle', label: 'Baby, Child & Toys' },
  { text: 'calculus puzzle', label: 'Baby, Child & Toys' },
  { text: 'statistics puzzle', label: 'Baby, Child & Toys' },
  { text: 'probability puzzle', label: 'Baby, Child & Toys' },
  { text: 'logic puzzle', label: 'Baby, Child & Toys' },
  { text: 'reasoning puzzle', label: 'Baby, Child & Toys' },
  { text: 'thinking puzzle', label: 'Baby, Child & Toys' },
  { text: 'brain puzzle', label: 'Baby, Child & Toys' },
  { text: 'mind puzzle', label: 'Baby, Child & Toys' },
  { text: 'mental puzzle', label: 'Baby, Child & Toys' },
  { text: 'cognitive puzzle', label: 'Baby, Child & Toys' },
  { text: 'intellectual puzzle', label: 'Baby, Child & Toys' },
  { text: 'smart puzzle', label: 'Baby, Child & Toys' },
  { text: 'clever puzzle', label: 'Baby, Child & Toys' },
  { text: 'intelligent puzzle', label: 'Baby, Child & Toys' },
  { text: 'wise puzzle', label: 'Baby, Child & Toys' },
  { text: 'brilliant puzzle', label: 'Baby, Child & Toys' },
  { text: 'genius puzzle', label: 'Baby, Child & Toys' },
  { text: 'mastermind puzzle', label: 'Baby, Child & Toys' },
  { text: 'expert puzzle', label: 'Baby, Child & Toys' },
  { text: 'professional puzzle', label: 'Baby, Child & Toys' },
  { text: 'specialist puzzle', label: 'Baby, Child & Toys' },
  { text: 'authority puzzle', label: 'Baby, Child & Toys' },
  { text: 'guru puzzle', label: 'Baby, Child & Toys' },
  { text: 'master puzzle', label: 'Baby, Child & Toys' },
  { text: 'champion puzzle', label: 'Baby, Child & Toys' },
  { text: 'winner puzzle', label: 'Baby, Child & Toys' },
  { text: 'victor puzzle', label: 'Baby, Child & Toys' },
  { text: 'conqueror puzzle', label: 'Baby, Child & Toys' },
  { text: 'hero puzzle', label: 'Baby, Child & Toys' },
  { text: 'legend puzzle', label: 'Baby, Child & Toys' },
  { text: 'icon puzzle', label: 'Baby, Child & Toys' },
  { text: 'star puzzle', label: 'Baby, Child & Toys' },
  { text: 'celebrity puzzle', label: 'Baby, Child & Toys' },
  { text: 'famous puzzle', label: 'Baby, Child & Toys' },
  { text: 'popular puzzle', label: 'Baby, Child & Toys' },
  { text: 'trending puzzle', label: 'Baby, Child & Toys' },
  { text: 'viral puzzle', label: 'Baby, Child & Toys' },
  { text: 'hot puzzle', label: 'Baby, Child & Toys' },
  { text: 'cool puzzle', label: 'Baby, Child & Toys' },
  { text: 'awesome puzzle', label: 'Baby, Child & Toys' },
  { text: 'amazing puzzle', label: 'Baby, Child & Toys' },
  { text: 'incredible puzzle', label: 'Baby, Child & Toys' },
  { text: 'fantastic puzzle', label: 'Baby, Child & Toys' },
  { text: 'wonderful puzzle', label: 'Baby, Child & Toys' },
  { text: 'marvelous puzzle', label: 'Baby, Child & Toys' },
  { text: 'spectacular puzzle', label: 'Baby, Child & Toys' },
  { text: 'outstanding puzzle', label: 'Baby, Child & Toys' },
  { text: 'excellent puzzle', label: 'Baby, Child & Toys' },
  { text: 'superb puzzle', label: 'Baby, Child & Toys' },
  { text: 'magnificent puzzle', label: 'Baby, Child & Toys' },
  { text: 'splendid puzzle', label: 'Baby, Child & Toys' },
  { text: 'glorious puzzle', label: 'Baby, Child & Toys' },
  { text: 'grand puzzle', label: 'Baby, Child & Toys' },
  { text: 'great puzzle', label: 'Baby, Child & Toys' },
  { text: 'good puzzle', label: 'Baby, Child & Toys' },
  { text: 'nice puzzle', label: 'Baby, Child & Toys' },
  { text: 'fine puzzle', label: 'Baby, Child & Toys' },
  { text: 'quality puzzle', label: 'Baby, Child & Toys' },
  { text: 'top puzzle', label: 'Baby, Child & Toys' },
  { text: 'best puzzle', label: 'Baby, Child & Toys' },
  { text: 'perfect puzzle', label: 'Baby, Child & Toys' },
  { text: 'ideal puzzle', label: 'Baby, Child & Toys' },
  { text: 'optimal puzzle', label: 'Baby, Child & Toys' },
  { text: 'prime puzzle', label: 'Baby, Child & Toys' },
  { text: 'first class puzzle', label: 'Baby, Child & Toys' },
  { text: 'high grade puzzle', label: 'Baby, Child & Toys' },
  { text: 'superior puzzle', label: 'Baby, Child & Toys' },
  { text: 'elite puzzle', label: 'Baby, Child & Toys' },
  { text: 'select puzzle', label: 'Baby, Child & Toys' },
  { text: 'choice puzzle', label: 'Baby, Child & Toys' },
  { text: 'preferred puzzle', label: 'Baby, Child & Toys' },
  { text: 'favorite puzzle', label: 'Baby, Child & Toys' },
  { text: 'beloved puzzle', label: 'Baby, Child & Toys' },
  { text: 'cherished puzzle', label: 'Baby, Child & Toys' },
  { text: 'treasured puzzle', label: 'Baby, Child & Toys' },
  { text: 'precious puzzle', label: 'Baby, Child & Toys' },
  { text: 'valuable puzzle', label: 'Baby, Child & Toys' },
  { text: 'priceless puzzle', label: 'Baby, Child & Toys' },
  { text: 'invaluable puzzle', label: 'Baby, Child & Toys' },
  { text: 'worthwhile puzzle', label: 'Baby, Child & Toys' },
  { text: 'beneficial puzzle', label: 'Baby, Child & Toys' },
  { text: 'useful puzzle', label: 'Baby, Child & Toys' },
  { text: 'helpful puzzle', label: 'Baby, Child & Toys' },
  { text: 'practical puzzle', label: 'Baby, Child & Toys' },
  { text: 'functional puzzle', label: 'Baby, Child & Toys' },
  { text: 'effective puzzle', label: 'Baby, Child & Toys' },
  { text: 'efficient puzzle', label: 'Baby, Child & Toys' },
  { text: 'productive puzzle', label: 'Baby, Child & Toys' },
  { text: 'successful puzzle', label: 'Baby, Child & Toys' },
  { text: 'winning puzzle', label: 'Baby, Child & Toys' },
  { text: 'triumphant puzzle', label: 'Baby, Child & Toys' },
  { text: 'victorious puzzle', label: 'Baby, Child & Toys' },
  { text: 'conquering puzzle', label: 'Baby, Child & Toys' },
  { text: 'dominating puzzle', label: 'Baby, Child & Toys' },
  { text: 'ruling puzzle', label: 'Baby, Child & Toys' },
  { text: 'leading puzzle', label: 'Baby, Child & Toys' },
  { text: 'commanding puzzle', label: 'Baby, Child & Toys' },
  { text: 'controlling puzzle', label: 'Baby, Child & Toys' },
  { text: 'governing puzzle', label: 'Baby, Child & Toys' },
  { text: 'managing puzzle', label: 'Baby, Child & Toys' },
  { text: 'directing puzzle', label: 'Baby, Child & Toys' },
  { text: 'guiding puzzle', label: 'Baby, Child & Toys' },
  { text: 'steering puzzle', label: 'Baby, Child & Toys' },
  { text: 'navigating puzzle', label: 'Baby, Child & Toys' },
  { text: 'piloting puzzle', label: 'Baby, Child & Toys' },
  { text: 'driving puzzle', label: 'Baby, Child & Toys' },
  { text: 'operating puzzle', label: 'Baby, Child & Toys' },
  { text: 'running puzzle', label: 'Baby, Child & Toys' },
  { text: 'working puzzle', label: 'Baby, Child & Toys' },
  { text: 'functioning puzzle', label: 'Baby, Child & Toys' },
  { text: 'performing puzzle', label: 'Baby, Child & Toys' },
  { text: 'executing puzzle', label: 'Baby, Child & Toys' },
  { text: 'implementing puzzle', label: 'Baby, Child & Toys' },
  { text: 'applying puzzle', label: 'Baby, Child & Toys' },
  { text: 'using puzzle', label: 'Baby, Child & Toys' },
  { text: 'utilizing puzzle', label: 'Baby, Child & Toys' },
  { text: 'employing puzzle', label: 'Baby, Child & Toys' },
  { text: 'engaging puzzle', label: 'Baby, Child & Toys' },
  { text: 'involving puzzle', label: 'Baby, Child & Toys' },
  { text: 'participating puzzle', label: 'Baby, Child & Toys' },
  { text: 'contributing puzzle', label: 'Baby, Child & Toys' },
  { text: 'sharing puzzle', label: 'Baby, Child & Toys' },
  { text: 'giving puzzle', label: 'Baby, Child & Toys' },
  { text: 'offering puzzle', label: 'Baby, Child & Toys' },
  { text: 'providing puzzle', label: 'Baby, Child & Toys' },
  { text: 'supplying puzzle', label: 'Baby, Child & Toys' },
  { text: 'delivering puzzle', label: 'Baby, Child & Toys' },
  { text: 'presenting puzzle', label: 'Baby, Child & Toys' },
  { text: 'showing puzzle', label: 'Baby, Child & Toys' },
  { text: 'displaying puzzle', label: 'Baby, Child & Toys' },
  { text: 'exhibiting puzzle', label: 'Baby, Child & Toys' },
  { text: 'demonstrating puzzle', label: 'Baby, Child & Toys' },
  { text: 'revealing puzzle', label: 'Baby, Child & Toys' },
  { text: 'exposing puzzle', label: 'Baby, Child & Toys' },
  { text: 'uncovering puzzle', label: 'Baby, Child & Toys' },
  { text: 'discovering puzzle', label: 'Baby, Child & Toys' },
  { text: 'finding puzzle', label: 'Baby, Child & Toys' },
  { text: 'locating puzzle', label: 'Baby, Child & Toys' },
  { text: 'identifying puzzle', label: 'Baby, Child & Toys' },
  { text: 'recognizing puzzle', label: 'Baby, Child & Toys' },
  { text: 'acknowledging puzzle', label: 'Baby, Child & Toys' },
  { text: 'accepting puzzle', label: 'Baby, Child & Toys' },
  { text: 'embracing puzzle', label: 'Baby, Child & Toys' },
  { text: 'welcoming puzzle', label: 'Baby, Child & Toys' },
  { text: 'greeting puzzle', label: 'Baby, Child & Toys' },
  { text: 'meeting puzzle', label: 'Baby, Child & Toys' },
  { text: 'encountering puzzle', label: 'Baby, Child & Toys' },
  { text: 'facing puzzle', label: 'Baby, Child & Toys' },
  { text: 'confronting puzzle', label: 'Baby, Child & Toys' },
  { text: 'challenging puzzle', label: 'Baby, Child & Toys' },
  { text: 'testing puzzle', label: 'Baby, Child & Toys' },
  { text: 'trying puzzle', label: 'Baby, Child & Toys' },
  { text: 'attempting puzzle', label: 'Baby, Child & Toys' },
  { text: 'endeavoring puzzle', label: 'Baby, Child & Toys' },
  { text: 'striving puzzle', label: 'Baby, Child & Toys' },
  { text: 'struggling puzzle', label: 'Baby, Child & Toys' },
  { text: 'fighting puzzle', label: 'Baby, Child & Toys' },
  { text: 'battling puzzle', label: 'Baby, Child & Toys' },
  { text: 'competing puzzle', label: 'Baby, Child & Toys' },
  { text: 'contesting puzzle', label: 'Baby, Child & Toys' },
  { text: 'rivaling puzzle', label: 'Baby, Child & Toys' },
  { text: 'opposing puzzle', label: 'Baby, Child & Toys' },
  { text: 'resisting puzzle', label: 'Baby, Child & Toys' },
  { text: 'defending puzzle', label: 'Baby, Child & Toys' },
  { text: 'protecting puzzle', label: 'Baby, Child & Toys' },
  { text: 'guarding puzzle', label: 'Baby, Child & Toys' },
  { text: 'shielding puzzle', label: 'Baby, Child & Toys' },
  { text: 'covering puzzle', label: 'Baby, Child & Toys' },
  { text: 'hiding puzzle', label: 'Baby, Child & Toys' },
  { text: 'concealing puzzle', label: 'Baby, Child & Toys' },
  { text: 'masking puzzle', label: 'Baby, Child & Toys' },
  { text: 'disguising puzzle', label: 'Baby, Child & Toys' },
  { text: 'camouflaging puzzle', label: 'Baby, Child & Toys' },
  { text: 'blending puzzle', label: 'Baby, Child & Toys' },
  { text: 'merging puzzle', label: 'Baby, Child & Toys' },
  { text: 'combining puzzle', label: 'Baby, Child & Toys' },
  { text: 'mixing puzzle', label: 'Baby, Child & Toys' },
  { text: 'stirring puzzle', label: 'Baby, Child & Toys' },
  { text: 'shaking puzzle', label: 'Baby, Child & Toys' },
  { text: 'moving puzzle', label: 'Baby, Child & Toys' },
  { text: 'shifting puzzle', label: 'Baby, Child & Toys' },
  { text: 'changing puzzle', label: 'Baby, Child & Toys' },
  { text: 'transforming puzzle', label: 'Baby, Child & Toys' },
  { text: 'converting puzzle', label: 'Baby, Child & Toys' },
  { text: 'adapting puzzle', label: 'Baby, Child & Toys' },
  { text: 'adjusting puzzle', label: 'Baby, Child & Toys' },
  { text: 'modifying puzzle', label: 'Baby, Child & Toys' }
];