const bakeryFastFoodData = [
  { text: 'bread', label: 'Bakery & Fast Food' },
  { text: 'white bread', label: 'Bakery & Fast Food' },
  { text: 'whole wheat bread', label: 'Bakery & Fast Food' },
  { text: 'sourdough bread', label: 'Bakery & Fast Food' },
  { text: 'rye bread', label: 'Bakery & Fast Food' },
  { text: 'pumpernickel bread', label: 'Bakery & Fast Food' },
  { text: 'multigrain bread', label: 'Bakery & Fast Food' },
  { text: 'french bread', label: 'Bakery & Fast Food' },
  { text: 'italian bread', label: 'Bakery & Fast Food' },
  { text: 'ciabatta', label: 'Bakery & Fast Food' },
  { text: 'focaccia', label: 'Bakery & Fast Food' },
  { text: 'baguette', label: 'Bakery & Fast Food' },
  { text: 'croissant', label: 'Bakery & Fast Food' },
  { text: 'pain au chocolat', label: 'Bakery & Fast Food' },
  { text: 'danish pastry', label: 'Bakery & Fast Food' },
  { text: 'muffin', label: 'Bakery & Fast Food' },
  { text: 'blueberry muffin', label: 'Bakery & Fast Food' },
  { text: 'chocolate chip muffin', label: 'Bakery & Fast Food' },
  { text: 'banana muffin', label: 'Bakery & Fast Food' },
  { text: 'bran muffin', label: 'Bakery & Fast Food' },
  { text: 'english muffin', label: 'Bakery & Fast Food' },
  { text: 'bagel', label: 'Bakery & Fast Food' },
  { text: 'plain bagel', label: 'Bakery & Fast Food' },
  { text: 'sesame bagel', label: 'Bakery & Fast Food' },
  { text: 'everything bagel', label: 'Bakery & Fast Food' },
  { text: 'poppy seed bagel', label: 'Bakery & Fast Food' },
  { text: 'onion bagel', label: 'Bakery & Fast Food' },
  { text: 'garlic bagel', label: 'Bakery & Fast Food' },
  { text: 'cinnamon raisin bagel', label: 'Bakery & Fast Food' },
  { text: 'blueberry bagel', label: 'Bakery & Fast Food' },
  { text: 'chocolate chip bagel', label: 'Bakery & Fast Food' },
  { text: 'donut', label: 'Bakery & Fast Food' },
  { text: 'glazed donut', label: 'Bakery & Fast Food' },
  { text: 'chocolate donut', label: 'Bakery & Fast Food' },
  { text: 'jelly donut', label: 'Bakery & Fast Food' },
  { text: 'cream filled donut', label: 'Bakery & Fast Food' },
  { text: 'boston cream donut', label: 'Bakery & Fast Food' },
  { text: 'old fashioned donut', label: 'Bakery & Fast Food' },
  { text: 'cake donut', label: 'Bakery & Fast Food' },
  { text: 'yeast donut', label: 'Bakery & Fast Food' },
  { text: 'cruller', label: 'Bakery & Fast Food' },
  { text: 'bear claw', label: 'Bakery & Fast Food' },
  { text: 'apple fritter', label: 'Bakery & Fast Food' },
  { text: 'cinnamon roll', label: 'Bakery & Fast Food' },
  { text: 'sticky bun', label: 'Bakery & Fast Food' },
  { text: 'coffee cake', label: 'Bakery & Fast Food' },
  { text: 'scone', label: 'Bakery & Fast Food' },
  { text: 'blueberry scone', label: 'Bakery & Fast Food' },
  { text: 'cranberry scone', label: 'Bakery & Fast Food' },
  { text: 'cheese scone', label: 'Bakery & Fast Food' },
  { text: 'biscuit', label: 'Bakery & Fast Food' },
  { text: 'buttermilk biscuit', label: 'Bakery & Fast Food' },
  { text: 'sausage biscuit', label: 'Bakery & Fast Food' },
  { text: 'chicken biscuit', label: 'Bakery & Fast Food' },
  { text: 'bacon biscuit', label: 'Bakery & Fast Food' },
  { text: 'egg biscuit', label: 'Bakery & Fast Food' },
  { text: 'sandwich', label: 'Bakery & Fast Food' },
  { text: 'ham sandwich', label: 'Bakery & Fast Food' },
  { text: 'turkey sandwich', label: 'Bakery & Fast Food' },
  { text: 'roast beef sandwich', label: 'Bakery & Fast Food' },
  { text: 'chicken sandwich', label: 'Bakery & Fast Food' },
  { text: 'tuna sandwich', label: 'Bakery & Fast Food' },
  { text: 'egg salad sandwich', label: 'Bakery & Fast Food' },
  { text: 'chicken salad sandwich', label: 'Bakery & Fast Food' },
  { text: 'blt sandwich', label: 'Bakery & Fast Food' },
  { text: 'club sandwich', label: 'Bakery & Fast Food' },
  { text: 'grilled cheese sandwich', label: 'Bakery & Fast Food' },
  { text: 'peanut butter sandwich', label: 'Bakery & Fast Food' },
  { text: 'peanut butter and jelly sandwich', label: 'Bakery & Fast Food' },
  { text: 'submarine sandwich', label: 'Bakery & Fast Food' },
  { text: 'hoagie', label: 'Bakery & Fast Food' },
  { text: 'sub', label: 'Bakery & Fast Food' },
  { text: 'hero sandwich', label: 'Bakery & Fast Food' },
  { text: 'panini', label: 'Bakery & Fast Food' },
  { text: 'wrap', label: 'Bakery & Fast Food' },
  { text: 'burrito', label: 'Bakery & Fast Food' },
  { text: 'quesadilla', label: 'Bakery & Fast Food' },
  { text: 'taco', label: 'Bakery & Fast Food' },
  { text: 'soft taco', label: 'Bakery & Fast Food' },
  { text: 'hard taco', label: 'Bakery & Fast Food' },
  { text: 'fish taco', label: 'Bakery & Fast Food' },
  { text: 'chicken taco', label: 'Bakery & Fast Food' },
  { text: 'beef taco', label: 'Bakery & Fast Food' },
  { text: 'pork taco', label: 'Bakery & Fast Food' },
  { text: 'carnitas taco', label: 'Bakery & Fast Food' },
  { text: 'al pastor taco', label: 'Bakery & Fast Food' },
  { text: 'barbacoa taco', label: 'Bakery & Fast Food' },
  { text: 'chorizo taco', label: 'Bakery & Fast Food' },
  { text: 'shrimp taco', label: 'Bakery & Fast Food' },
  { text: 'vegetarian taco', label: 'Bakery & Fast Food' },
  { text: 'black bean taco', label: 'Bakery & Fast Food' },
  { text: 'enchilada', label: 'Bakery & Fast Food' },
  { text: 'tamale', label: 'Bakery & Fast Food' },
  { text: 'empanada', label: 'Bakery & Fast Food' },
  { text: 'arepa', label: 'Bakery & Fast Food' },
  { text: 'pupusa', label: 'Bakery & Fast Food' },
  { text: 'gordita', label: 'Bakery & Fast Food' },
  { text: 'chalupa', label: 'Bakery & Fast Food' },
  { text: 'tostada', label: 'Bakery & Fast Food' },
  { text: 'nacho', label: 'Bakery & Fast Food' },
  { text: 'nachos', label: 'Bakery & Fast Food' },
  { text: 'loaded nachos', label: 'Bakery & Fast Food' },
  { text: 'cheese nachos', label: 'Bakery & Fast Food' },
  { text: 'chicken nachos', label: 'Bakery & Fast Food' },
  { text: 'beef nachos', label: 'Bakery & Fast Food' },
  { text: 'pizza', label: 'Bakery & Fast Food' },
  { text: 'calzone', label: 'Bakery & Fast Food' },
  { text: 'stromboli', label: 'Bakery & Fast Food' },
  { text: 'pizza roll', label: 'Bakery & Fast Food' },
  { text: 'garlic bread', label: 'Bakery & Fast Food' },
  { text: 'breadsticks', label: 'Bakery & Fast Food' },
  { text: 'cheese breadsticks', label: 'Bakery & Fast Food' },
  { text: 'garlic knots', label: 'Bakery & Fast Food' },
  { text: 'pretzel', label: 'Bakery & Fast Food' },
  { text: 'soft pretzel', label: 'Bakery & Fast Food' },
  { text: 'pretzel bun', label: 'Bakery & Fast Food' },
  { text: 'pretzel roll', label: 'Bakery & Fast Food' },
  { text: 'cinnamon pretzel', label: 'Bakery & Fast Food' },
  { text: 'cheese pretzel', label: 'Bakery & Fast Food' },
  { text: 'mustard pretzel', label: 'Bakery & Fast Food' },
  { text: 'hamburger', label: 'Bakery & Fast Food' },
  { text: 'cheeseburger', label: 'Bakery & Fast Food' },
  { text: 'bacon cheeseburger', label: 'Bakery & Fast Food' },
  { text: 'double cheeseburger', label: 'Bakery & Fast Food' },
  { text: 'quarter pounder', label: 'Bakery & Fast Food' },
  { text: 'big mac', label: 'Bakery & Fast Food' },
  { text: 'whopper', label: 'Bakery & Fast Food' },
  { text: 'veggie burger', label: 'Bakery & Fast Food' },
  { text: 'turkey burger', label: 'Bakery & Fast Food' },
  { text: 'chicken burger', label: 'Bakery & Fast Food' },
  { text: 'fish burger', label: 'Bakery & Fast Food' },
  { text: 'salmon burger', label: 'Bakery & Fast Food' },
  { text: 'black bean burger', label: 'Bakery & Fast Food' },
  { text: 'mushroom burger', label: 'Bakery & Fast Food' },
  { text: 'swiss burger', label: 'Bakery & Fast Food' },
  { text: 'blue cheese burger', label: 'Bakery & Fast Food' },
  { text: 'avocado burger', label: 'Bakery & Fast Food' },
  { text: 'jalapeno burger', label: 'Bakery & Fast Food' },
  { text: 'bbq burger', label: 'Bakery & Fast Food' },
  { text: 'mushroom swiss burger', label: 'Bakery & Fast Food' },
  { text: 'bacon burger', label: 'Bakery & Fast Food' },
  { text: 'onion ring burger', label: 'Bakery & Fast Food' },
  { text: 'slider', label: 'Bakery & Fast Food' },
  { text: 'mini burger', label: 'Bakery & Fast Food' },
  { text: 'hot dog', label: 'Bakery & Fast Food' },
  { text: 'corn dog', label: 'Bakery & Fast Food' },
  { text: 'chili dog', label: 'Bakery & Fast Food' },
  { text: 'cheese dog', label: 'Bakery & Fast Food' },
  { text: 'sauerkraut dog', label: 'Bakery & Fast Food' },
  { text: 'chicago dog', label: 'Bakery & Fast Food' },
  { text: 'new york dog', label: 'Bakery & Fast Food' },
  { text: 'coney dog', label: 'Bakery & Fast Food' },
  { text: 'bratwurst', label: 'Bakery & Fast Food' },
  { text: 'polish sausage', label: 'Bakery & Fast Food' },
  { text: 'italian sausage', label: 'Bakery & Fast Food' },
  { text: 'kielbasa', label: 'Bakery & Fast Food' },
  { text: 'chorizo', label: 'Bakery & Fast Food' },
  { text: 'andouille', label: 'Bakery & Fast Food' },
  { text: 'breakfast sausage', label: 'Bakery & Fast Food' },
  { text: 'sausage link', label: 'Bakery & Fast Food' },
  { text: 'sausage patty', label: 'Bakery & Fast Food' },
  { text: 'french fries', label: 'Bakery & Fast Food' },
  { text: 'fries', label: 'Bakery & Fast Food' },
  { text: 'curly fries', label: 'Bakery & Fast Food' },
  { text: 'waffle fries', label: 'Bakery & Fast Food' },
  { text: 'steak fries', label: 'Bakery & Fast Food' },
  { text: 'shoestring fries', label: 'Bakery & Fast Food' },
  { text: 'sweet potato fries', label: 'Bakery & Fast Food' },
  { text: 'cheese fries', label: 'Bakery & Fast Food' },
  { text: 'chili fries', label: 'Bakery & Fast Food' },
  { text: 'loaded fries', label: 'Bakery & Fast Food' },
  { text: 'garlic fries', label: 'Bakery & Fast Food' },
  { text: 'truffle fries', label: 'Bakery & Fast Food' },
  { text: 'parmesan fries', label: 'Bakery & Fast Food' },
  { text: 'cajun fries', label: 'Bakery & Fast Food' },
  { text: 'seasoned fries', label: 'Bakery & Fast Food' },
  { text: 'onion rings', label: 'Bakery & Fast Food' },
  { text: 'mozzarella sticks', label: 'Bakery & Fast Food' }
];

export default bakeryFastFoodData;