// Training data for Beauty & Personal Care category
// Singapore-specific beauty and personal care products

export const beautyPersonalCareTrainingData = [
  // Skincare
  { text: 'facial cleanser', label: 'beauty' },
  { text: 'moisturizer', label: 'beauty' },
  { text: 'sunscreen', label: 'beauty' },
  { text: 'toner', label: 'beauty' },
  { text: 'serum', label: 'beauty' },
  { text: 'face mask', label: 'beauty' },
  { text: 'eye cream', label: 'beauty' },
  { text: 'night cream', label: 'beauty' },
  { text: 'day cream', label: 'beauty' },
  { text: 'anti aging cream', label: 'beauty' },
  { text: 'acne treatment', label: 'beauty' },
  { text: 'blackhead remover', label: 'beauty' },
  { text: 'exfoliator', label: 'beauty' },
  { text: 'micellar water', label: 'beauty' },
  { text: 'makeup remover', label: 'beauty' },
  { text: 'bb cream', label: 'beauty' },
  { text: 'cc cream', label: 'beauty' },
  { text: 'primer', label: 'beauty' },
  { text: 'essence', label: 'beauty' },
  { text: 'ampoule', label: 'beauty' },
  
  // Hair care
  { text: 'shampoo', label: 'beauty' },
  { text: 'conditioner', label: 'beauty' },
  { text: 'hair mask', label: 'beauty' },
  { text: 'hair oil', label: 'beauty' },
  { text: 'hair serum', label: 'beauty' },
  { text: 'dry shampoo', label: 'beauty' },
  { text: 'hair spray', label: 'beauty' },
  { text: 'hair gel', label: 'beauty' },
  { text: 'hair wax', label: 'beauty' },
  { text: 'hair dye', label: 'beauty' },
  { text: 'hair color', label: 'beauty' },
  { text: 'hair treatment', label: 'beauty' },
  { text: 'scalp treatment', label: 'beauty' },
  { text: 'leave in conditioner', label: 'beauty' },
  { text: 'hair mousse', label: 'beauty' },
  
  // Body care
  { text: 'body wash', label: 'beauty' },
  { text: 'body lotion', label: 'beauty' },
  { text: 'body cream', label: 'beauty' },
  { text: 'body oil', label: 'beauty' },
  { text: 'body scrub', label: 'beauty' },
  { text: 'hand cream', label: 'beauty' },
  { text: 'foot cream', label: 'beauty' },
  { text: 'deodorant', label: 'beauty' },
  { text: 'antiperspirant', label: 'beauty' },
  { text: 'perfume', label: 'beauty' },
  { text: 'cologne', label: 'beauty' },
  { text: 'body mist', label: 'beauty' },
  { text: 'talcum powder', label: 'beauty' },
  { text: 'baby powder', label: 'beauty' },
  { text: 'body butter', label: 'beauty' },
  
  // Makeup
  { text: 'foundation', label: 'beauty' },
  { text: 'concealer', label: 'beauty' },
  { text: 'powder', label: 'beauty' },
  { text: 'blush', label: 'beauty' },
  { text: 'bronzer', label: 'beauty' },
  { text: 'highlighter', label: 'beauty' },
  { text: 'eyeshadow', label: 'beauty' },
  { text: 'eyeliner', label: 'beauty' },
  { text: 'mascara', label: 'beauty' },
  { text: 'lipstick', label: 'beauty' },
  { text: 'lip gloss', label: 'beauty' },
  { text: 'lip balm', label: 'beauty' },
  { text: 'lip tint', label: 'beauty' },
  { text: 'eyebrow pencil', label: 'beauty' },
  { text: 'setting spray', label: 'beauty' },
  
  // Personal hygiene
  { text: 'toothpaste', label: 'beauty' },
  { text: 'toothbrush', label: 'beauty' },
  { text: 'mouthwash', label: 'beauty' },
  { text: 'dental floss', label: 'beauty' },
  { text: 'whitening strips', label: 'beauty' },
  { text: 'soap', label: 'beauty' },
  { text: 'antibacterial soap', label: 'beauty' },
  { text: 'hand sanitizer', label: 'beauty' },
  { text: 'wet wipes', label: 'beauty' },
  { text: 'tissues', label: 'beauty' },
  { text: 'cotton pads', label: 'beauty' },
  { text: 'cotton swabs', label: 'beauty' },
  { text: 'nail clipper', label: 'beauty' },
  { text: 'nail file', label: 'beauty' },
  { text: 'nail polish', label: 'beauty' },
  
  // Men's grooming
  { text: 'shaving cream', label: 'beauty' },
  { text: 'aftershave', label: 'beauty' },
  { text: 'razor', label: 'beauty' },
  { text: 'shaving gel', label: 'beauty' },
  { text: 'beard oil', label: 'beauty' },
  { text: 'beard balm', label: 'beauty' },
  { text: 'mustache wax', label: 'beauty' },
  { text: 'face wash', label: 'beauty' },
  { text: 'mens moisturizer', label: 'beauty' },
  { text: 'hair pomade', label: 'beauty' },
  
  // Tools and accessories
  { text: 'makeup brush', label: 'beauty' },
  { text: 'beauty blender', label: 'beauty' },
  { text: 'makeup sponge', label: 'beauty' },
  { text: 'eyelash curler', label: 'beauty' },
  { text: 'tweezers', label: 'beauty' },
  { text: 'mirror', label: 'beauty' },
  { text: 'hair brush', label: 'beauty' },
  { text: 'comb', label: 'beauty' },
  { text: 'hair tie', label: 'beauty' },
  { text: 'bobby pins', label: 'beauty' },
  
  // Asian beauty brands popular in Singapore
  { text: 'sk ii', label: 'beauty' },
  { text: 'laneige', label: 'beauty' },
  { text: 'innisfree', label: 'beauty' },
  { text: 'etude house', label: 'beauty' },
  { text: 'the face shop', label: 'beauty' },
  { text: 'nature republic', label: 'beauty' },
  { text: 'sulwhasoo', label: 'beauty' },
  { text: 'hada labo', label: 'beauty' },
  { text: 'shiseido', label: 'beauty' },
  { text: 'shu uemura', label: 'beauty' }
];