// Training data for Beer, Wine & Spirits category
// Singapore-specific alcoholic beverages and spirits

export const beerWineSpiritsTrainingData = [
  // Beer
  { text: 'tiger beer', label: 'alcohol' },
  { text: 'heineken', label: 'alcohol' },
  { text: 'carlsberg', label: 'alcohol' },
  { text: 'stella artois', label: 'alcohol' },
  { text: 'corona', label: 'alcohol' },
  { text: 'guinness', label: 'alcohol' },
  { text: 'asahi', label: 'alcohol' },
  { text: 'kirin', label: 'alcohol' },
  { text: 'sapporo', label: 'alcohol' },
  { text: 'tsingtao', label: 'alcohol' },
  { text: 'budweiser', label: 'alcohol' },
  { text: 'hoegaarden', label: 'alcohol' },
  { text: 'chang beer', label: 'alcohol' },
  { text: 'singha', label: 'alcohol' },
  { text: 'leo beer', label: 'alcohol' },
  { text: 'san miguel', label: 'alcohol' },
  { text: 'anchor beer', label: 'alcohol' },
  { text: 'archipelago beer', label: 'alcohol' },
  { text: 'brewerkz', label: 'alcohol' },
  { text: 'craft beer', label: 'alcohol' },
  { text: 'ipa beer', label: 'alcohol' },
  { text: 'lager', label: 'alcohol' },
  { text: 'stout', label: 'alcohol' },
  { text: 'wheat beer', label: 'alcohol' },
  { text: 'pilsner', label: 'alcohol' },
  
  // Wine
  { text: 'red wine', label: 'alcohol' },
  { text: 'white wine', label: 'alcohol' },
  { text: 'rose wine', label: 'alcohol' },
  { text: 'sparkling wine', label: 'alcohol' },
  { text: 'champagne', label: 'alcohol' },
  { text: 'prosecco', label: 'alcohol' },
  { text: 'chardonnay', label: 'alcohol' },
  { text: 'sauvignon blanc', label: 'alcohol' },
  { text: 'pinot grigio', label: 'alcohol' },
  { text: 'riesling', label: 'alcohol' },
  { text: 'cabernet sauvignon', label: 'alcohol' },
  { text: 'merlot', label: 'alcohol' },
  { text: 'pinot noir', label: 'alcohol' },
  { text: 'shiraz', label: 'alcohol' },
  { text: 'malbec', label: 'alcohol' },
  { text: 'moscato', label: 'alcohol' },
  { text: 'port wine', label: 'alcohol' },
  { text: 'sherry', label: 'alcohol' },
  { text: 'dessert wine', label: 'alcohol' },
  { text: 'cooking wine', label: 'alcohol' },
  { text: 'wine vinegar', label: 'alcohol' },
  
  // Spirits
  { text: 'whiskey', label: 'alcohol' },
  { text: 'whisky', label: 'alcohol' },
  { text: 'scotch', label: 'alcohol' },
  { text: 'bourbon', label: 'alcohol' },
  { text: 'vodka', label: 'alcohol' },
  { text: 'gin', label: 'alcohol' },
  { text: 'rum', label: 'alcohol' },
  { text: 'tequila', label: 'alcohol' },
  { text: 'brandy', label: 'alcohol' },
  { text: 'cognac', label: 'alcohol' },
  { text: 'sake', label: 'alcohol' },
  { text: 'soju', label: 'alcohol' },
  { text: 'baijiu', label: 'alcohol' },
  { text: 'kaoliang', label: 'alcohol' },
  { text: 'shochu', label: 'alcohol' },
  { text: 'absinthe', label: 'alcohol' },
  { text: 'sambuca', label: 'alcohol' },
  { text: 'ouzo', label: 'alcohol' },
  { text: 'grappa', label: 'alcohol' },
  { text: 'armagnac', label: 'alcohol' },
  
  // Liqueurs
  { text: 'baileys', label: 'alcohol' },
  { text: 'kahlua', label: 'alcohol' },
  { text: 'amaretto', label: 'alcohol' },
  { text: 'cointreau', label: 'alcohol' },
  { text: 'grand marnier', label: 'alcohol' },
  { text: 'drambuie', label: 'alcohol' },
  { text: 'jagermeister', label: 'alcohol' },
  { text: 'sambuca', label: 'alcohol' },
  { text: 'limoncello', label: 'alcohol' },
  { text: 'frangelico', label: 'alcohol' },
  { text: 'chambord', label: 'alcohol' },
  { text: 'midori', label: 'alcohol' },
  { text: 'peach schnapps', label: 'alcohol' },
  { text: 'blue curacao', label: 'alcohol' },
  { text: 'triple sec', label: 'alcohol' },
  
  // Cocktail mixers and accessories
  { text: 'vermouth', label: 'alcohol' },
  { text: 'bitters', label: 'alcohol' },
  { text: 'grenadine', label: 'alcohol' },
  { text: 'simple syrup', label: 'alcohol' },
  { text: 'cocktail mixer', label: 'alcohol' },
  { text: 'margarita mix', label: 'alcohol' },
  { text: 'bloody mary mix', label: 'alcohol' },
  { text: 'tonic water', label: 'alcohol' },
  { text: 'soda water', label: 'alcohol' },
  { text: 'ginger beer', label: 'alcohol' },
  { text: 'club soda', label: 'alcohol' },
  { text: 'lime juice', label: 'alcohol' },
  { text: 'lemon juice', label: 'alcohol' },
  { text: 'orange juice', label: 'alcohol' },
  { text: 'cranberry juice', label: 'alcohol' },
  { text: 'pineapple juice', label: 'alcohol' },
  
  // Asian alcoholic beverages
  { text: 'chinese wine', label: 'alcohol' },
  { text: 'rice wine', label: 'alcohol' },
  { text: 'plum wine', label: 'alcohol' },
  { text: 'lychee wine', label: 'alcohol' },
  { text: 'makgeolli', label: 'alcohol' },
  { text: 'mirin', label: 'alcohol' },
  { text: 'shaoxing wine', label: 'alcohol' },
  { text: 'huangjiu', label: 'alcohol' },
  { text: 'awamori', label: 'alcohol' },
  { text: 'umeshu', label: 'alcohol' },
  
  // Non-alcoholic alternatives
  { text: 'non alcoholic beer', label: 'alcohol' },
  { text: 'alcohol free wine', label: 'alcohol' },
  { text: 'mocktail', label: 'alcohol' },
  { text: 'virgin cocktail', label: 'alcohol' }
];