export const dairyChilledEggsData = [
  { text: 'milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'whole milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'skim milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'low fat milk', label: 'Dairy, Chilled & Eggs' },
  { text: '2% milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'organic milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'lactose free milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'almond milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'soy milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'oat milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'coconut milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'rice milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'hemp milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'cashew milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'macadamia milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'pea milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'goat milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'sheep milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'buffalo milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'camel milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'condensed milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'evaporated milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'powdered milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'buttermilk', label: 'Dairy, Chilled & Eggs' },
  { text: 'heavy cream', label: 'Dairy, Chilled & Eggs' },
  { text: 'light cream', label: 'Dairy, Chilled & Eggs' },
  { text: 'half and half', label: 'Dairy, Chilled & Eggs' },
  { text: 'whipping cream', label: 'Dairy, Chilled & Eggs' },
  { text: 'double cream', label: 'Dairy, Chilled & Eggs' },
  { text: 'single cream', label: 'Dairy, Chilled & Eggs' },
  { text: 'clotted cream', label: 'Dairy, Chilled & Eggs' },
  { text: 'sour cream', label: 'Dairy, Chilled & Eggs' },
  { text: 'crème fraîche', label: 'Dairy, Chilled & Eggs' },
  { text: 'mascarpone', label: 'Dairy, Chilled & Eggs' },
  { text: 'ricotta', label: 'Dairy, Chilled & Eggs' },
  { text: 'cottage cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'cream cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'neufchatel', label: 'Dairy, Chilled & Eggs' },
  { text: 'philadelphia cream cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'farmer cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'quark', label: 'Dairy, Chilled & Eggs' },
  { text: 'fromage blanc', label: 'Dairy, Chilled & Eggs' },
  { text: 'fromage frais', label: 'Dairy, Chilled & Eggs' },
  { text: 'labneh', label: 'Dairy, Chilled & Eggs' },
  { text: 'greek yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'regular yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'plain yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'vanilla yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'strawberry yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'blueberry yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'peach yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'raspberry yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'mixed berry yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'banana yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'mango yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'coconut yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'honey yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'granola yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'probiotic yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'organic yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'low fat yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'non fat yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'whole milk yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'lactose free yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'goat yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'sheep yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'kefir', label: 'Dairy, Chilled & Eggs' },
  { text: 'drinking yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'yogurt drink', label: 'Dairy, Chilled & Eggs' },
  { text: 'lassi', label: 'Dairy, Chilled & Eggs' },
  { text: 'ayran', label: 'Dairy, Chilled & Eggs' },
  { text: 'skyr', label: 'Dairy, Chilled & Eggs' },
  { text: 'filmjölk', label: 'Dairy, Chilled & Eggs' },
  { text: 'viili', label: 'Dairy, Chilled & Eggs' },
  { text: 'cheddar cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'mozzarella cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'swiss cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'american cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'provolone cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'monterey jack cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'pepper jack cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'colby cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'colby jack cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'muenster cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'havarti cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'gouda cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'edam cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'brie cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'camembert cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'blue cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'roquefort cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'stilton cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'gorgonzola cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'feta cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'goat cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'parmesan cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'romano cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'asiago cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'pecorino cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'manchego cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'gruyere cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'emmental cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'jarlsberg cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'fontina cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'taleggio cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'limburger cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'port salut cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'babybel cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'string cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'cheese sticks', label: 'Dairy, Chilled & Eggs' },
  { text: 'cheese slices', label: 'Dairy, Chilled & Eggs' },
  { text: 'shredded cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'grated cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'cheese cubes', label: 'Dairy, Chilled & Eggs' },
  { text: 'cheese spread', label: 'Dairy, Chilled & Eggs' },
  { text: 'processed cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'velveeta cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'cheese whiz', label: 'Dairy, Chilled & Eggs' },
  { text: 'laughing cow cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'boursin cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'alouette cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'chicken eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'large eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'medium eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'small eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'extra large eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'jumbo eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'brown eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'white eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'organic eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'free range eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'cage free eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'pasture raised eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'omega 3 eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'fertile eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'duck eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'goose eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'quail eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'turkey eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'ostrich eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'emu eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'pheasant eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'guinea fowl eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'egg whites', label: 'Dairy, Chilled & Eggs' },
  { text: 'egg yolks', label: 'Dairy, Chilled & Eggs' },
  { text: 'liquid eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'egg substitute', label: 'Dairy, Chilled & Eggs' },
  { text: 'powdered eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'dried eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'pickled eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'deviled eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'hard boiled eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'soft boiled eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'poached eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'scrambled eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'fried eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'sunny side up eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'over easy eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'over medium eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'over hard eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'egg salad', label: 'Dairy, Chilled & Eggs' },
  { text: 'egg sandwich', label: 'Dairy, Chilled & Eggs' },
  { text: 'egg mcmuffin', label: 'Dairy, Chilled & Eggs' },
  { text: 'egg burrito', label: 'Dairy, Chilled & Eggs' },
  { text: 'egg wrap', label: 'Dairy, Chilled & Eggs' },
  { text: 'egg roll', label: 'Dairy, Chilled & Eggs' },
  { text: 'scotch egg', label: 'Dairy, Chilled & Eggs' },
  { text: 'century egg', label: 'Dairy, Chilled & Eggs' },
  { text: 'thousand year egg', label: 'Dairy, Chilled & Eggs' },
  { text: 'salted egg', label: 'Dairy, Chilled & Eggs' },
  { text: 'tea egg', label: 'Dairy, Chilled & Eggs' },
  { text: 'marbled egg', label: 'Dairy, Chilled & Eggs' },
  { text: 'soy sauce egg', label: 'Dairy, Chilled & Eggs' },
  { text: 'ramen egg', label: 'Dairy, Chilled & Eggs' },
  { text: 'ajitsuke egg', label: 'Dairy, Chilled & Eggs' },
  { text: 'onsen egg', label: 'Dairy, Chilled & Eggs' },
  { text: 'butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'salted butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'unsalted butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'sweet cream butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'cultured butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'european butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'irish butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'french butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'organic butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'grass fed butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'clarified butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'ghee', label: 'Dairy, Chilled & Eggs' },
  { text: 'brown butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'compound butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'herb butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'garlic butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'honey butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'cinnamon butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'margarine', label: 'Dairy, Chilled & Eggs' },
  { text: 'vegan butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'plant based butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'coconut butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'almond butter spread', label: 'Dairy, Chilled & Eggs' },
  { text: 'cashew butter spread', label: 'Dairy, Chilled & Eggs' },
  { text: 'sunflower butter spread', label: 'Dairy, Chilled & Eggs' },
  { text: 'soy butter', label: 'Dairy, Chilled & Eggs' }
];