/**
 * Training data for Dairy, Chilled & Eggs category
 * Singapore-focused dairy products, chilled items, and egg varieties
 */

export interface TrainingDataItem {
  text: string;
  label: string;
}

export const dairyChilledEggsTrainingData: TrainingDataItem[] = [
  // Fresh Milk
  { text: 'fresh milk', label: 'dairy' },
  { text: 'whole milk', label: 'dairy' },
  { text: 'low fat milk', label: 'dairy' },
  { text: 'skim milk', label: 'dairy' },
  { text: 'full cream milk', label: 'dairy' },
  { text: 'reduced fat milk', label: 'dairy' },
  { text: 'organic milk', label: 'dairy' },
  { text: 'pasteurized milk', label: 'dairy' },
  { text: 'uht milk', label: 'dairy' },
  { text: 'long life milk', label: 'dairy' },
  
  // Plant-Based Milk
  { text: 'soy milk', label: 'dairy' },
  { text: 'almond milk', label: 'dairy' },
  { text: 'oat milk', label: 'dairy' },
  { text: 'coconut milk', label: 'dairy' },
  { text: 'rice milk', label: 'dairy' },
  { text: 'cashew milk', label: 'dairy' },
  { text: 'macadamia milk', label: 'dairy' },
  { text: 'pea milk', label: 'dairy' },
  { text: 'hemp milk', label: 'dairy' },
  { text: 'hazelnut milk', label: 'dairy' },
  
  // Flavored Milk
  { text: 'chocolate milk', label: 'dairy' },
  { text: 'strawberry milk', label: 'dairy' },
  { text: 'banana milk', label: 'dairy' },
  { text: 'vanilla milk', label: 'dairy' },
  { text: 'malt milk', label: 'dairy' },
  { text: 'coffee milk', label: 'dairy' },
  { text: 'taro milk', label: 'dairy' },
  { text: 'matcha milk', label: 'dairy' },
  
  // Yogurt
  { text: 'yogurt', label: 'dairy' },
  { text: 'greek yogurt', label: 'dairy' },
  { text: 'plain yogurt', label: 'dairy' },
  { text: 'vanilla yogurt', label: 'dairy' },
  { text: 'strawberry yogurt', label: 'dairy' },
  { text: 'blueberry yogurt', label: 'dairy' },
  { text: 'peach yogurt', label: 'dairy' },
  { text: 'mango yogurt', label: 'dairy' },
  { text: 'mixed berry yogurt', label: 'dairy' },
  { text: 'honey yogurt', label: 'dairy' },
  { text: 'low fat yogurt', label: 'dairy' },
  { text: 'fat free yogurt', label: 'dairy' },
  { text: 'organic yogurt', label: 'dairy' },
  { text: 'probiotic yogurt', label: 'dairy' },
  { text: 'drinking yogurt', label: 'dairy' },
  { text: 'yogurt drink', label: 'dairy' },
  { text: 'lassi', label: 'dairy' },
  { text: 'kefir', label: 'dairy' },
  
  // Cheese - Local & International
  { text: 'cheese', label: 'dairy' },
  { text: 'cheddar cheese', label: 'dairy' },
  { text: 'mozzarella cheese', label: 'dairy' },
  { text: 'parmesan cheese', label: 'dairy' },
  { text: 'swiss cheese', label: 'dairy' },
  { text: 'gouda cheese', label: 'dairy' },
  { text: 'brie cheese', label: 'dairy' },
  { text: 'camembert cheese', label: 'dairy' },
  { text: 'blue cheese', label: 'dairy' },
  { text: 'feta cheese', label: 'dairy' },
  { text: 'cream cheese', label: 'dairy' },
  { text: 'cottage cheese', label: 'dairy' },
  { text: 'ricotta cheese', label: 'dairy' },
  { text: 'mascarpone cheese', label: 'dairy' },
  { text: 'processed cheese', label: 'dairy' },
  { text: 'cheese slice', label: 'dairy' },
  { text: 'string cheese', label: 'dairy' },
  { text: 'babybel cheese', label: 'dairy' },
  { text: 'laughing cow cheese', label: 'dairy' },
  { text: 'cheese spread', label: 'dairy' },
  { text: 'cheese block', label: 'dairy' },
  { text: 'shredded cheese', label: 'dairy' },
  { text: 'grated cheese', label: 'dairy' },
  
  // Butter & Spreads
  { text: 'butter', label: 'dairy' },
  { text: 'salted butter', label: 'dairy' },
  { text: 'unsalted butter', label: 'dairy' },
  { text: 'organic butter', label: 'dairy' },
  { text: 'grass fed butter', label: 'dairy' },
  { text: 'european butter', label: 'dairy' },
  { text: 'cultured butter', label: 'dairy' },
  { text: 'margarine', label: 'dairy' },
  { text: 'plant butter', label: 'dairy' },
  { text: 'vegan butter', label: 'dairy' },
  { text: 'ghee', label: 'dairy' },
  { text: 'clarified butter', label: 'dairy' },
  
  // Cream
  { text: 'cream', label: 'dairy' },
  { text: 'heavy cream', label: 'dairy' },
  { text: 'whipping cream', label: 'dairy' },
  { text: 'double cream', label: 'dairy' },
  { text: 'single cream', label: 'dairy' },
  { text: 'light cream', label: 'dairy' },
  { text: 'cooking cream', label: 'dairy' },
  { text: 'sour cream', label: 'dairy' },
  { text: 'crème fraîche', label: 'dairy' },
  { text: 'clotted cream', label: 'dairy' },
  { text: 'coconut cream', label: 'dairy' },
  { text: 'non dairy cream', label: 'dairy' },
  
  // Eggs - Chicken
  { text: 'eggs', label: 'dairy' },
  { text: 'chicken eggs', label: 'dairy' },
  { text: 'fresh eggs', label: 'dairy' },
  { text: 'cage free eggs', label: 'dairy' },
  { text: 'free range eggs', label: 'dairy' },
  { text: 'organic eggs', label: 'dairy' },
  { text: 'brown eggs', label: 'dairy' },
  { text: 'white eggs', label: 'dairy' },
  { text: 'large eggs', label: 'dairy' },
  { text: 'medium eggs', label: 'dairy' },
  { text: 'small eggs', label: 'dairy' },
  { text: 'jumbo eggs', label: 'dairy' },
  { text: 'omega 3 eggs', label: 'dairy' },
  { text: 'pastured eggs', label: 'dairy' },
  { text: 'farm fresh eggs', label: 'dairy' },
  
  // Specialty Eggs
  { text: 'duck eggs', label: 'dairy' },
  { text: 'quail eggs', label: 'dairy' },
  { text: 'goose eggs', label: 'dairy' },
  { text: 'century eggs', label: 'dairy' },
  { text: 'salted eggs', label: 'dairy' },
  { text: 'preserved eggs', label: 'dairy' },
  { text: 'tea eggs', label: 'dairy' },
  
  // Processed Egg Products
  { text: 'liquid eggs', label: 'dairy' },
  { text: 'egg whites', label: 'dairy' },
  { text: 'egg yolks', label: 'dairy' },
  { text: 'pasteurized eggs', label: 'dairy' },
  { text: 'powdered eggs', label: 'dairy' },
  { text: 'egg substitute', label: 'dairy' },
  
  // Chilled Desserts
  { text: 'pudding', label: 'dairy' },
  { text: 'custard', label: 'dairy' },
  { text: 'mousse', label: 'dairy' },
  { text: 'panna cotta', label: 'dairy' },
  { text: 'tiramisu', label: 'dairy' },
  { text: 'cheesecake', label: 'dairy' },
  { text: 'flan', label: 'dairy' },
  { text: 'crème brûlée', label: 'dairy' },
  { text: 'trifle', label: 'dairy' },
  { text: 'jelly', label: 'dairy' },
  { text: 'gelato', label: 'dairy' },
  { text: 'sorbet', label: 'dairy' },
  
  // Asian Dairy Products
  { text: 'tofu', label: 'dairy' },
  { text: 'silken tofu', label: 'dairy' },
  { text: 'firm tofu', label: 'dairy' },
  { text: 'soft tofu', label: 'dairy' },
  { text: 'tau kwa', label: 'dairy' },
  { text: 'tau pok', label: 'dairy' },
  { text: 'bean curd', label: 'dairy' },
  { text: 'soy bean curd', label: 'dairy' },
  { text: 'douhua', label: 'dairy' },
  { text: 'tau huay', label: 'dairy' },
  { text: 'soy pudding', label: 'dairy' },
  { text: 'almond tofu', label: 'dairy' },
  { text: 'miso', label: 'dairy' },
  { text: 'tempeh', label: 'dairy' },
  
  // Milk Powder & Condensed
  { text: 'milk powder', label: 'dairy' },
  { text: 'powdered milk', label: 'dairy' },
  { text: 'condensed milk', label: 'dairy' },
  { text: 'evaporated milk', label: 'dairy' },
  { text: 'sweetened condensed milk', label: 'dairy' },
  { text: 'coconut condensed milk', label: 'dairy' },
  { text: 'infant formula', label: 'dairy' },
  { text: 'baby formula', label: 'dairy' },
  { text: 'growing up milk', label: 'dairy' },
  { text: 'maternal milk', label: 'dairy' },
  
  // Chilled Beverages
  { text: 'buttermilk', label: 'dairy' },
  { text: 'chocolate drink', label: 'dairy' },
  { text: 'malted drink', label: 'dairy' },
  { text: 'protein shake', label: 'dairy' },
  { text: 'smoothie', label: 'dairy' },
  { text: 'milkshake', label: 'dairy' },
  { text: 'iced coffee', label: 'dairy' },
  { text: 'iced tea', label: 'dairy' },
  { text: 'bubble tea', label: 'dairy' },
  { text: 'milk tea', label: 'dairy' },
  
  // Specialty Dairy
  { text: 'goat milk', label: 'dairy' },
  { text: 'sheep milk', label: 'dairy' },
  { text: 'buffalo milk', label: 'dairy' },
  { text: 'camel milk', label: 'dairy' },
  { text: 'a2 milk', label: 'dairy' },
  { text: 'lactose free milk', label: 'dairy' },
  { text: 'protein milk', label: 'dairy' },
  { text: 'calcium enriched milk', label: 'dairy' },
  { text: 'vitamin d milk', label: 'dairy' },
  
  // Fermented Products
  { text: 'kimchi', label: 'dairy' },
  { text: 'sauerkraut', label: 'dairy' },
  { text: 'pickled vegetables', label: 'dairy' },
  { text: 'fermented bean paste', label: 'dairy' },
  { text: 'miso paste', label: 'dairy' },
  { text: 'kombucha', label: 'dairy' },
  { text: 'water kefir', label: 'dairy' },
  
  // Chilled Prepared Foods
  { text: 'fresh pasta', label: 'dairy' },
  { text: 'ravioli', label: 'dairy' },
  { text: 'tortellini', label: 'dairy' },
  { text: 'gnocchi', label: 'dairy' },
  { text: 'dumpling', label: 'dairy' },
  { text: 'wonton', label: 'dairy' },
  { text: 'gyoza', label: 'dairy' },
  { text: 'dim sum', label: 'dairy' },
  { text: 'siu mai', label: 'dairy' },
  { text: 'har gow', label: 'dairy' },
  
  // Chilled Soups
  { text: 'fresh soup', label: 'dairy' },
  { text: 'gazpacho', label: 'dairy' },
  { text: 'cold soup', label: 'dairy' },
  { text: 'chilled soup', label: 'dairy' },
  { text: 'bone broth', label: 'dairy' },
  { text: 'chicken broth', label: 'dairy' },
  { text: 'vegetable broth', label: 'dairy' },
  { text: 'miso soup', label: 'dairy' },
  
  // Chilled Salads
  { text: 'potato salad', label: 'dairy' },
  { text: 'coleslaw', label: 'dairy' },
  { text: 'pasta salad', label: 'dairy' },
  { text: 'chicken salad', label: 'dairy' },
  { text: 'tuna salad', label: 'dairy' },
  { text: 'egg salad', label: 'dairy' },
  { text: 'caesar salad', label: 'dairy' },
  { text: 'greek salad', label: 'dairy' },
  { text: 'garden salad', label: 'dairy' },
  { text: 'fruit salad', label: 'dairy' },
  
  // Dips & Spreads
  { text: 'hummus', label: 'dairy' },
  { text: 'guacamole', label: 'dairy' },
  { text: 'tzatziki', label: 'dairy' },
  { text: 'ranch dip', label: 'dairy' },
  { text: 'blue cheese dip', label: 'dairy' },
  { text: 'spinach dip', label: 'dairy' },
  { text: 'artichoke dip', label: 'dairy' },
  { text: 'onion dip', label: 'dairy' },
  { text: 'salsa', label: 'dairy' },
  { text: 'pesto', label: 'dairy' },
  
  // Chilled Meat Products
  { text: 'deli meat', label: 'dairy' },
  { text: 'cold cuts', label: 'dairy' },
  { text: 'ham', label: 'dairy' },
  { text: 'turkey', label: 'dairy' },
  { text: 'roast beef', label: 'dairy' },
  { text: 'salami', label: 'dairy' },
  { text: 'pepperoni', label: 'dairy' },
  { text: 'prosciutto', label: 'dairy' },
  { text: 'bacon', label: 'dairy' },
  { text: 'sausage', label: 'dairy' },
  
  // Premium & Artisanal
  { text: 'artisanal cheese', label: 'dairy' },
  { text: 'imported cheese', label: 'dairy' },
  { text: 'aged cheese', label: 'dairy' },
  { text: 'raw milk cheese', label: 'dairy' },
  { text: 'farmhouse cheese', label: 'dairy' },
  { text: 'organic yogurt', label: 'dairy' },
  { text: 'grass fed dairy', label: 'dairy' },
  { text: 'heritage breed', label: 'dairy' },
  { text: 'small batch', label: 'dairy' },
  { text: 'local dairy', label: 'dairy' }
];

export default dairyChilledEggsTrainingData;