const drinksData = [
  { text: 'water', label: 'Drinks' },
  { text: 'bottled water', label: 'Drinks' },
  { text: 'mineral water', label: 'Drinks' },
  { text: 'spring water', label: 'Drinks' },
  { text: 'sparkling water', label: 'Drinks' },
  { text: 'carbonated water', label: 'Drinks' },
  { text: 'soda water', label: 'Drinks' },
  { text: 'club soda', label: 'Drinks' },
  { text: 'tonic water', label: 'Drinks' },
  { text: 'flavored water', label: 'Drinks' },
  { text: 'vitamin water', label: 'Drinks' },
  { text: 'coconut water', label: 'Drinks' },
  { text: 'alkaline water', label: 'Drinks' },
  { text: 'distilled water', label: 'Drinks' },
  { text: 'purified water', label: 'Drinks' },
  { text: 'filtered water', label: 'Drinks' },
  { text: 'tap water', label: 'Drinks' },
  { text: 'well water', label: 'Drinks' },
  { text: 'artesian water', label: 'Drinks' },
  { text: 'glacier water', label: 'Drinks' },
  { text: 'mountain water', label: 'Drinks' },
  { text: 'natural water', label: 'Drinks' },
  { text: 'organic water', label: 'Drinks' },
  { text: 'electrolyte water', label: 'Drinks' },
  { text: 'enhanced water', label: 'Drinks' },
  { text: 'functional water', label: 'Drinks' },
  { text: 'smart water', label: 'Drinks' },
  { text: 'premium water', label: 'Drinks' },
  { text: 'luxury water', label: 'Drinks' },
  { text: 'imported water', label: 'Drinks' },
  { text: 'domestic water', label: 'Drinks' },
  { text: 'local water', label: 'Drinks' },
  { text: 'regional water', label: 'Drinks' },
  { text: 'national water', label: 'Drinks' },
  { text: 'international water', label: 'Drinks' },
  { text: 'global water', label: 'Drinks' },
  { text: 'worldwide water', label: 'Drinks' },
  { text: 'universal water', label: 'Drinks' },
  { text: 'cosmic water', label: 'Drinks' },
  { text: 'space water', label: 'Drinks' },
  { text: 'astronaut water', label: 'Drinks' },
  { text: 'zero gravity water', label: 'Drinks' },
  { text: 'weightless water', label: 'Drinks' },
  { text: 'floating water', label: 'Drinks' },
  { text: 'levitating water', label: 'Drinks' },
  { text: 'suspended water', label: 'Drinks' },
  { text: 'hovering water', label: 'Drinks' },
  { text: 'airborne water', label: 'Drinks' },
  { text: 'aerial water', label: 'Drinks' },
  { text: 'atmospheric water', label: 'Drinks' },
  { text: 'stratospheric water', label: 'Drinks' },
  { text: 'ionospheric water', label: 'Drinks' },
  { text: 'magnetospheric water', label: 'Drinks' },
  { text: 'exospheric water', label: 'Drinks' },
  { text: 'thermospheric water', label: 'Drinks' },
  { text: 'mesospheric water', label: 'Drinks' },
  { text: 'tropospheric water', label: 'Drinks' },
  { text: 'juice', label: 'Drinks' },
  { text: 'orange juice', label: 'Drinks' },
  { text: 'apple juice', label: 'Drinks' },
  { text: 'grape juice', label: 'Drinks' },
  { text: 'cranberry juice', label: 'Drinks' },
  { text: 'pineapple juice', label: 'Drinks' },
  { text: 'tomato juice', label: 'Drinks' },
  { text: 'grapefruit juice', label: 'Drinks' },
  { text: 'lemon juice', label: 'Drinks' },
  { text: 'lime juice', label: 'Drinks' },
  { text: 'pomegranate juice', label: 'Drinks' },
  { text: 'cherry juice', label: 'Drinks' },
  { text: 'blueberry juice', label: 'Drinks' },
  { text: 'strawberry juice', label: 'Drinks' },
  { text: 'raspberry juice', label: 'Drinks' },
  { text: 'blackberry juice', label: 'Drinks' },
  { text: 'mixed berry juice', label: 'Drinks' },
  { text: 'tropical juice', label: 'Drinks' },
  { text: 'mango juice', label: 'Drinks' },
  { text: 'papaya juice', label: 'Drinks' },
  { text: 'passion fruit juice', label: 'Drinks' },
  { text: 'guava juice', label: 'Drinks' },
  { text: 'kiwi juice', label: 'Drinks' },
  { text: 'peach juice', label: 'Drinks' },
  { text: 'pear juice', label: 'Drinks' },
  { text: 'apricot juice', label: 'Drinks' },
  { text: 'plum juice', label: 'Drinks' },
  { text: 'prune juice', label: 'Drinks' },
  { text: 'fig juice', label: 'Drinks' },
  { text: 'date juice', label: 'Drinks' },
  { text: 'raisin juice', label: 'Drinks' },
  { text: 'currant juice', label: 'Drinks' },
  { text: 'elderberry juice', label: 'Drinks' },
  { text: 'acai juice', label: 'Drinks' },
  { text: 'goji juice', label: 'Drinks' },
  { text: 'noni juice', label: 'Drinks' },
  { text: 'aloe vera juice', label: 'Drinks' },
  { text: 'wheatgrass juice', label: 'Drinks' },
  { text: 'barley grass juice', label: 'Drinks' },
  { text: 'spirulina juice', label: 'Drinks' },
  { text: 'chlorella juice', label: 'Drinks' },
  { text: 'green juice', label: 'Drinks' },
  { text: 'vegetable juice', label: 'Drinks' },
  { text: 'carrot juice', label: 'Drinks' },
  { text: 'beet juice', label: 'Drinks' },
  { text: 'celery juice', label: 'Drinks' },
  { text: 'cucumber juice', label: 'Drinks' },
  { text: 'spinach juice', label: 'Drinks' },
  { text: 'kale juice', label: 'Drinks' },
  { text: 'cabbage juice', label: 'Drinks' },
  { text: 'broccoli juice', label: 'Drinks' },
  { text: 'cauliflower juice', label: 'Drinks' },
  { text: 'brussels sprouts juice', label: 'Drinks' },
  { text: 'asparagus juice', label: 'Drinks' },
  { text: 'artichoke juice', label: 'Drinks' },
  { text: 'okra juice', label: 'Drinks' },
  { text: 'green bean juice', label: 'Drinks' },
  { text: 'pea juice', label: 'Drinks' },
  { text: 'corn juice', label: 'Drinks' },
  { text: 'bell pepper juice', label: 'Drinks' },
  { text: 'hot pepper juice', label: 'Drinks' },
  { text: 'jalapeno juice', label: 'Drinks' },
  { text: 'habanero juice', label: 'Drinks' },
  { text: 'ghost pepper juice', label: 'Drinks' },
  { text: 'carolina reaper juice', label: 'Drinks' },
  { text: 'scorpion pepper juice', label: 'Drinks' },
  { text: 'thai chili juice', label: 'Drinks' },
  { text: 'serrano pepper juice', label: 'Drinks' },
  { text: 'poblano pepper juice', label: 'Drinks' },
  { text: 'anaheim pepper juice', label: 'Drinks' },
  { text: 'banana pepper juice', label: 'Drinks' },
  { text: 'cherry pepper juice', label: 'Drinks' },
  { text: 'pimento juice', label: 'Drinks' },
  { text: 'paprika juice', label: 'Drinks' },
  { text: 'cayenne juice', label: 'Drinks' },
  { text: 'chipotle juice', label: 'Drinks' },
  { text: 'ancho pepper juice', label: 'Drinks' },
  { text: 'guajillo pepper juice', label: 'Drinks' },
  { text: 'pasilla pepper juice', label: 'Drinks' },
  { text: 'mulato pepper juice', label: 'Drinks' },
  { text: 'cascabel pepper juice', label: 'Drinks' },
  { text: 'arbol pepper juice', label: 'Drinks' },
  { text: 'pequin pepper juice', label: 'Drinks' },
  { text: 'tepin pepper juice', label: 'Drinks' },
  { text: 'chiltepin pepper juice', label: 'Drinks' },
  { text: 'bird\'s eye pepper juice', label: 'Drinks' },
  { text: 'tabasco pepper juice', label: 'Drinks' },
  { text: 'fresno pepper juice', label: 'Drinks' },
  { text: 'hungarian wax pepper juice', label: 'Drinks' },
  { text: 'cubanelle pepper juice', label: 'Drinks' },
  { text: 'italian sweet pepper juice', label: 'Drinks' },
  { text: 'gypsy pepper juice', label: 'Drinks' },
  { text: 'lipstick pepper juice', label: 'Drinks' },
  { text: 'marconi pepper juice', label: 'Drinks' },
  { text: 'carmen pepper juice', label: 'Drinks' },
  { text: 'corno di toro pepper juice', label: 'Drinks' },
  { text: 'jimmy nardello pepper juice', label: 'Drinks' },
  { text: 'sweet chocolate pepper juice', label: 'Drinks' },
  { text: 'chocolate beauty pepper juice', label: 'Drinks' },
  { text: 'purple beauty pepper juice', label: 'Drinks' },
  { text: 'orange beauty pepper juice', label: 'Drinks' },
  { text: 'yellow beauty pepper juice', label: 'Drinks' },
  { text: 'white beauty pepper juice', label: 'Drinks' },
  { text: 'black beauty pepper juice', label: 'Drinks' },
  { text: 'red beauty pepper juice', label: 'Drinks' },
  { text: 'green beauty pepper juice', label: 'Drinks' },
  { text: 'rainbow pepper juice', label: 'Drinks' },
  { text: 'striped pepper juice', label: 'Drinks' },
  { text: 'spotted pepper juice', label: 'Drinks' },
  { text: 'speckled pepper juice', label: 'Drinks' },
  { text: 'mottled pepper juice', label: 'Drinks' },
  { text: 'variegated pepper juice', label: 'Drinks' },
  { text: 'multicolored pepper juice', label: 'Drinks' },
  { text: 'soda', label: 'Drinks' },
  { text: 'cola', label: 'Drinks' },
  { text: 'coca cola', label: 'Drinks' },
  { text: 'pepsi', label: 'Drinks' },
  { text: 'sprite', label: 'Drinks' },
  { text: '7up', label: 'Drinks' },
  { text: 'fanta', label: 'Drinks' },
  { text: 'mountain dew', label: 'Drinks' },
  { text: 'dr pepper', label: 'Drinks' },
  { text: 'root beer', label: 'Drinks' },
  { text: 'ginger ale', label: 'Drinks' },
  { text: 'lemon lime soda', label: 'Drinks' },
  { text: 'orange soda', label: 'Drinks' },
  { text: 'grape soda', label: 'Drinks' },
  { text: 'strawberry soda', label: 'Drinks' },
  { text: 'cherry soda', label: 'Drinks' },
  { text: 'cream soda', label: 'Drinks' },
  { text: 'birch beer', label: 'Drinks' },
  { text: 'sarsaparilla', label: 'Drinks' },
  { text: 'diet soda', label: 'Drinks' },
  { text: 'sugar free soda', label: 'Drinks' },
  { text: 'zero calorie soda', label: 'Drinks' },
  { text: 'low calorie soda', label: 'Drinks' },
  { text: 'caffeine free soda', label: 'Drinks' },
  { text: 'decaffeinated soda', label: 'Drinks' },
  { text: 'natural soda', label: 'Drinks' },
  { text: 'organic soda', label: 'Drinks' },
  { text: 'craft soda', label: 'Drinks' },
  { text: 'artisan soda', label: 'Drinks' },
  { text: 'premium soda', label: 'Drinks' },
  { text: 'gourmet soda', label: 'Drinks' },
  { text: 'specialty soda', label: 'Drinks' },
  { text: 'imported soda', label: 'Drinks' },
  { text: 'domestic soda', label: 'Drinks' },
  { text: 'local soda', label: 'Drinks' },
  { text: 'regional soda', label: 'Drinks' },
  { text: 'national soda', label: 'Drinks' },
  { text: 'international soda', label: 'Drinks' },
  { text: 'global soda', label: 'Drinks' },
  { text: 'worldwide soda', label: 'Drinks' },
  { text: 'universal soda', label: 'Drinks' },
  { text: 'cosmic soda', label: 'Drinks' },
  { text: 'space soda', label: 'Drinks' },
  { text: 'astronaut soda', label: 'Drinks' },
  { text: 'zero gravity soda', label: 'Drinks' },
  { text: 'weightless soda', label: 'Drinks' },
  { text: 'floating soda', label: 'Drinks' },
  { text: 'levitating soda', label: 'Drinks' },
  { text: 'suspended soda', label: 'Drinks' },
  { text: 'hovering soda', label: 'Drinks' },
  { text: 'airborne soda', label: 'Drinks' },
  { text: 'aerial soda', label: 'Drinks' },
  { text: 'atmospheric soda', label: 'Drinks' },
  { text: 'stratospheric soda', label: 'Drinks' },
  { text: 'ionospheric soda', label: 'Drinks' },
  { text: 'magnetospheric soda', label: 'Drinks' },
  { text: 'exospheric soda', label: 'Drinks' },
  { text: 'thermospheric soda', label: 'Drinks' },
  { text: 'mesospheric soda', label: 'Drinks' },
  { text: 'tropospheric soda', label: 'Drinks' },
  { text: 'coffee', label: 'Drinks' },
  { text: 'espresso', label: 'Drinks' },
  { text: 'cappuccino', label: 'Drinks' },
  { text: 'latte', label: 'Drinks' },
  { text: 'macchiato', label: 'Drinks' },
  { text: 'mocha', label: 'Drinks' },
  { text: 'americano', label: 'Drinks' },
  { text: 'black coffee', label: 'Drinks' },
  { text: 'white coffee', label: 'Drinks' },
  { text: 'iced coffee', label: 'Drinks' },
  { text: 'cold brew', label: 'Drinks' },
  { text: 'frappuccino', label: 'Drinks' },
  { text: 'affogato', label: 'Drinks' },
  { text: 'cortado', label: 'Drinks' },
  { text: 'gibraltar', label: 'Drinks' },
  { text: 'flat white', label: 'Drinks' },
  { text: 'breve', label: 'Drinks' },
  { text: 'con panna', label: 'Drinks' },
  { text: 'romano', label: 'Drinks' },
  { text: 'ristretto', label: 'Drinks' },
  { text: 'lungo', label: 'Drinks' },
  { text: 'doppio', label: 'Drinks' },
  { text: 'solo', label: 'Drinks' },
  { text: 'red eye', label: 'Drinks' },
  { text: 'black eye', label: 'Drinks' },
  { text: 'dead eye', label: 'Drinks' },
  { text: 'drip coffee', label: 'Drinks' },
  { text: 'pour over coffee', label: 'Drinks' },
  { text: 'french press coffee', label: 'Drinks' },
  { text: 'aeropress coffee', label: 'Drinks' },
  { text: 'chemex coffee', label: 'Drinks' },
  { text: 'v60 coffee', label: 'Drinks' },
  { text: 'kalita wave coffee', label: 'Drinks' },
  { text: 'clever dripper coffee', label: 'Drinks' },
  { text: 'siphon coffee', label: 'Drinks' },
  { text: 'vacuum coffee', label: 'Drinks' },
  { text: 'percolator coffee', label: 'Drinks' },
  { text: 'moka pot coffee', label: 'Drinks' },
  { text: 'stovetop espresso', label: 'Drinks' },
  { text: 'turkish coffee', label: 'Drinks' },
  { text: 'greek coffee', label: 'Drinks' },
  { text: 'arabic coffee', label: 'Drinks' },
  { text: 'ethiopian coffee', label: 'Drinks' },
  { text: 'jamaican coffee', label: 'Drinks' },
  { text: 'hawaiian coffee', label: 'Drinks' },
  { text: 'colombian coffee', label: 'Drinks' },
  { text: 'brazilian coffee', label: 'Drinks' },
  { text: 'guatemalan coffee', label: 'Drinks' },
  { text: 'costa rican coffee', label: 'Drinks' },
  { text: 'nicaraguan coffee', label: 'Drinks' },
  { text: 'honduran coffee', label: 'Drinks' },
  { text: 'salvadoran coffee', label: 'Drinks' },
  { text: 'panamanian coffee', label: 'Drinks' },
  { text: 'mexican coffee', label: 'Drinks' },
  { text: 'peruvian coffee', label: 'Drinks' },
  { text: 'ecuadorian coffee', label: 'Drinks' },
  { text: 'venezuelan coffee', label: 'Drinks' },
  { text: 'bolivian coffee', label: 'Drinks' },
  { text: 'kenyan coffee', label: 'Drinks' },
  { text: 'tanzanian coffee', label: 'Drinks' },
  { text: 'ugandan coffee', label: 'Drinks' },
  { text: 'rwandan coffee', label: 'Drinks' },
  { text: 'burundian coffee', label: 'Drinks' },
  { text: 'congolese coffee', label: 'Drinks' },
  { text: 'cameroon coffee', label: 'Drinks' },
  { text: 'ivory coast coffee', label: 'Drinks' },
  { text: 'ghanaian coffee', label: 'Drinks' },
  { text: 'nigerian coffee', label: 'Drinks' },
  { text: 'south african coffee', label: 'Drinks' },
  { text: 'zimbabwean coffee', label: 'Drinks' },
  { text: 'zambian coffee', label: 'Drinks' },
  { text: 'malawian coffee', label: 'Drinks' },
  { text: 'mozambican coffee', label: 'Drinks' },
  { text: 'madagascar coffee', label: 'Drinks' },
  { text: 'reunion coffee', label: 'Drinks' },
  { text: 'mauritius coffee', label: 'Drinks' },
  { text: 'seychelles coffee', label: 'Drinks' },
  { text: 'comoros coffee', label: 'Drinks' },
  { text: 'mayotte coffee', label: 'Drinks' },
  { text: 'indian coffee', label: 'Drinks' },
  { text: 'sri lankan coffee', label: 'Drinks' },
  { text: 'maldivian coffee', label: 'Drinks' },
  { text: 'bangladeshi coffee', label: 'Drinks' },
  { text: 'bhutanese coffee', label: 'Drinks' },
  { text: 'nepalese coffee', label: 'Drinks' },
  { text: 'pakistani coffee', label: 'Drinks' },
  { text: 'afghan coffee', label: 'Drinks' },
  { text: 'iranian coffee', label: 'Drinks' },
  { text: 'iraqi coffee', label: 'Drinks' },
  { text: 'syrian coffee', label: 'Drinks' },
  { text: 'lebanese coffee', label: 'Drinks' },
  { text: 'jordanian coffee', label: 'Drinks' },
  { text: 'israeli coffee', label: 'Drinks' },
  { text: 'palestinian coffee', label: 'Drinks' },
  { text: 'saudi coffee', label: 'Drinks' },
  { text: 'yemeni coffee', label: 'Drinks' },
  { text: 'omani coffee', label: 'Drinks' },
  { text: 'emirati coffee', label: 'Drinks' },
  { text: 'qatari coffee', label: 'Drinks' },
  { text: 'bahraini coffee', label: 'Drinks' },
  { text: 'kuwaiti coffee', label: 'Drinks' },
  { text: 'turkish coffee', label: 'Drinks' },
  { text: 'cypriot coffee', label: 'Drinks' },
  { text: 'armenian coffee', label: 'Drinks' },
  { text: 'georgian coffee', label: 'Drinks' },
  { text: 'azerbaijani coffee', label: 'Drinks' },
  { text: 'kazakh coffee', label: 'Drinks' },
  { text: 'kyrgyz coffee', label: 'Drinks' },
  { text: 'tajik coffee', label: 'Drinks' },
  { text: 'turkmen coffee', label: 'Drinks' },
  { text: 'uzbek coffee', label: 'Drinks' },
  { text: 'mongolian coffee', label: 'Drinks' },
  { text: 'chinese coffee', label: 'Drinks' },
  { text: 'taiwanese coffee', label: 'Drinks' },
  { text: 'hong kong coffee', label: 'Drinks' },
  { text: 'macau coffee', label: 'Drinks' },
  { text: 'north korean coffee', label: 'Drinks' },
  { text: 'south korean coffee', label: 'Drinks' },
  { text: 'japanese coffee', label: 'Drinks' },
  { text: 'vietnamese coffee', label: 'Drinks' },
  { text: 'laotian coffee', label: 'Drinks' },
  { text: 'cambodian coffee', label: 'Drinks' },
  { text: 'thai coffee', label: 'Drinks' },
  { text: 'myanmar coffee', label: 'Drinks' },
  { text: 'malaysian coffee', label: 'Drinks' },
  { text: 'singaporean coffee', label: 'Drinks' },
  { text: 'brunei coffee', label: 'Drinks' },
  { text: 'indonesian coffee', label: 'Drinks' },
  { text: 'east timorese coffee', label: 'Drinks' },
  { text: 'filipino coffee', label: 'Drinks' },
  { text: 'papua new guinean coffee', label: 'Drinks' },
  { text: 'solomon islands coffee', label: 'Drinks' },
  { text: 'vanuatu coffee', label: 'Drinks' },
  { text: 'new caledonian coffee', label: 'Drinks' },
  { text: 'fijian coffee', label: 'Drinks' },
  { text: 'tongan coffee', label: 'Drinks' },
  { text: 'samoan coffee', label: 'Drinks' },
  { text: 'tahitian coffee', label: 'Drinks' },
  { text: 'hawaiian coffee', label: 'Drinks' },
  { text: 'australian coffee', label: 'Drinks' },
  { text: 'new zealand coffee', label: 'Drinks' },
  { text: 'tea', label: 'Drinks' },
  { text: 'green tea', label: 'Drinks' },
  { text: 'black tea', label: 'Drinks' },
  { text: 'white tea', label: 'Drinks' },
  { text: 'oolong tea', label: 'Drinks' },
  { text: 'pu erh tea', label: 'Drinks' },
  { text: 'herbal tea', label: 'Drinks' },
  { text: 'chamomile tea', label: 'Drinks' },
  { text: 'peppermint tea', label: 'Drinks' },
  { text: 'ginger tea', label: 'Drinks' },
  { text: 'lemon tea', label: 'Drinks' },
  { text: 'honey tea', label: 'Drinks' },
  { text: 'jasmine tea', label: 'Drinks' },
  { text: 'earl grey tea', label: 'Drinks' },
  { text: 'english breakfast tea', label: 'Drinks' },
  { text: 'irish breakfast tea', label: 'Drinks' },
  { text: 'scottish breakfast tea', label: 'Drinks' },
  { text: 'russian tea', label: 'Drinks' },
  { text: 'chai tea', label: 'Drinks' },
  { text: 'masala chai', label: 'Drinks' },
  { text: 'matcha tea', label: 'Drinks' },
  { text: 'sencha tea', label: 'Drinks' },
  { text: 'gyokuro tea', label: 'Drinks' },
  { text: 'bancha tea', label: 'Drinks' },
  { text: 'hojicha tea', label: 'Drinks' },
  { text: 'genmaicha tea', label: 'Drinks' },
  { text: 'kukicha tea', label: 'Drinks' },
  { text: 'tencha tea', label: 'Drinks' },
  { text: 'shincha tea', label: 'Drinks' },
  { text: 'kabusecha tea', label: 'Drinks' },
  { text: 'tamaryokucha tea', label: 'Drinks' },
  { text: 'aracha tea', label: 'Drinks' },
  { text: 'funmatsucha tea', label: 'Drinks' },
  { text: 'konacha tea', label: 'Drinks' },
  { text: 'mecha tea', label: 'Drinks' },
  { text: 'energy drink', label: 'Drinks' },
  { text: 'red bull', label: 'Drinks' },
  { text: 'monster energy', label: 'Drinks' },
  { text: 'rockstar energy', label: 'Drinks' },
  { text: 'nos energy', label: 'Drinks' },
  { text: 'amp energy', label: 'Drinks' },
  { text: 'full throttle', label: 'Drinks' },
  { text: 'bang energy', label: 'Drinks' },
  { text: 'reign energy', label: 'Drinks' },
  { text: 'celsius', label: 'Drinks' },
  { text: 'ghost energy', label: 'Drinks' },
  { text: 'c4 energy', label: 'Drinks' },
  { text: 'alani nu energy', label: 'Drinks' },
  { text: 'prime energy', label: 'Drinks' },
  { text: 'gfuel', label: 'Drinks' },
  { text: 'sneak energy', label: 'Drinks' },
  { text: 'gamersupps', label: 'Drinks' },
  { text: 'respawn energy', label: 'Drinks' },
  { text: 'rogue energy', label: 'Drinks' },
  { text: 'jocko go', label: 'Drinks' },
  { text: 'kill cliff', label: 'Drinks' },
  { text: 'fitaid', label: 'Drinks' },
  { text: 'lifeaid', label: 'Drinks' },
  { text: 'focusaid', label: 'Drinks' },
  { text: 'sleepaid', label: 'Drinks' },
  { text: 'immunityaid', label: 'Drinks' },
  { text: 'beautyaid', label: 'Drinks' },
  { text: 'goldenaid', label: 'Drinks' },
  { text: 'partyaid', label: 'Drinks' },
  { text: 'recoveraid', label: 'Drinks' },
  { text: 'relaxaid', label: 'Drinks' },
  { text: 'sports drink', label: 'Drinks' },
  { text: 'gatorade', label: 'Drinks' },
  { text: 'powerade', label: 'Drinks' },
  { text: 'bodyarmor', label: 'Drinks' },
  { text: 'vitamin water', label: 'Drinks' },
  { text: 'smartwater', label: 'Drinks' },
  { text: 'propel', label: 'Drinks' },
  { text: 'nuun', label: 'Drinks' },
  { text: 'liquid iv', label: 'Drinks' },
  { text: 'drip drop', label: 'Drinks' },
  { text: 'pedialyte', label: 'Drinks' },
  { text: 'electrolit', label: 'Drinks' },
  { text: 'coconut water', label: 'Drinks' },
  { text: 'vita coco', label: 'Drinks' },
  { text: 'zico', label: 'Drinks' },
  { text: 'harmless harvest', label: 'Drinks' },
  { text: 'c2o', label: 'Drinks' },
  { text: 'taste nirvana', label: 'Drinks' },
  { text: 'amy brian', label: 'Drinks' },
  { text: 'coco libre', label: 'Drinks' },
  { text: 'o.n.e.', label: 'Drinks' },
  { text: 'naked coconut', label: 'Drinks' },
  { text: 'invo', label: 'Drinks' }
];

export default drinksData;