/**
 * Training data for Drinks category
 * Singapore-focused beverages and drinks
 */

export interface TrainingDataItem {
  text: string;
  label: string;
}

export const drinksTrainingData: TrainingDataItem[] = [
  // Water
  { text: 'water', label: 'drinks' },
  { text: 'mineral water', label: 'drinks' },
  { text: 'spring water', label: 'drinks' },
  { text: 'distilled water', label: 'drinks' },
  { text: 'sparkling water', label: 'drinks' },
  { text: 'carbonated water', label: 'drinks' },
  { text: 'flavored water', label: 'drinks' },
  { text: 'vitamin water', label: 'drinks' },
  { text: 'alkaline water', label: 'drinks' },
  { text: 'coconut water', label: 'drinks' },
  { text: 'evian water', label: 'drinks' },
  { text: 'perrier water', label: 'drinks' },
  { text: 'dasani water', label: 'drinks' },
  { text: 'aquafina water', label: 'drinks' },
  { text: 'ice mountain water', label: 'drinks' },
  
  // Soft Drinks & Sodas
  { text: 'soft drinks', label: 'drinks' },
  { text: 'soda', label: 'drinks' },
  { text: 'cola', label: 'drinks' },
  { text: 'coca cola', label: 'drinks' },
  { text: 'pepsi', label: 'drinks' },
  { text: 'sprite', label: 'drinks' },
  { text: '7up', label: 'drinks' },
  { text: 'fanta', label: 'drinks' },
  { text: 'orange soda', label: 'drinks' },
  { text: 'lemon lime soda', label: 'drinks' },
  { text: 'ginger ale', label: 'drinks' },
  { text: 'root beer', label: 'drinks' },
  { text: 'dr pepper', label: 'drinks' },
  { text: 'mountain dew', label: 'drinks' },
  { text: 'diet coke', label: 'drinks' },
  { text: 'coke zero', label: 'drinks' },
  { text: 'diet pepsi', label: 'drinks' },
  { text: 'sugar free soda', label: 'drinks' },
  
  // Asian Soft Drinks
  { text: 'green spot', label: 'drinks' },
  { text: 'sarsi', label: 'drinks' },
  { text: 'kickapoo', label: 'drinks' },
  { text: 'ice lemon tea', label: 'drinks' },
  { text: 'chrysanthemum tea', label: 'drinks' },
  { text: 'winter melon tea', label: 'drinks' },
  { text: 'bandung', label: 'drinks' },
  { text: 'teh tarik', label: 'drinks' },
  { text: 'kopi', label: 'drinks' },
  { text: 'milo', label: 'drinks' },
  { text: 'horlicks', label: 'drinks' },
  { text: 'ovaltine', label: 'drinks' },
  { text: 'ribena', label: 'drinks' },
  { text: 'vitasoy', label: 'drinks' },
  { text: 'yeo hiap seng', label: 'drinks' },
  { text: 'pokka', label: 'drinks' },
  
  // Juices
  { text: 'juice', label: 'drinks' },
  { text: 'fruit juice', label: 'drinks' },
  { text: 'orange juice', label: 'drinks' },
  { text: 'apple juice', label: 'drinks' },
  { text: 'grape juice', label: 'drinks' },
  { text: 'cranberry juice', label: 'drinks' },
  { text: 'pineapple juice', label: 'drinks' },
  { text: 'mango juice', label: 'drinks' },
  { text: 'guava juice', label: 'drinks' },
  { text: 'passion fruit juice', label: 'drinks' },
  { text: 'lychee juice', label: 'drinks' },
  { text: 'coconut juice', label: 'drinks' },
  { text: 'watermelon juice', label: 'drinks' },
  { text: 'papaya juice', label: 'drinks' },
  { text: 'tomato juice', label: 'drinks' },
  { text: 'vegetable juice', label: 'drinks' },
  { text: 'carrot juice', label: 'drinks' },
  { text: 'beetroot juice', label: 'drinks' },
  { text: 'celery juice', label: 'drinks' },
  { text: 'green juice', label: 'drinks' },
  { text: 'mixed fruit juice', label: 'drinks' },
  { text: 'fresh juice', label: 'drinks' },
  { text: 'cold pressed juice', label: 'drinks' },
  { text: '100% juice', label: 'drinks' },
  { text: 'no sugar added juice', label: 'drinks' },
  
  // Tea
  { text: 'tea', label: 'drinks' },
  { text: 'black tea', label: 'drinks' },
  { text: 'green tea', label: 'drinks' },
  { text: 'white tea', label: 'drinks' },
  { text: 'oolong tea', label: 'drinks' },
  { text: 'earl grey tea', label: 'drinks' },
  { text: 'english breakfast tea', label: 'drinks' },
  { text: 'jasmine tea', label: 'drinks' },
  { text: 'chamomile tea', label: 'drinks' },
  { text: 'peppermint tea', label: 'drinks' },
  { text: 'ginger tea', label: 'drinks' },
  { text: 'lemon tea', label: 'drinks' },
  { text: 'honey tea', label: 'drinks' },
  { text: 'herbal tea', label: 'drinks' },
  { text: 'fruit tea', label: 'drinks' },
  { text: 'bubble tea', label: 'drinks' },
  { text: 'milk tea', label: 'drinks' },
  { text: 'thai tea', label: 'drinks' },
  { text: 'matcha', label: 'drinks' },
  { text: 'matcha latte', label: 'drinks' },
  { text: 'iced tea', label: 'drinks' },
  { text: 'sweet tea', label: 'drinks' },
  { text: 'unsweetened tea', label: 'drinks' },
  { text: 'bottled tea', label: 'drinks' },
  { text: 'ready to drink tea', label: 'drinks' },
  
  // Coffee
  { text: 'coffee', label: 'drinks' },
  { text: 'black coffee', label: 'drinks' },
  { text: 'espresso', label: 'drinks' },
  { text: 'americano', label: 'drinks' },
  { text: 'latte', label: 'drinks' },
  { text: 'cappuccino', label: 'drinks' },
  { text: 'macchiato', label: 'drinks' },
  { text: 'mocha', label: 'drinks' },
  { text: 'frappuccino', label: 'drinks' },
  { text: 'iced coffee', label: 'drinks' },
  { text: 'cold brew', label: 'drinks' },
  { text: 'instant coffee', label: 'drinks' },
  { text: 'ground coffee', label: 'drinks' },
  { text: 'coffee beans', label: 'drinks' },
  { text: 'decaf coffee', label: 'drinks' },
  { text: 'coffee pods', label: 'drinks' },
  { text: 'nespresso', label: 'drinks' },
  { text: 'keurig', label: 'drinks' },
  { text: 'bottled coffee', label: 'drinks' },
  { text: 'ready to drink coffee', label: 'drinks' },
  { text: 'coffee concentrate', label: 'drinks' },
  { text: 'vietnamese coffee', label: 'drinks' },
  { text: 'kopi o', label: 'drinks' },
  { text: 'kopi c', label: 'drinks' },
  
  // Energy Drinks
  { text: 'energy drink', label: 'drinks' },
  { text: 'red bull', label: 'drinks' },
  { text: 'monster energy', label: 'drinks' },
  { text: 'rockstar energy', label: 'drinks' },
  { text: '5 hour energy', label: 'drinks' },
  { text: 'gatorade', label: 'drinks' },
  { text: 'powerade', label: 'drinks' },
  { text: 'sports drink', label: 'drinks' },
  { text: 'isotonic drink', label: 'drinks' },
  { text: 'electrolyte drink', label: 'drinks' },
  { text: 'rehydration drink', label: 'drinks' },
  { text: 'recovery drink', label: 'drinks' },
  { text: 'pre workout drink', label: 'drinks' },
  { text: 'post workout drink', label: 'drinks' },
  { text: 'protein drink', label: 'drinks' },
  { text: 'amino acid drink', label: 'drinks' },
  { text: 'bcaa drink', label: 'drinks' },
  { text: 'creatine drink', label: 'drinks' },
  
  // Traditional Asian Drinks
  { text: 'soy bean drink', label: 'drinks' },
  { text: 'tau huay water', label: 'drinks' },
  { text: 'grass jelly drink', label: 'drinks' },
  { text: 'chin chow', label: 'drinks' },
  { text: 'barley water', label: 'drinks' },
  { text: 'corn silk tea', label: 'drinks' },
  { text: 'red date tea', label: 'drinks' },
  { text: 'longan drink', label: 'drinks' },
  { text: 'bird nest drink', label: 'drinks' },
  { text: 'ginseng drink', label: 'drinks' },
  { text: 'herbal drink', label: 'drinks' },
  { text: 'cooling tea', label: 'drinks' },
  { text: 'luo han guo', label: 'drinks' },
  { text: 'honeysuckle tea', label: 'drinks' },
  { text: 'pandan drink', label: 'drinks' },
  { text: 'sugarcane juice', label: 'drinks' },
  { text: 'lime juice', label: 'drinks' },
  { text: 'lime water', label: 'drinks' },
  { text: 'barley lime', label: 'drinks' },
  
  // Functional Drinks
  { text: 'functional beverage', label: 'drinks' },
  { text: 'health drink', label: 'drinks' },
  { text: 'wellness drink', label: 'drinks' },
  { text: 'vitamin drink', label: 'drinks' },
  { text: 'mineral drink', label: 'drinks' },
  { text: 'antioxidant drink', label: 'drinks' },
  { text: 'immune boost drink', label: 'drinks' },
  { text: 'detox drink', label: 'drinks' },
  { text: 'cleanse drink', label: 'drinks' },
  { text: 'digestive drink', label: 'drinks' },
  { text: 'fiber drink', label: 'drinks' },
  { text: 'collagen drink', label: 'drinks' },
  { text: 'beauty drink', label: 'drinks' },
  { text: 'anti aging drink', label: 'drinks' },
  { text: 'weight loss drink', label: 'drinks' },
  { text: 'meal replacement drink', label: 'drinks' },
  { text: 'protein shake', label: 'drinks' },
  { text: 'whey protein', label: 'drinks' },
  { text: 'casein protein', label: 'drinks' },
  { text: 'plant protein', label: 'drinks' },
  
  // Kombucha & Fermented Drinks
  { text: 'kombucha', label: 'drinks' },
  { text: 'fermented tea', label: 'drinks' },
  { text: 'probiotic tea', label: 'drinks' },
  { text: 'jun', label: 'drinks' },
  { text: 'water kefir', label: 'drinks' },
  { text: 'kvass', label: 'drinks' },
  { text: 'tepache', label: 'drinks' },
  { text: 'switchel', label: 'drinks' },
  { text: 'drinking vinegar', label: 'drinks' },
  { text: 'apple cider vinegar drink', label: 'drinks' },
  { text: 'shrub', label: 'drinks' },
  { text: 'live culture drink', label: 'drinks' },
  
  // Mocktails & Non-Alcoholic
  { text: 'mocktail', label: 'drinks' },
  { text: 'virgin cocktail', label: 'drinks' },
  { text: 'non alcoholic beer', label: 'drinks' },
  { text: 'alcohol free wine', label: 'drinks' },
  { text: 'virgin mojito', label: 'drinks' },
  { text: 'virgin bloody mary', label: 'drinks' },
  { text: 'shirley temple', label: 'drinks' },
  { text: 'arnold palmer', label: 'drinks' },
  { text: 'lemonade', label: 'drinks' },
  { text: 'pink lemonade', label: 'drinks' },
  { text: 'fruit punch', label: 'drinks' },
  { text: 'cocktail mixer', label: 'drinks' },
  { text: 'tonic water', label: 'drinks' },
  { text: 'club soda', label: 'drinks' },
  { text: 'ginger beer', label: 'drinks' },
  { text: 'bitter lemon', label: 'drinks' },
  
  // Hot Beverages
  { text: 'hot chocolate', label: 'drinks' },
  { text: 'cocoa', label: 'drinks' },
  { text: 'hot cocoa', label: 'drinks' },
  { text: 'drinking chocolate', label: 'drinks' },
  { text: 'chai', label: 'drinks' },
  { text: 'chai latte', label: 'drinks' },
  { text: 'spiced tea', label: 'drinks' },
  { text: 'mulled cider', label: 'drinks' },
  { text: 'hot toddy', label: 'drinks' },
  { text: 'warm milk', label: 'drinks' },
  { text: 'golden milk', label: 'drinks' },
  { text: 'turmeric latte', label: 'drinks' },
  { text: 'bone broth', label: 'drinks' },
  { text: 'broth', label: 'drinks' },
  
  // Specialty & Artisan Drinks
  { text: 'craft soda', label: 'drinks' },
  { text: 'artisan juice', label: 'drinks' },
  { text: 'small batch coffee', label: 'drinks' },
  { text: 'single origin coffee', label: 'drinks' },
  { text: 'specialty tea', label: 'drinks' },
  { text: 'premium water', label: 'drinks' },
  { text: 'imported drinks', label: 'drinks' },
  { text: 'organic drinks', label: 'drinks' },
  { text: 'natural drinks', label: 'drinks' },
  { text: 'raw juice', label: 'drinks' },
  { text: 'unpasteurized juice', label: 'drinks' },
  { text: 'fresh pressed juice', label: 'drinks' },
  { text: 'cold pressed juice', label: 'drinks' },
  { text: 'nitro coffee', label: 'drinks' },
  { text: 'nitrogen infused', label: 'drinks' },
  
  // Diet & Sugar-Free
  { text: 'diet drinks', label: 'drinks' },
  { text: 'sugar free drinks', label: 'drinks' },
  { text: 'zero calorie drinks', label: 'drinks' },
  { text: 'low calorie drinks', label: 'drinks' },
  { text: 'no added sugar', label: 'drinks' },
  { text: 'unsweetened drinks', label: 'drinks' },
  { text: 'stevia sweetened', label: 'drinks' },
  { text: 'monk fruit sweetened', label: 'drinks' },
  { text: 'erythritol sweetened', label: 'drinks' },
  { text: 'xylitol sweetened', label: 'drinks' },
  { text: 'aspartame free', label: 'drinks' },
  { text: 'artificial sweetener free', label: 'drinks' },
  
  // Kids Drinks
  { text: 'kids drinks', label: 'drinks' },
  { text: 'children drinks', label: 'drinks' },
  { text: 'baby drinks', label: 'drinks' },
  { text: 'toddler drinks', label: 'drinks' },
  { text: 'juice box', label: 'drinks' },
  { text: 'juice pouch', label: 'drinks' },
  { text: 'capri sun', label: 'drinks' },
  { text: 'hi c', label: 'drinks' },
  { text: 'kool aid', label: 'drinks' },
  { text: 'chocolate milk box', label: 'drinks' },
  { text: 'flavored milk box', label: 'drinks' },
  { text: 'organic kids juice', label: 'drinks' },
  { text: 'no sugar kids drinks', label: 'drinks' },
  { text: 'vitamin enriched kids drinks', label: 'drinks' }
];

export default drinksTrainingData;