// Training data for Electronics category
// Singapore-specific electronics and tech products

export const electronicsTrainingData = [
  // Mobile devices and accessories
  { text: 'smartphone', label: 'electronics' },
  { text: 'phone case', label: 'electronics' },
  { text: 'screen protector', label: 'electronics' },
  { text: 'phone charger', label: 'electronics' },
  { text: 'wireless charger', label: 'electronics' },
  { text: 'power bank', label: 'electronics' },
  { text: 'phone stand', label: 'electronics' },
  { text: 'car mount', label: 'electronics' },
  { text: 'selfie stick', label: 'electronics' },
  { text: 'phone grip', label: 'electronics' },
  { text: 'bluetooth earphones', label: 'electronics' },
  { text: 'wireless earbuds', label: 'electronics' },
  { text: 'airpods', label: 'electronics' },
  { text: 'headphones', label: 'electronics' },
  { text: 'earphones', label: 'electronics' },
  
  // Computing
  { text: 'laptop', label: 'electronics' },
  { text: 'tablet', label: 'electronics' },
  { text: 'ipad', label: 'electronics' },
  { text: 'computer mouse', label: 'electronics' },
  { text: 'keyboard', label: 'electronics' },
  { text: 'monitor', label: 'electronics' },
  { text: 'webcam', label: 'electronics' },
  { text: 'laptop stand', label: 'electronics' },
  { text: 'laptop bag', label: 'electronics' },
  { text: 'usb cable', label: 'electronics' },
  { text: 'usb hub', label: 'electronics' },
  { text: 'external hard drive', label: 'electronics' },
  { text: 'flash drive', label: 'electronics' },
  { text: 'memory card', label: 'electronics' },
  { text: 'sd card', label: 'electronics' },
  
  // Audio and entertainment
  { text: 'bluetooth speaker', label: 'electronics' },
  { text: 'portable speaker', label: 'electronics' },
  { text: 'soundbar', label: 'electronics' },
  { text: 'smart tv', label: 'electronics' },
  { text: 'streaming device', label: 'electronics' },
  { text: 'chromecast', label: 'electronics' },
  { text: 'apple tv', label: 'electronics' },
  { text: 'hdmi cable', label: 'electronics' },
  { text: 'aux cable', label: 'electronics' },
  { text: 'microphone', label: 'electronics' },
  { text: 'karaoke mic', label: 'electronics' },
  { text: 'radio', label: 'electronics' },
  { text: 'cd player', label: 'electronics' },
  { text: 'record player', label: 'electronics' },
  { text: 'vinyl records', label: 'electronics' },
  
  // Gaming
  { text: 'gaming console', label: 'electronics' },
  { text: 'playstation', label: 'electronics' },
  { text: 'xbox', label: 'electronics' },
  { text: 'nintendo switch', label: 'electronics' },
  { text: 'gaming controller', label: 'electronics' },
  { text: 'gaming headset', label: 'electronics' },
  { text: 'gaming mouse', label: 'electronics' },
  { text: 'gaming keyboard', label: 'electronics' },
  { text: 'gaming chair', label: 'electronics' },
  { text: 'video games', label: 'electronics' },
  { text: 'game cartridge', label: 'electronics' },
  { text: 'vr headset', label: 'electronics' },
  { text: 'racing wheel', label: 'electronics' },
  { text: 'arcade stick', label: 'electronics' },
  { text: 'gaming monitor', label: 'electronics' },
  
  // Photography and video
  { text: 'camera', label: 'electronics' },
  { text: 'digital camera', label: 'electronics' },
  { text: 'instant camera', label: 'electronics' },
  { text: 'polaroid', label: 'electronics' },
  { text: 'camera lens', label: 'electronics' },
  { text: 'tripod', label: 'electronics' },
  { text: 'camera bag', label: 'electronics' },
  { text: 'memory card', label: 'electronics' },
  { text: 'camera battery', label: 'electronics' },
  { text: 'camera charger', label: 'electronics' },
  { text: 'ring light', label: 'electronics' },
  { text: 'selfie ring light', label: 'electronics' },
  { text: 'gimbal', label: 'electronics' },
  { text: 'action camera', label: 'electronics' },
  { text: 'gopro', label: 'electronics' },
  
  // Smart home and IoT
  { text: 'smart speaker', label: 'electronics' },
  { text: 'alexa', label: 'electronics' },
  { text: 'google home', label: 'electronics' },
  { text: 'smart bulb', label: 'electronics' },
  { text: 'smart plug', label: 'electronics' },
  { text: 'smart switch', label: 'electronics' },
  { text: 'security camera', label: 'electronics' },
  { text: 'doorbell camera', label: 'electronics' },
  { text: 'smart lock', label: 'electronics' },
  { text: 'smart thermostat', label: 'electronics' },
  { text: 'robot vacuum', label: 'electronics' },
  { text: 'air purifier', label: 'electronics' },
  { text: 'humidifier', label: 'electronics' },
  { text: 'dehumidifier', label: 'electronics' },
  { text: 'smart doorbell', label: 'electronics' },
  
  // Wearables and fitness
  { text: 'smartwatch', label: 'electronics' },
  { text: 'apple watch', label: 'electronics' },
  { text: 'fitness tracker', label: 'electronics' },
  { text: 'fitbit', label: 'electronics' },
  { text: 'heart rate monitor', label: 'electronics' },
  { text: 'smart band', label: 'electronics' },
  { text: 'activity tracker', label: 'electronics' },
  { text: 'step counter', label: 'electronics' },
  { text: 'sleep tracker', label: 'electronics' },
  { text: 'gps watch', label: 'electronics' },
  { text: 'running watch', label: 'electronics' },
  { text: 'sports watch', label: 'electronics' },
  { text: 'smart ring', label: 'electronics' },
  { text: 'fitness scale', label: 'electronics' },
  { text: 'body composition scale', label: 'electronics' },
  
  // Cables and adapters
  { text: 'lightning cable', label: 'electronics' },
  { text: 'usb c cable', label: 'electronics' },
  { text: 'micro usb cable', label: 'electronics' },
  { text: 'charging cable', label: 'electronics' },
  { text: 'adapter', label: 'electronics' },
  { text: 'wall adapter', label: 'electronics' },
  { text: 'travel adapter', label: 'electronics' },
  { text: 'extension cord', label: 'electronics' },
  { text: 'power strip', label: 'electronics' },
  { text: 'surge protector', label: 'electronics' },
  { text: 'ethernet cable', label: 'electronics' },
  { text: 'coaxial cable', label: 'electronics' },
  { text: 'audio cable', label: 'electronics' },
  { text: 'video cable', label: 'electronics' },
  { text: 'splitter', label: 'electronics' },
  
  // Batteries and power
  { text: 'battery', label: 'electronics' },
  { text: 'aa battery', label: 'electronics' },
  { text: 'aaa battery', label: 'electronics' },
  { text: 'rechargeable battery', label: 'electronics' },
  { text: 'battery charger', label: 'electronics' },
  { text: 'car charger', label: 'electronics' },
  { text: 'solar charger', label: 'electronics' },
  { text: 'ups', label: 'electronics' },
  { text: 'inverter', label: 'electronics' },
  { text: 'generator', label: 'electronics' },
  { text: 'voltage regulator', label: 'electronics' },
  { text: 'power meter', label: 'electronics' },
  { text: 'multimeter', label: 'electronics' },
  { text: 'soldering iron', label: 'electronics' },
  { text: 'circuit board', label: 'electronics' }
];