const frozenData = [
  { text: 'frozen pizza', label: 'Frozen' },
  { text: 'frozen vegetables', label: 'Frozen' },
  { text: 'frozen fruits', label: 'Frozen' },
  { text: 'frozen berries', label: 'Frozen' },
  { text: 'frozen strawberries', label: 'Frozen' },
  { text: 'frozen blueberries', label: 'Frozen' },
  { text: 'frozen raspberries', label: 'Frozen' },
  { text: 'frozen blackberries', label: 'Frozen' },
  { text: 'frozen mixed berries', label: 'Frozen' },
  { text: 'frozen mango', label: 'Frozen' },
  { text: 'frozen pineapple', label: 'Frozen' },
  { text: 'frozen peaches', label: 'Frozen' },
  { text: 'frozen cherries', label: 'Frozen' },
  { text: 'frozen grapes', label: 'Frozen' },
  { text: 'frozen bananas', label: 'Frozen' },
  { text: 'frozen kiwi', label: 'Frozen' },
  { text: 'frozen papaya', label: 'Frozen' },
  { text: 'frozen dragon fruit', label: 'Frozen' },
  { text: 'frozen lychee', label: 'Frozen' },
  { text: 'frozen rambutan', label: 'Frozen' },
  { text: 'frozen durian', label: 'Frozen' },
  { text: 'frozen jackfruit', label: 'Frozen' },
  { text: 'frozen coconut', label: 'Frozen' },
  { text: 'frozen avocado', label: 'Frozen' },
  { text: 'frozen lime', label: 'Frozen' },
  { text: 'frozen lemon', label: 'Frozen' },
  { text: 'frozen orange', label: 'Frozen' },
  { text: 'frozen grapefruit', label: 'Frozen' },
  { text: 'frozen pomegranate', label: 'Frozen' },
  { text: 'frozen passion fruit', label: 'Frozen' },
  { text: 'frozen guava', label: 'Frozen' },
  { text: 'frozen star fruit', label: 'Frozen' },
  { text: 'frozen persimmon', label: 'Frozen' },
  { text: 'frozen fig', label: 'Frozen' },
  { text: 'frozen dates', label: 'Frozen' },
  { text: 'frozen apricot', label: 'Frozen' },
  { text: 'frozen plum', label: 'Frozen' },
  { text: 'frozen nectarine', label: 'Frozen' },
  { text: 'frozen apple', label: 'Frozen' },
  { text: 'frozen pear', label: 'Frozen' },
  { text: 'frozen cantaloupe', label: 'Frozen' },
  { text: 'frozen honeydew', label: 'Frozen' },
  { text: 'frozen watermelon', label: 'Frozen' },
  { text: 'frozen broccoli', label: 'Frozen' },
  { text: 'frozen cauliflower', label: 'Frozen' },
  { text: 'frozen carrots', label: 'Frozen' },
  { text: 'frozen peas', label: 'Frozen' },
  { text: 'frozen corn', label: 'Frozen' },
  { text: 'frozen green beans', label: 'Frozen' },
  { text: 'frozen spinach', label: 'Frozen' },
  { text: 'frozen kale', label: 'Frozen' },
  { text: 'frozen brussels sprouts', label: 'Frozen' },
  { text: 'frozen asparagus', label: 'Frozen' },
  { text: 'frozen artichoke', label: 'Frozen' },
  { text: 'frozen okra', label: 'Frozen' },
  { text: 'frozen edamame', label: 'Frozen' },
  { text: 'frozen lima beans', label: 'Frozen' },
  { text: 'frozen black beans', label: 'Frozen' },
  { text: 'frozen kidney beans', label: 'Frozen' },
  { text: 'frozen chickpeas', label: 'Frozen' },
  { text: 'frozen lentils', label: 'Frozen' },
  { text: 'frozen mixed vegetables', label: 'Frozen' },
  { text: 'frozen stir fry vegetables', label: 'Frozen' },
  { text: 'frozen california blend', label: 'Frozen' },
  { text: 'frozen normandy blend', label: 'Frozen' },
  { text: 'frozen italian blend', label: 'Frozen' },
  { text: 'frozen asian blend', label: 'Frozen' },
  { text: 'frozen mediterranean blend', label: 'Frozen' },
  { text: 'frozen mexican blend', label: 'Frozen' },
  { text: 'frozen southwestern blend', label: 'Frozen' },
  { text: 'frozen oriental blend', label: 'Frozen' },
  { text: 'frozen thai blend', label: 'Frozen' },
  { text: 'frozen chinese blend', label: 'Frozen' },
  { text: 'frozen japanese blend', label: 'Frozen' },
  { text: 'frozen korean blend', label: 'Frozen' },
  { text: 'frozen indian blend', label: 'Frozen' },
  { text: 'frozen middle eastern blend', label: 'Frozen' },
  { text: 'frozen european blend', label: 'Frozen' },
  { text: 'frozen american blend', label: 'Frozen' },
  { text: 'frozen organic vegetables', label: 'Frozen' },
  { text: 'frozen organic fruits', label: 'Frozen' },
  { text: 'frozen organic berries', label: 'Frozen' },
  { text: 'frozen organic broccoli', label: 'Frozen' },
  { text: 'frozen organic spinach', label: 'Frozen' },
  { text: 'frozen organic peas', label: 'Frozen' },
  { text: 'frozen organic corn', label: 'Frozen' },
  { text: 'frozen organic carrots', label: 'Frozen' },
  { text: 'frozen organic green beans', label: 'Frozen' },
  { text: 'frozen organic cauliflower', label: 'Frozen' },
  { text: 'frozen organic kale', label: 'Frozen' },
  { text: 'frozen organic brussels sprouts', label: 'Frozen' },
  { text: 'frozen organic asparagus', label: 'Frozen' },
  { text: 'frozen organic artichoke', label: 'Frozen' },
  { text: 'frozen organic okra', label: 'Frozen' },
  { text: 'frozen organic edamame', label: 'Frozen' },
  { text: 'frozen organic lima beans', label: 'Frozen' },
  { text: 'frozen organic black beans', label: 'Frozen' },
  { text: 'frozen organic kidney beans', label: 'Frozen' },
  { text: 'frozen organic chickpeas', label: 'Frozen' },
  { text: 'frozen organic lentils', label: 'Frozen' },
  { text: 'frozen organic mixed vegetables', label: 'Frozen' },
  { text: 'frozen organic stir fry vegetables', label: 'Frozen' },
  { text: 'frozen organic strawberries', label: 'Frozen' },
  { text: 'frozen organic blueberries', label: 'Frozen' },
  { text: 'frozen organic raspberries', label: 'Frozen' },
  { text: 'frozen organic blackberries', label: 'Frozen' },
  { text: 'frozen organic mixed berries', label: 'Frozen' },
  { text: 'frozen organic mango', label: 'Frozen' },
  { text: 'frozen organic pineapple', label: 'Frozen' },
  { text: 'frozen organic peaches', label: 'Frozen' },
  { text: 'frozen organic cherries', label: 'Frozen' },
  { text: 'frozen organic grapes', label: 'Frozen' },
  { text: 'frozen organic bananas', label: 'Frozen' },
  { text: 'frozen chicken', label: 'Frozen' },
  { text: 'frozen beef', label: 'Frozen' },
  { text: 'frozen pork', label: 'Frozen' },
  { text: 'frozen lamb', label: 'Frozen' },
  { text: 'frozen turkey', label: 'Frozen' },
  { text: 'frozen duck', label: 'Frozen' },
  { text: 'frozen goose', label: 'Frozen' },
  { text: 'frozen quail', label: 'Frozen' },
  { text: 'frozen rabbit', label: 'Frozen' },
  { text: 'frozen venison', label: 'Frozen' },
  { text: 'frozen elk', label: 'Frozen' },
  { text: 'frozen bison', label: 'Frozen' },
  { text: 'frozen wild boar', label: 'Frozen' },
  { text: 'frozen ostrich', label: 'Frozen' },
  { text: 'frozen emu', label: 'Frozen' },
  { text: 'frozen alligator', label: 'Frozen' },
  { text: 'frozen kangaroo', label: 'Frozen' },
  { text: 'frozen chicken breast', label: 'Frozen' },
  { text: 'frozen chicken thighs', label: 'Frozen' },
  { text: 'frozen chicken wings', label: 'Frozen' },
  { text: 'frozen chicken drumsticks', label: 'Frozen' },
  { text: 'frozen chicken tenders', label: 'Frozen' },
  { text: 'frozen chicken nuggets', label: 'Frozen' },
  { text: 'frozen chicken patties', label: 'Frozen' },
  { text: 'frozen chicken strips', label: 'Frozen' },
  { text: 'frozen chicken cutlets', label: 'Frozen' },
  { text: 'frozen chicken fillets', label: 'Frozen' },
  { text: 'frozen ground chicken', label: 'Frozen' },
  { text: 'frozen whole chicken', label: 'Frozen' },
  { text: 'frozen chicken quarters', label: 'Frozen' },
  { text: 'frozen chicken halves', label: 'Frozen' },
  { text: 'frozen chicken backs', label: 'Frozen' },
  { text: 'frozen chicken necks', label: 'Frozen' },
  { text: 'frozen chicken gizzards', label: 'Frozen' },
  { text: 'frozen chicken hearts', label: 'Frozen' },
  { text: 'frozen chicken livers', label: 'Frozen' },
  { text: 'frozen chicken feet', label: 'Frozen' },
  { text: 'frozen chicken heads', label: 'Frozen' },
  { text: 'frozen beef steaks', label: 'Frozen' },
  { text: 'frozen beef roasts', label: 'Frozen' },
  { text: 'frozen beef ribs', label: 'Frozen' },
  { text: 'frozen beef brisket', label: 'Frozen' },
  { text: 'frozen beef chuck', label: 'Frozen' },
  { text: 'frozen beef round', label: 'Frozen' },
  { text: 'frozen beef sirloin', label: 'Frozen' },
  { text: 'frozen beef tenderloin', label: 'Frozen' },
  { text: 'frozen beef strip', label: 'Frozen' },
  { text: 'frozen beef ribeye', label: 'Frozen' },
  { text: 'frozen beef t-bone', label: 'Frozen' },
  { text: 'frozen beef porterhouse', label: 'Frozen' },
  { text: 'frozen beef filet mignon', label: 'Frozen' },
  { text: 'frozen beef flank', label: 'Frozen' },
  { text: 'frozen beef skirt', label: 'Frozen' },
  { text: 'frozen beef hanger', label: 'Frozen' },
  { text: 'frozen beef flat iron', label: 'Frozen' },
  { text: 'frozen beef tri-tip', label: 'Frozen' },
  { text: 'frozen beef top sirloin', label: 'Frozen' },
  { text: 'frozen beef bottom sirloin', label: 'Frozen' },
  { text: 'frozen beef eye of round', label: 'Frozen' },
  { text: 'frozen beef top round', label: 'Frozen' },
  { text: 'frozen beef bottom round', label: 'Frozen' },
  { text: 'frozen ground beef', label: 'Frozen' },
  { text: 'frozen beef patties', label: 'Frozen' },
  { text: 'frozen beef burgers', label: 'Frozen' },
  { text: 'frozen beef meatballs', label: 'Frozen' },
  { text: 'frozen beef sausages', label: 'Frozen' },
  { text: 'frozen beef hot dogs', label: 'Frozen' },
  { text: 'frozen beef franks', label: 'Frozen' },
  { text: 'frozen beef bratwurst', label: 'Frozen' },
  { text: 'frozen beef kielbasa', label: 'Frozen' },
  { text: 'frozen beef chorizo', label: 'Frozen' },
  { text: 'frozen beef andouille', label: 'Frozen' },
  { text: 'frozen beef italian sausage', label: 'Frozen' },
  { text: 'frozen beef breakfast sausage', label: 'Frozen' },
  { text: 'frozen beef polish sausage', label: 'Frozen' },
  { text: 'frozen beef smoked sausage', label: 'Frozen' },
  { text: 'frozen beef summer sausage', label: 'Frozen' },
  { text: 'frozen beef liver', label: 'Frozen' },
  { text: 'frozen beef kidney', label: 'Frozen' },
  { text: 'frozen beef heart', label: 'Frozen' },
  { text: 'frozen beef tongue', label: 'Frozen' },
  { text: 'frozen beef brain', label: 'Frozen' },
  { text: 'frozen beef oxtail', label: 'Frozen' },
  { text: 'frozen beef marrow bones', label: 'Frozen' },
  { text: 'frozen beef soup bones', label: 'Frozen' },
  { text: 'frozen beef short ribs', label: 'Frozen' },
  { text: 'frozen beef back ribs', label: 'Frozen' },
  { text: 'frozen beef plate ribs', label: 'Frozen' },
  { text: 'frozen beef chuck ribs', label: 'Frozen' },
  { text: 'frozen pork chops', label: 'Frozen' },
  { text: 'frozen pork roasts', label: 'Frozen' },
  { text: 'frozen pork ribs', label: 'Frozen' },
  { text: 'frozen pork shoulder', label: 'Frozen' },
  { text: 'frozen pork butt', label: 'Frozen' },
  { text: 'frozen pork loin', label: 'Frozen' },
  { text: 'frozen pork tenderloin', label: 'Frozen' },
  { text: 'frozen pork belly', label: 'Frozen' },
  { text: 'frozen pork hocks', label: 'Frozen' },
  { text: 'frozen pork trotters', label: 'Frozen' },
  { text: 'frozen pork feet', label: 'Frozen' },
  { text: 'frozen pork knuckles', label: 'Frozen' },
  { text: 'frozen pork shanks', label: 'Frozen' },
  { text: 'frozen pork neck bones', label: 'Frozen' },
  { text: 'frozen pork back bones', label: 'Frozen' },
  { text: 'frozen pork spare ribs', label: 'Frozen' },
  { text: 'frozen pork baby back ribs', label: 'Frozen' },
  { text: 'frozen pork country style ribs', label: 'Frozen' },
  { text: 'frozen pork st louis ribs', label: 'Frozen' },
  { text: 'frozen ground pork', label: 'Frozen' },
  { text: 'frozen pork patties', label: 'Frozen' },
  { text: 'frozen pork burgers', label: 'Frozen' },
  { text: 'frozen pork meatballs', label: 'Frozen' },
  { text: 'frozen pork sausages', label: 'Frozen' },
  { text: 'frozen pork hot dogs', label: 'Frozen' },
  { text: 'frozen pork franks', label: 'Frozen' },
  { text: 'frozen pork bratwurst', label: 'Frozen' },
  { text: 'frozen pork kielbasa', label: 'Frozen' },
  { text: 'frozen pork chorizo', label: 'Frozen' },
  { text: 'frozen pork andouille', label: 'Frozen' },
  { text: 'frozen pork italian sausage', label: 'Frozen' },
  { text: 'frozen pork breakfast sausage', label: 'Frozen' },
  { text: 'frozen pork polish sausage', label: 'Frozen' },
  { text: 'frozen pork smoked sausage', label: 'Frozen' },
  { text: 'frozen pork summer sausage', label: 'Frozen' },
  { text: 'frozen bacon', label: 'Frozen' },
  { text: 'frozen ham', label: 'Frozen' },
  { text: 'frozen canadian bacon', label: 'Frozen' },
  { text: 'frozen pancetta', label: 'Frozen' },
  { text: 'frozen prosciutto', label: 'Frozen' },
  { text: 'frozen guanciale', label: 'Frozen' },
  { text: 'frozen coppa', label: 'Frozen' },
  { text: 'frozen lonza', label: 'Frozen' },
  { text: 'frozen bresaola', label: 'Frozen' },
  { text: 'frozen mortadella', label: 'Frozen' },
  { text: 'frozen salami', label: 'Frozen' },
  { text: 'frozen pepperoni', label: 'Frozen' },
  { text: 'frozen sopressata', label: 'Frozen' },
  { text: 'frozen capicola', label: 'Frozen' },
  { text: 'frozen gabagool', label: 'Frozen' },
  { text: 'frozen pastrami', label: 'Frozen' },
  { text: 'frozen corned beef', label: 'Frozen' },
  { text: 'frozen roast beef', label: 'Frozen' },
  { text: 'frozen turkey breast', label: 'Frozen' },
  { text: 'frozen turkey deli meat', label: 'Frozen' },
  { text: 'frozen chicken deli meat', label: 'Frozen' },
  { text: 'frozen ham deli meat', label: 'Frozen' },
  { text: 'frozen bologna', label: 'Frozen' },
  { text: 'frozen liverwurst', label: 'Frozen' },
  { text: 'frozen head cheese', label: 'Frozen' },
  { text: 'frozen blood sausage', label: 'Frozen' },
  { text: 'frozen black pudding', label: 'Frozen' },
  { text: 'frozen white pudding', label: 'Frozen' },
  { text: 'frozen haggis', label: 'Frozen' },
  { text: 'frozen boudin', label: 'Frozen' },
  { text: 'frozen scrapple', label: 'Frozen' },
  { text: 'frozen spam', label: 'Frozen' },
  { text: 'frozen vienna sausages', label: 'Frozen' },
  { text: 'frozen deviled ham', label: 'Frozen' },
  { text: 'frozen potted meat', label: 'Frozen' },
  { text: 'frozen fish', label: 'Frozen' },
  { text: 'frozen salmon', label: 'Frozen' },
  { text: 'frozen tuna', label: 'Frozen' },
  { text: 'frozen cod', label: 'Frozen' },
  { text: 'frozen halibut', label: 'Frozen' },
  { text: 'frozen mahi mahi', label: 'Frozen' },
  { text: 'frozen tilapia', label: 'Frozen' },
  { text: 'frozen catfish', label: 'Frozen' },
  { text: 'frozen bass', label: 'Frozen' },
  { text: 'frozen trout', label: 'Frozen' },
  { text: 'frozen mackerel', label: 'Frozen' },
  { text: 'frozen sardines', label: 'Frozen' },
  { text: 'frozen anchovies', label: 'Frozen' },
  { text: 'frozen herring', label: 'Frozen' },
  { text: 'frozen flounder', label: 'Frozen' },
  { text: 'frozen sole', label: 'Frozen' },
  { text: 'frozen plaice', label: 'Frozen' },
  { text: 'frozen turbot', label: 'Frozen' },
  { text: 'frozen brill', label: 'Frozen' },
  { text: 'frozen john dory', label: 'Frozen' },
  { text: 'frozen sea bass', label: 'Frozen' },
  { text: 'frozen sea bream', label: 'Frozen' },
  { text: 'frozen red snapper', label: 'Frozen' },
  { text: 'frozen grouper', label: 'Frozen' },
  { text: 'frozen amberjack', label: 'Frozen' },
  { text: 'frozen yellowtail', label: 'Frozen' },
  { text: 'frozen kingfish', label: 'Frozen' },
  { text: 'frozen barramundi', label: 'Frozen' },
  { text: 'frozen pomfret', label: 'Frozen' },
  { text: 'frozen monkfish', label: 'Frozen' },
  { text: 'frozen swordfish', label: 'Frozen' },
  { text: 'frozen marlin', label: 'Frozen' },
  { text: 'frozen shark', label: 'Frozen' },
  { text: 'frozen ray', label: 'Frozen' },
  { text: 'frozen skate', label: 'Frozen' },
  { text: 'frozen eel', label: 'Frozen' },
  { text: 'frozen conger eel', label: 'Frozen' },
  { text: 'frozen moray eel', label: 'Frozen' },
  { text: 'frozen electric eel', label: 'Frozen' },
  { text: 'frozen lamprey', label: 'Frozen' },
  { text: 'frozen hagfish', label: 'Frozen' },
  { text: 'frozen carp', label: 'Frozen' },
  { text: 'frozen pike', label: 'Frozen' },
  { text: 'frozen perch', label: 'Frozen' },
  { text: 'frozen walleye', label: 'Frozen' },
  { text: 'frozen zander', label: 'Frozen' },
  { text: 'frozen bream', label: 'Frozen' },
  { text: 'frozen roach', label: 'Frozen' },
  { text: 'frozen rudd', label: 'Frozen' },
  { text: 'frozen tench', label: 'Frozen' },
  { text: 'frozen barbel', label: 'Frozen' },
  { text: 'frozen chub', label: 'Frozen' },
  { text: 'frozen dace', label: 'Frozen' },
  { text: 'frozen gudgeon', label: 'Frozen' },
  { text: 'frozen bleak', label: 'Frozen' },
  { text: 'frozen minnow', label: 'Frozen' },
  { text: 'frozen loach', label: 'Frozen' },
  { text: 'frozen burbot', label: 'Frozen' },
  { text: 'frozen grayling', label: 'Frozen' },
  { text: 'frozen char', label: 'Frozen' },
  { text: 'frozen whitefish', label: 'Frozen' },
  { text: 'frozen cisco', label: 'Frozen' },
  { text: 'frozen lake trout', label: 'Frozen' },
  { text: 'frozen brook trout', label: 'Frozen' },
  { text: 'frozen brown trout', label: 'Frozen' },
  { text: 'frozen rainbow trout', label: 'Frozen' },
  { text: 'frozen cutthroat trout', label: 'Frozen' },
  { text: 'frozen steelhead trout', label: 'Frozen' },
  { text: 'frozen golden trout', label: 'Frozen' },
  { text: 'frozen bull trout', label: 'Frozen' },
  { text: 'frozen dolly varden', label: 'Frozen' },
  { text: 'frozen arctic char', label: 'Frozen' },
  { text: 'frozen lake char', label: 'Frozen' },
  { text: 'frozen splake', label: 'Frozen' },
  { text: 'frozen tiger trout', label: 'Frozen' },
  { text: 'frozen shrimp', label: 'Frozen' },
  { text: 'frozen prawns', label: 'Frozen' },
  { text: 'frozen lobster', label: 'Frozen' },
  { text: 'frozen crab', label: 'Frozen' },
  { text: 'frozen crayfish', label: 'Frozen' },
  { text: 'frozen langostino', label: 'Frozen' },
  { text: 'frozen scampi', label: 'Frozen' },
  { text: 'frozen langoustine', label: 'Frozen' },
  { text: 'frozen dublin bay prawns', label: 'Frozen' },
  { text: 'frozen norway lobster', label: 'Frozen' },
  { text: 'frozen spiny lobster', label: 'Frozen' },
  { text: 'frozen rock lobster', label: 'Frozen' },
  { text: 'frozen slipper lobster', label: 'Frozen' },
  { text: 'frozen squat lobster', label: 'Frozen' },
  { text: 'frozen hermit crab', label: 'Frozen' },
  { text: 'frozen king crab', label: 'Frozen' },
  { text: 'frozen snow crab', label: 'Frozen' },
  { text: 'frozen dungeness crab', label: 'Frozen' },
  { text: 'frozen blue crab', label: 'Frozen' },
  { text: 'frozen stone crab', label: 'Frozen' },
  { text: 'frozen mud crab', label: 'Frozen' },
  { text: 'frozen soft shell crab', label: 'Frozen' },
  { text: 'frozen hard shell crab', label: 'Frozen' },
  { text: 'frozen spider crab', label: 'Frozen' },
  { text: 'frozen horseshoe crab', label: 'Frozen' },
  { text: 'frozen fiddler crab', label: 'Frozen' },
  { text: 'frozen ghost crab', label: 'Frozen' },
  { text: 'frozen sand crab', label: 'Frozen' },
  { text: 'frozen rock crab', label: 'Frozen' },
  { text: 'frozen shore crab', label: 'Frozen' },
  { text: 'frozen swimming crab', label: 'Frozen' },
  { text: 'frozen velvet crab', label: 'Frozen' },
  { text: 'frozen edible crab', label: 'Frozen' },
  { text: 'frozen brown crab', label: 'Frozen' },
  { text: 'frozen green crab', label: 'Frozen' },
  { text: 'frozen red crab', label: 'Frozen' },
  { text: 'frozen orange crab', label: 'Frozen' },
  { text: 'frozen yellow crab', label: 'Frozen' },
  { text: 'frozen purple crab', label: 'Frozen' },
  { text: 'frozen black crab', label: 'Frozen' },
  { text: 'frozen white crab', label: 'Frozen' },
  { text: 'frozen pink crab', label: 'Frozen' },
  { text: 'frozen silver crab', label: 'Frozen' },
  { text: 'frozen golden crab', label: 'Frozen' },
  { text: 'frozen bronze crab', label: 'Frozen' },
  { text: 'frozen copper crab', label: 'Frozen' },
  { text: 'frozen brass crab', label: 'Frozen' },
  { text: 'frozen steel crab', label: 'Frozen' },
  { text: 'frozen iron crab', label: 'Frozen' },
  { text: 'frozen aluminum crab', label: 'Frozen' },
  { text: 'frozen titanium crab', label: 'Frozen' },
  { text: 'frozen platinum crab', label: 'Frozen' },
  { text: 'frozen diamond crab', label: 'Frozen' },
  { text: 'frozen crystal crab', label: 'Frozen' },
  { text: 'frozen glass crab', label: 'Frozen' },
  { text: 'frozen transparent crab', label: 'Frozen' },
  { text: 'frozen invisible crab', label: 'Frozen' },
  { text: 'frozen phantom crab', label: 'Frozen' },
  { text: 'frozen ghost shrimp', label: 'Frozen' },
  { text: 'frozen mantis shrimp', label: 'Frozen' },
  { text: 'frozen pistol shrimp', label: 'Frozen' },
  { text: 'frozen snapping shrimp', label: 'Frozen' },
  { text: 'frozen cleaner shrimp', label: 'Frozen' },
  { text: 'frozen brine shrimp', label: 'Frozen' },
  { text: 'frozen fairy shrimp', label: 'Frozen' },
  { text: 'frozen tadpole shrimp', label: 'Frozen' },
  { text: 'frozen clam shrimp', label: 'Frozen' },
  { text: 'frozen seed shrimp', label: 'Frozen' },
  { text: 'frozen mussel shrimp', label: 'Frozen' },
  { text: 'frozen barnacle', label: 'Frozen' },
  { text: 'frozen acorn barnacle', label: 'Frozen' },
  { text: 'frozen goose barnacle', label: 'Frozen' },
  { text: 'frozen stalked barnacle', label: 'Frozen' },
  { text: 'frozen parasitic barnacle', label: 'Frozen' },
  { text: 'frozen whale barnacle', label: 'Frozen' },
  { text: 'frozen turtle barnacle', label: 'Frozen' },
  { text: 'frozen crab barnacle', label: 'Frozen' },
  { text: 'frozen ship barnacle', label: 'Frozen' },
  { text: 'frozen rock barnacle', label: 'Frozen' },
  { text: 'frozen pier barnacle', label: 'Frozen' },
  { text: 'frozen dock barnacle', label: 'Frozen' },
  { text: 'frozen bridge barnacle', label: 'Frozen' },
  { text: 'frozen hull barnacle', label: 'Frozen' },
  { text: 'frozen propeller barnacle', label: 'Frozen' },
  { text: 'frozen anchor barnacle', label: 'Frozen' },
  { text: 'frozen chain barnacle', label: 'Frozen' },
  { text: 'frozen rope barnacle', label: 'Frozen' },
  { text: 'frozen buoy barnacle', label: 'Frozen' },
  { text: 'frozen float barnacle', label: 'Frozen' },
  { text: 'frozen marker barnacle', label: 'Frozen' },
  { text: 'frozen beacon barnacle', label: 'Frozen' },
  { text: 'frozen lighthouse barnacle', label: 'Frozen' },
  { text: 'frozen tower barnacle', label: 'Frozen' },
  { text: 'frozen pole barnacle', label: 'Frozen' },
  { text: 'frozen post barnacle', label: 'Frozen' },
  { text: 'frozen piling barnacle', label: 'Frozen' },
  { text: 'frozen jetty barnacle', label: 'Frozen' },
  { text: 'frozen breakwater barnacle', label: 'Frozen' },
  { text: 'frozen seawall barnacle', label: 'Frozen' },
  { text: 'frozen bulkhead barnacle', label: 'Frozen' },
  { text: 'frozen wharf barnacle', label: 'Frozen' },
  { text: 'frozen quay barnacle', label: 'Frozen' },
  { text: 'frozen marina barnacle', label: 'Frozen' },
  { text: 'frozen harbor barnacle', label: 'Frozen' },
  { text: 'frozen port barnacle', label: 'Frozen' },
  { text: 'frozen bay barnacle', label: 'Frozen' },
  { text: 'frozen inlet barnacle', label: 'Frozen' },
  { text: 'frozen cove barnacle', label: 'Frozen' },
  { text: 'frozen lagoon barnacle', label: 'Frozen' },
  { text: 'frozen estuary barnacle', label: 'Frozen' },
  { text: 'frozen delta barnacle', label: 'Frozen' },
  { text: 'frozen mouth barnacle', label: 'Frozen' },
  { text: 'frozen outlet barnacle', label: 'Frozen' },
  { text: 'frozen channel barnacle', label: 'Frozen' },
  { text: 'frozen strait barnacle', label: 'Frozen' },
  { text: 'frozen sound barnacle', label: 'Frozen' },
  { text: 'frozen fjord barnacle', label: 'Frozen' },
  { text: 'frozen fiord barnacle', label: 'Frozen' },
  { text: 'frozen loch barnacle', label: 'Frozen' },
  { text: 'frozen lake barnacle', label: 'Frozen' },
  { text: 'frozen pond barnacle', label: 'Frozen' },
  { text: 'frozen pool barnacle', label: 'Frozen' },
  { text: 'frozen puddle barnacle', label: 'Frozen' },
  { text: 'frozen stream barnacle', label: 'Frozen' },
  { text: 'frozen creek barnacle', label: 'Frozen' },
  { text: 'frozen brook barnacle', label: 'Frozen' },
  { text: 'frozen rivulet barnacle', label: 'Frozen' },
  { text: 'frozen rill barnacle', label: 'Frozen' },
  { text: 'frozen runnel barnacle', label: 'Frozen' },
  { text: 'frozen gully barnacle', label: 'Frozen' },
  { text: 'frozen ditch barnacle', label: 'Frozen' },
  { text: 'frozen drain barnacle', label: 'Frozen' },
  { text: 'frozen sewer barnacle', label: 'Frozen' },
  { text: 'frozen pipe barnacle', label: 'Frozen' },
  { text: 'frozen tube barnacle', label: 'Frozen' },
  { text: 'frozen hose barnacle', label: 'Frozen' },
  { text: 'frozen conduit barnacle', label: 'Frozen' },
  { text: 'frozen duct barnacle', label: 'Frozen' },
  { text: 'frozen tunnel barnacle', label: 'Frozen' },
  { text: 'frozen passage barnacle', label: 'Frozen' },
  { text: 'frozen corridor barnacle', label: 'Frozen' },
  { text: 'frozen hallway barnacle', label: 'Frozen' },
  { text: 'frozen aisle barnacle', label: 'Frozen' },
  { text: 'frozen lane barnacle', label: 'Frozen' },
  { text: 'frozen path barnacle', label: 'Frozen' },
  { text: 'frozen trail barnacle', label: 'Frozen' },
  { text: 'frozen track barnacle', label: 'Frozen' },
  { text: 'frozen route barnacle', label: 'Frozen' },
  { text: 'frozen road barnacle', label: 'Frozen' },
  { text: 'frozen street barnacle', label: 'Frozen' },
  { text: 'frozen avenue barnacle', label: 'Frozen' },
  { text: 'frozen boulevard barnacle', label: 'Frozen' },
  { text: 'frozen highway barnacle', label: 'Frozen' },
  { text: 'frozen freeway barnacle', label: 'Frozen' },
  { text: 'frozen expressway barnacle', label: 'Frozen' },
  { text: 'frozen parkway barnacle', label: 'Frozen' },
  { text: 'frozen turnpike barnacle', label: 'Frozen' },
  { text: 'frozen tollway barnacle', label: 'Frozen' },
  { text: 'frozen causeway barnacle', label: 'Frozen' },
  { text: 'frozen viaduct barnacle', label: 'Frozen' },
  { text: 'frozen overpass barnacle', label: 'Frozen' },
  { text: 'frozen underpass barnacle', label: 'Frozen' },
  { text: 'frozen flyover barnacle', label: 'Frozen' },
  { text: 'frozen cloverleaf barnacle', label: 'Frozen' },
  { text: 'frozen interchange barnacle', label: 'Frozen' },
  { text: 'frozen junction barnacle', label: 'Frozen' },
  { text: 'frozen intersection barnacle', label: 'Frozen' },
  { text: 'frozen crossroads barnacle', label: 'Frozen' },
  { text: 'frozen roundabout barnacle', label: 'Frozen' },
  { text: 'frozen traffic circle barnacle', label: 'Frozen' },
  { text: 'frozen rotary barnacle', label: 'Frozen' },
  { text: 'frozen circle barnacle', label: 'Frozen' },
  { text: 'frozen square barnacle', label: 'Frozen' },
  { text: 'frozen plaza barnacle', label: 'Frozen' },
  { text: 'frozen piazza barnacle', label: 'Frozen' },
  { text: 'frozen courtyard barnacle', label: 'Frozen' },
  { text: 'frozen quad barnacle', label: 'Frozen' },
  { text: 'frozen quadrangle barnacle', label: 'Frozen' },
  { text: 'frozen commons barnacle', label: 'Frozen' },
  { text: 'frozen green barnacle', label: 'Frozen' },
  { text: 'frozen park barnacle', label: 'Frozen' },
  { text: 'frozen garden barnacle', label: 'Frozen' },
  { text: 'frozen yard barnacle', label: 'Frozen' },
  { text: 'frozen lawn barnacle', label: 'Frozen' },
  { text: 'frozen field barnacle', label: 'Frozen' },
  { text: 'frozen meadow barnacle', label: 'Frozen' },
  { text: 'frozen pasture barnacle', label: 'Frozen' },
  { text: 'frozen prairie barnacle', label: 'Frozen' },
  { text: 'frozen plain barnacle', label: 'Frozen' },
  { text: 'frozen plateau barnacle', label: 'Frozen' },
  { text: 'frozen mesa barnacle', label: 'Frozen' },
  { text: 'frozen butte barnacle', label: 'Frozen' },
  { text: 'frozen hill barnacle', label: 'Frozen' },
  { text: 'frozen mountain barnacle', label: 'Frozen' },
  { text: 'frozen peak barnacle', label: 'Frozen' },
  { text: 'frozen summit barnacle', label: 'Frozen' },
  { text: 'frozen ridge barnacle', label: 'Frozen' },
  { text: 'frozen crest barnacle', label: 'Frozen' },
  { text: 'frozen slope barnacle', label: 'Frozen' },
  { text: 'frozen incline barnacle', label: 'Frozen' },
  { text: 'frozen grade barnacle', label: 'Frozen' },
  { text: 'frozen gradient barnacle', label: 'Frozen' },
  { text: 'frozen ramp barnacle', label: 'Frozen' },
  { text: 'frozen rise barnacle', label: 'Frozen' },
  { text: 'frozen ascent barnacle', label: 'Frozen' },
  { text: 'frozen descent barnacle', label: 'Frozen' },
  { text: 'frozen decline barnacle', label: 'Frozen' },
  { text: 'frozen drop barnacle', label: 'Frozen' },
  { text: 'frozen fall barnacle', label: 'Frozen' },
  { text: 'frozen cliff barnacle', label: 'Frozen' },
  { text: 'frozen precipice barnacle', label: 'Frozen' },
  { text: 'frozen bluff barnacle', label: 'Frozen' },
  { text: 'frozen escarpment barnacle', label: 'Frozen' },
  { text: 'frozen scarp barnacle', label: 'Frozen' },
  { text: 'frozen ledge barnacle', label: 'Frozen' },
  { text: 'frozen shelf barnacle', label: 'Frozen' },
  { text: 'frozen terrace barnacle', label: 'Frozen' },
  { text: 'frozen bench barnacle', label: 'Frozen' },
  { text: 'frozen step barnacle', label: 'Frozen' },
  { text: 'frozen stair barnacle', label: 'Frozen' },
  { text: 'frozen staircase barnacle', label: 'Frozen' },
  { text: 'frozen stairway barnacle', label: 'Frozen' },
  { text: 'frozen flight barnacle', label: 'Frozen' },
  { text: 'frozen escalator barnacle', label: 'Frozen' },
  { text: 'frozen elevator barnacle', label: 'Frozen' },
  { text: 'frozen lift barnacle', label: 'Frozen' },
  { text: 'frozen hoist barnacle', label: 'Frozen' },
  { text: 'frozen crane barnacle', label: 'Frozen' },
  { text: 'frozen derrick barnacle', label: 'Frozen' },
  { text: 'frozen winch barnacle', label: 'Frozen' },
  { text: 'frozen pulley barnacle', label: 'Frozen' },
  { text: 'frozen block barnacle', label: 'Frozen' },
  { text: 'frozen tackle barnacle', label: 'Frozen' },
  { text: 'frozen gear barnacle', label: 'Frozen' },
  { text: 'frozen mechanism barnacle', label: 'Frozen' },
  { text: 'frozen machine barnacle', label: 'Frozen' },
  { text: 'frozen device barnacle', label: 'Frozen' },
  { text: 'frozen apparatus barnacle', label: 'Frozen' },
  { text: 'frozen instrument barnacle', label: 'Frozen' },
  { text: 'frozen tool barnacle', label: 'Frozen' },
  { text: 'frozen implement barnacle', label: 'Frozen' },
  { text: 'frozen utensil barnacle', label: 'Frozen' },
  { text: 'frozen gadget barnacle', label: 'Frozen' },
  { text: 'frozen contraption barnacle', label: 'Frozen' },
  { text: 'frozen contrivance barnacle', label: 'Frozen' },
  { text: 'frozen invention barnacle', label: 'Frozen' },
  { text: 'frozen innovation barnacle', label: 'Frozen' },
  { text: 'frozen creation barnacle', label: 'Frozen' },
  { text: 'frozen design barnacle', label: 'Frozen' },
  { text: 'frozen blueprint barnacle', label: 'Frozen' },
  { text: 'frozen plan barnacle', label: 'Frozen' },
  { text: 'frozen scheme barnacle', label: 'Frozen' },
  { text: 'frozen strategy barnacle', label: 'Frozen' },
  { text: 'frozen tactic barnacle', label: 'Frozen' },
  { text: 'frozen method barnacle', label: 'Frozen' },
  { text: 'frozen approach barnacle', label: 'Frozen' },
  { text: 'frozen technique barnacle', label: 'Frozen' },
  { text: 'frozen procedure barnacle', label: 'Frozen' },
  { text: 'frozen process barnacle', label: 'Frozen' },
  { text: 'frozen system barnacle', label: 'Frozen' },
  { text: 'frozen protocol barnacle', label: 'Frozen' },
  { text: 'frozen routine barnacle', label: 'Frozen' },
  { text: 'frozen practice barnacle', label: 'Frozen' },
  { text: 'frozen custom barnacle', label: 'Frozen' },
  { text: 'frozen tradition barnacle', label: 'Frozen' },
  { text: 'frozen convention barnacle', label: 'Frozen' },
  { text: 'frozen standard barnacle', label: 'Frozen' },
  { text: 'frozen norm barnacle', label: 'Frozen' },
  { text: 'frozen rule barnacle', label: 'Frozen' },
  { text: 'frozen regulation barnacle', label: 'Frozen' },
  { text: 'frozen law barnacle', label: 'Frozen' },
  { text: 'frozen statute barnacle', label: 'Frozen' },
  { text: 'frozen ordinance barnacle', label: 'Frozen' },
  { text: 'frozen decree barnacle', label: 'Frozen' },
  { text: 'frozen edict barnacle', label: 'Frozen' },
  { text: 'frozen mandate barnacle', label: 'Frozen' },
  { text: 'frozen directive barnacle', label: 'Frozen' },
  { text: 'frozen order barnacle', label: 'Frozen' },
  { text: 'frozen command barnacle', label: 'Frozen' },
  { text: 'frozen instruction barnacle', label: 'Frozen' },
  { text: 'frozen direction barnacle', label: 'Frozen' },
  { text: 'frozen guidance barnacle', label: 'Frozen' },
  { text: 'frozen advice barnacle', label: 'Frozen' },
  { text: 'frozen counsel barnacle', label: 'Frozen' },
  { text: 'frozen recommendation barnacle', label: 'Frozen' },
  { text: 'frozen suggestion barnacle', label: 'Frozen' },
  { text: 'frozen proposal barnacle', label: 'Frozen' },
  { text: 'frozen proposition barnacle', label: 'Frozen' },
  { text: 'frozen offer barnacle', label: 'Frozen' },
  { text: 'frozen bid barnacle', label: 'Frozen' },
  { text: 'frozen tender barnacle', label: 'Frozen' },
  { text: 'frozen quote barnacle', label: 'Frozen' },
  { text: 'frozen estimate barnacle', label: 'Frozen' },
  { text: 'frozen assessment barnacle', label: 'Frozen' },
  { text: 'frozen evaluation barnacle', label: 'Frozen' },
  { text: 'frozen appraisal barnacle', label: 'Frozen' },
  { text: 'frozen valuation barnacle', label: 'Frozen' },
  { text: 'frozen calculation barnacle', label: 'Frozen' },
  { text: 'frozen computation barnacle', label: 'Frozen' },
  { text: 'frozen measurement barnacle', label: 'Frozen' },
  { text: 'frozen quantification barnacle', label: 'Frozen' },
  { text: 'frozen determination barnacle', label: 'Frozen' },
  { text: 'frozen analysis barnacle', label: 'Frozen' },
  { text: 'frozen examination barnacle', label: 'Frozen' },
  { text: 'frozen inspection barnacle', label: 'Frozen' },
  { text: 'frozen investigation barnacle', label: 'Frozen' },
  { text: 'frozen inquiry barnacle', label: 'Frozen' },
  { text: 'frozen research barnacle', label: 'Frozen' },
  { text: 'frozen study barnacle', label: 'Frozen' },
  { text: 'frozen survey barnacle', label: 'Frozen' },
  { text: 'frozen review barnacle', label: 'Frozen' },
  { text: 'frozen audit barnacle', label: 'Frozen' },
  { text: 'frozen check barnacle', label: 'Frozen' },
  { text: 'frozen test barnacle', label: 'Frozen' },
  { text: 'frozen trial barnacle', label: 'Frozen' },
  { text: 'frozen experiment barnacle', label: 'Frozen' },
  { text: 'frozen demonstration barnacle', label: 'Frozen' },
  { text: 'frozen proof barnacle', label: 'Frozen' },
  { text: 'frozen evidence barnacle', label: 'Frozen' },
  { text: 'frozen verification barnacle', label: 'Frozen' },
  { text: 'frozen confirmation barnacle', label: 'Frozen' },
  { text: 'frozen validation barnacle', label: 'Frozen' },
  { text: 'frozen authentication barnacle', label: 'Frozen' },
  { text: 'frozen certification barnacle', label: 'Frozen' },
  { text: 'frozen accreditation barnacle', label: 'Frozen' },
  { text: 'frozen authorization barnacle', label: 'Frozen' },
  { text: 'frozen approval barnacle', label: 'Frozen' },
  { text: 'frozen endorsement barnacle', label: 'Frozen' },
  { text: 'frozen sanction barnacle', label: 'Frozen' },
  { text: 'frozen permission barnacle', label: 'Frozen' },
  { text: 'frozen license barnacle', label: 'Frozen' },
  { text: 'frozen permit barnacle', label: 'Frozen' },
  { text: 'frozen warrant barnacle', label: 'Frozen' },
  { text: 'frozen charter barnacle', label: 'Frozen' },
  { text: 'frozen franchise barnacle', label: 'Frozen' },
  { text: 'frozen concession barnacle', label: 'Frozen' },
  { text: 'frozen grant barnacle', label: 'Frozen' },
  { text: 'frozen allowance barnacle', label: 'Frozen' },
  { text: 'frozen allocation barnacle', label: 'Frozen' },
  { text: 'frozen assignment barnacle', label: 'Frozen' },
  { text: 'frozen designation barnacle', label: 'Frozen' },
  { text: 'frozen appointment barnacle', label: 'Frozen' },
  { text: 'frozen nomination barnacle', label: 'Frozen' },
  { text: 'frozen selection barnacle', label: 'Frozen' },
  { text: 'frozen choice barnacle', label: 'Frozen' },
  { text: 'frozen option barnacle', label: 'Frozen' },
  { text: 'frozen alternative barnacle', label: 'Frozen' },
  { text: 'frozen possibility barnacle', label: 'Frozen' },
  { text: 'frozen opportunity barnacle', label: 'Frozen' },
  { text: 'frozen chance barnacle', label: 'Frozen' },
  { text: 'frozen prospect barnacle', label: 'Frozen' },
  { text: 'frozen potential barnacle', label: 'Frozen' },
  { text: 'frozen capability barnacle', label: 'Frozen' },
  { text: 'frozen capacity barnacle', label: 'Frozen' },
  { text: 'frozen ability barnacle', label: 'Frozen' },
  { text: 'frozen skill barnacle', label: 'Frozen' },
  { text: 'frozen talent barnacle', label: 'Frozen' },
  { text: 'frozen gift barnacle', label: 'Frozen' },
  { text: 'frozen aptitude barnacle', label: 'Frozen' },
  { text: 'frozen knack barnacle', label: 'Frozen' },
  { text: 'frozen flair barnacle', label: 'Frozen' },
  { text: 'frozen genius barnacle', label: 'Frozen' },
  { text: 'frozen brilliance barnacle', label: 'Frozen' },
  { text: 'frozen intelligence barnacle', label: 'Frozen' },
  { text: 'frozen wisdom barnacle', label: 'Frozen' },
  { text: 'frozen knowledge barnacle', label: 'Frozen' },
  { text: 'frozen understanding barnacle', label: 'Frozen' },
  { text: 'frozen comprehension barnacle', label: 'Frozen' },
  { text: 'frozen insight barnacle', label: 'Frozen' },
  { text: 'frozen perception barnacle', label: 'Frozen' },
  { text: 'frozen awareness barnacle', label: 'Frozen' },
  { text: 'frozen consciousness barnacle', label: 'Frozen' },
  { text: 'frozen cognition barnacle', label: 'Frozen' },
  { text: 'frozen recognition barnacle', label: 'Frozen' },
  { text: 'frozen realization barnacle', label: 'Frozen' },
  { text: 'frozen discovery barnacle', label: 'Frozen' },
  { text: 'frozen revelation barnacle', label: 'Frozen' },
  { text: 'frozen epiphany barnacle', label: 'Frozen' },
  { text: 'frozen enlightenment barnacle', label: 'Frozen' },
  { text: 'frozen illumination barnacle', label: 'Frozen' },
  { text: 'frozen clarification barnacle', label: 'Frozen' },
  { text: 'frozen explanation barnacle', label: 'Frozen' },
  { text: 'frozen interpretation barnacle', label: 'Frozen' },
  { text: 'frozen translation barnacle', label: 'Frozen' },
  { text: 'frozen conversion barnacle', label: 'Frozen' },
  { text: 'frozen transformation barnacle', label: 'Frozen' },
  { text: 'frozen metamorphosis barnacle', label: 'Frozen' },
  { text: 'frozen change barnacle', label: 'Frozen' },
  { text: 'frozen alteration barnacle', label: 'Frozen' },
  { text: 'frozen modification barnacle', label: 'Frozen' },
  { text: 'frozen adjustment barnacle', label: 'Frozen' },
  { text: 'frozen adaptation barnacle', label: 'Frozen' },
  { text: 'frozen evolution barnacle', label: 'Frozen' },
  { text: 'frozen development barnacle', label: 'Frozen' },
  { text: 'frozen growth barnacle', label: 'Frozen' },
  { text: 'frozen progress barnacle', label: 'Frozen' },
  { text: 'frozen advancement barnacle', label: 'Frozen' },
  { text: 'frozen improvement barnacle', label: 'Frozen' },
  { text: 'frozen enhancement barnacle', label: 'Frozen' },
  { text: 'frozen upgrade barnacle', label: 'Frozen' },
  { text: 'frozen refinement barnacle', label: 'Frozen' },
  { text: 'frozen perfection barnacle', label: 'Frozen' },
  { text: 'frozen optimization barnacle', label: 'Frozen' },
  { text: 'frozen maximization barnacle', label: 'Frozen' },
  { text: 'frozen minimization barnacle', label: 'Frozen' }
];

export default frozenData;