/**
 * Training data for Frozen category
 * Singapore-focused frozen foods and items
 */

export interface TrainingDataItem {
  text: string;
  label: string;
}

export const frozenTrainingData: TrainingDataItem[] = [
  // Frozen Vegetables
  { text: 'frozen vegetables', label: 'frozen' },
  { text: 'frozen peas', label: 'frozen' },
  { text: 'frozen corn', label: 'frozen' },
  { text: 'frozen carrots', label: 'frozen' },
  { text: 'frozen broccoli', label: 'frozen' },
  { text: 'frozen cauliflower', label: 'frozen' },
  { text: 'frozen green beans', label: 'frozen' },
  { text: 'frozen spinach', label: 'frozen' },
  { text: 'frozen mixed vegetables', label: 'frozen' },
  { text: 'frozen stir fry vegetables', label: 'frozen' },
  { text: 'frozen edamame', label: 'frozen' },
  { text: 'frozen okra', label: 'frozen' },
  { text: 'frozen asparagus', label: 'frozen' },
  { text: 'frozen brussels sprouts', label: 'frozen' },
  { text: 'frozen artichoke', label: 'frozen' },
  
  // Frozen Fruits
  { text: 'frozen fruits', label: 'frozen' },
  { text: 'frozen berries', label: 'frozen' },
  { text: 'frozen strawberries', label: 'frozen' },
  { text: 'frozen blueberries', label: 'frozen' },
  { text: 'frozen raspberries', label: 'frozen' },
  { text: 'frozen blackberries', label: 'frozen' },
  { text: 'frozen mixed berries', label: 'frozen' },
  { text: 'frozen mango', label: 'frozen' },
  { text: 'frozen pineapple', label: 'frozen' },
  { text: 'frozen peaches', label: 'frozen' },
  { text: 'frozen grapes', label: 'frozen' },
  { text: 'frozen banana', label: 'frozen' },
  { text: 'frozen kiwi', label: 'frozen' },
  { text: 'frozen lychee', label: 'frozen' },
  { text: 'frozen durian', label: 'frozen' },
  { text: 'frozen coconut', label: 'frozen' },
  { text: 'frozen passion fruit', label: 'frozen' },
  
  // Frozen Meat & Poultry
  { text: 'frozen chicken', label: 'frozen' },
  { text: 'frozen chicken breast', label: 'frozen' },
  { text: 'frozen chicken thigh', label: 'frozen' },
  { text: 'frozen chicken wings', label: 'frozen' },
  { text: 'frozen chicken drumstick', label: 'frozen' },
  { text: 'frozen whole chicken', label: 'frozen' },
  { text: 'frozen chicken nuggets', label: 'frozen' },
  { text: 'frozen chicken strips', label: 'frozen' },
  { text: 'frozen chicken patties', label: 'frozen' },
  { text: 'frozen beef', label: 'frozen' },
  { text: 'frozen beef mince', label: 'frozen' },
  { text: 'frozen beef steak', label: 'frozen' },
  { text: 'frozen beef patties', label: 'frozen' },
  { text: 'frozen hamburger patties', label: 'frozen' },
  { text: 'frozen pork', label: 'frozen' },
  { text: 'frozen pork chops', label: 'frozen' },
  { text: 'frozen pork ribs', label: 'frozen' },
  { text: 'frozen lamb', label: 'frozen' },
  { text: 'frozen lamb chops', label: 'frozen' },
  { text: 'frozen duck', label: 'frozen' },
  { text: 'frozen turkey', label: 'frozen' },
  
  // Frozen Seafood
  { text: 'frozen fish', label: 'frozen' },
  { text: 'frozen salmon', label: 'frozen' },
  { text: 'frozen cod', label: 'frozen' },
  { text: 'frozen tuna', label: 'frozen' },
  { text: 'frozen mackerel', label: 'frozen' },
  { text: 'frozen tilapia', label: 'frozen' },
  { text: 'frozen dory', label: 'frozen' },
  { text: 'frozen barramundi', label: 'frozen' },
  { text: 'frozen fish fillet', label: 'frozen' },
  { text: 'frozen fish fingers', label: 'frozen' },
  { text: 'frozen prawns', label: 'frozen' },
  { text: 'frozen shrimp', label: 'frozen' },
  { text: 'frozen crab', label: 'frozen' },
  { text: 'frozen lobster', label: 'frozen' },
  { text: 'frozen scallops', label: 'frozen' },
  { text: 'frozen mussels', label: 'frozen' },
  { text: 'frozen clams', label: 'frozen' },
  { text: 'frozen oysters', label: 'frozen' },
  { text: 'frozen squid', label: 'frozen' },
  { text: 'frozen octopus', label: 'frozen' },
  { text: 'frozen cuttlefish', label: 'frozen' },
  { text: 'frozen mixed seafood', label: 'frozen' },
  { text: 'frozen seafood mix', label: 'frozen' },
  
  // Frozen Ready Meals
  { text: 'frozen meals', label: 'frozen' },
  { text: 'frozen dinner', label: 'frozen' },
  { text: 'frozen tv dinner', label: 'frozen' },
  { text: 'frozen ready meals', label: 'frozen' },
  { text: 'frozen lasagna', label: 'frozen' },
  { text: 'frozen pizza', label: 'frozen' },
  { text: 'frozen pasta', label: 'frozen' },
  { text: 'frozen fried rice', label: 'frozen' },
  { text: 'frozen nasi lemak', label: 'frozen' },
  { text: 'frozen curry', label: 'frozen' },
  { text: 'frozen rendang', label: 'frozen' },
  { text: 'frozen laksa', label: 'frozen' },
  { text: 'frozen mee goreng', label: 'frozen' },
  { text: 'frozen char kway teow', label: 'frozen' },
  { text: 'frozen hokkien mee', label: 'frozen' },
  { text: 'frozen bak chor mee', label: 'frozen' },
  { text: 'frozen wonton noodles', label: 'frozen' },
  { text: 'frozen ramen', label: 'frozen' },
  { text: 'frozen udon', label: 'frozen' },
  
  // Frozen Dim Sum & Asian Foods
  { text: 'frozen dim sum', label: 'frozen' },
  { text: 'frozen dumplings', label: 'frozen' },
  { text: 'frozen gyoza', label: 'frozen' },
  { text: 'frozen potstickers', label: 'frozen' },
  { text: 'frozen siu mai', label: 'frozen' },
  { text: 'frozen har gow', label: 'frozen' },
  { text: 'frozen xiao long bao', label: 'frozen' },
  { text: 'frozen bao', label: 'frozen' },
  { text: 'frozen char siu bao', label: 'frozen' },
  { text: 'frozen mantou', label: 'frozen' },
  { text: 'frozen spring rolls', label: 'frozen' },
  { text: 'frozen popiah', label: 'frozen' },
  { text: 'frozen samosa', label: 'frozen' },
  { text: 'frozen curry puff', label: 'frozen' },
  { text: 'frozen wontons', label: 'frozen' },
  { text: 'frozen fish balls', label: 'frozen' },
  { text: 'frozen fish cake', label: 'frozen' },
  { text: 'frozen crab sticks', label: 'frozen' },
  { text: 'frozen tofu', label: 'frozen' },
  { text: 'frozen tau kwa', label: 'frozen' },
  
  // Frozen Bread & Pastries
  { text: 'frozen bread', label: 'frozen' },
  { text: 'frozen baguette', label: 'frozen' },
  { text: 'frozen croissant', label: 'frozen' },
  { text: 'frozen danish', label: 'frozen' },
  { text: 'frozen muffins', label: 'frozen' },
  { text: 'frozen bagels', label: 'frozen' },
  { text: 'frozen pita bread', label: 'frozen' },
  { text: 'frozen naan', label: 'frozen' },
  { text: 'frozen roti', label: 'frozen' },
  { text: 'frozen paratha', label: 'frozen' },
  { text: 'frozen puff pastry', label: 'frozen' },
  { text: 'frozen pie crust', label: 'frozen' },
  { text: 'frozen phyllo pastry', label: 'frozen' },
  { text: 'frozen waffles', label: 'frozen' },
  { text: 'frozen pancakes', label: 'frozen' },
  { text: 'frozen french toast', label: 'frozen' },
  
  // Frozen Desserts
  { text: 'frozen desserts', label: 'frozen' },
  { text: 'frozen cake', label: 'frozen' },
  { text: 'frozen cheesecake', label: 'frozen' },
  { text: 'frozen tiramisu', label: 'frozen' },
  { text: 'frozen mousse', label: 'frozen' },
  { text: 'frozen tart', label: 'frozen' },
  { text: 'frozen pie', label: 'frozen' },
  { text: 'frozen apple pie', label: 'frozen' },
  { text: 'frozen berry pie', label: 'frozen' },
  { text: 'frozen brownies', label: 'frozen' },
  { text: 'frozen cookies', label: 'frozen' },
  { text: 'frozen cookie dough', label: 'frozen' },
  { text: 'frozen ice cream cake', label: 'frozen' },
  { text: 'frozen yogurt', label: 'frozen' },
  { text: 'frozen sorbet', label: 'frozen' },
  { text: 'frozen gelato', label: 'frozen' },
  
  // Frozen Asian Desserts
  { text: 'frozen mochi', label: 'frozen' },
  { text: 'frozen ice cream mochi', label: 'frozen' },
  { text: 'frozen red bean ice cream', label: 'frozen' },
  { text: 'frozen green tea ice cream', label: 'frozen' },
  { text: 'frozen taro ice cream', label: 'frozen' },
  { text: 'frozen durian ice cream', label: 'frozen' },
  { text: 'frozen coconut ice cream', label: 'frozen' },
  { text: 'frozen tang yuan', label: 'frozen' },
  { text: 'frozen glutinous rice balls', label: 'frozen' },
  { text: 'frozen black sesame balls', label: 'frozen' },
  { text: 'frozen pandan cake', label: 'frozen' },
  { text: 'frozen kueh', label: 'frozen' },
  { text: 'frozen onde onde', label: 'frozen' },
  
  // Frozen Snacks
  { text: 'frozen fries', label: 'frozen' },
  { text: 'frozen french fries', label: 'frozen' },
  { text: 'frozen potato wedges', label: 'frozen' },
  { text: 'frozen hash browns', label: 'frozen' },
  { text: 'frozen tater tots', label: 'frozen' },
  { text: 'frozen onion rings', label: 'frozen' },
  { text: 'frozen mozzarella sticks', label: 'frozen' },
  { text: 'frozen jalapeno poppers', label: 'frozen' },
  { text: 'frozen corn dogs', label: 'frozen' },
  { text: 'frozen hot dogs', label: 'frozen' },
  { text: 'frozen sausages', label: 'frozen' },
  { text: 'frozen chicken wings', label: 'frozen' },
  { text: 'frozen buffalo wings', label: 'frozen' },
  { text: 'frozen popcorn chicken', label: 'frozen' },
  { text: 'frozen calamari rings', label: 'frozen' },
  { text: 'frozen tempura', label: 'frozen' },
  
  // Frozen Breakfast Items
  { text: 'frozen breakfast', label: 'frozen' },
  { text: 'frozen breakfast burrito', label: 'frozen' },
  { text: 'frozen breakfast sandwich', label: 'frozen' },
  { text: 'frozen breakfast bowl', label: 'frozen' },
  { text: 'frozen oatmeal', label: 'frozen' },
  { text: 'frozen smoothie packs', label: 'frozen' },
  { text: 'frozen acai bowl', label: 'frozen' },
  { text: 'frozen fruit bowl', label: 'frozen' },
  { text: 'frozen yogurt parfait', label: 'frozen' },
  
  // Frozen Noodles & Pasta
  { text: 'frozen noodles', label: 'frozen' },
  { text: 'frozen fresh noodles', label: 'frozen' },
  { text: 'frozen egg noodles', label: 'frozen' },
  { text: 'frozen rice noodles', label: 'frozen' },
  { text: 'frozen udon noodles', label: 'frozen' },
  { text: 'frozen soba noodles', label: 'frozen' },
  { text: 'frozen ramen noodles', label: 'frozen' },
  { text: 'frozen pasta', label: 'frozen' },
  { text: 'frozen ravioli', label: 'frozen' },
  { text: 'frozen tortellini', label: 'frozen' },
  { text: 'frozen gnocchi', label: 'frozen' },
  { text: 'frozen fettuccine', label: 'frozen' },
  { text: 'frozen linguine', label: 'frozen' },
  
  // Frozen Soups & Broths
  { text: 'frozen soup', label: 'frozen' },
  { text: 'frozen chicken soup', label: 'frozen' },
  { text: 'frozen vegetable soup', label: 'frozen' },
  { text: 'frozen mushroom soup', label: 'frozen' },
  { text: 'frozen tomato soup', label: 'frozen' },
  { text: 'frozen corn soup', label: 'frozen' },
  { text: 'frozen broth', label: 'frozen' },
  { text: 'frozen chicken broth', label: 'frozen' },
  { text: 'frozen beef broth', label: 'frozen' },
  { text: 'frozen vegetable broth', label: 'frozen' },
  { text: 'frozen bone broth', label: 'frozen' },
  { text: 'frozen stock', label: 'frozen' },
  
  // Frozen Herbs & Seasonings
  { text: 'frozen herbs', label: 'frozen' },
  { text: 'frozen basil', label: 'frozen' },
  { text: 'frozen parsley', label: 'frozen' },
  { text: 'frozen cilantro', label: 'frozen' },
  { text: 'frozen dill', label: 'frozen' },
  { text: 'frozen chives', label: 'frozen' },
  { text: 'frozen ginger', label: 'frozen' },
  { text: 'frozen garlic', label: 'frozen' },
  { text: 'frozen lemongrass', label: 'frozen' },
  { text: 'frozen curry leaves', label: 'frozen' },
  { text: 'frozen pandan leaves', label: 'frozen' },
  
  // Frozen Organic & Health Foods
  { text: 'frozen organic vegetables', label: 'frozen' },
  { text: 'frozen organic fruits', label: 'frozen' },
  { text: 'frozen organic meals', label: 'frozen' },
  { text: 'frozen gluten free', label: 'frozen' },
  { text: 'frozen vegan meals', label: 'frozen' },
  { text: 'frozen vegetarian meals', label: 'frozen' },
  { text: 'frozen low sodium', label: 'frozen' },
  { text: 'frozen low fat', label: 'frozen' },
  { text: 'frozen sugar free', label: 'frozen' },
  { text: 'frozen keto meals', label: 'frozen' },
  { text: 'frozen paleo meals', label: 'frozen' },
  
  // Frozen Specialty Items
  { text: 'frozen specialty foods', label: 'frozen' },
  { text: 'frozen gourmet meals', label: 'frozen' },
  { text: 'frozen artisan bread', label: 'frozen' },
  { text: 'frozen premium ice cream', label: 'frozen' },
  { text: 'frozen imported foods', label: 'frozen' },
  { text: 'frozen ethnic foods', label: 'frozen' },
  { text: 'frozen kosher meals', label: 'frozen' },
  { text: 'frozen halal meals', label: 'frozen' },
  { text: 'frozen baby food', label: 'frozen' },
  { text: 'frozen pet food', label: 'frozen' }
];

export default frozenTrainingData;