export const fruitsVegetablesData = [
  { text: 'apple', label: 'Fruits & Vegetables' },
  { text: 'banana', label: 'Fruits & Vegetables' },
  { text: 'orange', label: 'Fruits & Vegetables' },
  { text: 'grape', label: 'Fruits & Vegetables' },
  { text: 'strawberry', label: 'Fruits & Vegetables' },
  { text: 'blueberry', label: 'Fruits & Vegetables' },
  { text: 'raspberry', label: 'Fruits & Vegetables' },
  { text: 'blackberry', label: 'Fruits & Vegetables' },
  { text: 'pineapple', label: 'Fruits & Vegetables' },
  { text: 'mango', label: 'Fruits & Vegetables' },
  { text: 'papaya', label: 'Fruits & Vegetables' },
  { text: 'kiwi', label: 'Fruits & Vegetables' },
  { text: 'watermelon', label: 'Fruits & Vegetables' },
  { text: 'cantaloupe', label: 'Fruits & Vegetables' },
  { text: 'honeydew', label: 'Fruits & Vegetables' },
  { text: 'peach', label: 'Fruits & Vegetables' },
  { text: 'pear', label: 'Fruits & Vegetables' },
  { text: 'plum', label: 'Fruits & Vegetables' },
  { text: 'cherry', label: 'Fruits & Vegetables' },
  { text: 'apricot', label: 'Fruits & Vegetables' },
  { text: 'lemon', label: 'Fruits & Vegetables' },
  { text: 'lime', label: 'Fruits & Vegetables' },
  { text: 'grapefruit', label: 'Fruits & Vegetables' },
  { text: 'avocado', label: 'Fruits & Vegetables' },
  { text: 'coconut', label: 'Fruits & Vegetables' },
  { text: 'pomegranate', label: 'Fruits & Vegetables' },
  { text: 'fig', label: 'Fruits & Vegetables' },
  { text: 'date', label: 'Fruits & Vegetables' },
  { text: 'raisin', label: 'Fruits & Vegetables' },
  { text: 'cranberry', label: 'Fruits & Vegetables' },
  { text: 'tomato', label: 'Fruits & Vegetables' },
  { text: 'cucumber', label: 'Fruits & Vegetables' },
  { text: 'carrot', label: 'Fruits & Vegetables' },
  { text: 'potato', label: 'Fruits & Vegetables' },
  { text: 'sweet potato', label: 'Fruits & Vegetables' },
  { text: 'onion', label: 'Fruits & Vegetables' },
  { text: 'garlic', label: 'Fruits & Vegetables' },
  { text: 'ginger', label: 'Fruits & Vegetables' },
  { text: 'lettuce', label: 'Fruits & Vegetables' },
  { text: 'spinach', label: 'Fruits & Vegetables' },
  { text: 'kale', label: 'Fruits & Vegetables' },
  { text: 'broccoli', label: 'Fruits & Vegetables' },
  { text: 'cauliflower', label: 'Fruits & Vegetables' },
  { text: 'cabbage', label: 'Fruits & Vegetables' },
  { text: 'bell pepper', label: 'Fruits & Vegetables' },
  { text: 'chili pepper', label: 'Fruits & Vegetables' },
  { text: 'eggplant', label: 'Fruits & Vegetables' },
  { text: 'zucchini', label: 'Fruits & Vegetables' },
  { text: 'squash', label: 'Fruits & Vegetables' },
  { text: 'pumpkin', label: 'Fruits & Vegetables' },
  { text: 'corn', label: 'Fruits & Vegetables' },
  { text: 'green beans', label: 'Fruits & Vegetables' },
  { text: 'peas', label: 'Fruits & Vegetables' },
  { text: 'asparagus', label: 'Fruits & Vegetables' },
  { text: 'celery', label: 'Fruits & Vegetables' },
  { text: 'mushroom', label: 'Fruits & Vegetables' },
  { text: 'radish', label: 'Fruits & Vegetables' },
  { text: 'beetroot', label: 'Fruits & Vegetables' },
  { text: 'turnip', label: 'Fruits & Vegetables' },
  { text: 'parsnip', label: 'Fruits & Vegetables' },
  { text: 'leek', label: 'Fruits & Vegetables' },
  { text: 'shallot', label: 'Fruits & Vegetables' },
  { text: 'scallion', label: 'Fruits & Vegetables' },
  { text: 'spring onion', label: 'Fruits & Vegetables' },
  { text: 'chives', label: 'Fruits & Vegetables' },
  { text: 'parsley', label: 'Fruits & Vegetables' },
  { text: 'cilantro', label: 'Fruits & Vegetables' },
  { text: 'basil', label: 'Fruits & Vegetables' },
  { text: 'mint', label: 'Fruits & Vegetables' },
  { text: 'dill', label: 'Fruits & Vegetables' },
  { text: 'rosemary', label: 'Fruits & Vegetables' },
  { text: 'thyme', label: 'Fruits & Vegetables' },
  { text: 'oregano', label: 'Fruits & Vegetables' },
  { text: 'sage', label: 'Fruits & Vegetables' },
  { text: 'arugula', label: 'Fruits & Vegetables' },
  { text: 'watercress', label: 'Fruits & Vegetables' },
  { text: 'bok choy', label: 'Fruits & Vegetables' },
  { text: 'chinese cabbage', label: 'Fruits & Vegetables' },
  { text: 'napa cabbage', label: 'Fruits & Vegetables' },
  { text: 'brussels sprouts', label: 'Fruits & Vegetables' },
  { text: 'artichoke', label: 'Fruits & Vegetables' },
  { text: 'okra', label: 'Fruits & Vegetables' },
  { text: 'fennel', label: 'Fruits & Vegetables' },
  { text: 'endive', label: 'Fruits & Vegetables' },
  { text: 'radicchio', label: 'Fruits & Vegetables' },
  { text: 'swiss chard', label: 'Fruits & Vegetables' },
  { text: 'collard greens', label: 'Fruits & Vegetables' },
  { text: 'mustard greens', label: 'Fruits & Vegetables' },
  { text: 'turnip greens', label: 'Fruits & Vegetables' },
  { text: 'beet greens', label: 'Fruits & Vegetables' },
  { text: 'dandelion greens', label: 'Fruits & Vegetables' },
  { text: 'kohlrabi', label: 'Fruits & Vegetables' },
  { text: 'rutabaga', label: 'Fruits & Vegetables' },
  { text: 'jicama', label: 'Fruits & Vegetables' },
  { text: 'daikon', label: 'Fruits & Vegetables' },
  { text: 'horseradish', label: 'Fruits & Vegetables' },
  { text: 'wasabi', label: 'Fruits & Vegetables' },
  { text: 'lemongrass', label: 'Fruits & Vegetables' },
  { text: 'galangal', label: 'Fruits & Vegetables' },
  { text: 'turmeric', label: 'Fruits & Vegetables' },
  { text: 'taro', label: 'Fruits & Vegetables' },
  { text: 'yam', label: 'Fruits & Vegetables' },
  { text: 'cassava', label: 'Fruits & Vegetables' },
  { text: 'plantain', label: 'Fruits & Vegetables' },
  { text: 'breadfruit', label: 'Fruits & Vegetables' },
  { text: 'jackfruit', label: 'Fruits & Vegetables' },
  { text: 'durian', label: 'Fruits & Vegetables' },
  { text: 'rambutan', label: 'Fruits & Vegetables' },
  { text: 'lychee', label: 'Fruits & Vegetables' },
  { text: 'longan', label: 'Fruits & Vegetables' },
  { text: 'dragon fruit', label: 'Fruits & Vegetables' },
  { text: 'passion fruit', label: 'Fruits & Vegetables' },
  { text: 'star fruit', label: 'Fruits & Vegetables' },
  { text: 'guava', label: 'Fruits & Vegetables' },
  { text: 'persimmon', label: 'Fruits & Vegetables' },
  { text: 'pomelo', label: 'Fruits & Vegetables' },
  { text: 'mandarin', label: 'Fruits & Vegetables' },
  { text: 'tangerine', label: 'Fruits & Vegetables' },
  { text: 'clementine', label: 'Fruits & Vegetables' },
  { text: 'nectarine', label: 'Fruits & Vegetables' },
  { text: 'elderberry', label: 'Fruits & Vegetables' },
  { text: 'gooseberry', label: 'Fruits & Vegetables' },
  { text: 'currant', label: 'Fruits & Vegetables' },
  { text: 'mulberry', label: 'Fruits & Vegetables' },
  { text: 'boysenberry', label: 'Fruits & Vegetables' },
  { text: 'loganberry', label: 'Fruits & Vegetables' },
  { text: 'cloudberry', label: 'Fruits & Vegetables' },
  { text: 'huckleberry', label: 'Fruits & Vegetables' },
  { text: 'acai berry', label: 'Fruits & Vegetables' },
  { text: 'goji berry', label: 'Fruits & Vegetables' },
  { text: 'sea buckthorn', label: 'Fruits & Vegetables' },
  { text: 'cactus pear', label: 'Fruits & Vegetables' },
  { text: 'prickly pear', label: 'Fruits & Vegetables' },
  { text: 'quince', label: 'Fruits & Vegetables' },
  { text: 'medlar', label: 'Fruits & Vegetables' },
  { text: 'loquat', label: 'Fruits & Vegetables' },
  { text: 'tamarind', label: 'Fruits & Vegetables' },
  { text: 'soursop', label: 'Fruits & Vegetables' },
  { text: 'custard apple', label: 'Fruits & Vegetables' },
  { text: 'sugar apple', label: 'Fruits & Vegetables' },
  { text: 'cherimoya', label: 'Fruits & Vegetables' },
  { text: 'atemoya', label: 'Fruits & Vegetables' },
  { text: 'sapodilla', label: 'Fruits & Vegetables' },
  { text: 'mamey', label: 'Fruits & Vegetables' },
  { text: 'caimito', label: 'Fruits & Vegetables' },
  { text: 'abiu', label: 'Fruits & Vegetables' },
  { text: 'jabuticaba', label: 'Fruits & Vegetables' },
  { text: 'acerola', label: 'Fruits & Vegetables' },
  { text: 'caju', label: 'Fruits & Vegetables' },
  { text: 'pitanga', label: 'Fruits & Vegetables' },
  { text: 'cupuacu', label: 'Fruits & Vegetables' },
  { text: 'cacao', label: 'Fruits & Vegetables' },
  { text: 'vanilla bean', label: 'Fruits & Vegetables' },
  { text: 'black pepper', label: 'Fruits & Vegetables' },
  { text: 'white pepper', label: 'Fruits & Vegetables' },
  { text: 'green pepper', label: 'Fruits & Vegetables' },
  { text: 'pink pepper', label: 'Fruits & Vegetables' },
  { text: 'sichuan pepper', label: 'Fruits & Vegetables' },
  { text: 'long pepper', label: 'Fruits & Vegetables' },
  { text: 'cubeb pepper', label: 'Fruits & Vegetables' },
  { text: 'grains of paradise', label: 'Fruits & Vegetables' },
  { text: 'cardamom', label: 'Fruits & Vegetables' },
  { text: 'cinnamon', label: 'Fruits & Vegetables' },
  { text: 'cassia', label: 'Fruits & Vegetables' },
  { text: 'nutmeg', label: 'Fruits & Vegetables' },
  { text: 'mace', label: 'Fruits & Vegetables' },
  { text: 'cloves', label: 'Fruits & Vegetables' }
];