// Training data for Health & Wellness category
// Singapore-specific health and wellness products

export const healthWellnessTrainingData = [
  // Vitamins and supplements
  { text: 'vitamin c', label: 'health' },
  { text: 'vitamin d', label: 'health' },
  { text: 'vitamin b complex', label: 'health' },
  { text: 'multivitamin', label: 'health' },
  { text: 'calcium', label: 'health' },
  { text: 'iron supplement', label: 'health' },
  { text: 'omega 3', label: 'health' },
  { text: 'fish oil', label: 'health' },
  { text: 'probiotics', label: 'health' },
  { text: 'protein powder', label: 'health' },
  { text: 'collagen', label: 'health' },
  { text: 'glucosamine', label: 'health' },
  { text: 'zinc', label: 'health' },
  { text: 'magnesium', label: 'health' },
  { text: 'folic acid', label: 'health' },
  
  // Traditional Chinese Medicine (popular in Singapore)
  { text: 'bird nest', label: 'health' },
  { text: 'ginseng', label: 'health' },
  { text: 'cordyceps', label: 'health' },
  { text: 'lingzhi', label: 'health' },
  { text: 'royal jelly', label: 'health' },
  { text: 'propolis', label: 'health' },
  { text: 'essence of chicken', label: 'health' },
  { text: 'herbal tea', label: 'health' },
  { text: 'chrysanthemum tea', label: 'health' },
  { text: 'cooling tea', label: 'health' },
  { text: 'chinese herbs', label: 'health' },
  { text: 'traditional medicine', label: 'health' },
  { text: 'tcm', label: 'health' },
  { text: 'dried longan', label: 'health' },
  { text: 'red dates', label: 'health' },
  
  // Over-the-counter medications
  { text: 'paracetamol', label: 'health' },
  { text: 'ibuprofen', label: 'health' },
  { text: 'aspirin', label: 'health' },
  { text: 'cough syrup', label: 'health' },
  { text: 'throat lozenges', label: 'health' },
  { text: 'cold medicine', label: 'health' },
  { text: 'flu medicine', label: 'health' },
  { text: 'antacid', label: 'health' },
  { text: 'stomach medicine', label: 'health' },
  { text: 'diarrhea medicine', label: 'health' },
  { text: 'constipation relief', label: 'health' },
  { text: 'antihistamine', label: 'health' },
  { text: 'allergy medicine', label: 'health' },
  { text: 'eye drops', label: 'health' },
  { text: 'nasal spray', label: 'health' },
  
  // First aid and medical supplies
  { text: 'bandage', label: 'health' },
  { text: 'plaster', label: 'health' },
  { text: 'antiseptic', label: 'health' },
  { text: 'hydrogen peroxide', label: 'health' },
  { text: 'rubbing alcohol', label: 'health' },
  { text: 'cotton wool', label: 'health' },
  { text: 'gauze', label: 'health' },
  { text: 'medical tape', label: 'health' },
  { text: 'thermometer', label: 'health' },
  { text: 'blood pressure monitor', label: 'health' },
  { text: 'glucose meter', label: 'health' },
  { text: 'pulse oximeter', label: 'health' },
  { text: 'heating pad', label: 'health' },
  { text: 'ice pack', label: 'health' },
  { text: 'compression bandage', label: 'health' },
  
  // Topical treatments
  { text: 'muscle rub', label: 'health' },
  { text: 'pain relief gel', label: 'health' },
  { text: 'tiger balm', label: 'health' },
  { text: 'medicated oil', label: 'health' },
  { text: 'antifungal cream', label: 'health' },
  { text: 'antibiotic ointment', label: 'health' },
  { text: 'hydrocortisone cream', label: 'health' },
  { text: 'calamine lotion', label: 'health' },
  { text: 'insect bite cream', label: 'health' },
  { text: 'sunburn gel', label: 'health' },
  { text: 'hemorrhoid cream', label: 'health' },
  { text: 'acne treatment', label: 'health' },
  { text: 'wart remover', label: 'health' },
  { text: 'corn plaster', label: 'health' },
  { text: 'foot cream', label: 'health' },
  
  // Oral care
  { text: 'mouthwash', label: 'health' },
  { text: 'dental floss', label: 'health' },
  { text: 'teeth whitening', label: 'health' },
  { text: 'denture cleaner', label: 'health' },
  { text: 'oral gel', label: 'health' },
  { text: 'breath spray', label: 'health' },
  { text: 'tongue cleaner', label: 'health' },
  { text: 'mouth ulcer gel', label: 'health' },
  { text: 'gum care', label: 'health' },
  { text: 'fluoride rinse', label: 'health' },
  { text: 'sensitive teeth', label: 'health' },
  { text: 'orthodontic wax', label: 'health' },
  { text: 'retainer cleaner', label: 'health' },
  { text: 'dry mouth spray', label: 'health' },
  { text: 'teething gel', label: 'health' },
  
  // Women's health
  { text: 'sanitary pads', label: 'health' },
  { text: 'tampons', label: 'health' },
  { text: 'menstrual cup', label: 'health' },
  { text: 'panty liners', label: 'health' },
  { text: 'pregnancy test', label: 'health' },
  { text: 'ovulation test', label: 'health' },
  { text: 'prenatal vitamins', label: 'health' },
  { text: 'folic acid', label: 'health' },
  { text: 'iron tablets', label: 'health' },
  { text: 'breast pads', label: 'health' },
  { text: 'stretch mark cream', label: 'health' },
  { text: 'feminine wash', label: 'health' },
  { text: 'yeast infection treatment', label: 'health' },
  { text: 'uti relief', label: 'health' },
  { text: 'menopause support', label: 'health' },
  
  // Sleep and relaxation
  { text: 'melatonin', label: 'health' },
  { text: 'sleep aid', label: 'health' },
  { text: 'lavender oil', label: 'health' },
  { text: 'essential oil', label: 'health' },
  { text: 'aromatherapy', label: 'health' },
  { text: 'stress relief', label: 'health' },
  { text: 'relaxation tea', label: 'health' },
  { text: 'chamomile tea', label: 'health' },
  { text: 'valerian root', label: 'health' },
  { text: 'magnesium supplement', label: 'health' },
  { text: 'meditation app', label: 'health' },
  { text: 'white noise machine', label: 'health' },
  { text: 'sleep mask', label: 'health' },
  { text: 'earplugs', label: 'health' },
  { text: 'pillow spray', label: 'health' },

    // Fitness equipment
  { text: 'dumbbells', label: 'health' },
  { text: 'resistance bands', label: 'health' },
  { text: 'yoga mat', label: 'health' },
  { text: 'exercise ball', label: 'health' },
  { text: 'foam roller', label: 'health' },
  { text: 'kettlebell', label: 'health' },
  { text: 'pull up bar', label: 'health' },
  { text: 'jump rope', label: 'health' },
  { text: 'ab wheel', label: 'health' },
  { text: 'push up bars', label: 'health' },
  { text: 'weight plates', label: 'health' },
  { text: 'barbell', label: 'health' },
  { text: 'bench press', label: 'health' },
  { text: 'treadmill', label: 'health' },
  { text: 'stationary bike', label: 'health' },
  
  // Swimming (popular in Singapore)
  { text: 'swimsuit', label: 'health' },
  { text: 'swimming goggles', label: 'health' },
  { text: 'swim cap', label: 'health' },
  { text: 'kickboard', label: 'health' },
  { text: 'pool noodle', label: 'health' },
  { text: 'swimming fins', label: 'health' },
  { text: 'snorkel', label: 'health' },
  { text: 'diving mask', label: 'health' },
  { text: 'life jacket', label: 'health' },
  { text: 'floaties', label: 'health' },
  { text: 'pool float', label: 'health' },
  { text: 'waterproof bag', label: 'health' },
  { text: 'beach towel', label: 'health' },
  { text: 'swim bag', label: 'health' },
  { text: 'chlorine remover', label: 'health' },
  
  // Running and jogging
  { text: 'running shoes', label: 'health' },
  { text: 'running shorts', label: 'health' },
  { text: 'running shirt', label: 'health' },
  { text: 'sports bra', label: 'health' },
  { text: 'compression tights', label: 'health' },
  { text: 'running belt', label: 'health' },
  { text: 'armband', label: 'health' },
  { text: 'reflective vest', label: 'health' },
  { text: 'running cap', label: 'health' },
  { text: 'sweatband', label: 'health' },
  { text: 'running socks', label: 'health' },
  { text: 'gps watch', label: 'health' },
  { text: 'heart rate monitor', label: 'health' },
  { text: 'hydration pack', label: 'health' },
  { text: 'energy gel', label: 'health' },
  
  // Cycling
  { text: 'bicycle', label: 'health' },
  { text: 'bike helmet', label: 'health' },
  { text: 'cycling shorts', label: 'health' },
  { text: 'cycling jersey', label: 'health' },
  { text: 'bike lock', label: 'health' },
  { text: 'bike lights', label: 'health' },
  { text: 'bike pump', label: 'health' },
  { text: 'bike tire', label: 'health' },
  { text: 'bike chain', label: 'health' },
  { text: 'bike repair kit', label: 'health' },
  { text: 'bike bottle', label: 'health' },
  { text: 'bike bag', label: 'health' },
  { text: 'bike computer', label: 'health' },
  { text: 'bike gloves', label: 'health' },
  { text: 'bike seat', label: 'health' },
  
  // Badminton (very popular in Singapore)
  { text: 'badminton racket', label: 'health' },
  { text: 'shuttlecock', label: 'health' },
  { text: 'badminton shoes', label: 'health' },
  { text: 'badminton bag', label: 'health' },
  { text: 'grip tape', label: 'health' },
  { text: 'racket string', label: 'health' },
  { text: 'badminton net', label: 'health' },
  { text: 'court shoes', label: 'health' },
  { text: 'wrist support', label: 'health' },
  { text: 'knee support', label: 'health' },
  { text: 'ankle support', label: 'health' },
  { text: 'sports tape', label: 'health' },
  { text: 'muscle spray', label: 'health' },
  { text: 'cooling towel', label: 'health' },
  { text: 'sports drink', label: 'health' },
  
  // Tennis
  { text: 'tennis racket', label: 'health' },
  { text: 'tennis ball', label: 'health' },
  { text: 'tennis shoes', label: 'health' },
  { text: 'tennis bag', label: 'health' },
  { text: 'tennis string', label: 'health' },
  { text: 'tennis grip', label: 'health' },
  { text: 'tennis net', label: 'health' },
  { text: 'ball machine', label: 'health' },
  { text: 'tennis skirt', label: 'health' },
  { text: 'tennis shirt', label: 'health' },
  { text: 'visor', label: 'health' },
  { text: 'sweat absorber', label: 'health' },
  { text: 'elbow brace', label: 'health' },
  { text: 'tennis dampener', label: 'health' },
  { text: 'court marker', label: 'health' },
  
  // Basketball
  { text: 'basketball', label: 'health' },
  { text: 'basketball shoes', label: 'health' },
  { text: 'basketball hoop', label: 'health' },
  { text: 'basketball net', label: 'health' },
  { text: 'basketball shorts', label: 'health' },
  { text: 'basketball jersey', label: 'health' },
  { text: 'ball pump', label: 'health' },
  { text: 'basketball bag', label: 'health' },
  { text: 'shooting sleeve', label: 'health' },
  { text: 'headband', label: 'health' },
  { text: 'mouthguard', label: 'health' },
  { text: 'athletic tape', label: 'health' },
  { text: 'compression shorts', label: 'health' },
  { text: 'training cones', label: 'health' },
  { text: 'agility ladder', label: 'health' },
  
  // Football/Soccer
  { text: 'football', label: 'health' },
  { text: 'soccer ball', label: 'health' },
  { text: 'football boots', label: 'health' },
  { text: 'shin guards', label: 'health' },
  { text: 'football socks', label: 'health' },
  { text: 'football shorts', label: 'health' },
  { text: 'football jersey', label: 'health' },
  { text: 'goalkeeper gloves', label: 'health' },
  { text: 'football goal', label: 'health' },
  { text: 'football net', label: 'health' },
  { text: 'training bibs', label: 'health' },
  { text: 'corner flags', label: 'health' },
  { text: 'football bag', label: 'health' },
  { text: 'captain armband', label: 'health' },
  { text: 'referee whistle', label: 'health' },
  
  // Outdoor activities
  { text: 'hiking boots', label: 'health' },
  { text: 'backpack', label: 'health' },
  { text: 'camping tent', label: 'health' },
  { text: 'sleeping bag', label: 'health' },
  { text: 'camping chair', label: 'health' },
  { text: 'portable stove', label: 'health' },
  { text: 'camping cookware', label: 'health' },
  { text: 'water bottle', label: 'health' },
  { text: 'thermos flask', label: 'health' },
  { text: 'headlamp', label: 'health' },
  { text: 'flashlight', label: 'health' },
  { text: 'compass', label: 'health' },
  { text: 'binoculars', label: 'health' },
  { text: 'mosquito net', label: 'health' },
  { text: 'insect repellent', label: 'health' },
  
  // Water sports
  { text: 'surfboard', label: 'health' },
  { text: 'wetsuit', label: 'health' },
  { text: 'life vest', label: 'health' },
  { text: 'kayak', label: 'health' },
  { text: 'paddle', label: 'health' },
  { text: 'snorkeling gear', label: 'health' },
  { text: 'diving equipment', label: 'health' },
  { text: 'fishing rod', label: 'health' },
  { text: 'fishing reel', label: 'health' },
  { text: 'fishing bait', label: 'health' },
  { text: 'tackle box', label: 'health' },
  { text: 'fishing net', label: 'health' },
  { text: 'cooler box', label: 'health' },
  { text: 'beach umbrella', label: 'health' },
  { text: 'beach chair', label: 'health' }
];