// Training data for Household category
// Consolidated from householdEssentials.ts and householdCleaning.ts
// Singapore-specific household products and cleaning supplies

export const householdTrainingData = [
  // Cleaning supplies
  { text: 'detergent', label: 'household' },
  { text: 'laundry detergent', label: 'household' },
  { text: 'washing powder', label: 'household' },
  { text: 'liquid detergent', label: 'household' },
  { text: 'laundry pods', label: 'household' },
  { text: 'fabric softener', label: 'household' },
  { text: 'fabric conditioner', label: 'household' },
  { text: 'bleach', label: 'household' },
  { text: 'oxygen bleach', label: 'household' },
  { text: 'color safe bleach', label: 'household' },
  { text: 'dishwashing liquid', label: 'household' },
  { text: 'dish soap', label: 'household' },
  { text: 'dishwasher detergent', label: 'household' },
  { text: 'dishwasher pods', label: 'household' },
  { text: 'dishwasher tablets', label: 'household' },
  { text: 'rinse aid', label: 'household' },
  { text: 'dishwasher salt', label: 'household' },
  { text: 'floor cleaner', label: 'household' },
  { text: 'floor polish', label: 'household' },
  { text: 'floor wax', label: 'household' },
  { text: 'wood floor cleaner', label: 'household' },
  { text: 'laminate floor cleaner', label: 'household' },
  { text: 'tile floor cleaner', label: 'household' },
  { text: 'vinyl floor cleaner', label: 'household' },
  { text: 'marble floor cleaner', label: 'household' },
  { text: 'stone floor cleaner', label: 'household' },
  { text: 'toilet cleaner', label: 'household' },
  { text: 'toilet bowl cleaner', label: 'household' },
  { text: 'bathroom cleaner', label: 'household' },
  { text: 'shower cleaner', label: 'household' },
  { text: 'tub cleaner', label: 'household' },
  { text: 'tile cleaner', label: 'household' },
  { text: 'grout cleaner', label: 'household' },
  { text: 'glass cleaner', label: 'household' },
  { text: 'window cleaner', label: 'household' },
  { text: 'mirror cleaner', label: 'household' },
  { text: 'streak free cleaner', label: 'household' },
  { text: 'all purpose cleaner', label: 'household' },
  { text: 'multi surface cleaner', label: 'household' },
  { text: 'kitchen cleaner', label: 'household' },
  { text: 'oven cleaner', label: 'household' },
  { text: 'grill cleaner', label: 'household' },
  { text: 'stovetop cleaner', label: 'household' },
  { text: 'range hood cleaner', label: 'household' },
  { text: 'microwave cleaner', label: 'household' },
  { text: 'refrigerator cleaner', label: 'household' },
  { text: 'stainless steel cleaner', label: 'household' },
  { text: 'granite cleaner', label: 'household' },
  { text: 'countertop cleaner', label: 'household' },
  { text: 'cutting board cleaner', label: 'household' },
  { text: 'garbage disposal cleaner', label: 'household' },
  { text: 'coffee maker cleaner', label: 'household' },
  { text: 'descaler', label: 'household' },
  { text: 'kettle descaler', label: 'household' },
  { text: 'dishwasher cleaner', label: 'household' },
  { text: 'disinfectant', label: 'household' },
  { text: 'antibacterial spray', label: 'household' },
  { text: 'antibacterial cleaner', label: 'household' },
  { text: 'antiseptic', label: 'household' },
  { text: 'sanitizer', label: 'household' },
  { text: 'surface sanitizer', label: 'household' },
  { text: 'spray cleaner', label: 'household' },
  { text: 'stain remover', label: 'household' },
  { text: 'pre wash stain remover', label: 'household' },
  { text: 'carpet cleaner', label: 'household' },
  { text: 'rug cleaner', label: 'household' },
  { text: 'carpet shampoo', label: 'household' },
  { text: 'spot cleaner', label: 'household' },
  { text: 'steam cleaner', label: 'household' },
  { text: 'carpet steam cleaner', label: 'household' },
  { text: 'furniture polish', label: 'household' },
  { text: 'wood polish', label: 'household' },
  { text: 'wood cleaner', label: 'household' },
  { text: 'furniture wax', label: 'household' },
  { text: 'wood conditioner', label: 'household' },
  { text: 'leather cleaner', label: 'household' },
  { text: 'leather conditioner', label: 'household' },
  { text: 'upholstery cleaner', label: 'household' },
  { text: 'fabric cleaner', label: 'household' },
  { text: 'mold remover', label: 'household' },
  { text: 'mildew remover', label: 'household' },
  { text: 'lime scale remover', label: 'household' },
  { text: 'calcium remover', label: 'household' },
  { text: 'rust remover', label: 'household' },
  { text: 'soap scum remover', label: 'household' },
  { text: 'drain cleaner', label: 'household' },
  { text: 'pipe cleaner', label: 'household' },
  { text: 'laundry booster', label: 'household' },
  { text: 'washing machine cleaner', label: 'household' },
  { text: 'dryer sheets', label: 'household' },
  { text: 'wool wash', label: 'household' },
  { text: 'delicate wash', label: 'household' },
  { text: 'hypoallergenic detergent', label: 'household' },
  { text: 'eco friendly detergent', label: 'household' },
  { text: 'concentrated detergent', label: 'household' },
  { text: 'degreaser', label: 'household' },

  // Paper products
  { text: 'toilet paper', label: 'household' },
  { text: 'tissue paper', label: 'household' },
  { text: 'facial tissue', label: 'household' },
  { text: 'tissues', label: 'household' },
  { text: 'kitchen towel', label: 'household' },
  { text: 'paper towel', label: 'household' },
  { text: 'paper towels', label: 'household' },
  { text: 'kitchen roll', label: 'household' },
  { text: 'napkins', label: 'household' },
  { text: 'wet tissue', label: 'household' },
  { text: 'aluminum foil', label: 'household' },
  { text: 'cling wrap', label: 'household' },
  { text: 'plastic wrap', label: 'household' },
  { text: 'baking paper', label: 'household' },
  { text: 'parchment paper', label: 'household' },
  { text: 'garbage bags', label: 'household' },
  { text: 'trash bags', label: 'household' },
  { text: 'bin liners', label: 'household' },
  { text: 'recycling bags', label: 'household' },
  { text: 'compost bags', label: 'household' },
  { text: 'biodegradable bags', label: 'household' },
  { text: 'heavy duty bags', label: 'household' },
  { text: 'kitchen bags', label: 'household' },
  { text: 'tall kitchen bags', label: 'household' },
  { text: 'small trash bags', label: 'household' },
  { text: 'lawn bags', label: 'household' },
  { text: 'leaf bags', label: 'household' },
  { text: 'contractor bags', label: 'household' },
  { text: 'ziplock bags', label: 'household' },
  { text: 'food storage bags', label: 'household' },
  { text: 'freezer bags', label: 'household' },

  // Cleaning tools
  { text: 'sponge', label: 'household' },
  { text: 'scrubber', label: 'household' },
  { text: 'dish scrubber', label: 'household' },
  { text: 'steel wool', label: 'household' },
  { text: 'scouring pad', label: 'household' },
  { text: 'cleaning cloth', label: 'household' },
  { text: 'cleaning cloths', label: 'household' },
  { text: 'microfiber cloth', label: 'household' },
  { text: 'lint free cloth', label: 'household' },
  { text: 'chamois', label: 'household' },
  { text: 'disposable cloths', label: 'household' },
  { text: 'dust cloths', label: 'household' },
  { text: 'mop', label: 'household' },
  { text: 'floor mop', label: 'household' },
  { text: 'wet mop', label: 'household' },
  { text: 'dry mop', label: 'household' },
  { text: 'microfiber mop', label: 'household' },
  { text: 'steam mop', label: 'household' },
  { text: 'mop bucket', label: 'household' },
  { text: 'mop head', label: 'household' },
  { text: 'mop refill', label: 'household' },
  { text: 'broom', label: 'household' },
  { text: 'dustpan', label: 'household' },
  { text: 'vacuum cleaner', label: 'household' },
  { text: 'vacuum cleaner bags', label: 'household' },
  { text: 'vacuum bags', label: 'household' },
  { text: 'vacuum filter', label: 'household' },
  { text: 'rubber gloves', label: 'household' },
  { text: 'disposable gloves', label: 'household' },
  { text: 'cleaning gloves', label: 'household' },
  { text: 'toilet brush', label: 'household' },
  { text: 'bottle brush', label: 'household' },
  { text: 'scrub brush', label: 'household' },
  { text: 'dish brush', label: 'household' },
  { text: 'cleaning brush', label: 'household' },
  { text: 'toothbrush', label: 'household' },
  { text: 'old toothbrush', label: 'household' },
  { text: 'duster', label: 'household' },
  { text: 'feather duster', label: 'household' },
  { text: 'microfiber duster', label: 'household' },
  { text: 'extendable duster', label: 'household' },
  { text: 'squeegee', label: 'household' },
  { text: 'window squeegee', label: 'household' },
  { text: 'bucket', label: 'household' },
  { text: 'cleaning bucket', label: 'household' },
  { text: 'spray bottle', label: 'household' },
  { text: 'trigger spray', label: 'household' },
  { text: 'cleaning caddy', label: 'household' },
  { text: 'cleaning cart', label: 'household' },
  { text: 'step ladder', label: 'household' },
  { text: 'extension pole', label: 'household' },
  { text: 'plunger', label: 'household' },
  { text: 'toilet plunger', label: 'household' },

  // Air fresheners and odor control
  { text: 'air freshener', label: 'household' },
  { text: 'room spray', label: 'household' },
  { text: 'air spray', label: 'household' },
  { text: 'reed diffuser', label: 'household' },
  { text: 'scented candle', label: 'household' },
  { text: 'incense', label: 'household' },
  { text: 'odor eliminator', label: 'household' },
  { text: 'odor neutralizer', label: 'household' },
  { text: 'deodorizer', label: 'household' },
  { text: 'fabric refresher', label: 'household' },
  { text: 'plug in air freshener', label: 'household' },
  { text: 'automatic air freshener', label: 'household' },
  { text: 'car air freshener', label: 'household' },
  { text: 'toilet air freshener', label: 'household' },
  { text: 'closet freshener', label: 'household' },
  { text: 'shoe deodorizer', label: 'household' },
  { text: 'pet odor eliminator', label: 'household' },
  { text: 'smoke odor eliminator', label: 'household' },
  { text: 'mosquito coil', label: 'household' },
  { text: 'insect repellent', label: 'household' },
  { text: 'cockroach bait', label: 'household' },
  { text: 'ant killer', label: 'household' },
  { text: 'fly spray', label: 'household' },
  { text: 'mothballs', label: 'household' },
  { text: 'dehumidifier', label: 'household' },
  { text: 'moisture absorber', label: 'household' },
  { text: 'charcoal bag', label: 'household' },

  // Laundry accessories
  { text: 'starch spray', label: 'household' },
  { text: 'ironing spray', label: 'household' },
  { text: 'clothes hanger', label: 'household' },
  { text: 'hangers', label: 'household' },
  { text: 'clothes hangers', label: 'household' },
  { text: 'plastic hangers', label: 'household' },
  { text: 'wooden hangers', label: 'household' },
  { text: 'velvet hangers', label: 'household' },
  { text: 'clothespin', label: 'household' },
  { text: 'laundry net', label: 'household' },
  { text: 'color catcher', label: 'household' },
  { text: 'whitening agent', label: 'household' },
  { text: 'enzyme cleaner', label: 'household' },
  { text: 'garment bags', label: 'household' },
  { text: 'space saver bags', label: 'household' },
  { text: 'compression bags', label: 'household' },
  { text: 'cedar blocks', label: 'household' },
  { text: 'cedar balls', label: 'household' },
  { text: 'lavender sachets', label: 'household' },

  // Kitchen accessories
  { text: 'oven mitt', label: 'household' },
  { text: 'pot holder', label: 'household' },
  { text: 'dish towel', label: 'household' },
  { text: 'dish rack', label: 'household' },
  { text: 'dish drying mat', label: 'household' },
  { text: 'cutting board', label: 'household' },
  { text: 'food container', label: 'household' },
  { text: 'tupperware', label: 'household' },
  { text: 'ice cube tray', label: 'household' },
  { text: 'water filter', label: 'household' },

  // Bathroom accessories
  { text: 'shower curtain', label: 'household' },
  { text: 'bath mat', label: 'household' },
  { text: 'toilet seat cover', label: 'household' },
  { text: 'toilet paper holder', label: 'household' },
  { text: 'soap dispenser', label: 'household' },
  { text: 'toothbrush holder', label: 'household' },
  { text: 'towel rack', label: 'household' },
  { text: 'bathroom scale', label: 'household' },
  { text: 'drain stopper', label: 'household' },
  { text: 'shower head', label: 'household' },
  { text: 'bath towel', label: 'household' },
  { text: 'face towel', label: 'household' },
  { text: 'hand towel', label: 'household' },
  { text: 'washcloth', label: 'household' },

  // Hardware and tools
  { text: 'light bulb', label: 'household' },
  { text: 'led bulb', label: 'household' },
  { text: 'battery', label: 'household' },
  { text: 'extension cord', label: 'household' },
  { text: 'power strip', label: 'household' },
  { text: 'duct tape', label: 'household' },
  { text: 'super glue', label: 'household' },
  { text: 'screwdriver', label: 'household' },
  { text: 'hammer', label: 'household' },
  { text: 'nails', label: 'household' },
  { text: 'screws', label: 'household' },
  { text: 'wall hooks', label: 'household' },
  { text: 'command strips', label: 'household' },
  { text: 'cable ties', label: 'household' },
  { text: 'fuse', label: 'household' },

  // Wipes and disposables
  { text: 'wipes', label: 'household' },
  { text: 'cleaning wipes', label: 'household' },
  { text: 'disinfectant wipes', label: 'household' },
  { text: 'antibacterial wipes', label: 'household' },
  { text: 'wet wipes', label: 'household' },
  { text: 'disposable wipes', label: 'household' },
  { text: 'lint rollers', label: 'household' },
  { text: 'lint roller refills', label: 'household' },
  { text: 'dryer lint', label: 'household' },
  { text: 'cotton swabs', label: 'household' },
  { text: 'cotton balls', label: 'household' },
  { text: 'cotton pads', label: 'household' },

  // Pest control
  { text: 'insect spray', label: 'household' },
  { text: 'bug spray', label: 'household' },
  { text: 'roach killer', label: 'household' },
  { text: 'cockroach spray', label: 'household' },
  { text: 'mosquito spray', label: 'household' },
  { text: 'spider spray', label: 'household' },
  { text: 'wasp spray', label: 'household' },
  { text: 'termite spray', label: 'household' },
  { text: 'flea spray', label: 'household' },
  { text: 'tick spray', label: 'household' },
  { text: 'moth balls', label: 'household' },
  { text: 'mouse trap', label: 'household' },
  { text: 'rat trap', label: 'household' },
  { text: 'sticky trap', label: 'household' },
  { text: 'glue trap', label: 'household' },
  { text: 'bait station', label: 'household' },
  { text: 'poison bait', label: 'household' },
  { text: 'insecticide', label: 'household' },
  { text: 'pesticide', label: 'household' },

  // Storage and organization
  { text: 'storage containers', label: 'household' },
  { text: 'plastic containers', label: 'household' },
  { text: 'storage boxes', label: 'household' },
  { text: 'storage bins', label: 'household' },
  { text: 'organizers', label: 'household' },
  { text: 'drawer organizers', label: 'household' },
  { text: 'closet organizers', label: 'household' },
  { text: 'shoe organizers', label: 'household' },

  // Trash and recycling
  { text: 'trash can', label: 'household' },
  { text: 'garbage can', label: 'household' },
  { text: 'recycling bin', label: 'household' },

  // Specialty cleaners and removers
  { text: 'pet stain remover', label: 'household' },
  { text: 'urine odor remover', label: 'household' },
  { text: 'blood stain remover', label: 'household' },
  { text: 'grease remover', label: 'household' },
  { text: 'adhesive remover', label: 'household' },
  { text: 'gum remover', label: 'household' },
  { text: 'crayon remover', label: 'household' },
  { text: 'marker remover', label: 'household' },
  { text: 'ink remover', label: 'household' },
  { text: 'paint remover', label: 'household' },
  { text: 'tar remover', label: 'household' },
  { text: 'wax remover', label: 'household' },
  { text: 'polish remover', label: 'household' },
  { text: 'nail polish remover', label: 'household' },
  { text: 'acetone', label: 'household' },
  { text: 'rubbing alcohol', label: 'household' },
  { text: 'isopropyl alcohol', label: 'household' },
  { text: 'hydrogen peroxide', label: 'household' },
  { text: 'white vinegar', label: 'household' },
  { text: 'cleaning vinegar', label: 'household' },
  { text: 'baking soda', label: 'household' },
  { text: 'borax', label: 'household' },
  { text: 'washing soda', label: 'household' },
  { text: 'citric acid', label: 'household' },
  { text: 'oxalic acid', label: 'household' },

  // Eco-friendly products
  { text: 'eco friendly cleaner', label: 'household' },
  { text: 'natural cleaner', label: 'household' },
  { text: 'organic cleaner', label: 'household' },
  { text: 'biodegradable cleaner', label: 'household' },
  { text: 'non toxic cleaner', label: 'household' },
  { text: 'plant based cleaner', label: 'household' },
  { text: 'green cleaner', label: 'household' },
  { text: 'environmentally friendly', label: 'household' },
  { text: 'chemical free cleaner', label: 'household' },
  { text: 'phosphate free', label: 'household' },
  { text: 'ammonia free', label: 'household' },
  { text: 'chlorine free', label: 'household' },
  { text: 'fragrance free', label: 'household' },
  { text: 'hypoallergenic cleaner', label: 'household' },
  { text: 'sensitive skin cleaner', label: 'household' },
  { text: 'pet safe cleaner', label: 'household' },

  // Brand names and general terms
  { text: 'cleaning supplies', label: 'household' },
  { text: 'cleaning tools', label: 'household' },
  { text: 'lysol', label: 'household' },
  { text: 'dettol', label: 'household' },
  { text: 'clorox', label: 'household' },
  { text: 'mr clean', label: 'household' },
  { text: 'pine sol', label: 'household' },
  { text: 'fantastic', label: 'household' },
  { text: 'pledge', label: 'household' },
  { text: 'old english', label: 'household' },
  { text: 'murphy oil soap', label: 'household' },
  { text: 'febreze', label: 'household' },
  { text: 'glade', label: 'household' },
  { text: 'air wick', label: 'household' },
  { text: 'seventh generation', label: 'household' },
  { text: 'method', label: 'household' },
  { text: 'mrs meyers', label: 'household' },
  { text: 'ecover', label: 'household' },
  { text: 'windex', label: 'household' },
  { text: 'raid', label: 'household' },
  { text: 'baygon', label: 'household' },
  { text: 'mortein', label: 'household' },
  { text: 'newspaper', label: 'household' }
];

export default householdTrainingData;