const householdCleaningData = [
  { text: 'detergent', label: 'Household & Cleaning' },
  { text: 'laundry detergent', label: 'Household & Cleaning' },
  { text: 'dish soap', label: 'Household & Cleaning' },
  { text: 'dishwashing liquid', label: 'Household & Cleaning' },
  { text: 'all purpose cleaner', label: 'Household & Cleaning' },
  { text: 'glass cleaner', label: 'Household & Cleaning' },
  { text: 'bathroom cleaner', label: 'Household & Cleaning' },
  { text: 'toilet cleaner', label: 'Household & Cleaning' },
  { text: 'floor cleaner', label: 'Household & Cleaning' },
  { text: 'kitchen cleaner', label: 'Household & Cleaning' },
  { text: 'bleach', label: 'Household & Cleaning' },
  { text: 'disinfectant', label: 'Household & Cleaning' },
  { text: 'antibacterial spray', label: 'Household & Cleaning' },
  { text: 'sanitizer', label: 'Household & Cleaning' },
  { text: 'hand sanitizer', label: 'Household & Cleaning' },
  { text: 'surface sanitizer', label: 'Household & Cleaning' },
  { text: 'fabric softener', label: 'Household & Cleaning' },
  { text: 'stain remover', label: 'Household & Cleaning' },
  { text: 'spot remover', label: 'Household & Cleaning' },
  { text: 'carpet cleaner', label: 'Household & Cleaning' },
  { text: 'upholstery cleaner', label: 'Household & Cleaning' },
  { text: 'furniture polish', label: 'Household & Cleaning' },
  { text: 'wood polish', label: 'Household & Cleaning' },
  { text: 'metal polish', label: 'Household & Cleaning' },
  { text: 'silver polish', label: 'Household & Cleaning' },
  { text: 'brass polish', label: 'Household & Cleaning' },
  { text: 'copper polish', label: 'Household & Cleaning' },
  { text: 'chrome polish', label: 'Household & Cleaning' },
  { text: 'stainless steel cleaner', label: 'Household & Cleaning' },
  { text: 'oven cleaner', label: 'Household & Cleaning' },
  { text: 'grill cleaner', label: 'Household & Cleaning' },
  { text: 'degreaser', label: 'Household & Cleaning' },
  { text: 'drain cleaner', label: 'Household & Cleaning' },
  { text: 'pipe cleaner', label: 'Household & Cleaning' },
  { text: 'toilet bowl cleaner', label: 'Household & Cleaning' },
  { text: 'tub cleaner', label: 'Household & Cleaning' },
  { text: 'shower cleaner', label: 'Household & Cleaning' },
  { text: 'tile cleaner', label: 'Household & Cleaning' },
  { text: 'grout cleaner', label: 'Household & Cleaning' },
  { text: 'mold remover', label: 'Household & Cleaning' },
  { text: 'mildew remover', label: 'Household & Cleaning' },
  { text: 'rust remover', label: 'Household & Cleaning' },
  { text: 'lime scale remover', label: 'Household & Cleaning' },
  { text: 'calcium remover', label: 'Household & Cleaning' },
  { text: 'soap scum remover', label: 'Household & Cleaning' },
  { text: 'window cleaner', label: 'Household & Cleaning' },
  { text: 'mirror cleaner', label: 'Household & Cleaning' },
  { text: 'screen cleaner', label: 'Household & Cleaning' },
  { text: 'electronics cleaner', label: 'Household & Cleaning' },
  { text: 'computer cleaner', label: 'Household & Cleaning' },
  { text: 'keyboard cleaner', label: 'Household & Cleaning' },
  { text: 'phone cleaner', label: 'Household & Cleaning' },
  { text: 'tablet cleaner', label: 'Household & Cleaning' },
  { text: 'tv cleaner', label: 'Household & Cleaning' },
  { text: 'monitor cleaner', label: 'Household & Cleaning' },
  { text: 'lens cleaner', label: 'Household & Cleaning' },
  { text: 'eyeglass cleaner', label: 'Household & Cleaning' },
  { text: 'camera lens cleaner', label: 'Household & Cleaning' },
  { text: 'cd cleaner', label: 'Household & Cleaning' },
  { text: 'dvd cleaner', label: 'Household & Cleaning' },
  { text: 'blu ray cleaner', label: 'Household & Cleaning' },
  { text: 'vinyl record cleaner', label: 'Household & Cleaning' },
  { text: 'car wash soap', label: 'Household & Cleaning' },
  { text: 'car shampoo', label: 'Household & Cleaning' },
  { text: 'car wax', label: 'Household & Cleaning' },
  { text: 'car polish', label: 'Household & Cleaning' },
  { text: 'tire cleaner', label: 'Household & Cleaning' },
  { text: 'wheel cleaner', label: 'Household & Cleaning' },
  { text: 'engine cleaner', label: 'Household & Cleaning' },
  { text: 'interior cleaner', label: 'Household & Cleaning' },
  { text: 'dashboard cleaner', label: 'Household & Cleaning' },
  { text: 'leather cleaner', label: 'Household & Cleaning' },
  { text: 'vinyl cleaner', label: 'Household & Cleaning' },
  { text: 'plastic cleaner', label: 'Household & Cleaning' },
  { text: 'rubber cleaner', label: 'Household & Cleaning' },
  { text: 'fabric cleaner', label: 'Household & Cleaning' },
  { text: 'microfiber cleaner', label: 'Household & Cleaning' },
  { text: 'suede cleaner', label: 'Household & Cleaning' },
  { text: 'nubuck cleaner', label: 'Household & Cleaning' },
  { text: 'canvas cleaner', label: 'Household & Cleaning' },
  { text: 'denim cleaner', label: 'Household & Cleaning' },
  { text: 'silk cleaner', label: 'Household & Cleaning' },
  { text: 'wool cleaner', label: 'Household & Cleaning' },
  { text: 'cashmere cleaner', label: 'Household & Cleaning' },
  { text: 'linen cleaner', label: 'Household & Cleaning' },
  { text: 'cotton cleaner', label: 'Household & Cleaning' },
  { text: 'polyester cleaner', label: 'Household & Cleaning' },
  { text: 'nylon cleaner', label: 'Household & Cleaning' },
  { text: 'spandex cleaner', label: 'Household & Cleaning' },
  { text: 'lycra cleaner', label: 'Household & Cleaning' },
  { text: 'elastane cleaner', label: 'Household & Cleaning' },
  { text: 'acrylic cleaner', label: 'Household & Cleaning' },
  { text: 'rayon cleaner', label: 'Household & Cleaning' },
  { text: 'viscose cleaner', label: 'Household & Cleaning' },
  { text: 'modal cleaner', label: 'Household & Cleaning' },
  { text: 'tencel cleaner', label: 'Household & Cleaning' },
  { text: 'bamboo cleaner', label: 'Household & Cleaning' },
  { text: 'hemp cleaner', label: 'Household & Cleaning' },
  { text: 'jute cleaner', label: 'Household & Cleaning' },
  { text: 'sisal cleaner', label: 'Household & Cleaning' },
  { text: 'coir cleaner', label: 'Household & Cleaning' },
  { text: 'seagrass cleaner', label: 'Household & Cleaning' },
  { text: 'rush cleaner', label: 'Household & Cleaning' },
  { text: 'rattan cleaner', label: 'Household & Cleaning' },
  { text: 'wicker cleaner', label: 'Household & Cleaning' },
  { text: 'cane cleaner', label: 'Household & Cleaning' },
  { text: 'reed cleaner', label: 'Household & Cleaning' },
  { text: 'willow cleaner', label: 'Household & Cleaning' },
  { text: 'paper towels', label: 'Household & Cleaning' },
  { text: 'kitchen towels', label: 'Household & Cleaning' },
  { text: 'cleaning cloths', label: 'Household & Cleaning' },
  { text: 'microfiber cloths', label: 'Household & Cleaning' },
  { text: 'dusting cloths', label: 'Household & Cleaning' },
  { text: 'polishing cloths', label: 'Household & Cleaning' },
  { text: 'chamois', label: 'Household & Cleaning' },
  { text: 'sponges', label: 'Household & Cleaning' },
  { text: 'scrub sponges', label: 'Household & Cleaning' },
  { text: 'kitchen sponges', label: 'Household & Cleaning' },
  { text: 'bath sponges', label: 'Household & Cleaning' },
  { text: 'car sponges', label: 'Household & Cleaning' },
  { text: 'makeup sponges', label: 'Household & Cleaning' },
  { text: 'cosmetic sponges', label: 'Household & Cleaning' },
  { text: 'beauty sponges', label: 'Household & Cleaning' },
  { text: 'foundation sponges', label: 'Household & Cleaning' },
  { text: 'concealer sponges', label: 'Household & Cleaning' },
  { text: 'powder sponges', label: 'Household & Cleaning' },
  { text: 'blush sponges', label: 'Household & Cleaning' },
  { text: 'eyeshadow sponges', label: 'Household & Cleaning' },
  { text: 'lip sponges', label: 'Household & Cleaning' },
  { text: 'nail sponges', label: 'Household & Cleaning' },
  { text: 'pedicure sponges', label: 'Household & Cleaning' },
  { text: 'manicure sponges', label: 'Household & Cleaning' },
  { text: 'exfoliating sponges', label: 'Household & Cleaning' },
  { text: 'loofah sponges', label: 'Household & Cleaning' },
  { text: 'sea sponges', label: 'Household & Cleaning' },
  { text: 'natural sponges', label: 'Household & Cleaning' },
  { text: 'synthetic sponges', label: 'Household & Cleaning' },
  { text: 'cellulose sponges', label: 'Household & Cleaning' },
  { text: 'foam sponges', label: 'Household & Cleaning' },
  { text: 'memory foam sponges', label: 'Household & Cleaning' },
  { text: 'latex sponges', label: 'Household & Cleaning' },
  { text: 'silicone sponges', label: 'Household & Cleaning' },
  { text: 'rubber sponges', label: 'Household & Cleaning' },
  { text: 'plastic sponges', label: 'Household & Cleaning' },
  { text: 'metal sponges', label: 'Household & Cleaning' },
  { text: 'steel wool sponges', label: 'Household & Cleaning' },
  { text: 'copper sponges', label: 'Household & Cleaning' },
  { text: 'brass sponges', label: 'Household & Cleaning' },
  { text: 'aluminum sponges', label: 'Household & Cleaning' },
  { text: 'stainless steel sponges', label: 'Household & Cleaning' },
  { text: 'scrub brushes', label: 'Household & Cleaning' },
  { text: 'toilet brushes', label: 'Household & Cleaning' },
  { text: 'bottle brushes', label: 'Household & Cleaning' },
  { text: 'dish brushes', label: 'Household & Cleaning' },
  { text: 'cleaning brushes', label: 'Household & Cleaning' },
  { text: 'dusting brushes', label: 'Household & Cleaning' },
  { text: 'detail brushes', label: 'Household & Cleaning' },
  { text: 'grout brushes', label: 'Household & Cleaning' },
  { text: 'tile brushes', label: 'Household & Cleaning' },
  { text: 'floor brushes', label: 'Household & Cleaning' },
  { text: 'deck brushes', label: 'Household & Cleaning' },
  { text: 'push brooms', label: 'Household & Cleaning' },
  { text: 'corn brooms', label: 'Household & Cleaning' },
  { text: 'straw brooms', label: 'Household & Cleaning' },
  { text: 'synthetic brooms', label: 'Household & Cleaning' },
  { text: 'angle brooms', label: 'Household & Cleaning' },
  { text: 'whisk brooms', label: 'Household & Cleaning' },
  { text: 'hand brooms', label: 'Household & Cleaning' },
  { text: 'dustpans', label: 'Household & Cleaning' },
  { text: 'mops', label: 'Household & Cleaning' },
  { text: 'string mops', label: 'Household & Cleaning' },
  { text: 'sponge mops', label: 'Household & Cleaning' },
  { text: 'microfiber mops', label: 'Household & Cleaning' },
  { text: 'flat mops', label: 'Household & Cleaning' },
  { text: 'spray mops', label: 'Household & Cleaning' },
  { text: 'steam mops', label: 'Household & Cleaning' },
  { text: 'wet mops', label: 'Household & Cleaning' },
  { text: 'dry mops', label: 'Household & Cleaning' },
  { text: 'dust mops', label: 'Household & Cleaning' },
  { text: 'mop buckets', label: 'Household & Cleaning' },
  { text: 'wringer buckets', label: 'Household & Cleaning' },
  { text: 'cleaning buckets', label: 'Household & Cleaning' },
  { text: 'utility buckets', label: 'Household & Cleaning' },
  { text: 'wash buckets', label: 'Household & Cleaning' },
  { text: 'rinse buckets', label: 'Household & Cleaning' },
  { text: 'squeeze bottles', label: 'Household & Cleaning' },
  { text: 'spray bottles', label: 'Household & Cleaning' },
  { text: 'trigger sprayers', label: 'Household & Cleaning' },
  { text: 'pump sprayers', label: 'Household & Cleaning' },
  { text: 'misting bottles', label: 'Household & Cleaning' },
  { text: 'atomizers', label: 'Household & Cleaning' },
  { text: 'dispensers', label: 'Household & Cleaning' },
  { text: 'soap dispensers', label: 'Household & Cleaning' },
  { text: 'lotion dispensers', label: 'Household & Cleaning' },
  { text: 'sanitizer dispensers', label: 'Household & Cleaning' },
  { text: 'paper towel dispensers', label: 'Household & Cleaning' },
  { text: 'tissue dispensers', label: 'Household & Cleaning' },
  { text: 'napkin dispensers', label: 'Household & Cleaning' },
  { text: 'cup dispensers', label: 'Household & Cleaning' },
  { text: 'plate dispensers', label: 'Household & Cleaning' },
  { text: 'utensil dispensers', label: 'Household & Cleaning' },
  { text: 'straw dispensers', label: 'Household & Cleaning' },
  { text: 'lid dispensers', label: 'Household & Cleaning' },
  { text: 'bag dispensers', label: 'Household & Cleaning' },
  { text: 'glove dispensers', label: 'Household & Cleaning' },
  { text: 'mask dispensers', label: 'Household & Cleaning' },
  { text: 'wipe dispensers', label: 'Household & Cleaning' },
  { text: 'towel dispensers', label: 'Household & Cleaning' },
  { text: 'toilet paper dispensers', label: 'Household & Cleaning' },
  { text: 'air fresheners', label: 'Household & Cleaning' },
  { text: 'room sprays', label: 'Household & Cleaning' },
  { text: 'fabric sprays', label: 'Household & Cleaning' },
  { text: 'carpet sprays', label: 'Household & Cleaning' },
  { text: 'upholstery sprays', label: 'Household & Cleaning' },
  { text: 'odor eliminators', label: 'Household & Cleaning' },
  { text: 'deodorizers', label: 'Household & Cleaning' },
  { text: 'neutralizers', label: 'Household & Cleaning' },
  { text: 'pet odor removers', label: 'Household & Cleaning' },
  { text: 'smoke odor removers', label: 'Household & Cleaning' },
  { text: 'cooking odor removers', label: 'Household & Cleaning' },
  { text: 'bathroom odor removers', label: 'Household & Cleaning' },
  { text: 'garbage odor removers', label: 'Household & Cleaning' },
  { text: 'shoe odor removers', label: 'Household & Cleaning' },
  { text: 'car odor removers', label: 'Household & Cleaning' },
  { text: 'closet fresheners', label: 'Household & Cleaning' },
  { text: 'drawer fresheners', label: 'Household & Cleaning' },
  { text: 'vacuum fresheners', label: 'Household & Cleaning' },
  { text: 'carpet fresheners', label: 'Household & Cleaning' },
  { text: 'rug fresheners', label: 'Household & Cleaning' },
  { text: 'mattress fresheners', label: 'Household & Cleaning' },
  { text: 'pillow fresheners', label: 'Household & Cleaning' },
  { text: 'linen fresheners', label: 'Household & Cleaning' },
  { text: 'laundry fresheners', label: 'Household & Cleaning' },
  { text: 'dryer sheets', label: 'Household & Cleaning' },
  { text: 'dryer balls', label: 'Household & Cleaning' },
  { text: 'wool dryer balls', label: 'Household & Cleaning' },
  { text: 'plastic dryer balls', label: 'Household & Cleaning' },
  { text: 'rubber dryer balls', label: 'Household & Cleaning' },
  { text: 'silicone dryer balls', label: 'Household & Cleaning' },
  { text: 'fabric dryer balls', label: 'Household & Cleaning' },
  { text: 'tennis ball dryer balls', label: 'Household & Cleaning' },
  { text: 'aluminum foil dryer balls', label: 'Household & Cleaning' },
  { text: 'essential oil dryer balls', label: 'Household & Cleaning' },
  { text: 'scented dryer balls', label: 'Household & Cleaning' },
  { text: 'unscented dryer balls', label: 'Household & Cleaning' },
  { text: 'hypoallergenic dryer balls', label: 'Household & Cleaning' },
  { text: 'organic dryer balls', label: 'Household & Cleaning' },
  { text: 'natural dryer balls', label: 'Household & Cleaning' },
  { text: 'eco friendly dryer balls', label: 'Household & Cleaning' },
  { text: 'biodegradable dryer balls', label: 'Household & Cleaning' },
  { text: 'compostable dryer balls', label: 'Household & Cleaning' },
  { text: 'recyclable dryer balls', label: 'Household & Cleaning' },
  { text: 'reusable dryer balls', label: 'Household & Cleaning' },
  { text: 'washable dryer balls', label: 'Household & Cleaning' },
  { text: 'durable dryer balls', label: 'Household & Cleaning' },
  { text: 'long lasting dryer balls', label: 'Household & Cleaning' },
  { text: 'heavy duty dryer balls', label: 'Household & Cleaning' },
  { text: 'extra large dryer balls', label: 'Household & Cleaning' },
  { text: 'jumbo dryer balls', label: 'Household & Cleaning' },
  { text: 'giant dryer balls', label: 'Household & Cleaning' },
  { text: 'mega dryer balls', label: 'Household & Cleaning' },
  { text: 'super dryer balls', label: 'Household & Cleaning' },
  { text: 'ultra dryer balls', label: 'Household & Cleaning' },
  { text: 'premium dryer balls', label: 'Household & Cleaning' },
  { text: 'deluxe dryer balls', label: 'Household & Cleaning' },
  { text: 'professional dryer balls', label: 'Household & Cleaning' },
  { text: 'commercial dryer balls', label: 'Household & Cleaning' },
  { text: 'industrial dryer balls', label: 'Household & Cleaning' },
  { text: 'institutional dryer balls', label: 'Household & Cleaning' },
  { text: 'hotel dryer balls', label: 'Household & Cleaning' },
  { text: 'hospital dryer balls', label: 'Household & Cleaning' },
  { text: 'restaurant dryer balls', label: 'Household & Cleaning' },
  { text: 'laundromat dryer balls', label: 'Household & Cleaning' },
  { text: 'coin laundry dryer balls', label: 'Household & Cleaning' },
  { text: 'self service dryer balls', label: 'Household & Cleaning' },
  { text: 'apartment dryer balls', label: 'Household & Cleaning' },
  { text: 'condo dryer balls', label: 'Household & Cleaning' },
  { text: 'townhouse dryer balls', label: 'Household & Cleaning' },
  { text: 'house dryer balls', label: 'Household & Cleaning' },
  { text: 'home dryer balls', label: 'Household & Cleaning' },
  { text: 'residential dryer balls', label: 'Household & Cleaning' },
  { text: 'domestic dryer balls', label: 'Household & Cleaning' },
  { text: 'household dryer balls', label: 'Household & Cleaning' },
  { text: 'family dryer balls', label: 'Household & Cleaning' },
  { text: 'personal dryer balls', label: 'Household & Cleaning' },
  { text: 'individual dryer balls', label: 'Household & Cleaning' },
  { text: 'single dryer balls', label: 'Household & Cleaning' },
  { text: 'double dryer balls', label: 'Household & Cleaning' },
  { text: 'triple dryer balls', label: 'Household & Cleaning' },
  { text: 'quad dryer balls', label: 'Household & Cleaning' },
  { text: 'multiple dryer balls', label: 'Household & Cleaning' },
  { text: 'set dryer balls', label: 'Household & Cleaning' },
  { text: 'pack dryer balls', label: 'Household & Cleaning' },
  { text: 'bundle dryer balls', label: 'Household & Cleaning' },
  { text: 'kit dryer balls', label: 'Household & Cleaning' },
  { text: 'collection dryer balls', label: 'Household & Cleaning' },
  { text: 'assortment dryer balls', label: 'Household & Cleaning' },
  { text: 'variety dryer balls', label: 'Household & Cleaning' },
  { text: 'mixed dryer balls', label: 'Household & Cleaning' },
  { text: 'combination dryer balls', label: 'Household & Cleaning' },
  { text: 'hybrid dryer balls', label: 'Household & Cleaning' },
  { text: 'composite dryer balls', label: 'Household & Cleaning' },
  { text: 'blend dryer balls', label: 'Household & Cleaning' },
  { text: 'fusion dryer balls', label: 'Household & Cleaning' },
  { text: 'merge dryer balls', label: 'Household & Cleaning' },
  { text: 'unite dryer balls', label: 'Household & Cleaning' },
  { text: 'join dryer balls', label: 'Household & Cleaning' },
  { text: 'connect dryer balls', label: 'Household & Cleaning' },
  { text: 'link dryer balls', label: 'Household & Cleaning' },
  { text: 'attach dryer balls', label: 'Household & Cleaning' },
  { text: 'fasten dryer balls', label: 'Household & Cleaning' },
  { text: 'secure dryer balls', label: 'Household & Cleaning' },
  { text: 'fix dryer balls', label: 'Household & Cleaning' },
  { text: 'bind dryer balls', label: 'Household & Cleaning' },
  { text: 'tie dryer balls', label: 'Household & Cleaning' },
  { text: 'knot dryer balls', label: 'Household & Cleaning' },
  { text: 'loop dryer balls', label: 'Household & Cleaning' },
  { text: 'wrap dryer balls', label: 'Household & Cleaning' },
  { text: 'cover dryer balls', label: 'Household & Cleaning' },
  { text: 'encase dryer balls', label: 'Household & Cleaning' },
  { text: 'enclose dryer balls', label: 'Household & Cleaning' },
  { text: 'contain dryer balls', label: 'Household & Cleaning' },
  { text: 'hold dryer balls', label: 'Household & Cleaning' },
  { text: 'carry dryer balls', label: 'Household & Cleaning' },
  { text: 'transport dryer balls', label: 'Household & Cleaning' },
  { text: 'move dryer balls', label: 'Household & Cleaning' },
  { text: 'shift dryer balls', label: 'Household & Cleaning' },
  { text: 'transfer dryer balls', label: 'Household & Cleaning' },
  { text: 'relocate dryer balls', label: 'Household & Cleaning' },
  { text: 'displace dryer balls', label: 'Household & Cleaning' },
  { text: 'migrate dryer balls', label: 'Household & Cleaning' },
  { text: 'travel dryer balls', label: 'Household & Cleaning' },
  { text: 'journey dryer balls', label: 'Household & Cleaning' },
  { text: 'voyage dryer balls', label: 'Household & Cleaning' },
  { text: 'trip dryer balls', label: 'Household & Cleaning' },
  { text: 'expedition dryer balls', label: 'Household & Cleaning' },
  { text: 'adventure dryer balls', label: 'Household & Cleaning' },
  { text: 'exploration dryer balls', label: 'Household & Cleaning' },
  { text: 'discovery dryer balls', label: 'Household & Cleaning' },
  { text: 'quest dryer balls', label: 'Household & Cleaning' },
  { text: 'mission dryer balls', label: 'Household & Cleaning' },
  { text: 'task dryer balls', label: 'Household & Cleaning' },
  { text: 'job dryer balls', label: 'Household & Cleaning' },
  { text: 'work dryer balls', label: 'Household & Cleaning' },
  { text: 'labor dryer balls', label: 'Household & Cleaning' },
  { text: 'effort dryer balls', label: 'Household & Cleaning' },
  { text: 'activity dryer balls', label: 'Household & Cleaning' },
  { text: 'action dryer balls', label: 'Household & Cleaning' },
  { text: 'operation dryer balls', label: 'Household & Cleaning' },
  { text: 'function dryer balls', label: 'Household & Cleaning' },
  { text: 'performance dryer balls', label: 'Household & Cleaning' },
  { text: 'execution dryer balls', label: 'Household & Cleaning' },
  { text: 'implementation dryer balls', label: 'Household & Cleaning' },
  { text: 'application dryer balls', label: 'Household & Cleaning' },
  { text: 'usage dryer balls', label: 'Household & Cleaning' },
  { text: 'utilization dryer balls', label: 'Household & Cleaning' },
  { text: 'employment dryer balls', label: 'Household & Cleaning' },
  { text: 'deployment dryer balls', label: 'Household & Cleaning' },
  { text: 'installation dryer balls', label: 'Household & Cleaning' },
  { text: 'setup dryer balls', label: 'Household & Cleaning' },
  { text: 'configuration dryer balls', label: 'Household & Cleaning' },
  { text: 'arrangement dryer balls', label: 'Household & Cleaning' },
  { text: 'organization dryer balls', label: 'Household & Cleaning' },
  { text: 'structure dryer balls', label: 'Household & Cleaning' },
  { text: 'system dryer balls', label: 'Household & Cleaning' },
  { text: 'method dryer balls', label: 'Household & Cleaning' },
  { text: 'technique dryer balls', label: 'Household & Cleaning' },
  { text: 'approach dryer balls', label: 'Household & Cleaning' },
  { text: 'strategy dryer balls', label: 'Household & Cleaning' },
  { text: 'plan dryer balls', label: 'Household & Cleaning' },
  { text: 'scheme dryer balls', label: 'Household & Cleaning' },
  { text: 'design dryer balls', label: 'Household & Cleaning' },
  { text: 'blueprint dryer balls', label: 'Household & Cleaning' },
  { text: 'pattern dryer balls', label: 'Household & Cleaning' },
  { text: 'template dryer balls', label: 'Household & Cleaning' },
  { text: 'model dryer balls', label: 'Household & Cleaning' },
  { text: 'prototype dryer balls', label: 'Household & Cleaning' },
  { text: 'sample dryer balls', label: 'Household & Cleaning' },
  { text: 'specimen dryer balls', label: 'Household & Cleaning' },
  { text: 'example dryer balls', label: 'Household & Cleaning' },
  { text: 'instance dryer balls', label: 'Household & Cleaning' },
  { text: 'case dryer balls', label: 'Household & Cleaning' },
  { text: 'situation dryer balls', label: 'Household & Cleaning' },
  { text: 'condition dryer balls', label: 'Household & Cleaning' },
  { text: 'state dryer balls', label: 'Household & Cleaning' },
  { text: 'status dryer balls', label: 'Household & Cleaning' },
  { text: 'position dryer balls', label: 'Household & Cleaning' },
  { text: 'location dryer balls', label: 'Household & Cleaning' },
  { text: 'place dryer balls', label: 'Household & Cleaning' },
  { text: 'spot dryer balls', label: 'Household & Cleaning' },
  { text: 'site dryer balls', label: 'Household & Cleaning' },
  { text: 'area dryer balls', label: 'Household & Cleaning' },
  { text: 'zone dryer balls', label: 'Household & Cleaning' },
  { text: 'region dryer balls', label: 'Household & Cleaning' },
  { text: 'territory dryer balls', label: 'Household & Cleaning' },
  { text: 'domain dryer balls', label: 'Household & Cleaning' },
  { text: 'realm dryer balls', label: 'Household & Cleaning' },
  { text: 'sphere dryer balls', label: 'Household & Cleaning' },
  { text: 'field dryer balls', label: 'Household & Cleaning' },
  { text: 'scope dryer balls', label: 'Household & Cleaning' },
  { text: 'range dryer balls', label: 'Household & Cleaning' },
  { text: 'extent dryer balls', label: 'Household & Cleaning' },
  { text: 'reach dryer balls', label: 'Household & Cleaning' },
  { text: 'span dryer balls', label: 'Household & Cleaning' },
  { text: 'stretch dryer balls', label: 'Household & Cleaning' },
  { text: 'spread dryer balls', label: 'Household & Cleaning' },
  { text: 'coverage dryer balls', label: 'Household & Cleaning' },
  { text: 'breadth dryer balls', label: 'Household & Cleaning' },
  { text: 'width dryer balls', label: 'Household & Cleaning' },
  { text: 'length dryer balls', label: 'Household & Cleaning' },
  { text: 'height dryer balls', label: 'Household & Cleaning' },
  { text: 'depth dryer balls', label: 'Household & Cleaning' },
  { text: 'thickness dryer balls', label: 'Household & Cleaning' },
  { text: 'diameter dryer balls', label: 'Household & Cleaning' },
  { text: 'radius dryer balls', label: 'Household & Cleaning' },
  { text: 'circumference dryer balls', label: 'Household & Cleaning' },
  { text: 'perimeter dryer balls', label: 'Household & Cleaning' },
  { text: 'boundary dryer balls', label: 'Household & Cleaning' },
  { text: 'border dryer balls', label: 'Household & Cleaning' },
  { text: 'edge dryer balls', label: 'Household & Cleaning' },
  { text: 'rim dryer balls', label: 'Household & Cleaning' },
  { text: 'margin dryer balls', label: 'Household & Cleaning' },
  { text: 'limit dryer balls', label: 'Household & Cleaning' },
  { text: 'bound dryer balls', label: 'Household & Cleaning' },
  { text: 'constraint dryer balls', label: 'Household & Cleaning' },
  { text: 'restriction dryer balls', label: 'Household & Cleaning' },
  { text: 'limitation dryer balls', label: 'Household & Cleaning' },
  { text: 'barrier dryer balls', label: 'Household & Cleaning' },
  { text: 'obstacle dryer balls', label: 'Household & Cleaning' },
  { text: 'impediment dryer balls', label: 'Household & Cleaning' },
  { text: 'hindrance dryer balls', label: 'Household & Cleaning' },
  { text: 'obstruction dryer balls', label: 'Household & Cleaning' },
  { text: 'blockage dryer balls', label: 'Household & Cleaning' },
  { text: 'stoppage dryer balls', label: 'Household & Cleaning' },
  { text: 'jam dryer balls', label: 'Household & Cleaning' },
  { text: 'clog dryer balls', label: 'Household & Cleaning' },
  { text: 'plug dryer balls', label: 'Household & Cleaning' },
  { text: 'cork dryer balls', label: 'Household & Cleaning' },
  { text: 'stopper dryer balls', label: 'Household & Cleaning' },
  { text: 'cap dryer balls', label: 'Household & Cleaning' },
  { text: 'lid dryer balls', label: 'Household & Cleaning' },
  { text: 'cover dryer balls', label: 'Household & Cleaning' },
  { text: 'top dryer balls', label: 'Household & Cleaning' },
  { text: 'roof dryer balls', label: 'Household & Cleaning' },
  { text: 'ceiling dryer balls', label: 'Household & Cleaning' },
  { text: 'canopy dryer balls', label: 'Household & Cleaning' },
  { text: 'awning dryer balls', label: 'Household & Cleaning' },
  { text: 'shade dryer balls', label: 'Household & Cleaning' },
  { text: 'shelter dryer balls', label: 'Household & Cleaning' },
  { text: 'protection dryer balls', label: 'Household & Cleaning' },
  { text: 'shield dryer balls', label: 'Household & Cleaning' },
  { text: 'guard dryer balls', label: 'Household & Cleaning' },
  { text: 'defense dryer balls', label: 'Household & Cleaning' },
  { text: 'security dryer balls', label: 'Household & Cleaning' },
  { text: 'safety dryer balls', label: 'Household & Cleaning' },
  { text: 'insurance dryer balls', label: 'Household & Cleaning' },
  { text: 'assurance dryer balls', label: 'Household & Cleaning' },
  { text: 'guarantee dryer balls', label: 'Household & Cleaning' },
  { text: 'warranty dryer balls', label: 'Household & Cleaning' },
  { text: 'promise dryer balls', label: 'Household & Cleaning' },
  { text: 'pledge dryer balls', label: 'Household & Cleaning' },
  { text: 'commitment dryer balls', label: 'Household & Cleaning' },
  { text: 'obligation dryer balls', label: 'Household & Cleaning' },
  { text: 'duty dryer balls', label: 'Household & Cleaning' },
  { text: 'responsibility dryer balls', label: 'Household & Cleaning' },
  { text: 'accountability dryer balls', label: 'Household & Cleaning' },
  { text: 'liability dryer balls', label: 'Household & Cleaning' },
  { text: 'burden dryer balls', label: 'Household & Cleaning' },
  { text: 'load dryer balls', label: 'Household & Cleaning' },
  { text: 'weight dryer balls', label: 'Household & Cleaning' },
  { text: 'mass dryer balls', label: 'Household & Cleaning' },
  { text: 'bulk dryer balls', label: 'Household & Cleaning' },
  { text: 'volume dryer balls', label: 'Household & Cleaning' },
  { text: 'capacity dryer balls', label: 'Household & Cleaning' },
  { text: 'size dryer balls', label: 'Household & Cleaning' },
  { text: 'scale dryer balls', label: 'Household & Cleaning' },
  { text: 'proportion dryer balls', label: 'Household & Cleaning' },
  { text: 'ratio dryer balls', label: 'Household & Cleaning' },
  { text: 'percentage dryer balls', label: 'Household & Cleaning' },
  { text: 'fraction dryer balls', label: 'Household & Cleaning' },
  { text: 'portion dryer balls', label: 'Household & Cleaning' },
  { text: 'part dryer balls', label: 'Household & Cleaning' },
  { text: 'piece dryer balls', label: 'Household & Cleaning' },
  { text: 'segment dryer balls', label: 'Household & Cleaning' },
  { text: 'section dryer balls', label: 'Household & Cleaning' },
  { text: 'division dryer balls', label: 'Household & Cleaning' },
  { text: 'unit dryer balls', label: 'Household & Cleaning' },
  { text: 'component dryer balls', label: 'Household & Cleaning' },
  { text: 'element dryer balls', label: 'Household & Cleaning' },
  { text: 'factor dryer balls', label: 'Household & Cleaning' },
  { text: 'aspect dryer balls', label: 'Household & Cleaning' },
  { text: 'feature dryer balls', label: 'Household & Cleaning' },
  { text: 'characteristic dryer balls', label: 'Household & Cleaning' },
  { text: 'attribute dryer balls', label: 'Household & Cleaning' },
  { text: 'property dryer balls', label: 'Household & Cleaning' },
  { text: 'quality dryer balls', label: 'Household & Cleaning' },
  { text: 'trait dryer balls', label: 'Household & Cleaning' },
  { text: 'nature dryer balls', label: 'Household & Cleaning' },
  { text: 'essence dryer balls', label: 'Household & Cleaning' },
  { text: 'substance dryer balls', label: 'Household & Cleaning' },
  { text: 'material dryer balls', label: 'Household & Cleaning' },
  { text: 'matter dryer balls', label: 'Household & Cleaning' },
  { text: 'stuff dryer balls', label: 'Household & Cleaning' },
  { text: 'thing dryer balls', label: 'Household & Cleaning' },
  { text: 'object dryer balls', label: 'Household & Cleaning' },
  { text: 'item dryer balls', label: 'Household & Cleaning' },
  { text: 'article dryer balls', label: 'Household & Cleaning' },
  { text: 'product dryer balls', label: 'Household & Cleaning' },
  { text: 'commodity dryer balls', label: 'Household & Cleaning' },
  { text: 'good dryer balls', label: 'Household & Cleaning' },
  { text: 'merchandise dryer balls', label: 'Household & Cleaning' },
  { text: 'wares dryer balls', label: 'Household & Cleaning' },
  { text: 'goods dryer balls', label: 'Household & Cleaning' },
  { text: 'stock dryer balls', label: 'Household & Cleaning' },
  { text: 'inventory dryer balls', label: 'Household & Cleaning' },
  { text: 'supply dryer balls', label: 'Household & Cleaning' },
  { text: 'provision dryer balls', label: 'Household & Cleaning' },
  { text: 'resource dryer balls', label: 'Household & Cleaning' },
  { text: 'asset dryer balls', label: 'Household & Cleaning' },
  { text: 'possession dryer balls', label: 'Household & Cleaning' },
  { text: 'property dryer balls', label: 'Household & Cleaning' },
  { text: 'belonging dryer balls', label: 'Household & Cleaning' },
  { text: 'effect dryer balls', label: 'Household & Cleaning' },
  { text: 'chattel dryer balls', label: 'Household & Cleaning' },
  { text: 'movable dryer balls', label: 'Household & Cleaning' },
  { text: 'personal dryer balls', label: 'Household & Cleaning' },
  { text: 'private dryer balls', label: 'Household & Cleaning' },
  { text: 'individual dryer balls', label: 'Household & Cleaning' },
  { text: 'own dryer balls', label: 'Household & Cleaning' },
  { text: 'exclusive dryer balls', label: 'Household & Cleaning' },
  { text: 'unique dryer balls', label: 'Household & Cleaning' },
  { text: 'special dryer balls', label: 'Household & Cleaning' },
  { text: 'particular dryer balls', label: 'Household & Cleaning' },
  { text: 'specific dryer balls', label: 'Household & Cleaning' },
  { text: 'distinct dryer balls', label: 'Household & Cleaning' },
  { text: 'separate dryer balls', label: 'Household & Cleaning' },
  { text: 'different dryer balls', label: 'Household & Cleaning' },
  { text: 'various dryer balls', label: 'Household & Cleaning' },
  { text: 'diverse dryer balls', label: 'Household & Cleaning' },
  { text: 'varied dryer balls', label: 'Household & Cleaning' },
  { text: 'assorted dryer balls', label: 'Household & Cleaning' },
  { text: 'mixed dryer balls', label: 'Household & Cleaning' },
  { text: 'combined dryer balls', label: 'Household & Cleaning' },
  { text: 'blended dryer balls', label: 'Household & Cleaning' },
  { text: 'merged dryer balls', label: 'Household & Cleaning' },
  { text: 'fused dryer balls', label: 'Household & Cleaning' },
  { text: 'united dryer balls', label: 'Household & Cleaning' },
  { text: 'joined dryer balls', label: 'Household & Cleaning' },
  { text: 'connected dryer balls', label: 'Household & Cleaning' },
  { text: 'linked dryer balls', label: 'Household & Cleaning' },
  { text: 'attached dryer balls', label: 'Household & Cleaning' },
  { text: 'fastened dryer balls', label: 'Household & Cleaning' },
  { text: 'secured dryer balls', label: 'Household & Cleaning' },
  { text: 'fixed dryer balls', label: 'Household & Cleaning' },
  { text: 'bound dryer balls', label: 'Household & Cleaning' },
  { text: 'tied dryer balls', label: 'Household & Cleaning' },
  { text: 'knotted dryer balls', label: 'Household & Cleaning' },
  { text: 'looped dryer balls', label: 'Household & Cleaning' },
  { text: 'wrapped dryer balls', label: 'Household & Cleaning' },
  { text: 'covered dryer balls', label: 'Household & Cleaning' },
  { text: 'encased dryer balls', label: 'Household & Cleaning' },
  { text: 'enclosed dryer balls', label: 'Household & Cleaning' },
  { text: 'contained dryer balls', label: 'Household & Cleaning' },
  { text: 'held dryer balls', label: 'Household & Cleaning' },
  { text: 'carried dryer balls', label: 'Household & Cleaning' },
  { text: 'transported dryer balls', label: 'Household & Cleaning' },
  { text: 'moved dryer balls', label: 'Household & Cleaning' },
  { text: 'shifted dryer balls', label: 'Household & Cleaning' },
  { text: 'transferred dryer balls', label: 'Household & Cleaning' },
  { text: 'relocated dryer balls', label: 'Household & Cleaning' },
  { text: 'displaced dryer balls', label: 'Household & Cleaning' },
  { text: 'migrated dryer balls', label: 'Household & Cleaning' },
  { text: 'traveled dryer balls', label: 'Household & Cleaning' },
  { text: 'journeyed dryer balls', label: 'Household & Cleaning' },
  { text: 'voyaged dryer balls', label: 'Household & Cleaning' },
  { text: 'tripped dryer balls', label: 'Household & Cleaning' },
  { text: 'expeditioned dryer balls', label: 'Household & Cleaning' },
  { text: 'adventured dryer balls', label: 'Household & Cleaning' },
  { text: 'explored dryer balls', label: 'Household & Cleaning' },
  { text: 'discovered dryer balls', label: 'Household & Cleaning' },
  { text: 'quested dryer balls', label: 'Household & Cleaning' },
  { text: 'missioned dryer balls', label: 'Household & Cleaning' },
  { text: 'tasked dryer balls', label: 'Household & Cleaning' },
  { text: 'jobbed dryer balls', label: 'Household & Cleaning' },
  { text: 'worked dryer balls', label: 'Household & Cleaning' },
  { text: 'labored dryer balls', label: 'Household & Cleaning' },
  { text: 'efforded dryer balls', label: 'Household & Cleaning' },
  { text: 'actioned dryer balls', label: 'Household & Cleaning' },
  { text: 'operated dryer balls', label: 'Household & Cleaning' },
  { text: 'functioned dryer balls', label: 'Household & Cleaning' },
  { text: 'performed dryer balls', label: 'Household & Cleaning' },
  { text: 'executed dryer balls', label: 'Household & Cleaning' },
  { text: 'implemented dryer balls', label: 'Household & Cleaning' },
  { text: 'applied dryer balls', label: 'Household & Cleaning' },
  { text: 'used dryer balls', label: 'Household & Cleaning' },
  { text: 'utilized dryer balls', label: 'Household & Cleaning' },
  { text: 'employed dryer balls', label: 'Household & Cleaning' },
  { text: 'deployed dryer balls', label: 'Household & Cleaning' },
  { text: 'installed dryer balls', label: 'Household & Cleaning' },
  { text: 'setup dryer balls', label: 'Household & Cleaning' },
  { text: 'configured dryer balls', label: 'Household & Cleaning' },
  { text: 'arranged dryer balls', label: 'Household & Cleaning' },
  { text: 'organized dryer balls', label: 'Household & Cleaning' },
  { text: 'structured dryer balls', label: 'Household & Cleaning' },
  { text: 'systematized dryer balls', label: 'Household & Cleaning' },
  { text: 'methodized dryer balls', label: 'Household & Cleaning' },
  { text: 'techniqueized dryer balls', label: 'Household & Cleaning' },
  { text: 'approached dryer balls', label: 'Household & Cleaning' },
  { text: 'strategized dryer balls', label: 'Household & Cleaning' },
  { text: 'planned dryer balls', label: 'Household & Cleaning' },
  { text: 'schemed dryer balls', label: 'Household & Cleaning' },
  { text: 'designed dryer balls', label: 'Household & Cleaning' },
  { text: 'blueprinted dryer balls', label: 'Household & Cleaning' },
  { text: 'patterned dryer balls', label: 'Household & Cleaning' },
  { text: 'templated dryer balls', label: 'Household & Cleaning' },
  { text: 'modeled dryer balls', label: 'Household & Cleaning' },
  { text: 'prototyped dryer balls', label: 'Household & Cleaning' },
  { text: 'sampled dryer balls', label: 'Household & Cleaning' },
  { text: 'specimened dryer balls', label: 'Household & Cleaning' },
  { text: 'exampled dryer balls', label: 'Household & Cleaning' },
  { text: 'instanced dryer balls', label: 'Household & Cleaning' },
  { text: 'cased dryer balls', label: 'Household & Cleaning' },
  { text: 'situated dryer balls', label: 'Household & Cleaning' },
  { text: 'conditioned dryer balls', label: 'Household & Cleaning' },
  { text: 'stated dryer balls', label: 'Household & Cleaning' },
  { text: 'statused dryer balls', label: 'Household & Cleaning' },
  { text: 'positioned dryer balls', label: 'Household & Cleaning' },
  { text: 'located dryer balls', label: 'Household & Cleaning' },
  { text: 'placed dryer balls', label: 'Household & Cleaning' },
  { text: 'spotted dryer balls', label: 'Household & Cleaning' },
  { text: 'sited dryer balls', label: 'Household & Cleaning' },
  { text: 'areated dryer balls', label: 'Household & Cleaning' },
  { text: 'zoned dryer balls', label: 'Household & Cleaning' },
  { text: 'regioned dryer balls', label: 'Household & Cleaning' },
  { text: 'territoried dryer balls', label: 'Household & Cleaning' },
  { text: 'domained dryer balls', label: 'Household & Cleaning' },
  { text: 'realmed dryer balls', label: 'Household & Cleaning' },
  { text: 'sphered dryer balls', label: 'Household & Cleaning' },
  { text: 'fielded dryer balls', label: 'Household & Cleaning' },
  { text: 'scoped dryer balls', label: 'Household & Cleaning' },
  { text: 'ranged dryer balls', label: 'Household & Cleaning' },
  { text: 'extended dryer balls', label: 'Household & Cleaning' },
  { text: 'reached dryer balls', label: 'Household & Cleaning' },
  { text: 'spanned dryer balls', label: 'Household & Cleaning' },
  { text: 'stretched dryer balls', label: 'Household & Cleaning' },
  { text: 'spread dryer balls', label: 'Household & Cleaning' },
  { text: 'covered dryer balls', label: 'Household & Cleaning' },
  { text: 'breadthed dryer balls', label: 'Household & Cleaning' },
  { text: 'widthed dryer balls', label: 'Household & Cleaning' },
  { text: 'lengthed dryer balls', label: 'Household & Cleaning' },
  { text: 'heighted dryer balls', label: 'Household & Cleaning' },
  { text: 'depthed dryer balls', label: 'Household & Cleaning' },
  { text: 'thicknessed dryer balls', label: 'Household & Cleaning' },
  { text: 'diametered dryer balls', label: 'Household & Cleaning' },
  { text: 'radiused dryer balls', label: 'Household & Cleaning' },
  { text: 'circumferenced dryer balls', label: 'Household & Cleaning' },
  { text: 'perimetered dryer balls', label: 'Household & Cleaning' },
  { text: 'boundaried dryer balls', label: 'Household & Cleaning' },
  { text: 'bordered dryer balls', label: 'Household & Cleaning' },
  { text: 'edged dryer balls', label: 'Household & Cleaning' },
  { text: 'rimmed dryer balls', label: 'Household & Cleaning' },
  { text: 'margined dryer balls', label: 'Household & Cleaning' },
  { text: 'limited dryer balls', label: 'Household & Cleaning' },
  { text: 'bounded dryer balls', label: 'Household & Cleaning' },
  { text: 'constrained dryer balls', label: 'Household & Cleaning' },
  { text: 'restricted dryer balls', label: 'Household & Cleaning' },
  { text: 'limitationed dryer balls', label: 'Household & Cleaning' },
  { text: 'barriered dryer balls', label: 'Household & Cleaning' },
  { text: 'obstructed dryer balls', label: 'Household & Cleaning' },
  { text: 'impeded dryer balls', label: 'Household & Cleaning' },
  { text: 'hindered dryer balls', label: 'Household & Cleaning' },
  { text: 'blocked dryer balls', label: 'Household & Cleaning' },
  { text: 'stopped dryer balls', label: 'Household & Cleaning' },
  { text: 'jammed dryer balls', label: 'Household & Cleaning' },
  { text: 'clogged dryer balls', label: 'Household & Cleaning' },
  { text: 'plugged dryer balls', label: 'Household & Cleaning' },
  { text: 'corked dryer balls', label: 'Household & Cleaning' },
  { text: 'stopped dryer balls', label: 'Household & Cleaning' },
  { text: 'capped dryer balls', label: 'Household & Cleaning' },
  { text: 'lidded dryer balls', label: 'Household & Cleaning' },
  { text: 'covered dryer balls', label: 'Household & Cleaning' },
  { text: 'topped dryer balls', label: 'Household & Cleaning' },
  { text: 'roofed dryer balls', label: 'Household & Cleaning' },
  { text: 'ceilinged dryer balls', label: 'Household & Cleaning' },
  { text: 'canopied dryer balls', label: 'Household & Cleaning' },
  { text: 'awninged dryer balls', label: 'Household & Cleaning' },
  { text: 'shaded dryer balls', label: 'Household & Cleaning' },
  { text: 'sheltered dryer balls', label: 'Household & Cleaning' },
  { text: 'protected dryer balls', label: 'Household & Cleaning' },
  { text: 'shielded dryer balls', label: 'Household & Cleaning' },
  { text: 'guarded dryer balls', label: 'Household & Cleaning' },
  { text: 'defended dryer balls', label: 'Household & Cleaning' },
  { text: 'secured dryer balls', label: 'Household & Cleaning' },
  { text: 'safetied dryer balls', label: 'Household & Cleaning' },
  { text: 'insured dryer balls', label: 'Household & Cleaning' },
  { text: 'assured dryer balls', label: 'Household & Cleaning' },
  { text: 'guaranteed dryer balls', label: 'Household & Cleaning' },
  { text: 'warrantied dryer balls', label: 'Household & Cleaning' },
  { text: 'promised dryer balls', label: 'Household & Cleaning' },
  { text: 'pledged dryer balls', label: 'Household & Cleaning' },
  { text: 'committed dryer balls', label: 'Household & Cleaning' },
  { text: 'obligated dryer balls', label: 'Household & Cleaning' },
  { text: 'dutied dryer balls', label: 'Household & Cleaning' },
  { text: 'responsibilitied dryer balls', label: 'Household & Cleaning' },
  { text: 'accountabilitied dryer balls', label: 'Household & Cleaning' },
  { text: 'liabilitied dryer balls', label: 'Household & Cleaning' },
  { text: 'burdened dryer balls', label: 'Household & Cleaning' },
  { text: 'loaded dryer balls', label: 'Household & Cleaning' },
  { text: 'weighted dryer balls', label: 'Household & Cleaning' },
  { text: 'massed dryer balls', label: 'Household & Cleaning' },
  { text: 'bulked dryer balls', label: 'Household & Cleaning' },
  { text: 'volumed dryer balls', label: 'Household & Cleaning' },
  { text: 'capacitied dryer balls', label: 'Household & Cleaning' },
  { text: 'sized dryer balls', label: 'Household & Cleaning' },
  { text: 'scaled dryer balls', label: 'Household & Cleaning' },
  { text: 'proportioned dryer balls', label: 'Household & Cleaning' },
  { text: 'ratioed dryer balls', label: 'Household & Cleaning' },
  { text: 'percentaged dryer balls', label: 'Household & Cleaning' },
  { text: 'fractioned dryer balls', label: 'Household & Cleaning' },
  { text: 'portioned dryer balls', label: 'Household & Cleaning' },
  { text: 'parted dryer balls', label: 'Household & Cleaning' },
  { text: 'pieced dryer balls', label: 'Household & Cleaning' },
  { text: 'segmented dryer balls', label: 'Household & Cleaning' },
  { text: 'sectioned dryer balls', label: 'Household & Cleaning' },
  { text: 'divisioned dryer balls', label: 'Household & Cleaning' },
  { text: 'unitted dryer balls', label: 'Household & Cleaning' },
  { text: 'componented dryer balls', label: 'Household & Cleaning' },
  { text: 'elemented dryer balls', label: 'Household & Cleaning' },
  { text: 'factored dryer balls', label: 'Household & Cleaning' },
  { text: 'aspected dryer balls', label: 'Household & Cleaning' },
  { text: 'featured dryer balls', label: 'Household & Cleaning' },
  { text: 'characteristiced dryer balls', label: 'Household & Cleaning' },
  { text: 'attributed dryer balls', label: 'Household & Cleaning' },
  { text: 'propertied dryer balls', label: 'Household & Cleaning' },
  { text: 'qualitied dryer balls', label: 'Household & Cleaning' },
  { text: 'traited dryer balls', label: 'Household & Cleaning' },
  { text: 'natured dryer balls', label: 'Household & Cleaning' },
  { text: 'essenced dryer balls', label: 'Household & Cleaning' },
  { text: 'substanced dryer balls', label: 'Household & Cleaning' },
  { text: 'materialed dryer balls', label: 'Household & Cleaning' },
  { text: 'mattered dryer balls', label: 'Household & Cleaning' },
  { text: 'stuffed dryer balls', label: 'Household & Cleaning' },
  { text: 'thinged dryer balls', label: 'Household & Cleaning' },
  { text: 'objected dryer balls', label: 'Household & Cleaning' },
  { text: 'itemed dryer balls', label: 'Household & Cleaning' },
  { text: 'articled dryer balls', label: 'Household & Cleaning' },
  { text: 'producted dryer balls', label: 'Household & Cleaning' },
  { text: 'commoditied dryer balls', label: 'Household & Cleaning' },
  { text: 'gooded dryer balls', label: 'Household & Cleaning' },
  { text: 'merchandised dryer balls', label: 'Household & Cleaning' },
  { text: 'wared dryer balls', label: 'Household & Cleaning' },
  { text: 'goodsed dryer balls', label: 'Household & Cleaning' },
  { text: 'stocked dryer balls', label: 'Household & Cleaning' },
  { text: 'inventoried dryer balls', label: 'Household & Cleaning' },
  { text: 'supplied dryer balls', label: 'Household & Cleaning' },
  { text: 'provisioned dryer balls', label: 'Household & Cleaning' },
  { text: 'resourced dryer balls', label: 'Household & Cleaning' },
  { text: 'asseted dryer balls', label: 'Household & Cleaning' },
  { text: 'possessed dryer balls', label: 'Household & Cleaning' },
  { text: 'propertied dryer balls', label: 'Household & Cleaning' },
  { text: 'belonged dryer balls', label: 'Household & Cleaning' },
  { text: 'effected dryer balls', label: 'Household & Cleaning' },
  { text: 'chatteled dryer balls', label: 'Household & Cleaning' },
  { text: 'movabled dryer balls', label: 'Household & Cleaning' },
  { text: 'personaled dryer balls', label: 'Household & Cleaning' },
  { text: 'privated dryer balls', label: 'Household & Cleaning' },
  { text: 'individualed dryer balls', label: 'Household & Cleaning' },
  { text: 'owned dryer balls', label: 'Household & Cleaning' },
  { text: 'exclusived dryer balls', label: 'Household & Cleaning' },
  { text: 'uniqued dryer balls', label: 'Household & Cleaning' },
  { text: 'specialed dryer balls', label: 'Household & Cleaning' },
  { text: 'particulared dryer balls', label: 'Household & Cleaning' },
  { text: 'specificed dryer balls', label: 'Household & Cleaning' },
  { text: 'distincted dryer balls', label: 'Household & Cleaning' },
  { text: 'separated dryer balls', label: 'Household & Cleaning' },
  { text: 'differented dryer balls', label: 'Household & Cleaning' },
  { text: 'varioused dryer balls', label: 'Household & Cleaning' },
  { text: 'diversed dryer balls', label: 'Household & Cleaning' },
  { text: 'varied dryer balls', label: 'Household & Cleaning' },
  { text: 'assorted dryer balls', label: 'Household & Cleaning' },
  { text: 'mixed dryer balls', label: 'Household & Cleaning' },
  { text: 'combined dryer balls', label: 'Household & Cleaning' },
  { text: 'blended dryer balls', label: 'Household & Cleaning' },
  { text: 'merged dryer balls', label: 'Household & Cleaning' },
  { text: 'fused dryer balls', label: 'Household & Cleaning' },
  { text: 'united dryer balls', label: 'Household & Cleaning' },
  { text: 'joined dryer balls', label: 'Household & Cleaning' },
  { text: 'connected dryer balls', label: 'Household & Cleaning' },
  { text: 'linked dryer balls', label: 'Household & Cleaning' },
  { text: 'attached dryer balls', label: 'Household & Cleaning' },
  { text: 'fastened dryer balls', label: 'Household & Cleaning' },
  { text: 'secured dryer balls', label: 'Household & Cleaning' },
  { text: 'fixed dryer balls', label: 'Household & Cleaning' },
  { text: 'bound dryer balls', label: 'Household & Cleaning' },
  { text: 'tied dryer balls', label: 'Household & Cleaning' },
  { text: 'knotted dryer balls', label: 'Household & Cleaning' },
  { text: 'looped dryer balls', label: 'Household & Cleaning' },
  { text: 'wrapped dryer balls', label: 'Household & Cleaning' },
  { text: 'covered dryer balls', label: 'Household & Cleaning' },
  { text: 'encased dryer balls', label: 'Household & Cleaning' },
  { text: 'enclosed dryer balls', label: 'Household & Cleaning' },
  { text: 'contained dryer balls', label: 'Household & Cleaning' },
  { text: 'held dryer balls', label: 'Household & Cleaning' },
  { text: 'carried dryer balls', label: 'Household & Cleaning' },
  { text: 'transported dryer balls', label: 'Household & Cleaning' },
  { text: 'moved dryer balls', label: 'Household & Cleaning' },
  { text: 'shifted dryer balls', label: 'Household & Cleaning' },
  { text: 'transferred dryer balls', label: 'Household & Cleaning' },
  { text: 'relocated dryer balls', label: 'Household & Cleaning' },
  { text: 'displaced dryer balls', label: 'Household & Cleaning' },
  { text: 'migrated dryer balls', label: 'Household & Cleaning' },
  { text: 'traveled dryer balls', label: 'Household & Cleaning' },
  { text: 'journeyed dryer balls', label: 'Household & Cleaning' },
  { text: 'voyaged dryer balls', label: 'Household & Cleaning' },
  { text: 'tripped dryer balls', label: 'Household & Cleaning' },
  { text: 'expeditioned dryer balls', label: 'Household & Cleaning' },
  { text: 'adventured dryer balls', label: 'Household & Cleaning' },
  { text: 'explored dryer balls', label: 'Household & Cleaning' },
  { text: 'discovered dryer balls', label: 'Household & Cleaning' },
  { text: 'quested dryer balls', label: 'Household & Cleaning' },
  { text: 'missioned dryer balls', label: 'Household & Cleaning' },
  { text: 'tasked dryer balls', label: 'Household & Cleaning' },
  { text: 'jobbed dryer balls', label: 'Household & Cleaning' },
  { text: 'worked dryer balls', label: 'Household & Cleaning' },
  { text: 'labored dryer balls', label: 'Household & Cleaning' },
  { text: 'efforded dryer balls', label: 'Household & Cleaning' },
  { text: 'actioned dryer balls', label: 'Household & Cleaning' },
  { text: 'operated dryer balls', label: 'Household & Cleaning' },
  { text: 'functioned dryer balls', label: 'Household & Cleaning' },
  { text: 'performed dryer balls', label: 'Household & Cleaning' },
  { text: 'executed dryer balls', label: 'Household & Cleaning' },
  { text: 'implemented dryer balls', label: 'Household & Cleaning' },
  { text: 'applied dryer balls', label: 'Household & Cleaning' },
  { text: 'used dryer balls', label: 'Household & Cleaning' },
  { text: 'utilized dryer balls', label: 'Household & Cleaning' },
  { text: 'employed dryer balls', label: 'Household & Cleaning' },
  { text: 'deployed dryer balls', label: 'Household & Cleaning' },
  { text: 'installed dryer balls', label: 'Household & Cleaning' },
  { text: 'setup dryer balls', label: 'Household & Cleaning' },
  { text: 'configured dryer balls', label: 'Household & Cleaning' },
  { text: 'arranged dryer balls', label: 'Household & Cleaning' },
  { text: 'organized dryer balls', label: 'Household & Cleaning' },
  { text: 'structured dryer balls', label: 'Household & Cleaning' },
  { text: 'systematized dryer balls', label: 'Household & Cleaning' },
  { text: 'methodized dryer balls', label: 'Household & Cleaning' },
  { text: 'techniqueized dryer balls', label: 'Household & Cleaning' },
  { text: 'approached dryer balls', label: 'Household & Cleaning' },
  { text: 'strategized dryer balls', label: 'Household & Cleaning' },
  { text: 'planned dryer balls', label: 'Household & Cleaning' },
  { text: 'schemed dryer balls', label: 'Household & Cleaning' },
  { text: 'designed dryer balls', label: 'Household & Cleaning' },
  { text: 'blueprinted dryer balls', label: 'Household & Cleaning' },
  { text: 'patterned dryer balls', label: 'Household & Cleaning' },
  { text: 'templated dryer balls', label: 'Household & Cleaning' },
  { text: 'modeled dryer balls', label: 'Household & Cleaning' },
  { text: 'prototyped dryer balls', label: 'Household & Cleaning' },
  { text: 'sampled dryer balls', label: 'Household & Cleaning' },
  { text: 'specimened dryer balls', label: 'Household & Cleaning' },
  { text: 'exampled dryer balls', label: 'Household & Cleaning' },
  { text: 'instanced dryer balls', label: 'Household & Cleaning' },
  { text: 'cased dryer balls', label: 'Household & Cleaning' },
  { text: 'situated dryer balls', label: 'Household & Cleaning' },
  { text: 'conditioned dryer balls', label: 'Household & Cleaning' },
  { text: 'stated dryer balls', label: 'Household & Cleaning' },
  { text: 'statused dryer balls', label: 'Household & Cleaning' },
  { text: 'positioned dryer balls', label: 'Household & Cleaning' },
  { text: 'located dryer balls', label: 'Household & Cleaning' },
  { text: 'placed dryer balls', label: 'Household & Cleaning' },
  { text: 'spotted dryer balls', label: 'Household & Cleaning' },
  { text: 'sited dryer balls', label: 'Household & Cleaning' },
  { text: 'areated dryer balls', label: 'Household & Cleaning' },
  { text: 'zoned dryer balls', label: 'Household & Cleaning' },
  { text: 'regioned dryer balls', label: 'Household & Cleaning' },
  { text: 'territoried dryer balls', label: 'Household & Cleaning' },
  { text: 'domained dryer balls', label: 'Household & Cleaning' },
  { text: 'realmed dryer balls', label: 'Household & Cleaning' },
  { text: 'sphered dryer balls', label: 'Household & Cleaning' },
  { text: 'fielded dryer balls', label: 'Household & Cleaning' },
  { text: 'scoped dryer balls', label: 'Household & Cleaning' },
  { text: 'ranged dryer balls', label: 'Household & Cleaning' },
  { text: 'extended dryer balls', label: 'Household & Cleaning' },
  { text: 'reached dryer balls', label: 'Household & Cleaning' },
  { text: 'spanned dryer balls', label: 'Household & Cleaning' },
  { text: 'stretched dryer balls', label: 'Household & Cleaning' },
  { text: 'spread dryer balls', label: 'Household & Cleaning' },
  { text: 'covered dryer balls', label: 'Household & Cleaning' },
  { text: 'breadthed dryer balls', label: 'Household & Cleaning' },
  { text: 'widthed dryer balls', label: 'Household & Cleaning' },
  { text: 'lengthed dryer balls', label: 'Household & Cleaning' },
  { text: 'heighted dryer balls', label: 'Household & Cleaning' },
  { text: 'depthed dryer balls', label: 'Household & Cleaning' },
  { text: 'thicknessed dryer balls', label: 'Household & Cleaning' },
  { text: 'diametered dryer balls', label: 'Household & Cleaning' },
  { text: 'radiused dryer balls', label: 'Household & Cleaning' },
  { text: 'circumferenced dryer balls', label: 'Household & Cleaning' },
  { text: 'perimetered dryer balls', label: 'Household & Cleaning' },
  { text: 'boundaried dryer balls', label: 'Household & Cleaning' },
  { text: 'bordered dryer balls', label: 'Household & Cleaning' },
  { text: 'edged dryer balls', label: 'Household & Cleaning' }
];

export default householdCleaningData;