// Training data for Lifestyle category
// Singapore-specific lifestyle products and accessories

export const lifestyleTrainingData = [
  // Home decor
  { text: 'candle', label: 'lifestyle' },
  { text: 'picture frame', label: 'lifestyle' },
  { text: 'vase', label: 'lifestyle' },
  { text: 'cushion', label: 'lifestyle' },
  { text: 'throw pillow', label: 'lifestyle' },
  { text: 'blanket', label: 'lifestyle' },
  { text: 'wall art', label: 'lifestyle' },
  { text: 'decorative bowl', label: 'lifestyle' },
  { text: 'ornament', label: 'lifestyle' },
  { text: 'artificial flowers', label: 'lifestyle' },
  { text: 'table runner', label: 'lifestyle' },
  { text: 'placemats', label: 'lifestyle' },
  { text: 'coasters', label: 'lifestyle' },
  { text: 'lamp shade', label: 'lifestyle' },
  { text: 'fairy lights', label: 'lifestyle' },
  
  // Storage and organization
  { text: 'storage box', label: 'lifestyle' },
  { text: 'basket', label: 'lifestyle' },
  { text: 'organizer', label: 'lifestyle' },
  { text: 'drawer divider', label: 'lifestyle' },
  { text: 'jewelry box', label: 'lifestyle' },
  { text: 'shoe rack', label: 'lifestyle' },
  { text: 'wardrobe organizer', label: 'lifestyle' },
  { text: 'closet organizer', label: 'lifestyle' },
  { text: 'vacuum bag', label: 'lifestyle' },
  { text: 'storage jar', label: 'lifestyle' },
  { text: 'file organizer', label: 'lifestyle' },
  { text: 'magazine holder', label: 'lifestyle' },
  { text: 'bookend', label: 'lifestyle' },
  { text: 'coat hanger', label: 'lifestyle' },
  { text: 'laundry basket', label: 'lifestyle' },
  
  // Stationery and office
  { text: 'notebook', label: 'lifestyle' },
  { text: 'pen', label: 'lifestyle' },
  { text: 'pencil', label: 'lifestyle' },
  { text: 'marker', label: 'lifestyle' },
  { text: 'highlighter', label: 'lifestyle' },
  { text: 'sticky notes', label: 'lifestyle' },
  { text: 'paper clips', label: 'lifestyle' },
  { text: 'stapler', label: 'lifestyle' },
  { text: 'scissors', label: 'lifestyle' },
  { text: 'tape', label: 'lifestyle' },
  { text: 'glue stick', label: 'lifestyle' },
  { text: 'ruler', label: 'lifestyle' },
  { text: 'calculator', label: 'lifestyle' },
  { text: 'diary', label: 'lifestyle' },
  { text: 'planner', label: 'lifestyle' },
  
  // Bags and accessories
  { text: 'handbag', label: 'lifestyle' },
  { text: 'backpack', label: 'lifestyle' },
  { text: 'tote bag', label: 'lifestyle' },
  { text: 'wallet', label: 'lifestyle' },
  { text: 'purse', label: 'lifestyle' },
  { text: 'luggage', label: 'lifestyle' },
  { text: 'travel bag', label: 'lifestyle' },
  { text: 'gym bag', label: 'lifestyle' },
  { text: 'laptop bag', label: 'lifestyle' },
  { text: 'shopping bag', label: 'lifestyle' },
  { text: 'eco bag', label: 'lifestyle' },
  { text: 'reusable bag', label: 'lifestyle' },
  { text: 'cooler bag', label: 'lifestyle' },
  { text: 'lunch bag', label: 'lifestyle' },
  { text: 'cosmetic bag', label: 'lifestyle' },
  
  // Fashion accessories
  { text: 'sunglasses', label: 'lifestyle' },
  { text: 'hat', label: 'lifestyle' },
  { text: 'cap', label: 'lifestyle' },
  { text: 'scarf', label: 'lifestyle' },
  { text: 'belt', label: 'lifestyle' },
  { text: 'watch', label: 'lifestyle' },
  { text: 'jewelry', label: 'lifestyle' },
  { text: 'necklace', label: 'lifestyle' },
  { text: 'earrings', label: 'lifestyle' },
  { text: 'bracelet', label: 'lifestyle' },
  { text: 'ring', label: 'lifestyle' },
  { text: 'hair accessories', label: 'lifestyle' },
  { text: 'headband', label: 'lifestyle' },
  { text: 'hair clip', label: 'lifestyle' },
  { text: 'umbrella', label: 'lifestyle' },
  
  // Travel and outdoor
  { text: 'travel pillow', label: 'lifestyle' },
  { text: 'eye mask', label: 'lifestyle' },
  { text: 'travel adapter', label: 'lifestyle' },
  { text: 'luggage tag', label: 'lifestyle' },
  { text: 'passport holder', label: 'lifestyle' },
  { text: 'water bottle', label: 'lifestyle' },
  { text: 'thermos', label: 'lifestyle' },
  { text: 'tumbler', label: 'lifestyle' },
  { text: 'picnic mat', label: 'lifestyle' },
  { text: 'camping chair', label: 'lifestyle' },
  { text: 'flashlight', label: 'lifestyle' },
  { text: 'portable fan', label: 'lifestyle' },
  { text: 'power bank', label: 'lifestyle' },
  { text: 'phone case', label: 'lifestyle' },
  { text: 'screen protector', label: 'lifestyle' },
  
  // Gifts and novelty
  { text: 'gift card', label: 'lifestyle' },
  { text: 'greeting card', label: 'lifestyle' },
  { text: 'wrapping paper', label: 'lifestyle' },
  { text: 'gift bag', label: 'lifestyle' },
  { text: 'ribbon', label: 'lifestyle' },
  { text: 'keychain', label: 'lifestyle' },
  { text: 'magnet', label: 'lifestyle' },
  { text: 'bookmark', label: 'lifestyle' },
  { text: 'calendar', label: 'lifestyle' },
  { text: 'postcard', label: 'lifestyle' },
  { text: 'sticker', label: 'lifestyle' },
  { text: 'badge', label: 'lifestyle' },
  { text: 'pin', label: 'lifestyle' },
  { text: 'souvenir', label: 'lifestyle' },
  { text: 'collectible', label: 'lifestyle' }
];