export const meatSeafoodData = [
  { text: 'beef', label: 'Meat & Seafood' },
  { text: 'ground beef', label: 'Meat & Seafood' },
  { text: 'beef steak', label: 'Meat & Seafood' },
  { text: 'ribeye steak', label: 'Meat & Seafood' },
  { text: 'sirloin steak', label: 'Meat & Seafood' },
  { text: 'filet mignon', label: 'Meat & Seafood' },
  { text: 'new york strip', label: 'Meat & Seafood' },
  { text: 't-bone steak', label: 'Meat & Seafood' },
  { text: 'porterhouse steak', label: 'Meat & Seafood' },
  { text: 'flank steak', label: 'Meat & Seafood' },
  { text: 'skirt steak', label: 'Meat & Seafood' },
  { text: 'chuck roast', label: 'Meat & Seafood' },
  { text: 'pot roast', label: 'Meat & Seafood' },
  { text: 'beef brisket', label: 'Meat & Seafood' },
  { text: 'beef ribs', label: 'Meat & Seafood' },
  { text: 'short ribs', label: 'Meat & Seafood' },
  { text: 'beef tenderloin', label: 'Meat & Seafood' },
  { text: 'beef round', label: 'Meat & Seafood' },
  { text: 'beef shank', label: 'Meat & Seafood' },
  { text: 'beef liver', label: 'Meat & Seafood' },
  { text: 'beef heart', label: 'Meat & Seafood' },
  { text: 'beef tongue', label: 'Meat & Seafood' },
  { text: 'beef kidney', label: 'Meat & Seafood' },
  { text: 'beef tripe', label: 'Meat & Seafood' },
  { text: 'beef oxtail', label: 'Meat & Seafood' },
  { text: 'beef marrow', label: 'Meat & Seafood' },
  { text: 'pork', label: 'Meat & Seafood' },
  { text: 'ground pork', label: 'Meat & Seafood' },
  { text: 'pork chops', label: 'Meat & Seafood' },
  { text: 'pork tenderloin', label: 'Meat & Seafood' },
  { text: 'pork loin', label: 'Meat & Seafood' },
  { text: 'pork shoulder', label: 'Meat & Seafood' },
  { text: 'pork butt', label: 'Meat & Seafood' },
  { text: 'pork belly', label: 'Meat & Seafood' },
  { text: 'pork ribs', label: 'Meat & Seafood' },
  { text: 'baby back ribs', label: 'Meat & Seafood' },
  { text: 'spare ribs', label: 'Meat & Seafood' },
  { text: 'pork hocks', label: 'Meat & Seafood' },
  { text: 'pork feet', label: 'Meat & Seafood' },
  { text: 'pork liver', label: 'Meat & Seafood' },
  { text: 'pork kidney', label: 'Meat & Seafood' },
  { text: 'pork heart', label: 'Meat & Seafood' },
  { text: 'bacon', label: 'Meat & Seafood' },
  { text: 'ham', label: 'Meat & Seafood' },
  { text: 'prosciutto', label: 'Meat & Seafood' },
  { text: 'pancetta', label: 'Meat & Seafood' },
  { text: 'canadian bacon', label: 'Meat & Seafood' },
  { text: 'turkey bacon', label: 'Meat & Seafood' },
  { text: 'sausage', label: 'Meat & Seafood' },
  { text: 'italian sausage', label: 'Meat & Seafood' },
  { text: 'bratwurst', label: 'Meat & Seafood' },
  { text: 'chorizo', label: 'Meat & Seafood' },
  { text: 'kielbasa', label: 'Meat & Seafood' },
  { text: 'andouille', label: 'Meat & Seafood' },
  { text: 'breakfast sausage', label: 'Meat & Seafood' },
  { text: 'hot dogs', label: 'Meat & Seafood' },
  { text: 'frankfurters', label: 'Meat & Seafood' },
  { text: 'vienna sausage', label: 'Meat & Seafood' },
  { text: 'pepperoni', label: 'Meat & Seafood' },
  { text: 'salami', label: 'Meat & Seafood' },
  { text: 'bologna', label: 'Meat & Seafood' },
  { text: 'mortadella', label: 'Meat & Seafood' },
  { text: 'pastrami', label: 'Meat & Seafood' },
  { text: 'corned beef', label: 'Meat & Seafood' },
  { text: 'roast beef', label: 'Meat & Seafood' },
  { text: 'turkey', label: 'Meat & Seafood' },
  { text: 'ground turkey', label: 'Meat & Seafood' },
  { text: 'turkey breast', label: 'Meat & Seafood' },
  { text: 'turkey thigh', label: 'Meat & Seafood' },
  { text: 'turkey leg', label: 'Meat & Seafood' },
  { text: 'turkey wing', label: 'Meat & Seafood' },
  { text: 'whole turkey', label: 'Meat & Seafood' },
  { text: 'turkey deli meat', label: 'Meat & Seafood' },
  { text: 'smoked turkey', label: 'Meat & Seafood' },
  { text: 'chicken', label: 'Meat & Seafood' },
  { text: 'ground chicken', label: 'Meat & Seafood' },
  { text: 'chicken breast', label: 'Meat & Seafood' },
  { text: 'chicken thigh', label: 'Meat & Seafood' },
  { text: 'chicken leg', label: 'Meat & Seafood' },
  { text: 'chicken wing', label: 'Meat & Seafood' },
  { text: 'chicken drumstick', label: 'Meat & Seafood' },
  { text: 'whole chicken', label: 'Meat & Seafood' },
  { text: 'rotisserie chicken', label: 'Meat & Seafood' },
  { text: 'chicken tenders', label: 'Meat & Seafood' },
  { text: 'chicken cutlets', label: 'Meat & Seafood' },
  { text: 'chicken liver', label: 'Meat & Seafood' },
  { text: 'chicken gizzards', label: 'Meat & Seafood' },
  { text: 'chicken hearts', label: 'Meat & Seafood' },
  { text: 'duck', label: 'Meat & Seafood' },
  { text: 'duck breast', label: 'Meat & Seafood' },
  { text: 'duck leg', label: 'Meat & Seafood' },
  { text: 'whole duck', label: 'Meat & Seafood' },
  { text: 'duck liver', label: 'Meat & Seafood' },
  { text: 'foie gras', label: 'Meat & Seafood' },
  { text: 'goose', label: 'Meat & Seafood' },
  { text: 'goose breast', label: 'Meat & Seafood' },
  { text: 'whole goose', label: 'Meat & Seafood' },
  { text: 'quail', label: 'Meat & Seafood' },
  { text: 'pheasant', label: 'Meat & Seafood' },
  { text: 'cornish hen', label: 'Meat & Seafood' },
  { text: 'lamb', label: 'Meat & Seafood' },
  { text: 'ground lamb', label: 'Meat & Seafood' },
  { text: 'lamb chops', label: 'Meat & Seafood' },
  { text: 'lamb leg', label: 'Meat & Seafood' },
  { text: 'lamb shoulder', label: 'Meat & Seafood' },
  { text: 'lamb shank', label: 'Meat & Seafood' },
  { text: 'rack of lamb', label: 'Meat & Seafood' },
  { text: 'lamb ribs', label: 'Meat & Seafood' },
  { text: 'lamb liver', label: 'Meat & Seafood' },
  { text: 'lamb kidney', label: 'Meat & Seafood' },
  { text: 'veal', label: 'Meat & Seafood' },
  { text: 'veal chops', label: 'Meat & Seafood' },
  { text: 'veal cutlets', label: 'Meat & Seafood' },
  { text: 'veal scallopini', label: 'Meat & Seafood' },
  { text: 'veal shank', label: 'Meat & Seafood' },
  { text: 'veal osso buco', label: 'Meat & Seafood' },
  { text: 'goat', label: 'Meat & Seafood' },
  { text: 'goat meat', label: 'Meat & Seafood' },
  { text: 'chevon', label: 'Meat & Seafood' },
  { text: 'cabrito', label: 'Meat & Seafood' },
  { text: 'venison', label: 'Meat & Seafood' },
  { text: 'deer meat', label: 'Meat & Seafood' },
  { text: 'elk', label: 'Meat & Seafood' },
  { text: 'moose', label: 'Meat & Seafood' },
  { text: 'bison', label: 'Meat & Seafood' },
  { text: 'buffalo', label: 'Meat & Seafood' },
  { text: 'rabbit', label: 'Meat & Seafood' },
  { text: 'wild boar', label: 'Meat & Seafood' },
  { text: 'ostrich', label: 'Meat & Seafood' },
  { text: 'emu', label: 'Meat & Seafood' },
  { text: 'alligator', label: 'Meat & Seafood' },
  { text: 'kangaroo', label: 'Meat & Seafood' },
  { text: 'salmon', label: 'Meat & Seafood' },
  { text: 'atlantic salmon', label: 'Meat & Seafood' },
  { text: 'pacific salmon', label: 'Meat & Seafood' },
  { text: 'king salmon', label: 'Meat & Seafood' },
  { text: 'chinook salmon', label: 'Meat & Seafood' },
  { text: 'coho salmon', label: 'Meat & Seafood' },
  { text: 'sockeye salmon', label: 'Meat & Seafood' },
  { text: 'pink salmon', label: 'Meat & Seafood' },
  { text: 'chum salmon', label: 'Meat & Seafood' },
  { text: 'smoked salmon', label: 'Meat & Seafood' },
  { text: 'salmon fillet', label: 'Meat & Seafood' },
  { text: 'salmon steak', label: 'Meat & Seafood' },
  { text: 'tuna', label: 'Meat & Seafood' },
  { text: 'yellowfin tuna', label: 'Meat & Seafood' },
  { text: 'bluefin tuna', label: 'Meat & Seafood' },
  { text: 'albacore tuna', label: 'Meat & Seafood' },
  { text: 'skipjack tuna', label: 'Meat & Seafood' },
  { text: 'bigeye tuna', label: 'Meat & Seafood' },
  { text: 'tuna steak', label: 'Meat & Seafood' },
  { text: 'ahi tuna', label: 'Meat & Seafood' },
  { text: 'canned tuna', label: 'Meat & Seafood' },
  { text: 'cod', label: 'Meat & Seafood' },
  { text: 'atlantic cod', label: 'Meat & Seafood' },
  { text: 'pacific cod', label: 'Meat & Seafood' },
  { text: 'black cod', label: 'Meat & Seafood' },
  { text: 'sablefish', label: 'Meat & Seafood' },
  { text: 'cod fillet', label: 'Meat & Seafood' },
  { text: 'haddock', label: 'Meat & Seafood' },
  { text: 'pollock', label: 'Meat & Seafood' },
  { text: 'alaska pollock', label: 'Meat & Seafood' },
  { text: 'halibut', label: 'Meat & Seafood' },
  { text: 'pacific halibut', label: 'Meat & Seafood' },
  { text: 'atlantic halibut', label: 'Meat & Seafood' },
  { text: 'halibut steak', label: 'Meat & Seafood' },
  { text: 'halibut fillet', label: 'Meat & Seafood' },
  { text: 'flounder', label: 'Meat & Seafood' },
  { text: 'sole', label: 'Meat & Seafood' },
  { text: 'dover sole', label: 'Meat & Seafood' },
  { text: 'petrale sole', label: 'Meat & Seafood' },
  { text: 'lemon sole', label: 'Meat & Seafood' },
  { text: 'plaice', label: 'Meat & Seafood' },
  { text: 'turbot', label: 'Meat & Seafood' },
  { text: 'sea bass', label: 'Meat & Seafood' },
  { text: 'striped bass', label: 'Meat & Seafood' },
  { text: 'black sea bass', label: 'Meat & Seafood' },
  { text: 'chilean sea bass', label: 'Meat & Seafood' },
  { text: 'patagonian toothfish', label: 'Meat & Seafood' },
  { text: 'grouper', label: 'Meat & Seafood' },
  { text: 'red grouper', label: 'Meat & Seafood' },
  { text: 'black grouper', label: 'Meat & Seafood' },
  { text: 'goliath grouper', label: 'Meat & Seafood' },
  { text: 'snapper', label: 'Meat & Seafood' },
  { text: 'red snapper', label: 'Meat & Seafood' },
  { text: 'yellowtail snapper', label: 'Meat & Seafood' },
  { text: 'lane snapper', label: 'Meat & Seafood' },
  { text: 'mutton snapper', label: 'Meat & Seafood' },
  { text: 'mahi mahi', label: 'Meat & Seafood' },
  { text: 'dorado', label: 'Meat & Seafood' },
  { text: 'dolphinfish', label: 'Meat & Seafood' },
  { text: 'swordfish', label: 'Meat & Seafood' },
  { text: 'marlin', label: 'Meat & Seafood' },
  { text: 'blue marlin', label: 'Meat & Seafood' },
  { text: 'white marlin', label: 'Meat & Seafood' },
  { text: 'sailfish', label: 'Meat & Seafood' },
  { text: 'wahoo', label: 'Meat & Seafood' },
  { text: 'mackerel', label: 'Meat & Seafood' },
  { text: 'spanish mackerel', label: 'Meat & Seafood' },
  { text: 'king mackerel', label: 'Meat & Seafood' },
  { text: 'atlantic mackerel', label: 'Meat & Seafood' },
  { text: 'sardines', label: 'Meat & Seafood' },
  { text: 'anchovies', label: 'Meat & Seafood' },
  { text: 'herring', label: 'Meat & Seafood' },
  { text: 'pickled herring', label: 'Meat & Seafood' },
  { text: 'smoked herring', label: 'Meat & Seafood' },
  { text: 'kippers', label: 'Meat & Seafood' },
  { text: 'trout', label: 'Meat & Seafood' },
  { text: 'rainbow trout', label: 'Meat & Seafood' },
  { text: 'brook trout', label: 'Meat & Seafood' },
  { text: 'brown trout', label: 'Meat & Seafood' },
  { text: 'lake trout', label: 'Meat & Seafood' },
  { text: 'steelhead trout', label: 'Meat & Seafood' },
  { text: 'smoked trout', label: 'Meat & Seafood' },
  { text: 'catfish', label: 'Meat & Seafood' },
  { text: 'channel catfish', label: 'Meat & Seafood' },
  { text: 'blue catfish', label: 'Meat & Seafood' },
  { text: 'flathead catfish', label: 'Meat & Seafood' },
  { text: 'tilapia', label: 'Meat & Seafood' },
  { text: 'nile tilapia', label: 'Meat & Seafood' },
  { text: 'red tilapia', label: 'Meat & Seafood' },
  { text: 'swai', label: 'Meat & Seafood' },
  { text: 'basa', label: 'Meat & Seafood' },
  { text: 'pangasius', label: 'Meat & Seafood' },
  { text: 'monkfish', label: 'Meat & Seafood' },
  { text: 'anglerfish', label: 'Meat & Seafood' },
  { text: 'john dory', label: 'Meat & Seafood' },
  { text: 'pompano', label: 'Meat & Seafood' },
  { text: 'amberjack', label: 'Meat & Seafood' },
  { text: 'cobia', label: 'Meat & Seafood' },
  { text: 'barramundi', label: 'Meat & Seafood' },
  { text: 'arctic char', label: 'Meat & Seafood' },
  { text: 'branzino', label: 'Meat & Seafood' },
  { text: 'european sea bass', label: 'Meat & Seafood' },
  { text: 'rockfish', label: 'Meat & Seafood' },
  { text: 'lingcod', label: 'Meat & Seafood' },
  { text: 'opah', label: 'Meat & Seafood' },
  { text: 'moonfish', label: 'Meat & Seafood' },
  { text: 'escolar', label: 'Meat & Seafood' },
  { text: 'white tuna', label: 'Meat & Seafood' },
  { text: 'butterfish', label: 'Meat & Seafood' },
  { text: 'bluefish', label: 'Meat & Seafood' },
  { text: 'weakfish', label: 'Meat & Seafood' },
  { text: 'croaker', label: 'Meat & Seafood' },
  { text: 'drum', label: 'Meat & Seafood' },
  { text: 'red drum', label: 'Meat & Seafood' },
  { text: 'black drum', label: 'Meat & Seafood' },
  { text: 'sheepshead', label: 'Meat & Seafood' },
  { text: 'porgy', label: 'Meat & Seafood' },
  { text: 'scup', label: 'Meat & Seafood' },
  { text: 'sea bream', label: 'Meat & Seafood' },
  { text: 'red sea bream', label: 'Meat & Seafood' },
  { text: 'gilt head bream', label: 'Meat & Seafood' },
  { text: 'dentex', label: 'Meat & Seafood' },
  { text: 'wrasse', label: 'Meat & Seafood' },
  { text: 'parrotfish', label: 'Meat & Seafood' },
  { text: 'triggerfish', label: 'Meat & Seafood' },
  { text: 'filefish', label: 'Meat & Seafood' },
  { text: 'pufferfish', label: 'Meat & Seafood' },
  { text: 'fugu', label: 'Meat & Seafood' },
  { text: 'eel', label: 'Meat & Seafood' },
  { text: 'shrimp', label: 'Meat & Seafood' },
  { text: 'spot prawns', label: 'Meat & Seafood' },
  { text: 'langostino', label: 'Meat & Seafood' },
  { text: 'prawns', label: 'Meat & Seafood' },
  { text: 'jumbo shrimp', label: 'Meat & Seafood' },
  { text: 'crab', label: 'Meat & Seafood' },
  { text: 'lobster', label: 'Meat & Seafood' },
  { text: 'scallops', label: 'Meat & Seafood' },
  { text: 'oysters', label: 'Meat & Seafood' },
  { text: 'mussels', label: 'Meat & Seafood' },
  { text: 'blue mussels', label: 'Meat & Seafood' },
  { text: 'mediterranean mussels', label: 'Meat & Seafood' },
  { text: 'green mussels', label: 'Meat & Seafood' },
  { text: 'new zealand mussels', label: 'Meat & Seafood' },
  { text: 'prince edward island mussels', label: 'Meat & Seafood' },
  { text: 'clams', label: 'Meat & Seafood' },
  { text: 'abalone', label: 'Meat & Seafood' },
  { text: 'conch', label: 'Meat & Seafood' },
  { text: 'whelk', label: 'Meat & Seafood' },
  { text: 'periwinkle', label: 'Meat & Seafood' },
  { text: 'cockles', label: 'Meat & Seafood' },
  { text: 'sea snails', label: 'Meat & Seafood' },
  { text: 'escargot', label: 'Meat & Seafood' },
  { text: 'land snails', label: 'Meat & Seafood' },
  { text: 'squid', label: 'Meat & Seafood' },
  { text: 'calamari', label: 'Meat & Seafood' },
  { text: 'octopus', label: 'Meat & Seafood' },
  { text: 'cuttlefish', label: 'Meat & Seafood' },
  { text: 'nautilus', label: 'Meat & Seafood' },
  { text: 'sea urchin', label: 'Meat & Seafood' },
  { text: 'uni', label: 'Meat & Seafood' },
  { text: 'sea cucumber', label: 'Meat & Seafood' },
  { text: 'jellyfish', label: 'Meat & Seafood' },
  { text: 'starfish', label: 'Meat & Seafood' },
  { text: 'sea anemone', label: 'Meat & Seafood' },
  { text: 'barnacles', label: 'Meat & Seafood' },
  { text: 'gooseneck barnacles', label: 'Meat & Seafood' },
  { text: 'percebes', label: 'Meat & Seafood' },
  { text: 'sea beans', label: 'Meat & Seafood' },
  { text: 'samphire', label: 'Meat & Seafood' },
  { text: 'sea lettuce', label: 'Meat & Seafood' },
  { text: 'kelp', label: 'Meat & Seafood' },
  { text: 'nori', label: 'Meat & Seafood' },
  { text: 'wakame', label: 'Meat & Seafood' },
  { text: 'kombu', label: 'Meat & Seafood' },
  { text: 'dulse', label: 'Meat & Seafood' },
  { text: 'irish moss', label: 'Meat & Seafood' },
  { text: 'sea grapes', label: 'Meat & Seafood' },
  { text: 'caviar', label: 'Meat & Seafood' },
  { text: 'fish roe', label: 'Meat & Seafood' },
  { text: 'fish eggs', label: 'Meat & Seafood' },
  { text: 'roe', label: 'Meat & Seafood' }
];

export default meatSeafoodData;