/**
 * Training data for Meat & Seafood category
 * Singapore-focused meat, poultry, and seafood items
 */

export interface TrainingDataItem {
  text: string;
  label: string;
}

export const meatSeafoodTrainingData: TrainingDataItem[] = [
  // Chicken
  { text: 'chicken', label: 'meat' },
  { text: 'whole chicken', label: 'meat' },
  { text: 'chicken breast', label: 'meat' },
  { text: 'chicken thigh', label: 'meat' },
  { text: 'chicken drumstick', label: 'meat' },
  { text: 'chicken wing', label: 'meat' },
  { text: 'chicken leg', label: 'meat' },
  { text: 'chicken fillet', label: 'meat' },
  { text: 'boneless chicken', label: 'meat' },
  { text: 'skinless chicken', label: 'meat' },
  { text: 'organic chicken', label: 'meat' },
  { text: 'free range chicken', label: 'meat' },
  { text: 'kampong chicken', label: 'meat' },
  { text: 'black chicken', label: 'meat' },
  { text: 'chicken mince', label: 'meat' },
  { text: 'ground chicken', label: 'meat' },
  { text: 'chicken cutlet', label: 'meat' },
  { text: 'chicken tender', label: 'meat' },
  
  // Pork
  { text: 'pork', label: 'meat' },
  { text: 'pork chop', label: 'meat' },
  { text: 'pork belly', label: 'meat' },
  { text: 'pork shoulder', label: 'meat' },
  { text: 'pork loin', label: 'meat' },
  { text: 'pork ribs', label: 'meat' },
  { text: 'spare ribs', label: 'meat' },
  { text: 'baby back ribs', label: 'meat' },
  { text: 'pork tenderloin', label: 'meat' },
  { text: 'pork leg', label: 'meat' },
  { text: 'pork knuckle', label: 'meat' },
  { text: 'pork mince', label: 'meat' },
  { text: 'ground pork', label: 'meat' },
  { text: 'char siu', label: 'meat' },
  { text: 'roast pork', label: 'meat' },
  { text: 'pork slice', label: 'meat' },
  { text: 'bacon', label: 'meat' },
  { text: 'ham', label: 'meat' },
  { text: 'pancetta', label: 'meat' },
  { text: 'prosciutto', label: 'meat' },
  
  // Beef
  { text: 'beef', label: 'meat' },
  { text: 'beef steak', label: 'meat' },
  { text: 'ribeye steak', label: 'meat' },
  { text: 'sirloin steak', label: 'meat' },
  { text: 'tenderloin', label: 'meat' },
  { text: 'filet mignon', label: 'meat' },
  { text: 't-bone steak', label: 'meat' },
  { text: 'porterhouse steak', label: 'meat' },
  { text: 'strip steak', label: 'meat' },
  { text: 'beef brisket', label: 'meat' },
  { text: 'beef short ribs', label: 'meat' },
  { text: 'beef chuck', label: 'meat' },
  { text: 'beef round', label: 'meat' },
  { text: 'ground beef', label: 'meat' },
  { text: 'beef mince', label: 'meat' },
  { text: 'beef slice', label: 'meat' },
  { text: 'beef cube', label: 'meat' },
  { text: 'stewing beef', label: 'meat' },
  { text: 'wagyu beef', label: 'meat' },
  { text: 'angus beef', label: 'meat' },
  
  // Lamb & Mutton
  { text: 'lamb', label: 'meat' },
  { text: 'lamb chop', label: 'meat' },
  { text: 'lamb leg', label: 'meat' },
  { text: 'lamb shoulder', label: 'meat' },
  { text: 'lamb rack', label: 'meat' },
  { text: 'lamb shank', label: 'meat' },
  { text: 'ground lamb', label: 'meat' },
  { text: 'lamb mince', label: 'meat' },
  { text: 'mutton', label: 'meat' },
  { text: 'mutton chop', label: 'meat' },
  { text: 'mutton curry cut', label: 'meat' },
  
  // Duck & Other Poultry
  { text: 'duck', label: 'meat' },
  { text: 'whole duck', label: 'meat' },
  { text: 'duck breast', label: 'meat' },
  { text: 'duck leg', label: 'meat' },
  { text: 'duck thigh', label: 'meat' },
  { text: 'roast duck', label: 'meat' },
  { text: 'peking duck', label: 'meat' },
  { text: 'turkey', label: 'meat' },
  { text: 'turkey breast', label: 'meat' },
  { text: 'turkey leg', label: 'meat' },
  { text: 'goose', label: 'meat' },
  { text: 'quail', label: 'meat' },
  { text: 'pigeon', label: 'meat' },
  
  // Fish - Local Varieties
  { text: 'fish', label: 'meat' },
  { text: 'pomfret', label: 'meat' },
  { text: 'sea bass', label: 'meat' },
  { text: 'grouper', label: 'meat' },
  { text: 'red snapper', label: 'meat' },
  { text: 'threadfin', label: 'meat' },
  { text: 'mackerel', label: 'meat' },
  { text: 'spanish mackerel', label: 'meat' },
  { text: 'batang fish', label: 'meat' },
  { text: 'tenggiri', label: 'meat' },
  { text: 'stingray', label: 'meat' },
  { text: 'barramundi', label: 'meat' },
  { text: 'garoupa', label: 'meat' },
  { text: 'john dory', label: 'meat' },
  { text: 'dory fish', label: 'meat' },
  { text: 'tilapia', label: 'meat' },
  { text: 'catfish', label: 'meat' },
  { text: 'milkfish', label: 'meat' },
  { text: 'bangus', label: 'meat' },
  
  // Fish - International
  { text: 'salmon', label: 'meat' },
  { text: 'atlantic salmon', label: 'meat' },
  { text: 'norwegian salmon', label: 'meat' },
  { text: 'salmon fillet', label: 'meat' },
  { text: 'salmon steak', label: 'meat' },
  { text: 'smoked salmon', label: 'meat' },
  { text: 'tuna', label: 'meat' },
  { text: 'yellowfin tuna', label: 'meat' },
  { text: 'bluefin tuna', label: 'meat' },
  { text: 'tuna steak', label: 'meat' },
  { text: 'cod', label: 'meat' },
  { text: 'cod fillet', label: 'meat' },
  { text: 'halibut', label: 'meat' },
  { text: 'sole', label: 'meat' },
  { text: 'flounder', label: 'meat' },
  { text: 'mahi mahi', label: 'meat' },
  { text: 'swordfish', label: 'meat' },
  { text: 'sea bream', label: 'meat' },
  
  // Shellfish & Crustaceans
  { text: 'prawns', label: 'meat' },
  { text: 'shrimp', label: 'meat' },
  { text: 'tiger prawns', label: 'meat' },
  { text: 'white prawns', label: 'meat' },
  { text: 'king prawns', label: 'meat' },
  { text: 'jumbo prawns', label: 'meat' },
  { text: 'vannamei prawns', label: 'meat' },
  { text: 'crab', label: 'meat' },
  { text: 'mud crab', label: 'meat' },
  { text: 'flower crab', label: 'meat' },
  { text: 'blue swimmer crab', label: 'meat' },
  { text: 'dungeness crab', label: 'meat' },
  { text: 'king crab', label: 'meat' },
  { text: 'snow crab', label: 'meat' },
  { text: 'soft shell crab', label: 'meat' },
  { text: 'lobster', label: 'meat' },
  { text: 'rock lobster', label: 'meat' },
  { text: 'boston lobster', label: 'meat' },
  { text: 'crayfish', label: 'meat' },
  
  // Mollusks
  { text: 'squid', label: 'meat' },
  { text: 'sotong', label: 'meat' },
  { text: 'cuttlefish', label: 'meat' },
  { text: 'octopus', label: 'meat' },
  { text: 'baby octopus', label: 'meat' },
  { text: 'scallop', label: 'meat' },
  { text: 'sea scallop', label: 'meat' },
  { text: 'bay scallop', label: 'meat' },
  { text: 'mussel', label: 'meat' },
  { text: 'green mussel', label: 'meat' },
  { text: 'blue mussel', label: 'meat' },
  { text: 'clam', label: 'meat' },
  { text: 'cockles', label: 'meat' },
  { text: 'lala', label: 'meat' },
  { text: 'oyster', label: 'meat' },
  { text: 'fresh oyster', label: 'meat' },
  { text: 'rock oyster', label: 'meat' },
  { text: 'abalone', label: 'meat' },
  { text: 'sea cucumber', label: 'meat' },
  
  // Processed Seafood
  { text: 'fish ball', label: 'meat' },
  { text: 'fishball', label: 'meat' },
  { text: 'fish cake', label: 'meat' },
  { text: 'fishcake', label: 'meat' },
  { text: 'fish tofu', label: 'meat' },
  { text: 'crab stick', label: 'meat' },
  { text: 'imitation crab', label: 'meat' },
  { text: 'surimi', label: 'meat' },
  { text: 'fish sausage', label: 'meat' },
  { text: 'fish paste', label: 'meat' },
  { text: 'prawn paste', label: 'meat' },
  { text: 'fish maw', label: 'meat' },
  { text: 'dried fish', label: 'meat' },
  { text: 'salted fish', label: 'meat' },
  { text: 'fish fillet', label: 'meat' },
  { text: 'fish slice', label: 'meat' },
  
  // Processed Meat
  { text: 'sausage', label: 'meat' },
  { text: 'chicken sausage', label: 'meat' },
  { text: 'pork sausage', label: 'meat' },
  { text: 'beef sausage', label: 'meat' },
  { text: 'bratwurst', label: 'meat' },
  { text: 'chorizo', label: 'meat' },
  { text: 'salami', label: 'meat' },
  { text: 'pepperoni', label: 'meat' },
  { text: 'frankfurter', label: 'meat' },
  { text: 'hot dog', label: 'meat' },
  { text: 'vienna sausage', label: 'meat' },
  { text: 'luncheon meat', label: 'meat' },
  { text: 'spam', label: 'meat' },
  { text: 'corned beef', label: 'meat' },
  { text: 'pastrami', label: 'meat' },
  { text: 'mortadella', label: 'meat' },
  
  // Asian Processed Meat
  { text: 'lap cheong', label: 'meat' },
  { text: 'chinese sausage', label: 'meat' },
  { text: 'waxed sausage', label: 'meat' },
  { text: 'liver sausage', label: 'meat' },
  { text: 'blood sausage', label: 'meat' },
  { text: 'black pudding', label: 'meat' },
  { text: 'char siu bao', label: 'meat' },
  { text: 'siu mai', label: 'meat' },
  { text: 'har gow', label: 'meat' },
  { text: 'wonton', label: 'meat' },
  { text: 'dumpling', label: 'meat' },
  { text: 'gyoza', label: 'meat' },
  { text: 'meatball', label: 'meat' },
  { text: 'pork ball', label: 'meat' },
  { text: 'beef ball', label: 'meat' },
  { text: 'chicken ball', label: 'meat' },
  
  // Organ Meat
  { text: 'liver', label: 'meat' },
  { text: 'chicken liver', label: 'meat' },
  { text: 'pork liver', label: 'meat' },
  { text: 'beef liver', label: 'meat' },
  { text: 'kidney', label: 'meat' },
  { text: 'heart', label: 'meat' },
  { text: 'tongue', label: 'meat' },
  { text: 'tripe', label: 'meat' },
  { text: 'stomach', label: 'meat' },
  { text: 'intestine', label: 'meat' },
  { text: 'gizzard', label: 'meat' },
  { text: 'chicken feet', label: 'meat' },
  { text: 'pig trotters', label: 'meat' },
  { text: 'oxtail', label: 'meat' },
  { text: 'marrow bone', label: 'meat' },
  
  // Specialty & Exotic
  { text: 'venison', label: 'meat' },
  { text: 'rabbit', label: 'meat' },
  { text: 'wild boar', label: 'meat' },
  { text: 'ostrich', label: 'meat' },
  { text: 'emu', label: 'meat' },
  { text: 'kangaroo', label: 'meat' },
  { text: 'crocodile', label: 'meat' },
  { text: 'frog legs', label: 'meat' },
  { text: 'turtle', label: 'meat' },
  { text: 'shark fin', label: 'meat' },
  { text: 'sea urchin', label: 'meat' },
  { text: 'jellyfish', label: 'meat' },
  
  // Marinated & Prepared
  { text: 'marinated chicken', label: 'meat' },
  { text: 'marinated pork', label: 'meat' },
  { text: 'marinated beef', label: 'meat' },
  { text: 'bbq meat', label: 'meat' },
  { text: 'grilled meat', label: 'meat' },
  { text: 'roasted meat', label: 'meat' },
  { text: 'smoked meat', label: 'meat' },
  { text: 'cured meat', label: 'meat' },
  { text: 'jerky', label: 'meat' },
  { text: 'bak kwa', label: 'meat' },
  { text: 'dried meat', label: 'meat' },
  
  // Frozen Seafood
  { text: 'frozen fish', label: 'meat' },
  { text: 'frozen prawns', label: 'meat' },
  { text: 'frozen crab', label: 'meat' },
  { text: 'frozen squid', label: 'meat' },
  { text: 'frozen scallop', label: 'meat' },
  { text: 'frozen mussel', label: 'meat' },
  { text: 'frozen lobster', label: 'meat' },
  { text: 'frozen salmon', label: 'meat' },
  { text: 'frozen tuna', label: 'meat' },
  { text: 'frozen cod', label: 'meat' },
  
  // Premium & Organic
  { text: 'organic beef', label: 'meat' },
  { text: 'organic chicken', label: 'meat' },
  { text: 'organic pork', label: 'meat' },
  { text: 'grass fed beef', label: 'meat' },
  { text: 'free range chicken', label: 'meat' },
  { text: 'wild caught fish', label: 'meat' },
  { text: 'sustainable seafood', label: 'meat' },
  { text: 'premium meat', label: 'meat' },
  { text: 'aged beef', label: 'meat' },
  { text: 'dry aged beef', label: 'meat' },
  { text: 'prime cut', label: 'meat' },
  { text: 'choice grade', label: 'meat' },
  
  // Halal Certified
  { text: 'halal chicken', label: 'meat' },
  { text: 'halal beef', label: 'meat' },
  { text: 'halal lamb', label: 'meat' },
  { text: 'halal meat', label: 'meat' },
  { text: 'halal sausage', label: 'meat' },
  { text: 'halal mince', label: 'meat' },
  
  // Ready-to-Cook
  { text: 'kebab', label: 'meat' },
  { text: 'satay', label: 'meat' },
  { text: 'burger patty', label: 'meat' },
  { text: 'meatloaf', label: 'meat' },
  { text: 'stuffed chicken', label: 'meat' },
  { text: 'cordon bleu', label: 'meat' },
  { text: 'schnitzel', label: 'meat' },
  { text: 'cutlet', label: 'meat' },
  { text: 'breaded chicken', label: 'meat' },
  { text: 'tempura prawns', label: 'meat' }
];

export default meatSeafoodTrainingData;