// Training data for Pet Supplies category
// Singapore-specific pet products and supplies

export const petSuppliesTrainingData = [
  // Dog food and treats
  { text: 'dog food', label: 'pet' },
  { text: 'puppy food', label: 'pet' },
  { text: 'senior dog food', label: 'pet' },
  { text: 'dry dog food', label: 'pet' },
  { text: 'wet dog food', label: 'pet' },
  { text: 'dog treats', label: 'pet' },
  { text: 'dog biscuits', label: 'pet' },
  { text: 'dog chews', label: 'pet' },
  { text: 'dental chews', label: 'pet' },
  { text: 'rawhide', label: 'pet' },
  { text: 'dog bones', label: 'pet' },
  { text: 'training treats', label: 'pet' },
  { text: 'freeze dried treats', label: 'pet' },
  { text: 'jerky treats', label: 'pet' },
  { text: 'grain free dog food', label: 'pet' },
  
  // Cat food and treats
  { text: 'cat food', label: 'pet' },
  { text: 'kitten food', label: 'pet' },
  { text: 'senior cat food', label: 'pet' },
  { text: 'dry cat food', label: 'pet' },
  { text: 'wet cat food', label: 'pet' },
  { text: 'cat treats', label: 'pet' },
  { text: 'catnip', label: 'pet' },
  { text: 'cat grass', label: 'pet' },
  { text: 'hairball control', label: 'pet' },
  { text: 'urinary care cat food', label: 'pet' },
  { text: 'indoor cat food', label: 'pet' },
  { text: 'grain free cat food', label: 'pet' },
  { text: 'cat milk', label: 'pet' },
  { text: 'freeze dried cat treats', label: 'pet' },
  { text: 'tuna treats', label: 'pet' },
  
  // Dog accessories
  { text: 'dog collar', label: 'pet' },
  { text: 'dog leash', label: 'pet' },
  { text: 'dog harness', label: 'pet' },
  { text: 'dog bed', label: 'pet' },
  { text: 'dog blanket', label: 'pet' },
  { text: 'dog crate', label: 'pet' },
  { text: 'dog carrier', label: 'pet' },
  { text: 'dog bowl', label: 'pet' },
  { text: 'food bowl', label: 'pet' },
  { text: 'dog toy', label: 'pet' },
  
  // Cat accessories
  { text: 'cat collar', label: 'pet' },
  { text: 'cat bed', label: 'pet' },
  { text: 'cat blanket', label: 'pet' },
  { text: 'cat carrier', label: 'pet' },
  { text: 'cat bowl', label: 'pet' },
  { text: 'cat toy', label: 'pet' },
  { text: 'cat tunnel', label: 'pet' },
  { text: 'cat tree', label: 'pet' },
  { text: 'scratching post', label: 'pet' },
  { text: 'cat scratcher', label: 'pet' },
  { text: 'cat house', label: 'pet' },
  { text: 'cat cave', label: 'pet' },
  
  // Litter and hygiene
  { text: 'cat litter', label: 'pet' },
  { text: 'clumping litter', label: 'pet' },
  { text: 'biodegradable litter', label: 'pet' },
  { text: 'litter box', label: 'pet' },
  { text: 'litter scoop', label: 'pet' },
  { text: 'litter mat', label: 'pet' },
  { text: 'litter deodorizer', label: 'pet' },
  { text: 'poop bags', label: 'pet' },
  { text: 'waste bags', label: 'pet' },
  { text: 'pet wipes', label: 'pet' },
  { text: 'dog pads', label: 'pet' },
  { text: 'training pads', label: 'pet' },
  { text: 'puppy pads', label: 'pet' },
  
  // Grooming supplies
  { text: 'pet shampoo', label: 'pet' },
  { text: 'dog shampoo', label: 'pet' },
  { text: 'cat shampoo', label: 'pet' },
  { text: 'pet conditioner', label: 'pet' },
  { text: 'flea shampoo', label: 'pet' },
  { text: 'dry shampoo', label: 'pet' },
  { text: 'pet brush', label: 'pet' },
  { text: 'slicker brush', label: 'pet' },
  { text: 'pin brush', label: 'pet' },
  { text: 'deshedding tool', label: 'pet' },
  
  // Health and wellness
  { text: 'flea treatment', label: 'pet' },
  { text: 'tick treatment', label: 'pet' },
  { text: 'flea collar', label: 'pet' },
  { text: 'flea spray', label: 'pet' },
  { text: 'deworming tablets', label: 'pet' },
  
  // Small pets (hamsters, rabbits, birds)
  { text: 'hamster food', label: 'pet' },
  { text: 'rabbit food', label: 'pet' },
  { text: 'guinea pig food', label: 'pet' },
  { text: 'bird food', label: 'pet' },
  { text: 'bird seed', label: 'pet' },
  { text: 'hamster cage', label: 'pet' },
  { text: 'rabbit cage', label: 'pet' },
  { text: 'bird cage', label: 'pet' },
  { text: 'hamster wheel', label: 'pet' },
  { text: 'hay', label: 'pet' },
  { text: 'timothy hay', label: 'pet' },
  { text: 'wood shavings', label: 'pet' },
  { text: 'nesting material', label: 'pet' },
  
  // Fish and aquarium
  { text: 'fish food', label: 'pet' },
  { text: 'goldfish food', label: 'pet' },
  { text: 'tropical fish food', label: 'pet' },
  { text: 'betta food', label: 'pet' },
  { text: 'fish flakes', label: 'pet' },
  { text: 'fish pellets', label: 'pet' },
  { text: 'aquarium', label: 'pet' },
  { text: 'fish tank', label: 'pet' },
  { text: 'aquarium filter', label: 'pet' },
  { text: 'aquarium heater', label: 'pet' },
  { text: 'aquarium light', label: 'pet' },
  { text: 'gravel', label: 'pet' },
  { text: 'aquarium plants', label: 'pet' },
  { text: 'fish net', label: 'pet' },
  
  // Training and behavior
  { text: 'clicker', label: 'pet' },
  { text: 'training whistle', label: 'pet' },
  { text: 'treat pouch', label: 'pet' },
  { text: 'snuffle mat', label: 'pet' },
  { text: 'barrier spray', label: 'pet' },
  { text: 'deterrent spray', label: 'pet' },
  { text: 'bitter apple spray', label: 'pet' },
  { text: 'pheromone diffuser', label: 'pet' },
  
  // Travel and safety
  { text: 'pet gate', label: 'pet' },
  { text: 'pet stroller', label: 'pet' },
  { text: 'pet insurance', label: 'pet' },
  { text: 'pet thermometer', label: 'pet' }
];