/**
 * Training data for Rice, Noodles & Ingredients category
 * Singapore-focused rice varieties, noodles, and cooking ingredients
 */

export interface TrainingDataItem {
  text: string;
  label: string;
}

export const riceNoodlesIngredientsTrainingData: TrainingDataItem[] = [
  // Rice Varieties
  { text: 'rice', label: 'rice' },
  { text: 'jasmine rice', label: 'rice' },
  { text: 'basmati rice', label: 'rice' },
  { text: 'brown rice', label: 'rice' },
  { text: 'white rice', label: 'rice' },
  { text: 'long grain rice', label: 'rice' },
  { text: 'short grain rice', label: 'rice' },
  { text: 'medium grain rice', label: 'rice' },
  { text: 'glutinous rice', label: 'rice' },
  { text: 'sticky rice', label: 'rice' },
  { text: 'black rice', label: 'rice' },
  { text: 'red rice', label: 'rice' },
  { text: 'wild rice', label: 'rice' },
  { text: 'arborio rice', label: 'rice' },
  { text: 'sushi rice', label: 'rice' },
  { text: 'calrose rice', label: 'rice' },
  { text: 'parboiled rice', label: 'rice' },
  { text: 'instant rice', label: 'rice' },
  { text: 'minute rice', label: 'rice' },
  { text: 'organic rice', label: 'rice' },
  
  // Asian Rice Specialties
  { text: 'thai fragrant rice', label: 'rice' },
  { text: 'cambodian rice', label: 'rice' },
  { text: 'vietnamese rice', label: 'rice' },
  { text: 'japanese rice', label: 'rice' },
  { text: 'korean rice', label: 'rice' },
  { text: 'indian rice', label: 'rice' },
  { text: 'ponni rice', label: 'rice' },
  { text: 'sona masoori rice', label: 'rice' },
  { text: 'broken rice', label: 'rice' },
  { text: 'rice bran', label: 'rice' },
  
  // Fresh Noodles
  { text: 'noodles', label: 'rice' },
  { text: 'fresh noodles', label: 'rice' },
  { text: 'yellow noodles', label: 'rice' },
  { text: 'mee', label: 'rice' },
  { text: 'hokkien mee', label: 'rice' },
  { text: 'wanton noodles', label: 'rice' },
  { text: 'kway teow', label: 'rice' },
  { text: 'flat rice noodles', label: 'rice' },
  { text: 'hor fun', label: 'rice' },
  { text: 'bee hoon', label: 'rice' },
  { text: 'rice vermicelli', label: 'rice' },
  { text: 'mee sua', label: 'rice' },
  { text: 'thin noodles', label: 'rice' },
  { text: 'thick noodles', label: 'rice' },
  { text: 'laksa noodles', label: 'rice' },
  
  // Dried Noodles
  { text: 'dried noodles', label: 'rice' },
  { text: 'instant noodles', label: 'rice' },
  { text: 'maggi noodles', label: 'rice' },
  { text: 'cup noodles', label: 'rice' },
  { text: 'ramen noodles', label: 'rice' },
  { text: 'udon noodles', label: 'rice' },
  { text: 'soba noodles', label: 'rice' },
  { text: 'somen noodles', label: 'rice' },
  { text: 'shirataki noodles', label: 'rice' },
  { text: 'glass noodles', label: 'rice' },
  { text: 'cellophane noodles', label: 'rice' },
  { text: 'mung bean noodles', label: 'rice' },
  { text: 'sweet potato noodles', label: 'rice' },
  
  // Pasta
  { text: 'pasta', label: 'rice' },
  { text: 'spaghetti', label: 'rice' },
  { text: 'linguine', label: 'rice' },
  { text: 'fettuccine', label: 'rice' },
  { text: 'penne', label: 'rice' },
  { text: 'fusilli', label: 'rice' },
  { text: 'rigatoni', label: 'rice' },
  { text: 'macaroni', label: 'rice' },
  { text: 'farfalle', label: 'rice' },
  { text: 'rotini', label: 'rice' },
  { text: 'angel hair pasta', label: 'rice' },
  { text: 'lasagna sheets', label: 'rice' },
  { text: 'ravioli', label: 'rice' },
  { text: 'tortellini', label: 'rice' },
  { text: 'gnocchi', label: 'rice' },
  { text: 'orzo', label: 'rice' },
  { text: 'whole wheat pasta', label: 'rice' },
  { text: 'gluten free pasta', label: 'rice' },
  
  // Flour & Starches
  { text: 'flour', label: 'rice' },
  { text: 'all purpose flour', label: 'rice' },
  { text: 'plain flour', label: 'rice' },
  { text: 'bread flour', label: 'rice' },
  { text: 'cake flour', label: 'rice' },
  { text: 'self raising flour', label: 'rice' },
  { text: 'whole wheat flour', label: 'rice' },
  { text: 'rice flour', label: 'rice' },
  { text: 'glutinous rice flour', label: 'rice' },
  { text: 'tapioca flour', label: 'rice' },
  { text: 'potato starch', label: 'rice' },
  { text: 'corn starch', label: 'rice' },
  { text: 'arrowroot powder', label: 'rice' },
  { text: 'coconut flour', label: 'rice' },
  { text: 'almond flour', label: 'rice' },
  { text: 'chickpea flour', label: 'rice' },
  { text: 'besan', label: 'rice' },
  
  // Cooking Oils
  { text: 'cooking oil', label: 'rice' },
  { text: 'vegetable oil', label: 'rice' },
  { text: 'palm oil', label: 'rice' },
  { text: 'sunflower oil', label: 'rice' },
  { text: 'canola oil', label: 'rice' },
  { text: 'olive oil', label: 'rice' },
  { text: 'extra virgin olive oil', label: 'rice' },
  { text: 'sesame oil', label: 'rice' },
  { text: 'peanut oil', label: 'rice' },
  { text: 'coconut oil', label: 'rice' },
  { text: 'corn oil', label: 'rice' },
  { text: 'soybean oil', label: 'rice' },
  { text: 'rice bran oil', label: 'rice' },
  { text: 'avocado oil', label: 'rice' },
  { text: 'grapeseed oil', label: 'rice' },
  
  // Vinegars
  { text: 'vinegar', label: 'rice' },
  { text: 'white vinegar', label: 'rice' },
  { text: 'rice vinegar', label: 'rice' },
  { text: 'apple cider vinegar', label: 'rice' },
  { text: 'balsamic vinegar', label: 'rice' },
  { text: 'red wine vinegar', label: 'rice' },
  { text: 'white wine vinegar', label: 'rice' },
  { text: 'malt vinegar', label: 'rice' },
  { text: 'black vinegar', label: 'rice' },
  { text: 'chinese black vinegar', label: 'rice' },
  
  // Soy Sauces & Asian Condiments
  { text: 'soy sauce', label: 'rice' },
  { text: 'light soy sauce', label: 'rice' },
  { text: 'dark soy sauce', label: 'rice' },
  { text: 'thick soy sauce', label: 'rice' },
  { text: 'sweet soy sauce', label: 'rice' },
  { text: 'kecap manis', label: 'rice' },
  { text: 'tamari', label: 'rice' },
  { text: 'fish sauce', label: 'rice' },
  { text: 'oyster sauce', label: 'rice' },
  { text: 'hoisin sauce', label: 'rice' },
  { text: 'teriyaki sauce', label: 'rice' },
  { text: 'miso paste', label: 'rice' },
  { text: 'mirin', label: 'rice' },
  { text: 'sake', label: 'rice' },
  { text: 'shaoxing wine', label: 'rice' },
  
  // Spices & Seasonings
  { text: 'salt', label: 'rice' },
  { text: 'sea salt', label: 'rice' },
  { text: 'rock salt', label: 'rice' },
  { text: 'himalayan salt', label: 'rice' },
  { text: 'black pepper', label: 'rice' },
  { text: 'white pepper', label: 'rice' },
  { text: 'ground pepper', label: 'rice' },
  { text: 'peppercorns', label: 'rice' },
  { text: 'chili powder', label: 'rice' },
  { text: 'paprika', label: 'rice' },
  { text: 'cayenne pepper', label: 'rice' },
  { text: 'turmeric powder', label: 'rice' },
  { text: 'coriander powder', label: 'rice' },
  { text: 'cumin powder', label: 'rice' },
  { text: 'fennel powder', label: 'rice' },
  { text: 'cardamom', label: 'rice' },
  { text: 'cinnamon', label: 'rice' },
  { text: 'star anise', label: 'rice' },
  { text: 'cloves', label: 'rice' },
  { text: 'nutmeg', label: 'rice' },
  
  // Asian Spice Mixes
  { text: 'five spice powder', label: 'rice' },
  { text: 'curry powder', label: 'rice' },
  { text: 'garam masala', label: 'rice' },
  { text: 'tandoori masala', label: 'rice' },
  { text: 'biryani masala', label: 'rice' },
  { text: 'meat curry powder', label: 'rice' },
  { text: 'fish curry powder', label: 'rice' },
  { text: 'rendang paste', label: 'rice' },
  { text: 'laksa paste', label: 'rice' },
  { text: 'tom yum paste', label: 'rice' },
  { text: 'green curry paste', label: 'rice' },
  { text: 'red curry paste', label: 'rice' },
  
  // Dried Beans & Legumes
  { text: 'beans', label: 'rice' },
  { text: 'black beans', label: 'rice' },
  { text: 'kidney beans', label: 'rice' },
  { text: 'chickpeas', label: 'rice' },
  { text: 'lentils', label: 'rice' },
  { text: 'red lentils', label: 'rice' },
  { text: 'green lentils', label: 'rice' },
  { text: 'yellow lentils', label: 'rice' },
  { text: 'split peas', label: 'rice' },
  { text: 'mung beans', label: 'rice' },
  { text: 'adzuki beans', label: 'rice' },
  { text: 'black eyed peas', label: 'rice' },
  { text: 'lima beans', label: 'rice' },
  { text: 'navy beans', label: 'rice' },
  { text: 'pinto beans', label: 'rice' },
  
  // Canned Goods
  { text: 'canned beans', label: 'rice' },
  { text: 'canned tomatoes', label: 'rice' },
  { text: 'tomato paste', label: 'rice' },
  { text: 'tomato sauce', label: 'rice' },
  { text: 'coconut milk', label: 'rice' },
  { text: 'coconut cream', label: 'rice' },
  { text: 'evaporated milk', label: 'rice' },
  { text: 'condensed milk', label: 'rice' },
  { text: 'chicken stock', label: 'rice' },
  { text: 'vegetable stock', label: 'rice' },
  { text: 'beef stock', label: 'rice' },
  { text: 'fish stock', label: 'rice' },
  
  // Sugar & Sweeteners
  { text: 'sugar', label: 'rice' },
  { text: 'white sugar', label: 'rice' },
  { text: 'brown sugar', label: 'rice' },
  { text: 'raw sugar', label: 'rice' },
  { text: 'caster sugar', label: 'rice' },
  { text: 'icing sugar', label: 'rice' },
  { text: 'powdered sugar', label: 'rice' },
  { text: 'palm sugar', label: 'rice' },
  { text: 'coconut sugar', label: 'rice' },
  { text: 'rock sugar', label: 'rice' },
  { text: 'honey', label: 'rice' },
  { text: 'maple syrup', label: 'rice' },
  { text: 'golden syrup', label: 'rice' },
  { text: 'corn syrup', label: 'rice' },
  { text: 'molasses', label: 'rice' },
  
  // Baking Ingredients
  { text: 'baking powder', label: 'rice' },
  { text: 'baking soda', label: 'rice' },
  { text: 'yeast', label: 'rice' },
  { text: 'active dry yeast', label: 'rice' },
  { text: 'instant yeast', label: 'rice' },
  { text: 'vanilla extract', label: 'rice' },
  { text: 'almond extract', label: 'rice' },
  { text: 'food coloring', label: 'rice' },
  { text: 'gelatin', label: 'rice' },
  { text: 'agar agar', label: 'rice' },
  { text: 'cream of tartar', label: 'rice' },
  
  // Nuts & Seeds
  { text: 'almonds', label: 'rice' },
  { text: 'cashews', label: 'rice' },
  { text: 'peanuts', label: 'rice' },
  { text: 'walnuts', label: 'rice' },
  { text: 'pistachios', label: 'rice' },
  { text: 'hazelnuts', label: 'rice' },
  { text: 'macadamia nuts', label: 'rice' },
  { text: 'pine nuts', label: 'rice' },
  { text: 'sesame seeds', label: 'rice' },
  { text: 'sunflower seeds', label: 'rice' },
  { text: 'pumpkin seeds', label: 'rice' },
  { text: 'chia seeds', label: 'rice' },
  { text: 'flax seeds', label: 'rice' },
  { text: 'poppy seeds', label: 'rice' },
  
  // Dried Fruits
  { text: 'raisins', label: 'rice' },
  { text: 'dates', label: 'rice' },
  { text: 'dried apricots', label: 'rice' },
  { text: 'dried figs', label: 'rice' },
  { text: 'dried cranberries', label: 'rice' },
  { text: 'dried mango', label: 'rice' },
  { text: 'dried pineapple', label: 'rice' },
  { text: 'prunes', label: 'rice' },
  { text: 'sultanas', label: 'rice' },
  { text: 'currants', label: 'rice' },
  
  // Asian Dried Ingredients
  { text: 'dried mushrooms', label: 'rice' },
  { text: 'dried shiitake', label: 'rice' },
  { text: 'dried seaweed', label: 'rice' },
  { text: 'dried kelp', label: 'rice' },
  { text: 'dried shrimp', label: 'rice' },
  { text: 'dried scallops', label: 'rice' },
  { text: 'dried fish', label: 'rice' },
  { text: 'dried squid', label: 'rice' },
  { text: 'bird nest', label: 'rice' },
  { text: 'shark fin', label: 'rice' },
  
  // Pickled & Preserved
  { text: 'pickled vegetables', label: 'rice' },
  { text: 'pickled mustard greens', label: 'rice' },
  { text: 'preserved vegetables', label: 'rice' },
  { text: 'salted vegetables', label: 'rice' },
  { text: 'kimchi', label: 'rice' },
  { text: 'sauerkraut', label: 'rice' },
  { text: 'pickled ginger', label: 'rice' },
  { text: 'pickled radish', label: 'rice' },
  
  // Specialty Ingredients
  { text: 'tamarind paste', label: 'rice' },
  { text: 'shrimp paste', label: 'rice' },
  { text: 'belacan', label: 'rice' },
  { text: 'fermented black beans', label: 'rice' },
  { text: 'preserved mustard greens', label: 'rice' },
  { text: 'bamboo shoots', label: 'rice' },
  { text: 'water chestnuts', label: 'rice' },
  { text: 'lotus root', label: 'rice' },
  { text: 'wood ear mushrooms', label: 'rice' },
  { text: 'century eggs', label: 'rice' },
  
  // Instant Mixes
  { text: 'pancake mix', label: 'rice' },
  { text: 'cake mix', label: 'rice' },
  { text: 'muffin mix', label: 'rice' },
  { text: 'bread mix', label: 'rice' },
  { text: 'curry mix', label: 'rice' },
  { text: 'soup mix', label: 'rice' },
  { text: 'seasoning mix', label: 'rice' },
  { text: 'marinade mix', label: 'rice' },
  { text: 'coating mix', label: 'rice' },
  { text: 'tempura mix', label: 'rice' }
];

export default riceNoodlesIngredientsTrainingData;