const riceNoodlesIngredientsData = [
  { text: 'rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'white rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'brown rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'jasmine rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'basmati rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'long grain rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'short grain rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'medium grain rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'arborio rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'wild rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'black rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'red rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'sticky rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'glutinous rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'sushi rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'risotto rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'paella rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'bomba rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'calrose rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'carolina rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'texmati rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'wehani rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'forbidden rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'purple rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'cargo rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'parboiled rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'converted rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'instant rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'minute rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'precooked rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice starch', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice bran', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice vinegar', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice wine', label: 'Rice, Noodles & Ingredients' },
  { text: 'sake', label: 'Rice, Noodles & Ingredients' },
  { text: 'mirin', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice milk', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice paper', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice crackers', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice cakes', label: 'Rice, Noodles & Ingredients' },
  { text: 'puffed rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice cereal', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice krispies', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice pudding', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice porridge', label: 'Rice, Noodles & Ingredients' },
  { text: 'congee', label: 'Rice, Noodles & Ingredients' },
  { text: 'jook', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice gruel', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice soup', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice salad', label: 'Rice, Noodles & Ingredients' },
  { text: 'fried rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'steamed rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'boiled rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'baked rice', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice pilaf', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice risotto', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice paella', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice jambalaya', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice biryani', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice curry', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice stir fry', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice bowl', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice burrito', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice wrap', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice roll', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice ball', label: 'Rice, Noodles & Ingredients' },
  { text: 'onigiri', label: 'Rice, Noodles & Ingredients' },
  { text: 'musubi', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice triangle', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice sandwich', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice burger', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice bun', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice bread', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice vermicelli', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice stick noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'pad thai noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'pho noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'bun noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'banh pho', label: 'Rice, Noodles & Ingredients' },
  { text: 'fresh rice noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'dried rice noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'wide rice noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'thin rice noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'flat rice noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'round rice noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'thick rice noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'angel hair rice noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice sheets', label: 'Rice, Noodles & Ingredients' },
  { text: 'rice wrappers', label: 'Rice, Noodles & Ingredients' },
  { text: 'spring roll wrappers', label: 'Rice, Noodles & Ingredients' },
  { text: 'summer roll wrappers', label: 'Rice, Noodles & Ingredients' },
  { text: 'vietnamese rice paper', label: 'Rice, Noodles & Ingredients' },
  { text: 'thai rice paper', label: 'Rice, Noodles & Ingredients' },
  { text: 'chinese rice paper', label: 'Rice, Noodles & Ingredients' },
  { text: 'noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'wheat noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'egg noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'pasta', label: 'Rice, Noodles & Ingredients' },
  { text: 'spaghetti', label: 'Rice, Noodles & Ingredients' },
  { text: 'linguine', label: 'Rice, Noodles & Ingredients' },
  { text: 'fettuccine', label: 'Rice, Noodles & Ingredients' },
  { text: 'angel hair pasta', label: 'Rice, Noodles & Ingredients' },
  { text: 'capellini', label: 'Rice, Noodles & Ingredients' },
  { text: 'vermicelli', label: 'Rice, Noodles & Ingredients' },
  { text: 'penne', label: 'Rice, Noodles & Ingredients' },
  { text: 'rigatoni', label: 'Rice, Noodles & Ingredients' },
  { text: 'fusilli', label: 'Rice, Noodles & Ingredients' },
  { text: 'rotini', label: 'Rice, Noodles & Ingredients' },
  { text: 'farfalle', label: 'Rice, Noodles & Ingredients' },
  { text: 'bow tie pasta', label: 'Rice, Noodles & Ingredients' },
  { text: 'conchiglie', label: 'Rice, Noodles & Ingredients' },
  { text: 'macaroni', label: 'Rice, Noodles & Ingredients' },
  { text: 'elbow macaroni', label: 'Rice, Noodles & Ingredients' },
  { text: 'ziti', label: 'Rice, Noodles & Ingredients' },
  { text: 'mostaccioli', label: 'Rice, Noodles & Ingredients' },
  { text: 'cavatappi', label: 'Rice, Noodles & Ingredients' },
  { text: 'gemelli', label: 'Rice, Noodles & Ingredients' },
  { text: 'radiatori', label: 'Rice, Noodles & Ingredients' },
  { text: 'campanelle', label: 'Rice, Noodles & Ingredients' },
  { text: 'orecchiette', label: 'Rice, Noodles & Ingredients' },
  { text: 'cavatelli', label: 'Rice, Noodles & Ingredients' },
  { text: 'gnocchi', label: 'Rice, Noodles & Ingredients' },
  { text: 'potato gnocchi', label: 'Rice, Noodles & Ingredients' },
  { text: 'ricotta gnocchi', label: 'Rice, Noodles & Ingredients' },
  { text: 'spinach gnocchi', label: 'Rice, Noodles & Ingredients' },
  { text: 'pumpkin gnocchi', label: 'Rice, Noodles & Ingredients' },
  { text: 'sweet potato gnocchi', label: 'Rice, Noodles & Ingredients' },
  { text: 'ravioli', label: 'Rice, Noodles & Ingredients' },
  { text: 'cheese ravioli', label: 'Rice, Noodles & Ingredients' },
  { text: 'meat ravioli', label: 'Rice, Noodles & Ingredients' },
  { text: 'spinach ravioli', label: 'Rice, Noodles & Ingredients' },
  { text: 'mushroom ravioli', label: 'Rice, Noodles & Ingredients' },
  { text: 'lobster ravioli', label: 'Rice, Noodles & Ingredients' },
  { text: 'crab ravioli', label: 'Rice, Noodles & Ingredients' },
  { text: 'butternut squash ravioli', label: 'Rice, Noodles & Ingredients' },
  { text: 'pumpkin ravioli', label: 'Rice, Noodles & Ingredients' },
  { text: 'tortellini', label: 'Rice, Noodles & Ingredients' },
  { text: 'cheese tortellini', label: 'Rice, Noodles & Ingredients' },
  { text: 'meat tortellini', label: 'Rice, Noodles & Ingredients' },
  { text: 'spinach tortellini', label: 'Rice, Noodles & Ingredients' },
  { text: 'prosciutto tortellini', label: 'Rice, Noodles & Ingredients' },
  { text: 'cappelletti', label: 'Rice, Noodles & Ingredients' },
  { text: 'agnolotti', label: 'Rice, Noodles & Ingredients' },
  { text: 'culurgiones', label: 'Rice, Noodles & Ingredients' },
  { text: 'pansotti', label: 'Rice, Noodles & Ingredients' },
  { text: 'casoncelli', label: 'Rice, Noodles & Ingredients' },
  { text: 'cappellacci', label: 'Rice, Noodles & Ingredients' },
  { text: 'tortelli', label: 'Rice, Noodles & Ingredients' },
  { text: 'mezzelune', label: 'Rice, Noodles & Ingredients' },
  { text: 'fagottini', label: 'Rice, Noodles & Ingredients' },
  { text: 'sacchettini', label: 'Rice, Noodles & Ingredients' },
  { text: 'triangoli', label: 'Rice, Noodles & Ingredients' },
  { text: 'quadrelli', label: 'Rice, Noodles & Ingredients' },
  { text: 'rotolini', label: 'Rice, Noodles & Ingredients' },
  { text: 'involtini', label: 'Rice, Noodles & Ingredients' },
  { text: 'cannelloni', label: 'Rice, Noodles & Ingredients' },
  { text: 'manicotti', label: 'Rice, Noodles & Ingredients' },
  { text: 'lasagne', label: 'Rice, Noodles & Ingredients' },
  { text: 'lasagna sheets', label: 'Rice, Noodles & Ingredients' },
  { text: 'lasagnette', label: 'Rice, Noodles & Ingredients' },
  { text: 'mafaldine', label: 'Rice, Noodles & Ingredients' },
  { text: 'reginette', label: 'Rice, Noodles & Ingredients' },
  { text: 'pappardelle', label: 'Rice, Noodles & Ingredients' },
  { text: 'tagliatelle', label: 'Rice, Noodles & Ingredients' },
  { text: 'tagliolini', label: 'Rice, Noodles & Ingredients' },
  { text: 'tajarin', label: 'Rice, Noodles & Ingredients' },
  { text: 'bavette', label: 'Rice, Noodles & Ingredients' },
  { text: 'linguettine', label: 'Rice, Noodles & Ingredients' },
  { text: 'trenette', label: 'Rice, Noodles & Ingredients' },
  { text: 'bucatini', label: 'Rice, Noodles & Ingredients' },
  { text: 'perciatelli', label: 'Rice, Noodles & Ingredients' },
  { text: 'bigoli', label: 'Rice, Noodles & Ingredients' },
  { text: 'pici', label: 'Rice, Noodles & Ingredients' },
  { text: 'tonnarelli', label: 'Rice, Noodles & Ingredients' },
  { text: 'spaghettini', label: 'Rice, Noodles & Ingredients' },
  { text: 'spaghettoni', label: 'Rice, Noodles & Ingredients' },
  { text: 'lumache', label: 'Rice, Noodles & Ingredients' },
  { text: 'pipe rigate', label: 'Rice, Noodles & Ingredients' },
  { text: 'paccheri', label: 'Rice, Noodles & Ingredients' },
  { text: 'calamarata', label: 'Rice, Noodles & Ingredients' },
  { text: 'garganelli', label: 'Rice, Noodles & Ingredients' },
  { text: 'strozzapreti', label: 'Rice, Noodles & Ingredients' },
  { text: 'trofie', label: 'Rice, Noodles & Ingredients' },
  { text: 'busiate', label: 'Rice, Noodles & Ingredients' },
  { text: 'casarecce', label: 'Rice, Noodles & Ingredients' },
  { text: 'malloreddus', label: 'Rice, Noodles & Ingredients' },
  { text: 'lorighittas', label: 'Rice, Noodles & Ingredients' },
  { text: 'fregola', label: 'Rice, Noodles & Ingredients' },
  { text: 'couscous', label: 'Rice, Noodles & Ingredients' },
  { text: 'israeli couscous', label: 'Rice, Noodles & Ingredients' },
  { text: 'pearl couscous', label: 'Rice, Noodles & Ingredients' },
  { text: 'moroccan couscous', label: 'Rice, Noodles & Ingredients' },
  { text: 'lebanese couscous', label: 'Rice, Noodles & Ingredients' },
  { text: 'whole wheat couscous', label: 'Rice, Noodles & Ingredients' },
  { text: 'tricolor couscous', label: 'Rice, Noodles & Ingredients' },
  { text: 'flavored couscous', label: 'Rice, Noodles & Ingredients' },
  { text: 'instant couscous', label: 'Rice, Noodles & Ingredients' },
  { text: 'orzo', label: 'Rice, Noodles & Ingredients' },
  { text: 'ditalini', label: 'Rice, Noodles & Ingredients' },
  { text: 'tubetti', label: 'Rice, Noodles & Ingredients' },
  { text: 'ditali', label: 'Rice, Noodles & Ingredients' },
  { text: 'maccheroni', label: 'Rice, Noodles & Ingredients' },
  { text: 'asian noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'ramen noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'instant ramen', label: 'Rice, Noodles & Ingredients' },
  { text: 'fresh ramen', label: 'Rice, Noodles & Ingredients' },
  { text: 'dried ramen', label: 'Rice, Noodles & Ingredients' },
  { text: 'udon noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'fresh udon', label: 'Rice, Noodles & Ingredients' },
  { text: 'dried udon', label: 'Rice, Noodles & Ingredients' },
  { text: 'frozen udon', label: 'Rice, Noodles & Ingredients' },
  { text: 'soba noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'buckwheat noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'fresh soba', label: 'Rice, Noodles & Ingredients' },
  { text: 'dried soba', label: 'Rice, Noodles & Ingredients' },
  { text: 'green tea soba', label: 'Rice, Noodles & Ingredients' },
  { text: 'cha soba', label: 'Rice, Noodles & Ingredients' },
  { text: 'somen noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'hiyamugi noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'shirataki noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'konjac noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'miracle noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'kelp noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'seaweed noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'glass noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'cellophane noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'bean thread noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'mung bean noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'sweet potato noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'korean sweet potato noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'naengmyeon', label: 'Rice, Noodles & Ingredients' },
  { text: 'cold buckwheat noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'lo mein noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'chow mein noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'crispy noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'fried noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'wonton noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'dumpling noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'hand pulled noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'lamian', label: 'Rice, Noodles & Ingredients' },
  { text: 'dan dan noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'sesame noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'peanut noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'cold noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'hot noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'spicy noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'mild noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'soup noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'dry noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'stir fried noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'boiled noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'steamed noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'baked noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'grilled noodles', label: 'Rice, Noodles & Ingredients' },
  { text: 'flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'all purpose flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'bread flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'cake flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'pastry flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'self rising flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'whole wheat flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'white flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'unbleached flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'bleached flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'organic flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'gluten free flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'almond flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'coconut flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'oat flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'barley flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'rye flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'spelt flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'buckwheat flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'quinoa flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'amaranth flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'teff flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'millet flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'sorghum flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'tapioca flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'cassava flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'potato flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'sweet potato flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'corn flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'cornmeal', label: 'Rice, Noodles & Ingredients' },
  { text: 'cornstarch', label: 'Rice, Noodles & Ingredients' },
  { text: 'arrowroot flour', label: 'Rice, Noodles & Ingredients' },
  { text: 'potato starch', label: 'Rice, Noodles & Ingredients' },
  { text: 'tapioca starch', label: 'Rice, Noodles & Ingredients' },
  { text: 'wheat starch', label: 'Rice, Noodles & Ingredients' },
  { text: 'vital wheat gluten', label: 'Rice, Noodles & Ingredients' },
  { text: 'xanthan gum', label: 'Rice, Noodles & Ingredients' },
  { text: 'guar gum', label: 'Rice, Noodles & Ingredients' },
  { text: 'psyllium husk', label: 'Rice, Noodles & Ingredients' },
  { text: 'baking powder', label: 'Rice, Noodles & Ingredients' },
  { text: 'baking soda', label: 'Rice, Noodles & Ingredients' },
  { text: 'cream of tartar', label: 'Rice, Noodles & Ingredients' },
  { text: 'yeast', label: 'Rice, Noodles & Ingredients' },
  { text: 'active dry yeast', label: 'Rice, Noodles & Ingredients' },
  { text: 'instant yeast', label: 'Rice, Noodles & Ingredients' },
  { text: 'bread machine yeast', label: 'Rice, Noodles & Ingredients' },
  { text: 'fresh yeast', label: 'Rice, Noodles & Ingredients' },
  { text: 'compressed yeast', label: 'Rice, Noodles & Ingredients' },
  { text: 'nutritional yeast', label: 'Rice, Noodles & Ingredients' },
  { text: 'brewers yeast', label: 'Rice, Noodles & Ingredients' },
  { text: 'sourdough starter', label: 'Rice, Noodles & Ingredients' },
  { text: 'mother dough', label: 'Rice, Noodles & Ingredients' },
  { text: 'levain', label: 'Rice, Noodles & Ingredients' },
  { text: 'salt', label: 'Rice, Noodles & Ingredients' },
  { text: 'table salt', label: 'Rice, Noodles & Ingredients' },
  { text: 'sea salt', label: 'Rice, Noodles & Ingredients' },
  { text: 'kosher salt', label: 'Rice, Noodles & Ingredients' },
  { text: 'rock salt', label: 'Rice, Noodles & Ingredients' },
  { text: 'himalayan salt', label: 'Rice, Noodles & Ingredients' },
  { text: 'pink salt', label: 'Rice, Noodles & Ingredients' },
  { text: 'black salt', label: 'Rice, Noodles & Ingredients' },
  { text: 'flaky salt', label: 'Rice, Noodles & Ingredients' },
  { text: 'finishing salt', label: 'Rice, Noodles & Ingredients' },
  { text: 'flavored salt', label: 'Rice, Noodles & Ingredients' },
  { text: 'garlic salt', label: 'Rice, Noodles & Ingredients' },
  { text: 'onion salt', label: 'Rice, Noodles & Ingredients' },
  { text: 'celery salt', label: 'Rice, Noodles & Ingredients' },
  { text: 'seasoned salt', label: 'Rice, Noodles & Ingredients' },
  { text: 'smoked salt', label: 'Rice, Noodles & Ingredients' },
  { text: 'truffle salt', label: 'Rice, Noodles & Ingredients' },
  { text: 'herb salt', label: 'Rice, Noodles & Ingredients' },
  { text: 'sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'white sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'granulated sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'caster sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'superfine sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'confectioners sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'powdered sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'icing sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'brown sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'light brown sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'dark brown sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'raw sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'turbinado sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'demerara sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'muscovado sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'coconut sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'palm sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'jaggery', label: 'Rice, Noodles & Ingredients' },
  { text: 'panela', label: 'Rice, Noodles & Ingredients' },
  { text: 'piloncillo', label: 'Rice, Noodles & Ingredients' },
  { text: 'rock sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'crystal sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'cube sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'lump sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'pearl sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'sanding sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'decorating sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'colored sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'vanilla sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'cinnamon sugar', label: 'Rice, Noodles & Ingredients' },
  { text: 'honey', label: 'Rice, Noodles & Ingredients' },
  { text: 'raw honey', label: 'Rice, Noodles & Ingredients' },
  { text: 'wildflower honey', label: 'Rice, Noodles & Ingredients' },
  { text: 'clover honey', label: 'Rice, Noodles & Ingredients' },
  { text: 'orange blossom honey', label: 'Rice, Noodles & Ingredients' },
  { text: 'acacia honey', label: 'Rice, Noodles & Ingredients' },
  { text: 'manuka honey', label: 'Rice, Noodles & Ingredients' },
  { text: 'buckwheat honey', label: 'Rice, Noodles & Ingredients' },
  { text: 'lavender honey', label: 'Rice, Noodles & Ingredients' },
  { text: 'eucalyptus honey', label: 'Rice, Noodles & Ingredients' },
  { text: 'tupelo honey', label: 'Rice, Noodles & Ingredients' },
  { text: 'sage honey', label: 'Rice, Noodles & Ingredients' },
  { text: 'basswood honey', label: 'Rice, Noodles & Ingredients' },
  { text: 'linden honey', label: 'Rice, Noodles & Ingredients' },
  { text: 'chestnut honey', label: 'Rice, Noodles & Ingredients' },
  { text: 'heather honey', label: 'Rice, Noodles & Ingredients' },
  { text: 'thyme honey', label: 'Rice, Noodles & Ingredients' },
  { text: 'rosemary honey', label: 'Rice, Noodles & Ingredients' },
  { text: 'creamed honey', label: 'Rice, Noodles & Ingredients' },
  { text: 'whipped honey', label: 'Rice, Noodles & Ingredients' },
  { text: 'crystallized honey', label: 'Rice, Noodles & Ingredients' },
  { text: 'liquid honey', label: 'Rice, Noodles & Ingredients' },
  { text: 'comb honey', label: 'Rice, Noodles & Ingredients' },
  { text: 'honeycomb', label: 'Rice, Noodles & Ingredients' },
  { text: 'maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'pure maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'grade a maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'grade b maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'dark maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'light maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'amber maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'golden maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'robust maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'delicate maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'organic maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'canadian maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'vermont maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'new hampshire maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'maine maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'new york maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'wisconsin maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'michigan maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'pennsylvania maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'ohio maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'connecticut maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'massachusetts maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'rhode island maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'quebec maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'ontario maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'new brunswick maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'nova scotia maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'prince edward island maple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'corn syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'light corn syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'dark corn syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'high fructose corn syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'golden syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'treacle', label: 'Rice, Noodles & Ingredients' },
  { text: 'molasses', label: 'Rice, Noodles & Ingredients' },
  { text: 'blackstrap molasses', label: 'Rice, Noodles & Ingredients' },
  { text: 'light molasses', label: 'Rice, Noodles & Ingredients' },
  { text: 'dark molasses', label: 'Rice, Noodles & Ingredients' },
  { text: 'unsulfured molasses', label: 'Rice, Noodles & Ingredients' },
  { text: 'sulfured molasses', label: 'Rice, Noodles & Ingredients' },
  { text: 'agave syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'agave nectar', label: 'Rice, Noodles & Ingredients' },
  { text: 'blue agave syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'light agave', label: 'Rice, Noodles & Ingredients' },
  { text: 'dark agave', label: 'Rice, Noodles & Ingredients' },
  { text: 'raw agave', label: 'Rice, Noodles & Ingredients' },
  { text: 'organic agave', label: 'Rice, Noodles & Ingredients' },
  { text: 'brown rice syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'barley malt syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'date syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'fig syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'pomegranate syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'pomegranate molasses', label: 'Rice, Noodles & Ingredients' },
  { text: 'elderflower syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'simple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'vanilla syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'caramel syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'chocolate syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'strawberry syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'raspberry syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'blueberry syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'blackberry syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'cherry syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'peach syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'apricot syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'apple syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'pear syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'grape syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'orange syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'lemon syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'lime syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'grapefruit syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'coconut syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'almond syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'hazelnut syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'walnut syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'pecan syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'pistachio syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'macadamia syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'cashew syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'peanut syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'sesame syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'tahini syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'sunflower syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'pumpkin seed syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'flax seed syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'chia seed syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'hemp seed syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'poppy seed syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'mustard seed syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'caraway seed syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'fennel seed syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'anise seed syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'star anise syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'cardamom syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'cinnamon syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'clove syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'nutmeg syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'allspice syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'ginger syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'turmeric syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'black pepper syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'white pepper syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'pink pepper syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'green pepper syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'sichuan pepper syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'long pepper syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'cubeb pepper syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'grains of paradise syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'pink peppercorn syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'juniper berry syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'bay leaf syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'thyme syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'rosemary syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'sage syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'oregano syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'marjoram syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'basil syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'mint syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'spearmint syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'peppermint syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'chocolate mint syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'apple mint syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'orange mint syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'pineapple mint syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'ginger mint syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'lemon mint syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'lime mint syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'grapefruit mint syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'lavender syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'chamomile syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'hibiscus syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'rose syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'violet syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'jasmine syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'elderflower syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'lemon balm syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'lemon verbena syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'lemon thyme syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'lemon basil syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'lime basil syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'thai basil syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'holy basil syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'purple basil syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'cinnamon basil syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'anise basil syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'clove basil syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'camphor basil syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'african blue basil syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'cardinal basil syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'dark opal basil syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'genovese basil syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'greek basil syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'lettuce leaf basil syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'mammoth basil syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'napoletano basil syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'piccolo fino verde basil syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'red rubin basil syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'spicy globe basil syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'sweet basil syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'tree basil syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'wild basil syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'yemenite basil syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'zaatar syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'sumac syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'pomegranate molasses syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'tamarind syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'date molasses syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'grape molasses syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'carob syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'locust bean syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'mesquite syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'yacon syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'lucuma syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'monk fruit syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'stevia syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'erythritol syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'xylitol syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'sorbitol syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'mannitol syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'maltitol syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'isomalt syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'lactitol syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'glycerol syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'glycerin syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'vegetable glycerin syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'propylene glycol syrup', label: 'Rice, Noodles & Ingredients' },
  { text: 'ethylene glycol syrup', label: 'Rice, Noodles & Ingredients' }
];

export default riceNoodlesIngredientsData;