/**
 * Training data for Snacks & Confectionery category
 * Singapore-focused snacks, sweets, and confectionery items
 */

export interface TrainingDataItem {
  text: string;
  label: string;
}

export const snacksConfectioneryTrainingData: TrainingDataItem[] = [
  // Chips & Crisps
  { text: 'chips', label: 'snacks' },
  { text: 'potato chips', label: 'snacks' },
  { text: 'crisps', label: 'snacks' },
  { text: 'corn chips', label: 'snacks' },
  { text: 'tortilla chips', label: 'snacks' },
  { text: 'nacho chips', label: 'snacks' },
  { text: 'pringles', label: 'snacks' },
  { text: 'lays chips', label: 'snacks' },
  { text: 'kettle chips', label: 'snacks' },
  { text: 'sweet potato chips', label: 'snacks' },
  { text: 'vegetable chips', label: 'snacks' },
  { text: 'banana chips', label: 'snacks' },
  { text: 'cassava chips', label: 'snacks' },
  { text: 'tapioca chips', label: 'snacks' },
  { text: 'prawn crackers', label: 'snacks' },
  { text: 'keropok', label: 'snacks' },
  { text: 'fish crackers', label: 'snacks' },
  { text: 'rice crackers', label: 'snacks' },
  
  // Nuts & Seeds
  { text: 'nuts', label: 'snacks' },
  { text: 'mixed nuts', label: 'snacks' },
  { text: 'peanuts', label: 'snacks' },
  { text: 'roasted peanuts', label: 'snacks' },
  { text: 'salted peanuts', label: 'snacks' },
  { text: 'cashew nuts', label: 'snacks' },
  { text: 'almonds', label: 'snacks' },
  { text: 'walnuts', label: 'snacks' },
  { text: 'pistachios', label: 'snacks' },
  { text: 'macadamia nuts', label: 'snacks' },
  { text: 'hazelnuts', label: 'snacks' },
  { text: 'pine nuts', label: 'snacks' },
  { text: 'sunflower seeds', label: 'snacks' },
  { text: 'pumpkin seeds', label: 'snacks' },
  { text: 'watermelon seeds', label: 'snacks' },
  { text: 'trail mix', label: 'snacks' },
  { text: 'nut mix', label: 'snacks' },
  
  // Crackers & Biscuits
  { text: 'crackers', label: 'snacks' },
  { text: 'cream crackers', label: 'snacks' },
  { text: 'water crackers', label: 'snacks' },
  { text: 'cheese crackers', label: 'snacks' },
  { text: 'wheat crackers', label: 'snacks' },
  { text: 'saltine crackers', label: 'snacks' },
  { text: 'graham crackers', label: 'snacks' },
  { text: 'biscuits', label: 'snacks' },
  { text: 'digestive biscuits', label: 'snacks' },
  { text: 'marie biscuits', label: 'snacks' },
  { text: 'rich tea biscuits', label: 'snacks' },
  { text: 'oatmeal biscuits', label: 'snacks' },
  { text: 'chocolate biscuits', label: 'snacks' },
  { text: 'sandwich biscuits', label: 'snacks' },
  { text: 'oreo cookies', label: 'snacks' },
  
  // Cookies
  { text: 'cookies', label: 'snacks' },
  { text: 'chocolate chip cookies', label: 'snacks' },
  { text: 'oatmeal cookies', label: 'snacks' },
  { text: 'sugar cookies', label: 'snacks' },
  { text: 'gingerbread cookies', label: 'snacks' },
  { text: 'shortbread cookies', label: 'snacks' },
  { text: 'butter cookies', label: 'snacks' },
  { text: 'fortune cookies', label: 'snacks' },
  { text: 'wafer cookies', label: 'snacks' },
  { text: 'coconut cookies', label: 'snacks' },
  { text: 'peanut butter cookies', label: 'snacks' },
  { text: 'almond cookies', label: 'snacks' },
  { text: 'sesame cookies', label: 'snacks' },
  
  // Chocolate & Candy
  { text: 'chocolate', label: 'snacks' },
  { text: 'milk chocolate', label: 'snacks' },
  { text: 'dark chocolate', label: 'snacks' },
  { text: 'white chocolate', label: 'snacks' },
  { text: 'chocolate bar', label: 'snacks' },
  { text: 'chocolate chips', label: 'snacks' },
  { text: 'chocolate wafer', label: 'snacks' },
  { text: 'kit kat', label: 'snacks' },
  { text: 'snickers', label: 'snacks' },
  { text: 'mars bar', label: 'snacks' },
  { text: 'twix', label: 'snacks' },
  { text: 'toblerone', label: 'snacks' },
  { text: 'ferrero rocher', label: 'snacks' },
  { text: 'lindt chocolate', label: 'snacks' },
  { text: 'godiva chocolate', label: 'snacks' },
  
  // Candy & Sweets
  { text: 'candy', label: 'snacks' },
  { text: 'sweets', label: 'snacks' },
  { text: 'lollipop', label: 'snacks' },
  { text: 'hard candy', label: 'snacks' },
  { text: 'soft candy', label: 'snacks' },
  { text: 'gummy bears', label: 'snacks' },
  { text: 'gummy candy', label: 'snacks' },
  { text: 'jelly beans', label: 'snacks' },
  { text: 'marshmallow', label: 'snacks' },
  { text: 'toffee', label: 'snacks' },
  { text: 'caramel', label: 'snacks' },
  { text: 'fudge', label: 'snacks' },
  { text: 'nougat', label: 'snacks' },
  { text: 'mints', label: 'snacks' },
  { text: 'mentos', label: 'snacks' },
  { text: 'tic tac', label: 'snacks' },
  
  // Asian Sweets
  { text: 'white rabbit candy', label: 'snacks' },
  { text: 'hi-chew', label: 'snacks' },
  { text: 'pocky', label: 'snacks' },
  { text: 'pretz', label: 'snacks' },
  { text: 'yan yan', label: 'snacks' },
  { text: 'koala march', label: 'snacks' },
  { text: 'hello panda', label: 'snacks' },
  { text: 'meiji chocolate', label: 'snacks' },
  { text: 'morinaga candy', label: 'snacks' },
  { text: 'kasugai gummy', label: 'snacks' },
  { text: 'pineapple cake', label: 'snacks' },
  { text: 'mochi', label: 'snacks' },
  { text: 'daifuku', label: 'snacks' },
  { text: 'dorayaki', label: 'snacks' },
  { text: 'taiyaki', label: 'snacks' },
  
  // Popcorn
  { text: 'popcorn', label: 'snacks' },
  { text: 'butter popcorn', label: 'snacks' },
  { text: 'caramel popcorn', label: 'snacks' },
  { text: 'cheese popcorn', label: 'snacks' },
  { text: 'kettle corn', label: 'snacks' },
  { text: 'flavored popcorn', label: 'snacks' },
  { text: 'microwave popcorn', label: 'snacks' },
  { text: 'air popped popcorn', label: 'snacks' },
  
  // Dried Fruits
  { text: 'dried fruit', label: 'snacks' },
  { text: 'raisins', label: 'snacks' },
  { text: 'dried mango', label: 'snacks' },
  { text: 'dried pineapple', label: 'snacks' },
  { text: 'dried banana', label: 'snacks' },
  { text: 'dried apple', label: 'snacks' },
  { text: 'dried apricot', label: 'snacks' },
  { text: 'dried cranberry', label: 'snacks' },
  { text: 'dried strawberry', label: 'snacks' },
  { text: 'dried kiwi', label: 'snacks' },
  { text: 'fruit leather', label: 'snacks' },
  { text: 'fruit roll ups', label: 'snacks' },
  { text: 'fruit gummies', label: 'snacks' },
  
  // Jerky & Meat Snacks
  { text: 'jerky', label: 'snacks' },
  { text: 'beef jerky', label: 'snacks' },
  { text: 'pork jerky', label: 'snacks' },
  { text: 'chicken jerky', label: 'snacks' },
  { text: 'bak kwa', label: 'snacks' },
  { text: 'dried meat', label: 'snacks' },
  { text: 'meat floss', label: 'snacks' },
  { text: 'pork floss', label: 'snacks' },
  { text: 'fish jerky', label: 'snacks' },
  { text: 'squid jerky', label: 'snacks' },
  { text: 'dried squid', label: 'snacks' },
  { text: 'shredded squid', label: 'snacks' },
  
  // Ice Cream & Frozen Treats
  { text: 'ice cream', label: 'snacks' },
  { text: 'vanilla ice cream', label: 'snacks' },
  { text: 'chocolate ice cream', label: 'snacks' },
  { text: 'strawberry ice cream', label: 'snacks' },
  { text: 'cookies and cream', label: 'snacks' },
  { text: 'mint chocolate chip', label: 'snacks' },
  { text: 'rocky road', label: 'snacks' },
  { text: 'neapolitan ice cream', label: 'snacks' },
  { text: 'gelato', label: 'snacks' },
  { text: 'sorbet', label: 'snacks' },
  { text: 'popsicle', label: 'snacks' },
  { text: 'ice lolly', label: 'snacks' },
  { text: 'ice bar', label: 'snacks' },
  { text: 'frozen yogurt', label: 'snacks' },
  
  // Asian Ice Cream
  { text: 'red bean ice cream', label: 'snacks' },
  { text: 'green tea ice cream', label: 'snacks' },
  { text: 'taro ice cream', label: 'snacks' },
  { text: 'durian ice cream', label: 'snacks' },
  { text: 'coconut ice cream', label: 'snacks' },
  { text: 'mango ice cream', label: 'snacks' },
  { text: 'lychee ice cream', label: 'snacks' },
  { text: 'black sesame ice cream', label: 'snacks' },
  { text: 'corn ice cream', label: 'snacks' },
  { text: 'ube ice cream', label: 'snacks' },
  
  // Gum & Breath Fresheners
  { text: 'gum', label: 'snacks' },
  { text: 'chewing gum', label: 'snacks' },
  { text: 'bubble gum', label: 'snacks' },
  { text: 'sugar free gum', label: 'snacks' },
  { text: 'mint gum', label: 'snacks' },
  { text: 'fruit gum', label: 'snacks' },
  { text: 'breath mints', label: 'snacks' },
  { text: 'breath strips', label: 'snacks' },
  { text: 'throat lozenges', label: 'snacks' },
  { text: 'cough drops', label: 'snacks' },
  
  // Cereal Bars & Energy Bars
  { text: 'cereal bar', label: 'snacks' },
  { text: 'granola bar', label: 'snacks' },
  { text: 'energy bar', label: 'snacks' },
  { text: 'protein bar', label: 'snacks' },
  { text: 'nutrition bar', label: 'snacks' },
  { text: 'muesli bar', label: 'snacks' },
  { text: 'oat bar', label: 'snacks' },
  { text: 'fruit bar', label: 'snacks' },
  { text: 'nut bar', label: 'snacks' },
  { text: 'power bar', label: 'snacks' },
  { text: 'cliff bar', label: 'snacks' },
  { text: 'kind bar', label: 'snacks' },
  
  // Pretzels & Savory Snacks
  { text: 'pretzels', label: 'snacks' },
  { text: 'soft pretzels', label: 'snacks' },
  { text: 'pretzel sticks', label: 'snacks' },
  { text: 'cheese puffs', label: 'snacks' },
  { text: 'corn puffs', label: 'snacks' },
  { text: 'rice cakes', label: 'snacks' },
  { text: 'rice puffs', label: 'snacks' },
  { text: 'wasabi peas', label: 'snacks' },
  { text: 'roasted chickpeas', label: 'snacks' },
  { text: 'edamame', label: 'snacks' },
  { text: 'seaweed snacks', label: 'snacks' },
  { text: 'nori sheets', label: 'snacks' },
  
  // Traditional Asian Snacks
  { text: 'murukku', label: 'snacks' },
  { text: 'vadai', label: 'snacks' },
  { text: 'thosai chips', label: 'snacks' },
  { text: 'banana leaf chips', label: 'snacks' },
  { text: 'kuih', label: 'snacks' },
  { text: 'onde onde', label: 'snacks' },
  { text: 'kuih lapis', label: 'snacks' },
  { text: 'ang ku kueh', label: 'snacks' },
  { text: 'pineapple tart', label: 'snacks' },
  { text: 'love letters', label: 'snacks' },
  { text: 'kaya puff', label: 'snacks' },
  { text: 'curry puff', label: 'snacks' },
  
  // Instant Snacks
  { text: 'instant noodles', label: 'snacks' },
  { text: 'cup noodles', label: 'snacks' },
  { text: 'maggi mee', label: 'snacks' },
  { text: 'ramen', label: 'snacks' },
  { text: 'instant soup', label: 'snacks' },
  { text: 'instant porridge', label: 'snacks' },
  { text: 'instant oatmeal', label: 'snacks' },
  { text: 'instant cereal', label: 'snacks' },
  
  // Healthy Snacks
  { text: 'veggie chips', label: 'snacks' },
  { text: 'kale chips', label: 'snacks' },
  { text: 'beet chips', label: 'snacks' },
  { text: 'quinoa chips', label: 'snacks' },
  { text: 'lentil chips', label: 'snacks' },
  { text: 'chickpea chips', label: 'snacks' },
  { text: 'multigrain chips', label: 'snacks' },
  { text: 'organic snacks', label: 'snacks' },
  { text: 'gluten free snacks', label: 'snacks' },
  { text: 'sugar free candy', label: 'snacks' },
  
  // Seasonal & Festival Snacks
  { text: 'chinese new year cookies', label: 'snacks' },
  { text: 'pineapple cookies', label: 'snacks' },
  { text: 'almond cookies', label: 'snacks' },
  { text: 'bak kwa', label: 'snacks' },
  { text: 'mandarin oranges', label: 'snacks' },
  { text: 'festive cookies', label: 'snacks' },
  { text: 'holiday treats', label: 'snacks' },
  { text: 'gift boxes', label: 'snacks' },
  { text: 'assorted snacks', label: 'snacks' },
  { text: 'party mix', label: 'snacks' },
  
  // Premium & Imported
  { text: 'imported chocolate', label: 'snacks' },
  { text: 'artisan chocolate', label: 'snacks' },
  { text: 'gourmet cookies', label: 'snacks' },
  { text: 'premium nuts', label: 'snacks' },
  { text: 'organic candy', label: 'snacks' },
  { text: 'fair trade chocolate', label: 'snacks' },
  { text: 'handmade sweets', label: 'snacks' },
  { text: 'luxury snacks', label: 'snacks' },
  { text: 'specialty treats', label: 'snacks' },
  { text: 'international snacks', label: 'snacks' }
];

export default snacksConfectioneryTrainingData;