const snacksConfectioneryData = [
  { text: 'chips', label: 'Snacks & Confectionery' },
  { text: 'potato chips', label: 'Snacks & Confectionery' },
  { text: 'corn chips', label: 'Snacks & Confectionery' },
  { text: 'tortilla chips', label: 'Snacks & Confectionery' },
  { text: 'nacho chips', label: 'Snacks & Confectionery' },
  { text: 'pita chips', label: 'Snacks & Confectionery' },
  { text: 'bagel chips', label: 'Snacks & Confectionery' },
  { text: 'vegetable chips', label: 'Snacks & Confectionery' },
  { text: 'sweet potato chips', label: 'Snacks & Confectionery' },
  { text: 'beet chips', label: 'Snacks & Confectionery' },
  { text: 'kale chips', label: 'Snacks & Confectionery' },
  { text: 'banana chips', label: 'Snacks & Confectionery' },
  { text: 'apple chips', label: 'Snacks & Confectionery' },
  { text: 'coconut chips', label: 'Snacks & Confectionery' },
  { text: 'plantain chips', label: 'Snacks & Confectionery' },
  { text: 'cassava chips', label: 'Snacks & Confectionery' },
  { text: 'taro chips', label: 'Snacks & Confectionery' },
  { text: 'yuca chips', label: 'Snacks & Confectionery' },
  { text: 'parsnip chips', label: 'Snacks & Confectionery' },
  { text: 'turnip chips', label: 'Snacks & Confectionery' },
  { text: 'radish chips', label: 'Snacks & Confectionery' },
  { text: 'carrot chips', label: 'Snacks & Confectionery' },
  { text: 'zucchini chips', label: 'Snacks & Confectionery' },
  { text: 'squash chips', label: 'Snacks & Confectionery' },
  { text: 'pumpkin chips', label: 'Snacks & Confectionery' },
  { text: 'butternut squash chips', label: 'Snacks & Confectionery' },
  { text: 'acorn squash chips', label: 'Snacks & Confectionery' },
  { text: 'delicata squash chips', label: 'Snacks & Confectionery' },
  { text: 'hubbard squash chips', label: 'Snacks & Confectionery' },
  { text: 'kabocha squash chips', label: 'Snacks & Confectionery' },
  { text: 'spaghetti squash chips', label: 'Snacks & Confectionery' },
  { text: 'yellow squash chips', label: 'Snacks & Confectionery' },
  { text: 'patty pan squash chips', label: 'Snacks & Confectionery' },
  { text: 'crookneck squash chips', label: 'Snacks & Confectionery' },
  { text: 'straightneck squash chips', label: 'Snacks & Confectionery' },
  { text: 'scallop squash chips', label: 'Snacks & Confectionery' },
  { text: 'sunburst squash chips', label: 'Snacks & Confectionery' },
  { text: 'eight ball squash chips', label: 'Snacks & Confectionery' },
  { text: 'round zucchini chips', label: 'Snacks & Confectionery' },
  { text: 'costata romanesco chips', label: 'Snacks & Confectionery' },
  { text: 'cocozelle chips', label: 'Snacks & Confectionery' },
  { text: 'gadzukes chips', label: 'Snacks & Confectionery' },
  { text: 'magda chips', label: 'Snacks & Confectionery' },
  { text: 'pattypan chips', label: 'Snacks & Confectionery' },
  { text: 'ronde de nice chips', label: 'Snacks & Confectionery' },
  { text: 'tatume chips', label: 'Snacks & Confectionery' },
  { text: 'tromboncino chips', label: 'Snacks & Confectionery' },
  { text: 'zephyr chips', label: 'Snacks & Confectionery' },
  { text: 'crackers', label: 'Snacks & Confectionery' },
  { text: 'saltine crackers', label: 'Snacks & Confectionery' },
  { text: 'graham crackers', label: 'Snacks & Confectionery' },
  { text: 'cheese crackers', label: 'Snacks & Confectionery' },
  { text: 'water crackers', label: 'Snacks & Confectionery' },
  { text: 'oyster crackers', label: 'Snacks & Confectionery' },
  { text: 'soda crackers', label: 'Snacks & Confectionery' },
  { text: 'club crackers', label: 'Snacks & Confectionery' },
  { text: 'ritz crackers', label: 'Snacks & Confectionery' },
  { text: 'wheat crackers', label: 'Snacks & Confectionery' },
  { text: 'whole grain crackers', label: 'Snacks & Confectionery' },
  { text: 'multigrain crackers', label: 'Snacks & Confectionery' },
  { text: 'seed crackers', label: 'Snacks & Confectionery' },
  { text: 'nut crackers', label: 'Snacks & Confectionery' },
  { text: 'rice crackers', label: 'Snacks & Confectionery' },
  { text: 'corn crackers', label: 'Snacks & Confectionery' },
  { text: 'oat crackers', label: 'Snacks & Confectionery' },
  { text: 'barley crackers', label: 'Snacks & Confectionery' },
  { text: 'rye crackers', label: 'Snacks & Confectionery' },
  { text: 'spelt crackers', label: 'Snacks & Confectionery' },
  { text: 'quinoa crackers', label: 'Snacks & Confectionery' },
  { text: 'amaranth crackers', label: 'Snacks & Confectionery' },
  { text: 'buckwheat crackers', label: 'Snacks & Confectionery' },
  { text: 'millet crackers', label: 'Snacks & Confectionery' },
  { text: 'teff crackers', label: 'Snacks & Confectionery' },
  { text: 'sorghum crackers', label: 'Snacks & Confectionery' },
  { text: 'cassava crackers', label: 'Snacks & Confectionery' },
  { text: 'tapioca crackers', label: 'Snacks & Confectionery' },
  { text: 'potato crackers', label: 'Snacks & Confectionery' },
  { text: 'sweet potato crackers', label: 'Snacks & Confectionery' },
  { text: 'yam crackers', label: 'Snacks & Confectionery' },
  { text: 'plantain crackers', label: 'Snacks & Confectionery' },
  { text: 'banana crackers', label: 'Snacks & Confectionery' },
  { text: 'coconut crackers', label: 'Snacks & Confectionery' },
  { text: 'almond crackers', label: 'Snacks & Confectionery' },
  { text: 'walnut crackers', label: 'Snacks & Confectionery' },
  { text: 'pecan crackers', label: 'Snacks & Confectionery' },
  { text: 'hazelnut crackers', label: 'Snacks & Confectionery' },
  { text: 'pistachio crackers', label: 'Snacks & Confectionery' },
  { text: 'macadamia crackers', label: 'Snacks & Confectionery' },
  { text: 'cashew crackers', label: 'Snacks & Confectionery' },
  { text: 'brazil nut crackers', label: 'Snacks & Confectionery' },
  { text: 'pine nut crackers', label: 'Snacks & Confectionery' },
  { text: 'chestnut crackers', label: 'Snacks & Confectionery' },
  { text: 'acorn crackers', label: 'Snacks & Confectionery' },
  { text: 'beechnut crackers', label: 'Snacks & Confectionery' },
  { text: 'butternut crackers', label: 'Snacks & Confectionery' },
  { text: 'black walnut crackers', label: 'Snacks & Confectionery' },
  { text: 'english walnut crackers', label: 'Snacks & Confectionery' },
  { text: 'persian walnut crackers', label: 'Snacks & Confectionery' },
  { text: 'carpathian walnut crackers', label: 'Snacks & Confectionery' },
  { text: 'heartnut crackers', label: 'Snacks & Confectionery' },
  { text: 'butternut crackers', label: 'Snacks & Confectionery' },
  { text: 'hickory nut crackers', label: 'Snacks & Confectionery' },
  { text: 'shagbark hickory crackers', label: 'Snacks & Confectionery' },
  { text: 'shellbark hickory crackers', label: 'Snacks & Confectionery' },
  { text: 'mockernut hickory crackers', label: 'Snacks & Confectionery' },
  { text: 'pignut hickory crackers', label: 'Snacks & Confectionery' },
  { text: 'bitternut hickory crackers', label: 'Snacks & Confectionery' },
  { text: 'water hickory crackers', label: 'Snacks & Confectionery' },
  { text: 'nutmeg hickory crackers', label: 'Snacks & Confectionery' },
  { text: 'sand hickory crackers', label: 'Snacks & Confectionery' },
  { text: 'scrub hickory crackers', label: 'Snacks & Confectionery' },
  { text: 'southern shagbark crackers', label: 'Snacks & Confectionery' },
  { text: 'red hickory crackers', label: 'Snacks & Confectionery' },
  { text: 'black hickory crackers', label: 'Snacks & Confectionery' },
  { text: 'pale hickory crackers', label: 'Snacks & Confectionery' },
  { text: 'popcorn', label: 'Snacks & Confectionery' },
  { text: 'buttered popcorn', label: 'Snacks & Confectionery' },
  { text: 'salted popcorn', label: 'Snacks & Confectionery' },
  { text: 'caramel popcorn', label: 'Snacks & Confectionery' },
  { text: 'cheese popcorn', label: 'Snacks & Confectionery' },
  { text: 'kettle corn', label: 'Snacks & Confectionery' },
  { text: 'air popped popcorn', label: 'Snacks & Confectionery' },
  { text: 'oil popped popcorn', label: 'Snacks & Confectionery' },
  { text: 'microwave popcorn', label: 'Snacks & Confectionery' },
  { text: 'stovetop popcorn', label: 'Snacks & Confectionery' },
  { text: 'movie theater popcorn', label: 'Snacks & Confectionery' },
  { text: 'gourmet popcorn', label: 'Snacks & Confectionery' },
  { text: 'flavored popcorn', label: 'Snacks & Confectionery' },
  { text: 'sweet popcorn', label: 'Snacks & Confectionery' },
  { text: 'savory popcorn', label: 'Snacks & Confectionery' },
  { text: 'spicy popcorn', label: 'Snacks & Confectionery' },
  { text: 'chocolate popcorn', label: 'Snacks & Confectionery' },
  { text: 'white chocolate popcorn', label: 'Snacks & Confectionery' },
  { text: 'dark chocolate popcorn', label: 'Snacks & Confectionery' },
  { text: 'milk chocolate popcorn', label: 'Snacks & Confectionery' },
  { text: 'peanut butter popcorn', label: 'Snacks & Confectionery' },
  { text: 'almond popcorn', label: 'Snacks & Confectionery' },
  { text: 'pecan popcorn', label: 'Snacks & Confectionery' },
  { text: 'walnut popcorn', label: 'Snacks & Confectionery' },
  { text: 'cashew popcorn', label: 'Snacks & Confectionery' },
  { text: 'pistachio popcorn', label: 'Snacks & Confectionery' },
  { text: 'macadamia popcorn', label: 'Snacks & Confectionery' },
  { text: 'hazelnut popcorn', label: 'Snacks & Confectionery' },
  { text: 'brazil nut popcorn', label: 'Snacks & Confectionery' },
  { text: 'pine nut popcorn', label: 'Snacks & Confectionery' },
  { text: 'chestnut popcorn', label: 'Snacks & Confectionery' },
  { text: 'coconut popcorn', label: 'Snacks & Confectionery' },
  { text: 'sesame popcorn', label: 'Snacks & Confectionery' },
  { text: 'sunflower seed popcorn', label: 'Snacks & Confectionery' },
  { text: 'pumpkin seed popcorn', label: 'Snacks & Confectionery' },
  { text: 'chia seed popcorn', label: 'Snacks & Confectionery' },
  { text: 'flax seed popcorn', label: 'Snacks & Confectionery' },
  { text: 'hemp seed popcorn', label: 'Snacks & Confectionery' },
  { text: 'poppy seed popcorn', label: 'Snacks & Confectionery' },
  { text: 'mustard seed popcorn', label: 'Snacks & Confectionery' },
  { text: 'caraway seed popcorn', label: 'Snacks & Confectionery' },
  { text: 'fennel seed popcorn', label: 'Snacks & Confectionery' },
  { text: 'anise seed popcorn', label: 'Snacks & Confectionery' },
  { text: 'coriander seed popcorn', label: 'Snacks & Confectionery' },
  { text: 'cumin seed popcorn', label: 'Snacks & Confectionery' },
  { text: 'dill seed popcorn', label: 'Snacks & Confectionery' },
  { text: 'celery seed popcorn', label: 'Snacks & Confectionery' },
  { text: 'nigella seed popcorn', label: 'Snacks & Confectionery' },
  { text: 'black sesame popcorn', label: 'Snacks & Confectionery' },
  { text: 'white sesame popcorn', label: 'Snacks & Confectionery' },
  { text: 'tahini popcorn', label: 'Snacks & Confectionery' },
  { text: 'hummus popcorn', label: 'Snacks & Confectionery' },
  { text: 'ranch popcorn', label: 'Snacks & Confectionery' },
  { text: 'bbq popcorn', label: 'Snacks & Confectionery' },
  { text: 'buffalo popcorn', label: 'Snacks & Confectionery' },
  { text: 'jalapeño popcorn', label: 'Snacks & Confectionery' },
  { text: 'sriracha popcorn', label: 'Snacks & Confectionery' },
  { text: 'hot sauce popcorn', label: 'Snacks & Confectionery' },
  { text: 'chili popcorn', label: 'Snacks & Confectionery' },
  { text: 'cayenne popcorn', label: 'Snacks & Confectionery' },
  { text: 'paprika popcorn', label: 'Snacks & Confectionery' },
  { text: 'smoked paprika popcorn', label: 'Snacks & Confectionery' },
  { text: 'chipotle popcorn', label: 'Snacks & Confectionery' },
  { text: 'adobo popcorn', label: 'Snacks & Confectionery' },
  { text: 'cajun popcorn', label: 'Snacks & Confectionery' },
  { text: 'creole popcorn', label: 'Snacks & Confectionery' },
  { text: 'jerk popcorn', label: 'Snacks & Confectionery' },
  { text: 'curry popcorn', label: 'Snacks & Confectionery' },
  { text: 'turmeric popcorn', label: 'Snacks & Confectionery' },
  { text: 'garam masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'tandoori popcorn', label: 'Snacks & Confectionery' },
  { text: 'tikka masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'madras curry popcorn', label: 'Snacks & Confectionery' },
  { text: 'vindaloo popcorn', label: 'Snacks & Confectionery' },
  { text: 'korma popcorn', label: 'Snacks & Confectionery' },
  { text: 'biryani popcorn', label: 'Snacks & Confectionery' },
  { text: 'masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'chaat masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'garam masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'sambar masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'rasam masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'pav bhaji masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'chole masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'rajma masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'dal masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'sabzi masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'meat masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'fish masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'chicken masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'mutton masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'lamb masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'goat masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'beef masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'pork masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'duck masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'turkey masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'quail masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'pheasant masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'partridge masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'grouse masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'ptarmigan masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'woodcock masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'snipe masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'dove masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'pigeon masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'squab masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'guinea fowl masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'cornish hen masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'rock cornish hen masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'capon masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'rooster masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'cockerel masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'pullet masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'hen masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'broiler masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'fryer masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'stewing hen masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'free range chicken masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'organic chicken masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'pasture raised chicken masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'heritage chicken masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'heirloom chicken masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'rare breed chicken masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'native chicken masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'wild chicken masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'jungle fowl masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'red jungle fowl masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'grey jungle fowl masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'green jungle fowl masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'sri lankan jungle fowl masala popcorn', label: 'Snacks & Confectionery' },
  { text: 'nuts', label: 'Snacks & Confectionery' },
  { text: 'mixed nuts', label: 'Snacks & Confectionery' },
  { text: 'salted nuts', label: 'Snacks & Confectionery' },
  { text: 'roasted nuts', label: 'Snacks & Confectionery' },
  { text: 'raw nuts', label: 'Snacks & Confectionery' },
  { text: 'honey roasted nuts', label: 'Snacks & Confectionery' },
  { text: 'spiced nuts', label: 'Snacks & Confectionery' },
  { text: 'candied nuts', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered nuts', label: 'Snacks & Confectionery' },
  { text: 'yogurt covered nuts', label: 'Snacks & Confectionery' },
  { text: 'caramelized nuts', label: 'Snacks & Confectionery' },
  { text: 'glazed nuts', label: 'Snacks & Confectionery' },
  { text: 'seasoned nuts', label: 'Snacks & Confectionery' },
  { text: 'flavored nuts', label: 'Snacks & Confectionery' },
  { text: 'smoked nuts', label: 'Snacks & Confectionery' },
  { text: 'barbecue nuts', label: 'Snacks & Confectionery' },
  { text: 'ranch nuts', label: 'Snacks & Confectionery' },
  { text: 'buffalo nuts', label: 'Snacks & Confectionery' },
  { text: 'jalapeño nuts', label: 'Snacks & Confectionery' },
  { text: 'sriracha nuts', label: 'Snacks & Confectionery' },
  { text: 'wasabi nuts', label: 'Snacks & Confectionery' },
  { text: 'curry nuts', label: 'Snacks & Confectionery' },
  { text: 'cajun nuts', label: 'Snacks & Confectionery' },
  { text: 'chili lime nuts', label: 'Snacks & Confectionery' },
  { text: 'garlic nuts', label: 'Snacks & Confectionery' },
  { text: 'onion nuts', label: 'Snacks & Confectionery' },
  { text: 'herb nuts', label: 'Snacks & Confectionery' },
  { text: 'rosemary nuts', label: 'Snacks & Confectionery' },
  { text: 'thyme nuts', label: 'Snacks & Confectionery' },
  { text: 'sage nuts', label: 'Snacks & Confectionery' },
  { text: 'oregano nuts', label: 'Snacks & Confectionery' },
  { text: 'basil nuts', label: 'Snacks & Confectionery' },
  { text: 'parsley nuts', label: 'Snacks & Confectionery' },
  { text: 'cilantro nuts', label: 'Snacks & Confectionery' },
  { text: 'dill nuts', label: 'Snacks & Confectionery' },
  { text: 'chives nuts', label: 'Snacks & Confectionery' },
  { text: 'tarragon nuts', label: 'Snacks & Confectionery' },
  { text: 'marjoram nuts', label: 'Snacks & Confectionery' },
  { text: 'savory nuts', label: 'Snacks & Confectionery' },
  { text: 'mint nuts', label: 'Snacks & Confectionery' },
  { text: 'lavender nuts', label: 'Snacks & Confectionery' },
  { text: 'lemon nuts', label: 'Snacks & Confectionery' },
  { text: 'lime nuts', label: 'Snacks & Confectionery' },
  { text: 'orange nuts', label: 'Snacks & Confectionery' },
  { text: 'grapefruit nuts', label: 'Snacks & Confectionery' },
  { text: 'tangerine nuts', label: 'Snacks & Confectionery' },
  { text: 'mandarin nuts', label: 'Snacks & Confectionery' },
  { text: 'clementine nuts', label: 'Snacks & Confectionery' },
  { text: 'satsuma nuts', label: 'Snacks & Confectionery' },
  { text: 'yuzu nuts', label: 'Snacks & Confectionery' },
  { text: 'bergamot nuts', label: 'Snacks & Confectionery' },
  { text: 'pomelo nuts', label: 'Snacks & Confectionery' },
  { text: 'ugli fruit nuts', label: 'Snacks & Confectionery' },
  { text: 'tangelo nuts', label: 'Snacks & Confectionery' },
  { text: 'minneola nuts', label: 'Snacks & Confectionery' },
  { text: 'orlando nuts', label: 'Snacks & Confectionery' },
  { text: 'seminole nuts', label: 'Snacks & Confectionery' },
  { text: 'nova nuts', label: 'Snacks & Confectionery' },
  { text: 'page nuts', label: 'Snacks & Confectionery' },
  { text: 'robinson nuts', label: 'Snacks & Confectionery' },
  { text: 'lee nuts', label: 'Snacks & Confectionery' },
  { text: 'osceola nuts', label: 'Snacks & Confectionery' },
  { text: 'sunburst nuts', label: 'Snacks & Confectionery' },
  { text: 'wekiwa nuts', label: 'Snacks & Confectionery' },
  { text: 'fairchild nuts', label: 'Snacks & Confectionery' },
  { text: 'nova nuts', label: 'Snacks & Confectionery' },
  { text: 'chocolate', label: 'Snacks & Confectionery' },
  { text: 'dark chocolate', label: 'Snacks & Confectionery' },
  { text: 'milk chocolate', label: 'Snacks & Confectionery' },
  { text: 'white chocolate', label: 'Snacks & Confectionery' },
  { text: 'semi sweet chocolate', label: 'Snacks & Confectionery' },
  { text: 'bittersweet chocolate', label: 'Snacks & Confectionery' },
  { text: 'unsweetened chocolate', label: 'Snacks & Confectionery' },
  { text: 'cocoa powder', label: 'Snacks & Confectionery' },
  { text: 'chocolate chips', label: 'Snacks & Confectionery' },
  { text: 'chocolate chunks', label: 'Snacks & Confectionery' },
  { text: 'chocolate bars', label: 'Snacks & Confectionery' },
  { text: 'chocolate squares', label: 'Snacks & Confectionery' },
  { text: 'chocolate wafers', label: 'Snacks & Confectionery' },
  { text: 'chocolate discs', label: 'Snacks & Confectionery' },
  { text: 'chocolate melts', label: 'Snacks & Confectionery' },
  { text: 'chocolate coating', label: 'Snacks & Confectionery' },
  { text: 'chocolate candy', label: 'Snacks & Confectionery' },
  { text: 'chocolate truffles', label: 'Snacks & Confectionery' },
  { text: 'chocolate bonbons', label: 'Snacks & Confectionery' },
  { text: 'chocolate pralines', label: 'Snacks & Confectionery' },
  { text: 'chocolate ganache', label: 'Snacks & Confectionery' },
  { text: 'chocolate fudge', label: 'Snacks & Confectionery' },
  { text: 'chocolate caramel', label: 'Snacks & Confectionery' },
  { text: 'chocolate nougat', label: 'Snacks & Confectionery' },
  { text: 'chocolate toffee', label: 'Snacks & Confectionery' },
  { text: 'chocolate brittle', label: 'Snacks & Confectionery' },
  { text: 'chocolate bark', label: 'Snacks & Confectionery' },
  { text: 'chocolate clusters', label: 'Snacks & Confectionery' },
  { text: 'chocolate raisins', label: 'Snacks & Confectionery' },
  { text: 'chocolate almonds', label: 'Snacks & Confectionery' },
  { text: 'chocolate peanuts', label: 'Snacks & Confectionery' },
  { text: 'chocolate cashews', label: 'Snacks & Confectionery' },
  { text: 'chocolate walnuts', label: 'Snacks & Confectionery' },
  { text: 'chocolate pecans', label: 'Snacks & Confectionery' },
  { text: 'chocolate hazelnuts', label: 'Snacks & Confectionery' },
  { text: 'chocolate pistachios', label: 'Snacks & Confectionery' },
  { text: 'chocolate macadamias', label: 'Snacks & Confectionery' },
  { text: 'chocolate brazil nuts', label: 'Snacks & Confectionery' },
  { text: 'chocolate pine nuts', label: 'Snacks & Confectionery' },
  { text: 'chocolate chestnuts', label: 'Snacks & Confectionery' },
  { text: 'chocolate coconut', label: 'Snacks & Confectionery' },
  { text: 'chocolate espresso beans', label: 'Snacks & Confectionery' },
  { text: 'chocolate coffee beans', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered strawberries', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered cherries', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered blueberries', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered raspberries', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered blackberries', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered cranberries', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered goji berries', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered mulberries', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered elderberries', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered gooseberries', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered currants', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered sultanas', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered dates', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered figs', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered apricots', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered prunes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered banana chips', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered apple chips', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered pineapple', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered mango', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered papaya', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered kiwi', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered orange peel', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered lemon peel', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered lime peel', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered grapefruit peel', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered candied ginger', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered crystallized ginger', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered marshmallows', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered graham crackers', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered cookies', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered biscuits', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered wafers', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered pretzels', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered potato chips', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered popcorn', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered rice cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered rice crackers', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered corn cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered oat cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered quinoa cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered amaranth cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered buckwheat cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered millet cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered teff cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered sorghum cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered spelt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered kamut cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered einkorn cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered emmer cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered farro cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered freekeh cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered bulgur cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered cracked wheat cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered wheat berries cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered rye berries cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered barley cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered pearl barley cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered hulled barley cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered pot barley cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered scotch barley cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered quick barley cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered instant barley cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered flaked barley cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered rolled barley cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered steel cut barley cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered ground barley cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered barley flour cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered barley meal cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered barley grits cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered barley flakes cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered barley bran cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered barley germ cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered malted barley cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered barley syrup cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered barley malt syrup cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered barley malt extract cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered liquid barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered dry barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered powdered barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered granulated barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered crystallized barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered caramelized barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered roasted barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered toasted barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered smoked barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered charred barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered burnt barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered blackened barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered dark barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered light barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered pale barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered amber barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered golden barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered honey barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered caramel barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered chocolate barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered black barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered brown barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered red barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered white barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered yellow barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered green barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered blue barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered purple barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered pink barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered orange barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered silver barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered gold barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered copper barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered bronze barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered brass barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered pewter barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered platinum barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered titanium barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered steel barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered iron barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered aluminum barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered zinc barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered tin barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered lead barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered nickel barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered chromium barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered cobalt barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered manganese barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered vanadium barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered molybdenum barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered tungsten barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered tantalum barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered niobium barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered rhenium barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered osmium barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered iridium barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered rhodium barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered palladium barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered ruthenium barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate covered technetium barley malt cakes', label: 'Snacks & Confectionery' },
  { text: 'candy', label: 'Snacks & Confectionery' },
  { text: 'hard candy', label: 'Snacks & Confectionery' },
  { text: 'soft candy', label: 'Snacks & Confectionery' },
  { text: 'chewy candy', label: 'Snacks & Confectionery' },
  { text: 'gummy candy', label: 'Snacks & Confectionery' },
  { text: 'jelly candy', label: 'Snacks & Confectionery' },
  { text: 'fruit candy', label: 'Snacks & Confectionery' },
  { text: 'sour candy', label: 'Snacks & Confectionery' },
  { text: 'sweet candy', label: 'Snacks & Confectionery' },
  { text: 'sugar candy', label: 'Snacks & Confectionery' },
  { text: 'rock candy', label: 'Snacks & Confectionery' },
  { text: 'crystal candy', label: 'Snacks & Confectionery' },
  { text: 'lollipops', label: 'Snacks & Confectionery' },
  { text: 'suckers', label: 'Snacks & Confectionery' },
  { text: 'popsicles', label: 'Snacks & Confectionery' },
  { text: 'ice pops', label: 'Snacks & Confectionery' },
  { text: 'freeze pops', label: 'Snacks & Confectionery' },
  { text: 'otter pops', label: 'Snacks & Confectionery' },
  { text: 'push pops', label: 'Snacks & Confectionery' },
  { text: 'ring pops', label: 'Snacks & Confectionery' },
  { text: 'blow pops', label: 'Snacks & Confectionery' },
  { text: 'dum dums', label: 'Snacks & Confectionery' },
  { text: 'tootsie pops', label: 'Snacks & Confectionery' },
  { text: 'chupa chups', label: 'Snacks & Confectionery' },
  { text: 'jolly ranchers', label: 'Snacks & Confectionery' },
  { text: 'life savers', label: 'Snacks & Confectionery' },
  { text: 'werther\'s originals', label: 'Snacks & Confectionery' },
  { text: 'butterscotch candy', label: 'Snacks & Confectionery' },
  { text: 'caramel candy', label: 'Snacks & Confectionery' },
  { text: 'toffee candy', label: 'Snacks & Confectionery' },
  { text: 'taffy candy', label: 'Snacks & Confectionery' },
  { text: 'salt water taffy', label: 'Snacks & Confectionery' },
  { text: 'laffy taffy', label: 'Snacks & Confectionery' },
  { text: 'airheads', label: 'Snacks & Confectionery' },
  { text: 'now and later', label: 'Snacks & Confectionery' },
  { text: 'starburst', label: 'Snacks & Confectionery' },
  { text: 'skittles', label: 'Snacks & Confectionery' },
  { text: 'sour patch kids', label: 'Snacks & Confectionery' },
  { text: 'swedish fish', label: 'Snacks & Confectionery' },
  { text: 'gummy bears', label: 'Snacks & Confectionery' },
  { text: 'gummy worms', label: 'Snacks & Confectionery' },
  { text: 'haribo', label: 'Snacks & Confectionery' },
  { text: 'albanese', label: 'Snacks & Confectionery' },
  { text: 'ferrara', label: 'Snacks & Confectionery' },
  { text: 'mondelez', label: 'Snacks & Confectionery' },
  { text: 'mars', label: 'Snacks & Confectionery' },
  { text: 'nestle', label: 'Snacks & Confectionery' },
  { text: 'hershey', label: 'Snacks & Confectionery' },
  { text: 'lindt', label: 'Snacks & Confectionery' },
  { text: 'godiva', label: 'Snacks & Confectionery' },
  { text: 'ghirardelli', label: 'Snacks & Confectionery' },
  { text: 'cadbury', label: 'Snacks & Confectionery' },
  { text: 'toblerone', label: 'Snacks & Confectionery' },
  { text: 'ferrero rocher', label: 'Snacks & Confectionery' },
  { text: 'nutella', label: 'Snacks & Confectionery' },
  { text: 'kinder', label: 'Snacks & Confectionery' },
  { text: 'milka', label: 'Snacks & Confectionery' },
  { text: 'ritter sport', label: 'Snacks & Confectionery' },
  { text: 'aero', label: 'Snacks & Confectionery' },
  { text: 'kit kat', label: 'Snacks & Confectionery' },
  { text: 'twix', label: 'Snacks & Confectionery' },
  { text: 'snickers', label: 'Snacks & Confectionery' },
  { text: 'milky way', label: 'Snacks & Confectionery' },
  { text: '3 musketeers', label: 'Snacks & Confectionery' },
  { text: 'butterfinger', label: 'Snacks & Confectionery' },
  { text: 'crunch', label: 'Snacks & Confectionery' },
  { text: 'mr goodbar', label: 'Snacks & Confectionery' },
  { text: 'krackel', label: 'Snacks & Confectionery' },
  { text: 'special dark', label: 'Snacks & Confectionery' },
  { text: 'cookies and cream', label: 'Snacks & Confectionery' },
  { text: 'cookies n creme', label: 'Snacks & Confectionery' },
  { text: 'oreo', label: 'Snacks & Confectionery' },
  { text: 'nutter butter', label: 'Snacks & Confectionery' },
  { text: 'chips ahoy', label: 'Snacks & Confectionery' },
  { text: 'pepperidge farm', label: 'Snacks & Confectionery' },
  { text: 'keebler', label: 'Snacks & Confectionery' },
  { text: 'nabisco', label: 'Snacks & Confectionery' },
  { text: 'little debbie', label: 'Snacks & Confectionery' },
  { text: 'hostess', label: 'Snacks & Confectionery' },
  { text: 'twinkies', label: 'Snacks & Confectionery' },
  { text: 'ho hos', label: 'Snacks & Confectionery' },
  { text: 'ding dongs', label: 'Snacks & Confectionery' },
  { text: 'cupcakes', label: 'Snacks & Confectionery' },
  { text: 'donettes', label: 'Snacks & Confectionery' },
  { text: 'zingers', label: 'Snacks & Confectionery' },
  { text: 'sno balls', label: 'Snacks & Confectionery' },
  { text: 'fruit pies', label: 'Snacks & Confectionery' },
  { text: 'honey buns', label: 'Snacks & Confectionery' },
  { text: 'swiss rolls', label: 'Snacks & Confectionery' },
  { text: 'cosmic brownies', label: 'Snacks & Confectionery' },
  { text: 'zebra cakes', label: 'Snacks & Confectionery' },
  { text: 'oatmeal creme pies', label: 'Snacks & Confectionery' },
  { text: 'nutty bars', label: 'Snacks & Confectionery' },
  { text: 'star crunch', label: 'Snacks & Confectionery' },
  { text: 'fudge rounds', label: 'Snacks & Confectionery' },
  { text: 'christmas tree cakes', label: 'Snacks & Confectionery' },
  { text: 'valentine cakes', label: 'Snacks & Confectionery' },
  { text: 'easter cakes', label: 'Snacks & Confectionery' },
  { text: 'halloween cakes', label: 'Snacks & Confectionery' },
  { text: 'birthday cakes', label: 'Snacks & Confectionery' },
  { text: 'celebration cakes', label: 'Snacks & Confectionery' },
  { text: 'party cakes', label: 'Snacks & Confectionery' },
  { text: 'special occasion cakes', label: 'Snacks & Confectionery' },
  { text: 'seasonal cakes', label: 'Snacks & Confectionery' },
  { text: 'holiday cakes', label: 'Snacks & Confectionery' },
  { text: 'festive cakes', label: 'Snacks & Confectionery' },
  { text: 'themed cakes', label: 'Snacks & Confectionery' },
  { text: 'character cakes', label: 'Snacks & Confectionery' },
  { text: 'cartoon cakes', label: 'Snacks & Confectionery' },
  { text: 'movie cakes', label: 'Snacks & Confectionery' },
  { text: 'tv show cakes', label: 'Snacks & Confectionery' },
  { text: 'superhero cakes', label: 'Snacks & Confectionery' },
  { text: 'princess cakes', label: 'Snacks & Confectionery' },
  { text: 'sports cakes', label: 'Snacks & Confectionery' },
  { text: 'team cakes', label: 'Snacks & Confectionery' },
  { text: 'mascot cakes', label: 'Snacks & Confectionery' },
  { text: 'logo cakes', label: 'Snacks & Confectionery' },
  { text: 'brand cakes', label: 'Snacks & Confectionery' },
  { text: 'corporate cakes', label: 'Snacks & Confectionery' },
  { text: 'business cakes', label: 'Snacks & Confectionery' },
  { text: 'office cakes', label: 'Snacks & Confectionery' },
  { text: 'workplace cakes', label: 'Snacks & Confectionery' },
  { text: 'employee cakes', label: 'Snacks & Confectionery' },
  { text: 'staff cakes', label: 'Snacks & Confectionery' },
  { text: 'team building cakes', label: 'Snacks & Confectionery' },
  { text: 'meeting cakes', label: 'Snacks & Confectionery' },
  { text: 'conference cakes', label: 'Snacks & Confectionery' },
  { text: 'seminar cakes', label: 'Snacks & Confectionery' },
  { text: 'workshop cakes', label: 'Snacks & Confectionery' },
  { text: 'training cakes', label: 'Snacks & Confectionery' },
  { text: 'presentation cakes', label: 'Snacks & Confectionery' },
  { text: 'launch cakes', label: 'Snacks & Confectionery' },
  { text: 'opening cakes', label: 'Snacks & Confectionery' },
  { text: 'grand opening cakes', label: 'Snacks & Confectionery' },
  { text: 'ribbon cutting cakes', label: 'Snacks & Confectionery' },
  { text: 'ceremony cakes', label: 'Snacks & Confectionery' },
  { text: 'award cakes', label: 'Snacks & Confectionery' },
  { text: 'recognition cakes', label: 'Snacks & Confectionery' },
  { text: 'achievement cakes', label: 'Snacks & Confectionery' },
  { text: 'milestone cakes', label: 'Snacks & Confectionery' },
  { text: 'anniversary cakes', label: 'Snacks & Confectionery' },
  { text: 'retirement cakes', label: 'Snacks & Confectionery' },
  { text: 'farewell cakes', label: 'Snacks & Confectionery' },
  { text: 'goodbye cakes', label: 'Snacks & Confectionery' },
  { text: 'welcome cakes', label: 'Snacks & Confectionery' },
  { text: 'hello cakes', label: 'Snacks & Confectionery' },
  { text: 'greeting cakes', label: 'Snacks & Confectionery' },
  { text: 'introduction cakes', label: 'Snacks & Confectionery' },
  { text: 'orientation cakes', label: 'Snacks & Confectionery' },
  { text: 'onboarding cakes', label: 'Snacks & Confectionery' },
  { text: 'new hire cakes', label: 'Snacks & Confectionery' },
  { text: 'new employee cakes', label: 'Snacks & Confectionery' },
  { text: 'new member cakes', label: 'Snacks & Confectionery' },
  { text: 'new recruit cakes', label: 'Snacks & Confectionery' },
  { text: 'new addition cakes', label: 'Snacks & Confectionery' },
  { text: 'new arrival cakes', label: 'Snacks & Confectionery' },
  { text: 'new starter cakes', label: 'Snacks & Confectionery' },
  { text: 'new joiner cakes', label: 'Snacks & Confectionery' },
  { text: 'fresh face cakes', label: 'Snacks & Confectionery' },
  { text: 'newcomer cakes', label: 'Snacks & Confectionery' },
  { text: 'rookie cakes', label: 'Snacks & Confectionery' },
  { text: 'beginner cakes', label: 'Snacks & Confectionery' },
  { text: 'novice cakes', label: 'Snacks & Confectionery' },
  { text: 'trainee cakes', label: 'Snacks & Confectionery' },
  { text: 'apprentice cakes', label: 'Snacks & Confectionery' },
  { text: 'intern cakes', label: 'Snacks & Confectionery' },
  { text: 'student cakes', label: 'Snacks & Confectionery' },
  { text: 'learner cakes', label: 'Snacks & Confectionery' },
  { text: 'pupil cakes', label: 'Snacks & Confectionery' },
  { text: 'scholar cakes', label: 'Snacks & Confectionery' },
  { text: 'academic cakes', label: 'Snacks & Confectionery' },
  { text: 'educational cakes', label: 'Snacks & Confectionery' },
  { text: 'school cakes', label: 'Snacks & Confectionery' },
  { text: 'university cakes', label: 'Snacks & Confectionery' },
  { text: 'college cakes', label: 'Snacks & Confectionery' },
  { text: 'graduation cakes', label: 'Snacks & Confectionery' },
  { text: 'diploma cakes', label: 'Snacks & Confectionery' },
  { text: 'degree cakes', label: 'Snacks & Confectionery' },
  { text: 'certificate cakes', label: 'Snacks & Confectionery' },
  { text: 'qualification cakes', label: 'Snacks & Confectionery' },
  { text: 'credential cakes', label: 'Snacks & Confectionery' },
  { text: 'license cakes', label: 'Snacks & Confectionery' },
  { text: 'permit cakes', label: 'Snacks & Confectionery' },
  { text: 'authorization cakes', label: 'Snacks & Confectionery' },
  { text: 'approval cakes', label: 'Snacks & Confectionery' },
  { text: 'endorsement cakes', label: 'Snacks & Confectionery' },
  { text: 'recommendation cakes', label: 'Snacks & Confectionery' },
  { text: 'referral cakes', label: 'Snacks & Confectionery' },
  { text: 'testimonial cakes', label: 'Snacks & Confectionery' },
  { text: 'review cakes', label: 'Snacks & Confectionery' },
  { text: 'feedback cakes', label: 'Snacks & Confectionery' },
  { text: 'comment cakes', label: 'Snacks & Confectionery' },
  { text: 'opinion cakes', label: 'Snacks & Confectionery' },
  { text: 'thought cakes', label: 'Snacks & Confectionery' },
  { text: 'idea cakes', label: 'Snacks & Confectionery' },
  { text: 'concept cakes', label: 'Snacks & Confectionery' },
  { text: 'notion cakes', label: 'Snacks & Confectionery' },
  { text: 'theory cakes', label: 'Snacks & Confectionery' },
  { text: 'hypothesis cakes', label: 'Snacks & Confectionery' },
  { text: 'assumption cakes', label: 'Snacks & Confectionery' },
  { text: 'presumption cakes', label: 'Snacks & Confectionery' },
  { text: 'supposition cakes', label: 'Snacks & Confectionery' },
  { text: 'conjecture cakes', label: 'Snacks & Confectionery' },
  { text: 'speculation cakes', label: 'Snacks & Confectionery' },
  { text: 'guess cakes', label: 'Snacks & Confectionery' },
  { text: 'estimate cakes', label: 'Snacks & Confectionery' },
  { text: 'approximation cakes', label: 'Snacks & Confectionery' },
  { text: 'calculation cakes', label: 'Snacks & Confectionery' },
  { text: 'computation cakes', label: 'Snacks & Confectionery' },
  { text: 'measurement cakes', label: 'Snacks & Confectionery' },
  { text: 'assessment cakes', label: 'Snacks & Confectionery' },
  { text: 'evaluation cakes', label: 'Snacks & Confectionery' },
  { text: 'analysis cakes', label: 'Snacks & Confectionery' },
  { text: 'examination cakes', label: 'Snacks & Confectionery' },
  { text: 'inspection cakes', label: 'Snacks & Confectionery' },
  { text: 'investigation cakes', label: 'Snacks & Confectionery' },
  { text: 'research cakes', label: 'Snacks & Confectionery' },
  { text: 'study cakes', label: 'Snacks & Confectionery' },
  { text: 'survey cakes', label: 'Snacks & Confectionery' },
  { text: 'poll cakes', label: 'Snacks & Confectionery' },
  { text: 'questionnaire cakes', label: 'Snacks & Confectionery' },
  { text: 'interview cakes', label: 'Snacks & Confectionery' },
  { text: 'discussion cakes', label: 'Snacks & Confectionery' },
  { text: 'conversation cakes', label: 'Snacks & Confectionery' },
  { text: 'dialogue cakes', label: 'Snacks & Confectionery' },
  { text: 'chat cakes', label: 'Snacks & Confectionery' },
  { text: 'talk cakes', label: 'Snacks & Confectionery' },
  { text: 'speech cakes', label: 'Snacks & Confectionery' },
  { text: 'address cakes', label: 'Snacks & Confectionery' },
  { text: 'lecture cakes', label: 'Snacks & Confectionery' },
  { text: 'sermon cakes', label: 'Snacks & Confectionery' },
  { text: 'homily cakes', label: 'Snacks & Confectionery' },
  { text: 'discourse cakes', label: 'Snacks & Confectionery' },
  { text: 'oration cakes', label: 'Snacks & Confectionery' },
  { text: 'monologue cakes', label: 'Snacks & Confectionery' },
  { text: 'soliloquy cakes', label: 'Snacks & Confectionery' },
  { text: 'recitation cakes', label: 'Snacks & Confectionery' },
  { text: 'narration cakes', label: 'Snacks & Confectionery' },
  { text: 'storytelling cakes', label: 'Snacks & Confectionery' },
  { text: 'tale cakes', label: 'Snacks & Confectionery' },
  { text: 'story cakes', label: 'Snacks & Confectionery' },
  { text: 'narrative cakes', label: 'Snacks & Confectionery' },
  { text: 'account cakes', label: 'Snacks & Confectionery' },
  { text: 'report cakes', label: 'Snacks & Confectionery' },
  { text: 'record cakes', label: 'Snacks & Confectionery' },
  { text: 'chronicle cakes', label: 'Snacks & Confectionery' },
  { text: 'history cakes', label: 'Snacks & Confectionery' },
  { text: 'biography cakes', label: 'Snacks & Confectionery' },
  { text: 'autobiography cakes', label: 'Snacks & Confectionery' },
  { text: 'memoir cakes', label: 'Snacks & Confectionery' },
  { text: 'diary cakes', label: 'Snacks & Confectionery' },
  { text: 'journal cakes', label: 'Snacks & Confectionery' },
  { text: 'log cakes', label: 'Snacks & Confectionery' },
  { text: 'logbook cakes', label: 'Snacks & Confectionery' },
  { text: 'register cakes', label: 'Snacks & Confectionery' },
  { text: 'ledger cakes', label: 'Snacks & Confectionery' },
  { text: 'book cakes', label: 'Snacks & Confectionery' },
  { text: 'novel cakes', label: 'Snacks & Confectionery' },
  { text: 'fiction cakes', label: 'Snacks & Confectionery' },
  { text: 'non-fiction cakes', label: 'Snacks & Confectionery' },
  { text: 'fantasy cakes', label: 'Snacks & Confectionery' },
  { text: 'science fiction cakes', label: 'Snacks & Confectionery' },
  { text: 'mystery cakes', label: 'Snacks & Confectionery' },
  { text: 'thriller cakes', label: 'Snacks & Confectionery' },
  { text: 'horror cakes', label: 'Snacks & Confectionery' },
  { text: 'romance cakes', label: 'Snacks & Confectionery' },
  { text: 'drama cakes', label: 'Snacks & Confectionery' },
  { text: 'comedy cakes', label: 'Snacks & Confectionery' },
  { text: 'action cakes', label: 'Snacks & Confectionery' },
  { text: 'adventure cakes', label: 'Snacks & Confectionery' },
  { text: 'western cakes', label: 'Snacks & Confectionery' },
  { text: 'historical cakes', label: 'Snacks & Confectionery' },
  { text: 'period cakes', label: 'Snacks & Confectionery' },
  { text: 'contemporary cakes', label: 'Snacks & Confectionery' },
  { text: 'modern cakes', label: 'Snacks & Confectionery' },
  { text: 'classic cakes', label: 'Snacks & Confectionery' },
  { text: 'vintage cakes', label: 'Snacks & Confectionery' },
  { text: 'retro cakes', label: 'Snacks & Confectionery' },
  { text: 'antique cakes', label: 'Snacks & Confectionery' },
  { text: 'old fashioned cakes', label: 'Snacks & Confectionery' },
  { text: 'traditional cakes', label: 'Snacks & Confectionery' },
  { text: 'conventional cakes', label: 'Snacks & Confectionery' },
  { text: 'standard cakes', label: 'Snacks & Confectionery' },
  { text: 'regular cakes', label: 'Snacks & Confectionery' },
  { text: 'normal cakes', label: 'Snacks & Confectionery' },
  { text: 'ordinary cakes', label: 'Snacks & Confectionery' },
  { text: 'common cakes', label: 'Snacks & Confectionery' },
  { text: 'typical cakes', label: 'Snacks & Confectionery' },
  { text: 'usual cakes', label: 'Snacks & Confectionery' },
  { text: 'everyday cakes', label: 'Snacks & Confectionery' },
  { text: 'basic cakes', label: 'Snacks & Confectionery' },
  { text: 'simple cakes', label: 'Snacks & Confectionery' },
  { text: 'plain cakes', label: 'Snacks & Confectionery' },
  { text: 'vanilla cakes', label: 'Snacks & Confectionery' },
  { text: 'chocolate cakes', label: 'Snacks & Confectionery' },
  { text: 'strawberry cakes', label: 'Snacks & Confectionery' },
  { text: 'lemon cakes', label: 'Snacks & Confectionery' },
  { text: 'orange cakes', label: 'Snacks & Confectionery' },
  { text: 'coconut cakes', label: 'Snacks & Confectionery' },
  { text: 'carrot cakes', label: 'Snacks & Confectionery' },
  { text: 'red velvet cakes', label: 'Snacks & Confectionery' },
  { text: 'funfetti cakes', label: 'Snacks & Confectionery' },
  { text: 'confetti cakes', label: 'Snacks & Confectionery' },
  { text: 'rainbow cakes', label: 'Snacks & Confectionery' },
  { text: 'marble cakes', label: 'Snacks & Confectionery' },
  { text: 'pound cakes', label: 'Snacks & Confectionery' },
  { text: 'bundt cakes', label: 'Snacks & Confectionery' },
  { text: 'layer cakes', label: 'Snacks & Confectionery' },
  { text: 'sheet cakes', label: 'Snacks & Confectionery' },
  { text: 'round cakes', label: 'Snacks & Confectionery' },
  { text: 'square cakes', label: 'Snacks & Confectionery' },
  { text: 'rectangular cakes', label: 'Snacks & Confectionery' },
  { text: 'heart shaped cakes', label: 'Snacks & Confectionery' },
  { text: 'star shaped cakes', label: 'Snacks & Confectionery' },
  { text: 'flower shaped cakes', label: 'Snacks & Confectionery' },
  { text: 'animal shaped cakes', label: 'Snacks & Confectionery' },
  { text: 'number cakes', label: 'Snacks & Confectionery' },
  { text: 'letter cakes', label: 'Snacks & Confectionery' },
  { text: 'custom shaped cakes', label: 'Snacks & Confectionery' },
  { text: 'novelty cakes', label: 'Snacks & Confectionery' },
  { text: 'specialty cakes', label: 'Snacks & Confectionery' },
  { text: 'designer cakes', label: 'Snacks & Confectionery' },
  { text: 'artisan cakes', label: 'Snacks & Confectionery' },
  { text: 'handmade cakes', label: 'Snacks & Confectionery' },
  { text: 'homemade cakes', label: 'Snacks & Confectionery' },
  { text: 'fresh baked cakes', label: 'Snacks & Confectionery' },
  { text: 'bakery cakes', label: 'Snacks & Confectionery' },
  { text: 'store bought cakes', label: 'Snacks & Confectionery' },
  { text: 'packaged cakes', label: 'Snacks & Confectionery' },
  { text: 'frozen cakes', label: 'Snacks & Confectionery' },
  { text: 'thawed cakes', label: 'Snacks & Confectionery' },
  { text: 'defrosted cakes', label: 'Snacks & Confectionery' },
  { text: 'room temperature cakes', label: 'Snacks & Confectionery' },
  { text: 'chilled cakes', label: 'Snacks & Confectionery' },
  { text: 'refrigerated cakes', label: 'Snacks & Confectionery' },
  { text: 'cold cakes', label: 'Snacks & Confectionery' },
  { text: 'warm cakes', label: 'Snacks & Confectionery' },
  { text: 'hot cakes', label: 'Snacks & Confectionery' },
  { text: 'heated cakes', label: 'Snacks & Confectionery' },
  { text: 'microwaved cakes', label: 'Snacks & Confectionery' },
  { text: 'toasted cakes', label: 'Snacks & Confectionery' },
  { text: 'grilled cakes', label: 'Snacks & Confectionery' },
  { text: 'baked cakes', label: 'Snacks & Confectionery' },
  { text: 'oven baked cakes', label: 'Snacks & Confectionery' },
  { text: 'convection baked cakes', label: 'Snacks & Confectionery' },
  { text: 'steam baked cakes', label: 'Snacks & Confectionery' },
  { text: 'pressure cooked cakes', label: 'Snacks & Confectionery' },
  { text: 'slow cooked cakes', label: 'Snacks & Confectionery' },
  { text: 'crockpot cakes', label: 'Snacks & Confectionery' },
  { text: 'instant pot cakes', label: 'Snacks & Confectionery' },
  { text: 'air fryer cakes', label: 'Snacks & Confectionery' },
  { text: 'deep fried cakes', label: 'Snacks & Confectionery' },
  { text: 'pan fried cakes', label: 'Snacks & Confectionery' },
  { text: 'skillet cakes', label: 'Snacks & Confectionery' },
  { text: 'griddle cakes', label: 'Snacks & Confectionery' },
  { text: 'pancake cakes', label: 'Snacks & Confectionery' },
  { text: 'waffle cakes', label: 'Snacks & Confectionery' },
  { text: 'crepe cakes', label: 'Snacks & Confectionery' },
  { text: 'mille crepe cakes', label: 'Snacks & Confectionery' },
  { text: 'tiramisu cakes', label: 'Snacks & Confectionery' },
  { text: 'tres leches cakes', label: 'Snacks & Confectionery' },
  { text: 'black forest cakes', label: 'Snacks & Confectionery' },
  { text: 'german chocolate cakes', label: 'Snacks & Confectionery' },
  { text: 'devil\'s food cakes', label: 'Snacks & Confectionery' },
  { text: 'angel food cakes', label: 'Snacks & Confectionery' },
  { text: 'chiffon cakes', label: 'Snacks & Confectionery' },
  { text: 'sponge cakes', label: 'Snacks & Confectionery' },
  { text: 'genoise cakes', label: 'Snacks & Confectionery' },
  { text: 'victoria sponge cakes', label: 'Snacks & Confectionery' },
  { text: 'madeira cakes', label: 'Snacks & Confectionery' },
  { text: 'battenberg cakes', label: 'Snacks & Confectionery' },
  { text: 'dundee cakes', label: 'Snacks & Confectionery' },
  { text: 'fruitcakes', label: 'Snacks & Confectionery' },
  { text: 'christmas cakes', label: 'Snacks & Confectionery' },
  { text: 'wedding cakes', label: 'Snacks & Confectionery' },
  { text: 'engagement cakes', label: 'Snacks & Confectionery' },
  { text: 'anniversary cakes', label: 'Snacks & Confectionery' },
  { text: 'baby shower cakes', label: 'Snacks & Confectionery' },
  { text: 'gender reveal cakes', label: 'Snacks & Confectionery' },
  { text: 'baptism cakes', label: 'Snacks & Confectionery' },
  { text: 'christening cakes', label: 'Snacks & Confectionery' },
  { text: 'communion cakes', label: 'Snacks & Confectionery' },
  { text: 'confirmation cakes', label: 'Snacks & Confectionery' },
  { text: 'bar mitzvah cakes', label: 'Snacks & Confectionery' },
  { text: 'bat mitzvah cakes', label: 'Snacks & Confectionery' },
  { text: 'quinceañera cakes', label: 'Snacks & Confectionery' },
  { text: 'sweet sixteen cakes', label: 'Snacks & Confectionery' },
  { text: 'coming of age cakes', label: 'Snacks & Confectionery' },
  { text: 'rite of passage cakes', label: 'Snacks & Confectionery' },
  { text: 'cultural cakes', label: 'Snacks & Confectionery' },
  { text: 'religious cakes', label: 'Snacks & Confectionery' },
  { text: 'spiritual cakes', label: 'Snacks & Confectionery' },
  { text: 'sacred cakes', label: 'Snacks & Confectionery' },
  { text: 'blessed cakes', label: 'Snacks & Confectionery' },
  { text: 'holy cakes', label: 'Snacks & Confectionery' },
  { text: 'divine cakes', label: 'Snacks & Confectionery' },
  { text: 'heavenly cakes', label: 'Snacks & Confectionery' },
  { text: 'angelic cakes', label: 'Snacks & Confectionery' },
  { text: 'celestial cakes', label: 'Snacks & Confectionery' },
  { text: 'ethereal cakes', label: 'Snacks & Confectionery' },
  { text: 'mystical cakes', label: 'Snacks & Confectionery' },
  { text: 'magical cakes', label: 'Snacks & Confectionery' },
  { text: 'enchanted cakes', label: 'Snacks & Confectionery' },
  { text: 'fairy tale cakes', label: 'Snacks & Confectionery' },
  { text: 'fantasy cakes', label: 'Snacks & Confectionery' },
  { text: 'mythical cakes', label: 'Snacks & Confectionery' },
  { text: 'legendary cakes', label: 'Snacks & Confectionery' },
  { text: 'epic cakes', label: 'Snacks & Confectionery' },
  { text: 'heroic cakes', label: 'Snacks & Confectionery' },
  { text: 'brave cakes', label: 'Snacks & Confectionery' },
  { text: 'courageous cakes', label: 'Snacks & Confectionery' },
  { text: 'fearless cakes', label: 'Snacks & Confectionery' },
  { text: 'bold cakes', label: 'Snacks & Confectionery' },
  { text: 'daring cakes', label: 'Snacks & Confectionery' },
  { text: 'adventurous cakes', label: 'Snacks & Confectionery' },
  { text: 'exciting cakes', label: 'Snacks & Confectionery' },
  { text: 'thrilling cakes', label: 'Snacks & Confectionery' },
  { text: 'exhilarating cakes', label: 'Snacks & Confectionery' },
  { text: 'stimulating cakes', label: 'Snacks & Confectionery' },
  { text: 'invigorating cakes', label: 'Snacks & Confectionery' },
  { text: 'energizing cakes', label: 'Snacks & Confectionery' },
  { text: 'refreshing cakes', label: 'Snacks & Confectionery' },
  { text: 'revitalizing cakes', label: 'Snacks & Confectionery' },
  { text: 'rejuvenating cakes', label: 'Snacks & Confectionery' },
  { text: 'renewing cakes', label: 'Snacks & Confectionery' },
  { text: 'restoring cakes', label: 'Snacks & Confectionery' },
  { text: 'healing cakes', label: 'Snacks & Confectionery' },
  { text: 'therapeutic cakes', label: 'Snacks & Confectionery' },
  { text: 'medicinal cakes', label: 'Snacks & Confectionery' },
  { text: 'health cakes', label: 'Snacks & Confectionery' },
  { text: 'wellness cakes', label: 'Snacks & Confectionery' },
  { text: 'fitness cakes', label: 'Snacks & Confectionery' },
  { text: 'nutrition cakes', label: 'Snacks & Confectionery' },
  { text: 'diet cakes', label: 'Snacks & Confectionery' },
  { text: 'low calorie cakes', label: 'Snacks & Confectionery' },
  { text: 'sugar free cakes', label: 'Snacks & Confectionery' },
  { text: 'fat free cakes', label: 'Snacks & Confectionery' },
  { text: 'gluten free cakes', label: 'Snacks & Confectionery' },
  { text: 'dairy free cakes', label: 'Snacks & Confectionery' },
  { text: 'vegan cakes', label: 'Snacks & Confectionery' },
  { text: 'vegetarian cakes', label: 'Snacks & Confectionery' },
  { text: 'organic cakes', label: 'Snacks & Confectionery' },
  { text: 'natural cakes', label: 'Snacks & Confectionery' },
  { text: 'whole grain cakes', label: 'Snacks & Confectionery' },
  { text: 'whole wheat cakes', label: 'Snacks & Confectionery' },
  { text: 'multigrain cakes', label: 'Snacks & Confectionery' },
  { text: 'high fiber cakes', label: 'Snacks & Confectionery' },
  { text: 'high protein cakes', label: 'Snacks & Confectionery' },
  { text: 'fortified cakes', label: 'Snacks & Confectionery' },
  { text: 'enriched cakes', label: 'Snacks & Confectionery' },
  { text: 'vitamin enriched cakes', label: 'Snacks & Confectionery' },
  { text: 'mineral enriched cakes', label: 'Snacks & Confectionery' },
  { text: 'calcium enriched cakes', label: 'Snacks & Confectionery' },
  { text: 'iron enriched cakes', label: 'Snacks & Confectionery' },
  { text: 'zinc enriched cakes', label: 'Snacks & Confectionery' },
  { text: 'magnesium enriched cakes', label: 'Snacks & Confectionery' },
  { text: 'potassium enriched cakes', label: 'Snacks & Confectionery' },
  { text: 'sodium reduced cakes', label: 'Snacks & Confectionery' },
  { text: 'low sodium cakes', label: 'Snacks & Confectionery' },
  { text: 'salt free cakes', label: 'Snacks & Confectionery' },
  { text: 'unsalted cakes', label: 'Snacks & Confectionery' },
  { text: 'no added salt cakes', label: 'Snacks & Confectionery' },
  { text: 'reduced sugar cakes', label: 'Snacks & Confectionery' },
  { text: 'low sugar cakes', label: 'Snacks & Confectionery' },
  { text: 'no added sugar cakes', label: 'Snacks & Confectionery' },
  { text: 'unsweetened cakes', label: 'Snacks & Confectionery' },
  { text: 'artificially sweetened cakes', label: 'Snacks & Confectionery' },
  { text: 'naturally sweetened cakes', label: 'Snacks & Confectionery' },
  { text: 'honey sweetened cakes', label: 'Snacks & Confectionery' },
  { text: 'maple sweetened cakes', label: 'Snacks & Confectionery' },
  { text: 'agave sweetened cakes', label: 'Snacks & Confectionery' },
  { text: 'stevia sweetened cakes', label: 'Snacks & Confectionery' },
  { text: 'monk fruit sweetened cakes', label: 'Snacks & Confectionery' },
  { text: 'erythritol sweetened cakes', label: 'Snacks & Confectionery' },
  { text: 'xylitol sweetened cakes', label: 'Snacks & Confectionery' },
  { text: 'sorbitol sweetened cakes', label: 'Snacks & Confectionery' },
  { text: 'mannitol sweetened cakes', label: 'Snacks & Confectionery' },
  { text: 'maltitol sweetened cakes', label: 'Snacks & Confectionery' },
  { text: 'isomalt sweetened cakes', label: 'Snacks & Confectionery' },
  { text: 'lactitol sweetened cakes', label: 'Snacks & Confectionery' },
  { text: 'glycerol sweetened cakes', label: 'Snacks & Confectionery' },
  { text: 'glycerin sweetened cakes', label: 'Snacks & Confectionery' },
  { text: 'vegetable glycerin sweetened cakes', label: 'Snacks & Confectionery' },
  { text: 'propylene glycol sweetened cakes', label: 'Snacks & Confectionery' },
  { text: 'ethylene glycol sweetened cakes', label: 'Snacks & Confectionery' }
];

export default snacksConfectioneryData;