export const TRAINING_DATA = [
  // General (100+ items)
  { text: 'miscellaneous item', label: 'General' },
  { text: 'random product', label: 'General' },
  { text: 'unspecified goods', label: 'General' },
  { text: 'general merchandise', label: 'General' },
  { text: 'assorted items', label: 'General' },
  { text: 'mixed products', label: 'General' },
  { text: 'various goods', label: 'General' },
  { text: 'other items', label: 'General' },
  { text: 'specialty products', label: 'General' },
  { text: 'unique items', label: 'General' },
  { text: 'custom goods', label: 'General' },
  { text: 'special order', label: 'General' },
  { text: 'imported goods', label: 'General' },
  { text: 'local products', label: 'General' },
  { text: 'artisan items', label: 'General' },
  { text: 'handmade goods', label: 'General' },
  { text: 'craft supplies', label: 'General' },
  { text: 'hobby materials', label: 'General' },
  { text: 'collectibles', label: 'General' },
  { text: 'novelty items', label: 'General' },
  { text: 'gift items', label: 'General' },
  { text: 'souvenir', label: 'General' },
  { text: 'memento', label: 'General' },
  { text: 'keepsake', label: 'General' },
  { text: 'trinket', label: 'General' },
  { text: 'gadget', label: 'General' },
  { text: 'tool', label: 'General' },
  { text: 'equipment', label: 'General' },
  { text: 'apparatus', label: 'General' },
  { text: 'device', label: 'General' },
  { text: 'instrument', label: 'General' },
  { text: 'utensil', label: 'General' },
  { text: 'accessory', label: 'General' },
  { text: 'component', label: 'General' },
  { text: 'part', label: 'General' },
  { text: 'spare part', label: 'General' },
  { text: 'replacement', label: 'General' },
  { text: 'refill', label: 'General' },
  { text: 'cartridge', label: 'General' },
  { text: 'filter', label: 'General' },
  { text: 'adapter', label: 'General' },
  { text: 'connector', label: 'General' },
  { text: 'cable', label: 'General' },
  { text: 'cord', label: 'General' },
  { text: 'wire', label: 'General' },
  { text: 'string', label: 'General' },
  { text: 'rope', label: 'General' },
  { text: 'chain', label: 'General' },
  { text: 'strap', label: 'General' },
  { text: 'belt', label: 'General' },
  { text: 'band', label: 'General' },
  { text: 'tie', label: 'General' },
  { text: 'fastener', label: 'General' },
  { text: 'clip', label: 'General' },
  { text: 'clamp', label: 'General' },
  { text: 'bracket', label: 'General' },
  { text: 'holder', label: 'General' },
  { text: 'stand', label: 'General' },
  { text: 'rack', label: 'General' },
  { text: 'shelf', label: 'General' },
  { text: 'container', label: 'General' },
  { text: 'box', label: 'General' },
  { text: 'case', label: 'General' },
  { text: 'bag', label: 'General' },
  { text: 'pouch', label: 'General' },
  { text: 'wallet', label: 'General' },
  { text: 'purse', label: 'General' },
  { text: 'backpack', label: 'General' },
  { text: 'suitcase', label: 'General' },
  { text: 'luggage', label: 'General' },
  { text: 'travel gear', label: 'General' },
  { text: 'outdoor equipment', label: 'General' },
  { text: 'camping gear', label: 'General' },
  { text: 'sports equipment', label: 'General' },
  { text: 'fitness gear', label: 'General' },
  { text: 'exercise equipment', label: 'General' },
  { text: 'workout gear', label: 'General' },
  { text: 'athletic wear', label: 'General' },
  { text: 'sportswear', label: 'General' },
  { text: 'activewear', label: 'General' },
  { text: 'casual wear', label: 'General' },
  { text: 'formal wear', label: 'General' },
  { text: 'business attire', label: 'General' },
  { text: 'work clothes', label: 'General' },
  { text: 'uniform', label: 'General' },
  { text: 'costume', label: 'General' },
  { text: 'disguise', label: 'General' },
  { text: 'mask', label: 'General' },
  { text: 'hat', label: 'General' },
  { text: 'cap', label: 'General' },
  { text: 'helmet', label: 'General' },
  { text: 'headgear', label: 'General' },
  { text: 'eyewear', label: 'General' },
  { text: 'glasses', label: 'General' },
  { text: 'sunglasses', label: 'General' },
  { text: 'goggles', label: 'General' },
  { text: 'protective gear', label: 'General' },
  { text: 'safety equipment', label: 'General' },
  { text: 'security device', label: 'General' },
  { text: 'alarm system', label: 'General' },
  { text: 'monitoring device', label: 'General' },
  { text: 'surveillance equipment', label: 'General' },
  { text: 'communication device', label: 'General' },
  { text: 'navigation tool', label: 'General' },
  { text: 'measurement tool', label: 'General' },
  { text: 'testing equipment', label: 'General' },
  { text: 'diagnostic tool', label: 'General' },

  // Baby, Child & Toys (100+ items)
  { text: 'baby formula', label: 'Baby, Child & Toys' },
  { text: 'infant formula', label: 'Baby, Child & Toys' },
  { text: 'baby food', label: 'Baby, Child & Toys' },
  { text: 'baby cereal', label: 'Baby, Child & Toys' },
  { text: 'baby puree', label: 'Baby, Child & Toys' },
  { text: 'baby snacks', label: 'Baby, Child & Toys' },
  { text: 'teething biscuits', label: 'Baby, Child & Toys' },
  { text: 'baby bottle', label: 'Baby, Child & Toys' },
  { text: 'sippy cup', label: 'Baby, Child & Toys' },
  { text: 'baby spoon', label: 'Baby, Child & Toys' },
  { text: 'baby fork', label: 'Baby, Child & Toys' },
  { text: 'high chair', label: 'Baby, Child & Toys' },
  { text: 'booster seat', label: 'Baby, Child & Toys' },
  { text: 'baby bib', label: 'Baby, Child & Toys' },
  { text: 'burp cloth', label: 'Baby, Child & Toys' },
  { text: 'diapers', label: 'Baby, Child & Toys' },
  { text: 'nappies', label: 'Baby, Child & Toys' },
  { text: 'baby wipes', label: 'Baby, Child & Toys' },
  { text: 'diaper cream', label: 'Baby, Child & Toys' },
  { text: 'baby powder', label: 'Baby, Child & Toys' },
  { text: 'baby lotion', label: 'Baby, Child & Toys' },
  { text: 'baby shampoo', label: 'Baby, Child & Toys' },
  { text: 'baby soap', label: 'Baby, Child & Toys' },
  { text: 'baby oil', label: 'Baby, Child & Toys' },
  { text: 'pacifier', label: 'Baby, Child & Toys' },
  { text: 'dummy', label: 'Baby, Child & Toys' },
  { text: 'teether', label: 'Baby, Child & Toys' },
  { text: 'rattle', label: 'Baby, Child & Toys' },
  { text: 'baby toy', label: 'Baby, Child & Toys' },
  { text: 'stuffed animal', label: 'Baby, Child & Toys' },
  { text: 'plush toy', label: 'Baby, Child & Toys' },
  { text: 'teddy bear', label: 'Baby, Child & Toys' },
  { text: 'doll', label: 'Baby, Child & Toys' },
  { text: 'action figure', label: 'Baby, Child & Toys' },
  { text: 'toy car', label: 'Baby, Child & Toys' },
  { text: 'toy truck', label: 'Baby, Child & Toys' },
  { text: 'toy train', label: 'Baby, Child & Toys' },
  { text: 'toy plane', label: 'Baby, Child & Toys' },
  { text: 'building blocks', label: 'Baby, Child & Toys' },
  { text: 'lego', label: 'Baby, Child & Toys' },
  { text: 'puzzle', label: 'Baby, Child & Toys' },
  { text: 'board game', label: 'Baby, Child & Toys' },
  { text: 'card game', label: 'Baby, Child & Toys' },
  { text: 'educational toy', label: 'Baby, Child & Toys' },
  { text: 'learning toy', label: 'Baby, Child & Toys' },
  { text: 'musical toy', label: 'Baby, Child & Toys' },
  { text: 'toy piano', label: 'Baby, Child & Toys' },
  { text: 'toy guitar', label: 'Baby, Child & Toys' },
  { text: 'toy drum', label: 'Baby, Child & Toys' },
  { text: 'art supplies', label: 'Baby, Child & Toys' },
  { text: 'crayons', label: 'Baby, Child & Toys' },
  { text: 'colored pencils', label: 'Baby, Child & Toys' },
  { text: 'markers', label: 'Baby, Child & Toys' },
  { text: 'paint set', label: 'Baby, Child & Toys' },
  { text: 'coloring book', label: 'Baby, Child & Toys' },
  { text: 'sticker book', label: 'Baby, Child & Toys' },
  { text: 'activity book', label: 'Baby, Child & Toys' },
  { text: 'picture book', label: 'Baby, Child & Toys' },
  { text: 'story book', label: 'Baby, Child & Toys' },
  { text: 'children book', label: 'Baby, Child & Toys' },
  { text: 'baby book', label: 'Baby, Child & Toys' },
  { text: 'nursery rhyme book', label: 'Baby, Child & Toys' },
  { text: 'baby clothes', label: 'Baby, Child & Toys' },
  { text: 'baby onesie', label: 'Baby, Child & Toys' },
  { text: 'baby romper', label: 'Baby, Child & Toys' },
  { text: 'baby sleeper', label: 'Baby, Child & Toys' },
  { text: 'baby pajamas', label: 'Baby, Child & Toys' },
  { text: 'baby socks', label: 'Baby, Child & Toys' },
  { text: 'baby shoes', label: 'Baby, Child & Toys' },
  { text: 'baby hat', label: 'Baby, Child & Toys' },
  { text: 'baby mittens', label: 'Baby, Child & Toys' },
  { text: 'baby blanket', label: 'Baby, Child & Toys' },
  { text: 'swaddle', label: 'Baby, Child & Toys' },
  { text: 'baby towel', label: 'Baby, Child & Toys' },
  { text: 'baby washcloth', label: 'Baby, Child & Toys' },
  { text: 'baby carrier', label: 'Baby, Child & Toys' },
  { text: 'baby sling', label: 'Baby, Child & Toys' },
  { text: 'stroller', label: 'Baby, Child & Toys' },
  { text: 'pram', label: 'Baby, Child & Toys' },
  { text: 'car seat', label: 'Baby, Child & Toys' },
  { text: 'baby gate', label: 'Baby, Child & Toys' },
  { text: 'baby monitor', label: 'Baby, Child & Toys' },
  { text: 'night light', label: 'Baby, Child & Toys' },
  { text: 'mobile', label: 'Baby, Child & Toys' },
  { text: 'play mat', label: 'Baby, Child & Toys' },
  { text: 'activity mat', label: 'Baby, Child & Toys' },
  { text: 'bouncer', label: 'Baby, Child & Toys' },
  { text: 'swing', label: 'Baby, Child & Toys' },
  { text: 'walker', label: 'Baby, Child & Toys' },
  { text: 'jumper', label: 'Baby, Child & Toys' },
  { text: 'playpen', label: 'Baby, Child & Toys' },
  { text: 'crib', label: 'Baby, Child & Toys' },
  { text: 'bassinet', label: 'Baby, Child & Toys' },
  { text: 'changing pad', label: 'Baby, Child & Toys' },
  { text: 'diaper bag', label: 'Baby, Child & Toys' },
  { text: 'baby thermometer', label: 'Baby, Child & Toys' },
  { text: 'baby nail clippers', label: 'Baby, Child & Toys' },
  { text: 'baby brush', label: 'Baby, Child & Toys' },
  { text: 'baby comb', label: 'Baby, Child & Toys' },
  { text: 'baby toothbrush', label: 'Baby, Child & Toys' },
  { text: 'training pants', label: 'Baby, Child & Toys' },
  { text: 'potty', label: 'Baby, Child & Toys' },
  { text: 'toilet seat', label: 'Baby, Child & Toys' },
  { text: 'step stool', label: 'Baby, Child & Toys' },
  { text: 'child safety lock', label: 'Baby, Child & Toys' },
  { text: 'outlet cover', label: 'Baby, Child & Toys' },
  { text: 'corner guard', label: 'Baby, Child & Toys' },

  // Fruits & Vegetables (100+ items)
  { text: 'apple', label: 'Fruits & Vegetables' },
  { text: 'banana', label: 'Fruits & Vegetables' },
  { text: 'orange', label: 'Fruits & Vegetables' },
  { text: 'grape', label: 'Fruits & Vegetables' },
  { text: 'strawberry', label: 'Fruits & Vegetables' },
  { text: 'blueberry', label: 'Fruits & Vegetables' },
  { text: 'raspberry', label: 'Fruits & Vegetables' },
  { text: 'blackberry', label: 'Fruits & Vegetables' },
  { text: 'pineapple', label: 'Fruits & Vegetables' },
  { text: 'mango', label: 'Fruits & Vegetables' },
  { text: 'papaya', label: 'Fruits & Vegetables' },
  { text: 'kiwi', label: 'Fruits & Vegetables' },
  { text: 'watermelon', label: 'Fruits & Vegetables' },
  { text: 'cantaloupe', label: 'Fruits & Vegetables' },
  { text: 'honeydew', label: 'Fruits & Vegetables' },
  { text: 'peach', label: 'Fruits & Vegetables' },
  { text: 'pear', label: 'Fruits & Vegetables' },
  { text: 'plum', label: 'Fruits & Vegetables' },
  { text: 'cherry', label: 'Fruits & Vegetables' },
  { text: 'apricot', label: 'Fruits & Vegetables' },
  { text: 'lemon', label: 'Fruits & Vegetables' },
  { text: 'lime', label: 'Fruits & Vegetables' },
  { text: 'grapefruit', label: 'Fruits & Vegetables' },
  { text: 'avocado', label: 'Fruits & Vegetables' },
  { text: 'coconut', label: 'Fruits & Vegetables' },
  { text: 'durian', label: 'Fruits & Vegetables' },
  { text: 'jackfruit', label: 'Fruits & Vegetables' },
  { text: 'rambutan', label: 'Fruits & Vegetables' },
  { text: 'lychee', label: 'Fruits & Vegetables' },
  { text: 'longan', label: 'Fruits & Vegetables' },
  { text: 'dragon fruit', label: 'Fruits & Vegetables' },
  { text: 'passion fruit', label: 'Fruits & Vegetables' },
  { text: 'guava', label: 'Fruits & Vegetables' },
  { text: 'starfruit', label: 'Fruits & Vegetables' },
  { text: 'pomegranate', label: 'Fruits & Vegetables' },
  { text: 'fig', label: 'Fruits & Vegetables' },
  { text: 'date', label: 'Fruits & Vegetables' },
  { text: 'persimmon', label: 'Fruits & Vegetables' },
  { text: 'tomato', label: 'Fruits & Vegetables' },
  { text: 'cucumber', label: 'Fruits & Vegetables' },
  { text: 'carrot', label: 'Fruits & Vegetables' },
  { text: 'potato', label: 'Fruits & Vegetables' },
  { text: 'sweet potato', label: 'Fruits & Vegetables' },
  { text: 'onion', label: 'Fruits & Vegetables' },
  { text: 'garlic', label: 'Fruits & Vegetables' },
  { text: 'ginger', label: 'Fruits & Vegetables' },
  { text: 'lettuce', label: 'Fruits & Vegetables' },
  { text: 'spinach', label: 'Fruits & Vegetables' },
  { text: 'kale', label: 'Fruits & Vegetables' },
  { text: 'cabbage', label: 'Fruits & Vegetables' },
  { text: 'broccoli', label: 'Fruits & Vegetables' },
  { text: 'cauliflower', label: 'Fruits & Vegetables' },
  { text: 'bell pepper', label: 'Fruits & Vegetables' },
  { text: 'chili pepper', label: 'Fruits & Vegetables' },
  { text: 'eggplant', label: 'Fruits & Vegetables' },
  { text: 'zucchini', label: 'Fruits & Vegetables' },
  { text: 'squash', label: 'Fruits & Vegetables' },
  { text: 'pumpkin', label: 'Fruits & Vegetables' },
  { text: 'corn', label: 'Fruits & Vegetables' },
  { text: 'green beans', label: 'Fruits & Vegetables' },
  { text: 'peas', label: 'Fruits & Vegetables' },
  { text: 'asparagus', label: 'Fruits & Vegetables' },
  { text: 'celery', label: 'Fruits & Vegetables' },
  { text: 'radish', label: 'Fruits & Vegetables' },
  { text: 'beetroot', label: 'Fruits & Vegetables' },
  { text: 'turnip', label: 'Fruits & Vegetables' },
  { text: 'parsnip', label: 'Fruits & Vegetables' },
  { text: 'leek', label: 'Fruits & Vegetables' },
  { text: 'scallion', label: 'Fruits & Vegetables' },
  { text: 'spring onion', label: 'Fruits & Vegetables' },
  { text: 'shallot', label: 'Fruits & Vegetables' },
  { text: 'mushroom', label: 'Fruits & Vegetables' },
  { text: 'shiitake', label: 'Fruits & Vegetables' },
  { text: 'oyster mushroom', label: 'Fruits & Vegetables' },
  { text: 'button mushroom', label: 'Fruits & Vegetables' },
  { text: 'enoki mushroom', label: 'Fruits & Vegetables' },
  { text: 'bok choy', label: 'Fruits & Vegetables' },
  { text: 'pak choy', label: 'Fruits & Vegetables' },
  { text: 'chinese cabbage', label: 'Fruits & Vegetables' },
  { text: 'napa cabbage', label: 'Fruits & Vegetables' },
  { text: 'watercress', label: 'Fruits & Vegetables' },
  { text: 'kangkung', label: 'Fruits & Vegetables' },
  { text: 'water spinach', label: 'Fruits & Vegetables' },
  { text: 'bean sprouts', label: 'Fruits & Vegetables' },
  { text: 'alfalfa sprouts', label: 'Fruits & Vegetables' },
  { text: 'bamboo shoots', label: 'Fruits & Vegetables' },
  { text: 'lotus root', label: 'Fruits & Vegetables' },
  { text: 'taro', label: 'Fruits & Vegetables' },
  { text: 'yam', label: 'Fruits & Vegetables' },
  { text: 'cassava', label: 'Fruits & Vegetables' },
  { text: 'okra', label: 'Fruits & Vegetables' },
  { text: 'bitter gourd', label: 'Fruits & Vegetables' },
  { text: 'winter melon', label: 'Fruits & Vegetables' },
  { text: 'bottle gourd', label: 'Fruits & Vegetables' },
  { text: 'ridge gourd', label: 'Fruits & Vegetables' },
  { text: 'snake gourd', label: 'Fruits & Vegetables' },
  { text: 'long beans', label: 'Fruits & Vegetables' },
  { text: 'yard long beans', label: 'Fruits & Vegetables' },
  { text: 'french beans', label: 'Fruits & Vegetables' },
  { text: 'snow peas', label: 'Fruits & Vegetables' },
  { text: 'sugar snap peas', label: 'Fruits & Vegetables' },
  { text: 'edamame', label: 'Fruits & Vegetables' },
  { text: 'artichoke', label: 'Fruits & Vegetables' },
  { text: 'fennel', label: 'Fruits & Vegetables' },
  { text: 'endive', label: 'Fruits & Vegetables' },
  { text: 'arugula', label: 'Fruits & Vegetables' },
  { text: 'rocket', label: 'Fruits & Vegetables' },
  { text: 'swiss chard', label: 'Fruits & Vegetables' },
  { text: 'collard greens', label: 'Fruits & Vegetables' },
  { text: 'mustard greens', label: 'Fruits & Vegetables' },
  { text: 'turnip greens', label: 'Fruits & Vegetables' },
  { text: 'beet greens', label: 'Fruits & Vegetables' },

  // Dairy, Chilled & Eggs (100+ items)
  { text: 'milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'whole milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'skim milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'low fat milk', label: 'Dairy, Chilled & Eggs' },
  { text: '2% milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'organic milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'fresh milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'uht milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'lactose free milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'almond milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'soy milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'oat milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'coconut milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'rice milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'cashew milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'hemp milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'pea milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'goat milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'sheep milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'buffalo milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'condensed milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'evaporated milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'powdered milk', label: 'Dairy, Chilled & Eggs' },
  { text: 'buttermilk', label: 'Dairy, Chilled & Eggs' },
  { text: 'heavy cream', label: 'Dairy, Chilled & Eggs' },
  { text: 'whipping cream', label: 'Dairy, Chilled & Eggs' },
  { text: 'light cream', label: 'Dairy, Chilled & Eggs' },
  { text: 'half and half', label: 'Dairy, Chilled & Eggs' },
  { text: 'sour cream', label: 'Dairy, Chilled & Eggs' },
  { text: 'crème fraîche', label: 'Dairy, Chilled & Eggs' },
  { text: 'double cream', label: 'Dairy, Chilled & Eggs' },
  { text: 'single cream', label: 'Dairy, Chilled & Eggs' },
  { text: 'clotted cream', label: 'Dairy, Chilled & Eggs' },
  { text: 'butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'salted butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'unsalted butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'organic butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'grass fed butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'cultured butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'clarified butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'ghee', label: 'Dairy, Chilled & Eggs' },
  { text: 'margarine', label: 'Dairy, Chilled & Eggs' },
  { text: 'vegan butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'plant butter', label: 'Dairy, Chilled & Eggs' },
  { text: 'cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'cheddar cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'mozzarella cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'parmesan cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'swiss cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'gouda cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'brie cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'camembert cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'blue cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'feta cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'goat cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'cream cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'cottage cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'ricotta cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'mascarpone cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'string cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'processed cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'cheese slices', label: 'Dairy, Chilled & Eggs' },
  { text: 'shredded cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'grated cheese', label: 'Dairy, Chilled & Eggs' },
  { text: 'cheese spread', label: 'Dairy, Chilled & Eggs' },
  { text: 'yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'greek yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'plain yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'vanilla yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'strawberry yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'blueberry yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'peach yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'mixed berry yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'low fat yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'fat free yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'organic yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'probiotic yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'drinking yogurt', label: 'Dairy, Chilled & Eggs' },
  { text: 'yogurt drink', label: 'Dairy, Chilled & Eggs' },
  { text: 'kefir', label: 'Dairy, Chilled & Eggs' },
  { text: 'lassi', label: 'Dairy, Chilled & Eggs' },
  { text: 'eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'chicken eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'large eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'medium eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'small eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'extra large eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'jumbo eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'brown eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'white eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'free range eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'cage free eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'organic eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'pasture raised eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'omega 3 eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'duck eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'quail eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'goose eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'egg whites', label: 'Dairy, Chilled & Eggs' },
  { text: 'liquid eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'egg substitute', label: 'Dairy, Chilled & Eggs' },
  { text: 'powdered eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'pickled eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'century eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'salted eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'tea eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'scotch eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'deviled eggs', label: 'Dairy, Chilled & Eggs' },
  { text: 'egg salad', label: 'Dairy, Chilled & Eggs' },
  { text: 'custard', label: 'Dairy, Chilled & Eggs' },
  { text: 'pudding', label: 'Dairy, Chilled & Eggs' },
  { text: 'flan', label: 'Dairy, Chilled & Eggs' },
  { text: 'crème brûlée', label: 'Dairy, Chilled & Eggs' },
  { text: 'panna cotta', label: 'Dairy, Chilled & Eggs' },
  { text: 'mousse', label: 'Dairy, Chilled & Eggs' },
  { text: 'tiramisu', label: 'Dairy, Chilled & Eggs' },
  { text: 'cheesecake', label: 'Dairy, Chilled & Eggs' },

  // Meat & Seafood (100+ items)
  { text: 'beef', label: 'Meat & Seafood' },
  { text: 'ground beef', label: 'Meat & Seafood' },
  { text: 'beef steak', label: 'Meat & Seafood' },
  { text: 'ribeye steak', label: 'Meat & Seafood' },
  { text: 'sirloin steak', label: 'Meat & Seafood' },
  { text: 'filet mignon', label: 'Meat & Seafood' },
  { text: 'beef tenderloin', label: 'Meat & Seafood' },
  { text: 'beef brisket', label: 'Meat & Seafood' },
  { text: 'beef ribs', label: 'Meat & Seafood' },
  { text: 'beef short ribs', label: 'Meat & Seafood' },
  { text: 'beef chuck roast', label: 'Meat & Seafood' },
  { text: 'beef round roast', label: 'Meat & Seafood' },
  { text: 'beef rump roast', label: 'Meat & Seafood' },
  { text: 'beef eye round', label: 'Meat & Seafood' },
  { text: 'beef top round', label: 'Meat & Seafood' },
  { text: 'beef bottom round', label: 'Meat & Seafood' },
  { text: 'beef flank steak', label: 'Meat & Seafood' },
  { text: 'beef skirt steak', label: 'Meat & Seafood' },
  { text: 'beef hanger steak', label: 'Meat & Seafood' },
  { text: 'beef tri tip', label: 'Meat & Seafood' },
  { text: 'beef strip steak', label: 'Meat & Seafood' },
  { text: 'beef t-bone steak', label: 'Meat & Seafood' },
  { text: 'beef porterhouse', label: 'Meat & Seafood' },
  { text: 'beef cube steak', label: 'Meat & Seafood' },
  { text: 'beef stew meat', label: 'Meat & Seafood' },
  { text: 'beef liver', label: 'Meat & Seafood' },
  { text: 'beef kidney', label: 'Meat & Seafood' },
  { text: 'beef heart', label: 'Meat & Seafood' },
  { text: 'beef tongue', label: 'Meat & Seafood' },
  { text: 'beef oxtail', label: 'Meat & Seafood' },
  { text: 'beef marrow bones', label: 'Meat & Seafood' },
  { text: 'pork', label: 'Meat & Seafood' },
  { text: 'ground pork', label: 'Meat & Seafood' },
  { text: 'pork chops', label: 'Meat & Seafood' },
  { text: 'pork tenderloin', label: 'Meat & Seafood' },
  { text: 'pork loin', label: 'Meat & Seafood' },
  { text: 'pork shoulder', label: 'Meat & Seafood' },
  { text: 'pork butt', label: 'Meat & Seafood' },
  { text: 'pork ribs', label: 'Meat & Seafood' },
  { text: 'pork spare ribs', label: 'Meat & Seafood' },
  { text: 'pork baby back ribs', label: 'Meat & Seafood' },
  { text: 'pork belly', label: 'Meat & Seafood' },
  { text: 'pork hock', label: 'Meat & Seafood' },
  { text: 'pork shank', label: 'Meat & Seafood' },
  { text: 'pork leg', label: 'Meat & Seafood' },
  { text: 'pork ham', label: 'Meat & Seafood' },
  { text: 'pork bacon', label: 'Meat & Seafood' },
  { text: 'pork sausage', label: 'Meat & Seafood' },
  { text: 'pork chorizo', label: 'Meat & Seafood' },
  { text: 'pork bratwurst', label: 'Meat & Seafood' },
  { text: 'pork kielbasa', label: 'Meat & Seafood' },
  { text: 'pork hot dogs', label: 'Meat & Seafood' },
  { text: 'pork frankfurters', label: 'Meat & Seafood' },
  { text: 'pork salami', label: 'Meat & Seafood' },
  { text: 'pork pepperoni', label: 'Meat & Seafood' },
  { text: 'pork prosciutto', label: 'Meat & Seafood' },
  { text: 'pork pancetta', label: 'Meat & Seafood' },
  { text: 'pork guanciale', label: 'Meat & Seafood' },
  { text: 'chicken', label: 'Meat & Seafood' },
  { text: 'whole chicken', label: 'Meat & Seafood' },
  { text: 'chicken breast', label: 'Meat & Seafood' },
  { text: 'chicken thighs', label: 'Meat & Seafood' },
  { text: 'chicken drumsticks', label: 'Meat & Seafood' },
  { text: 'chicken wings', label: 'Meat & Seafood' },
  { text: 'chicken legs', label: 'Meat & Seafood' },
  { text: 'chicken quarters', label: 'Meat & Seafood' },
  { text: 'chicken tenders', label: 'Meat & Seafood' },
  { text: 'chicken cutlets', label: 'Meat & Seafood' },
  { text: 'ground chicken', label: 'Meat & Seafood' },
  { text: 'chicken sausage', label: 'Meat & Seafood' },
  { text: 'chicken liver', label: 'Meat & Seafood' },
  { text: 'chicken gizzards', label: 'Meat & Seafood' },
  { text: 'chicken hearts', label: 'Meat & Seafood' },
  { text: 'chicken feet', label: 'Meat & Seafood' },
  { text: 'chicken neck', label: 'Meat & Seafood' },
  { text: 'turkey', label: 'Meat & Seafood' },
  { text: 'whole turkey', label: 'Meat & Seafood' },
  { text: 'turkey breast', label: 'Meat & Seafood' },
  { text: 'turkey thighs', label: 'Meat & Seafood' },
  { text: 'turkey drumsticks', label: 'Meat & Seafood' },
  { text: 'turkey wings', label: 'Meat & Seafood' },
  { text: 'ground turkey', label: 'Meat & Seafood' },
  { text: 'turkey sausage', label: 'Meat & Seafood' },
  { text: 'turkey bacon', label: 'Meat & Seafood' },
  { text: 'turkey deli meat', label: 'Meat & Seafood' },
  { text: 'duck', label: 'Meat & Seafood' },
  { text: 'whole duck', label: 'Meat & Seafood' },
  { text: 'duck breast', label: 'Meat & Seafood' },
  { text: 'duck legs', label: 'Meat & Seafood' },
  { text: 'duck confit', label: 'Meat & Seafood' },
  { text: 'lamb', label: 'Meat & Seafood' },
  { text: 'lamb chops', label: 'Meat & Seafood' },
  { text: 'lamb leg', label: 'Meat & Seafood' },
  { text: 'lamb shoulder', label: 'Meat & Seafood' },
  { text: 'lamb rack', label: 'Meat & Seafood' },
  { text: 'lamb shank', label: 'Meat & Seafood' },
  { text: 'ground lamb', label: 'Meat & Seafood' },
  { text: 'fish', label: 'Meat & Seafood' },
  { text: 'salmon', label: 'Meat & Seafood' },
  { text: 'tuna', label: 'Meat & Seafood' },
  { text: 'cod', label: 'Meat & Seafood' },
  { text: 'halibut', label: 'Meat & Seafood' },
  { text: 'mahi mahi', label: 'Meat & Seafood' },
  { text: 'sea bass', label: 'Meat & Seafood' },
  { text: 'red snapper', label: 'Meat & Seafood' },
  { text: 'grouper', label: 'Meat & Seafood' },
  { text: 'flounder', label: 'Meat & Seafood' },
  { text: 'sole', label: 'Meat & Seafood' },
  { text: 'tilapia', label: 'Meat & Seafood' },
  { text: 'catfish', label: 'Meat & Seafood' },
  { text: 'trout', label: 'Meat & Seafood' },
  { text: 'mackerel', label: 'Meat & Seafood' },
  { text: 'sardines', label: 'Meat & Seafood' },
  { text: 'anchovies', label: 'Meat & Seafood' },
  { text: 'herring', label: 'Meat & Seafood' },
  { text: 'swordfish', label: 'Meat & Seafood' },
  { text: 'shark', label: 'Meat & Seafood' },
  { text: 'eel', label: 'Meat & Seafood' },
  { text: 'shellfish', label: 'Meat & Seafood' },
  { text: 'shrimp', label: 'Meat & Seafood' },
  { text: 'prawns', label: 'Meat & Seafood' },
  { text: 'lobster', label: 'Meat & Seafood' },
  { text: 'crab', label: 'Meat & Seafood' },
  { text: 'crab legs', label: 'Meat & Seafood' },
  { text: 'crab meat', label: 'Meat & Seafood' },
  { text: 'scallops', label: 'Meat & Seafood' },
  { text: 'oysters', label: 'Meat & Seafood' },
  { text: 'mussels', label: 'Meat & Seafood' },
  { text: 'clams', label: 'Meat & Seafood' },
  { text: 'squid', label: 'Meat & Seafood' },
  { text: 'octopus', label: 'Meat & Seafood' },
  { text: 'cuttlefish', label: 'Meat & Seafood' },
  { text: 'sea urchin', label: 'Meat & Seafood' },
  { text: 'abalone', label: 'Meat & Seafood' },
  { text: 'conch', label: 'Meat & Seafood' },
  { text: 'whelk', label: 'Meat & Seafood' },
  { text: 'sea cucumber', label: 'Meat & Seafood' },
  { text: 'fish fillet', label: 'Meat & Seafood' },
  { text: 'fish steak', label: 'Meat & Seafood' },
  { text: 'whole fish', label: 'Meat & Seafood' },
  { text: 'fish head', label: 'Meat & Seafood' },
  { text: 'fish bones', label: 'Meat & Seafood' },
  { text: 'fish stock', label: 'Meat & Seafood' },
  { text: 'smoked salmon', label: 'Meat & Seafood' },
  { text: 'smoked trout', label: 'Meat & Seafood' },
  { text: 'smoked mackerel', label: 'Meat & Seafood' },
  { text: 'canned tuna', label: 'Meat & Seafood' },
  { text: 'canned salmon', label: 'Meat & Seafood' },
  { text: 'canned sardines', label: 'Meat & Seafood' },
  { text: 'canned crab', label: 'Meat & Seafood' },
  { text: 'imitation crab', label: 'Meat & Seafood' },
  { text: 'surimi', label: 'Meat & Seafood' },
  { text: 'fish cake', label: 'Meat & Seafood' },
  { text: 'fish ball', label: 'Meat & Seafood' },
  { text: 'fish paste', label: 'Meat & Seafood' },
  { text: 'fish sauce', label: 'Meat & Seafood' },
  { text: 'oyster sauce', label: 'Meat & Seafood' },
  { text: 'shrimp paste', label: 'Meat & Seafood' },
  { text: 'dried shrimp', label: 'Meat & Seafood' },
  { text: 'dried squid', label: 'Meat & Seafood' },
  { text: 'dried fish', label: 'Meat & Seafood' },
  { text: 'salted fish', label: 'Meat & Seafood' },
  { text: 'pickled fish', label: 'Meat & Seafood' },
  { text: 'caviar', label: 'Meat & Seafood' },
  { text: 'roe', label: 'Meat & Seafood' },
  { text: 'fish roe', label: 'Meat & Seafood' },
  { text: 'salmon roe', label: 'Meat & Seafood' },
  { text: 'tobiko', label: 'Meat & Seafood' },
  { text: 'ikura', label: 'Meat & Seafood' },
  { text: 'uni', label: 'Meat & Seafood' },
  { text: 'sashimi', label: 'Meat & Seafood' },
  { text: 'sushi grade fish', label: 'Meat & Seafood' },

  // Bakery & Fast Food (100+ items)
  { text: 'bread', label: 'Bakery & Fast Food' },
  { text: 'white bread', label: 'Bakery & Fast Food' },
  { text: 'whole wheat bread', label: 'Bakery & Fast Food' },
  { text: 'multigrain bread', label: 'Bakery & Fast Food' },
  { text: 'sourdough bread', label: 'Bakery & Fast Food' },
  { text: 'rye bread', label: 'Bakery & Fast Food' },
  { text: 'pumpernickel bread', label: 'Bakery & Fast Food' },
  { text: 'french bread', label: 'Bakery & Fast Food' },
  { text: 'baguette', label: 'Bakery & Fast Food' },
  { text: 'ciabatta', label: 'Bakery & Fast Food' },
  { text: 'focaccia', label: 'Bakery & Fast Food' },
  { text: 'pita bread', label: 'Bakery & Fast Food' },
  { text: 'naan bread', label: 'Bakery & Fast Food' },
  { text: 'flatbread', label: 'Bakery & Fast Food' },
  { text: 'tortilla', label: 'Bakery & Fast Food' },
  { text: 'wrap', label: 'Bakery & Fast Food' },
  { text: 'bagel', label: 'Bakery & Fast Food' },
  { text: 'english muffin', label: 'Bakery & Fast Food' },
  { text: 'croissant', label: 'Bakery & Fast Food' },
  { text: 'danish pastry', label: 'Bakery & Fast Food' },
  { text: 'muffin', label: 'Bakery & Fast Food' },
  { text: 'cupcake', label: 'Bakery & Fast Food' },
  { text: 'donut', label: 'Bakery & Fast Food' },
  { text: 'doughnut', label: 'Bakery & Fast Food' },
  { text: 'cake', label: 'Bakery & Fast Food' },
  { text: 'birthday cake', label: 'Bakery & Fast Food' },
  { text: 'wedding cake', label: 'Bakery & Fast Food' },
  { text: 'chocolate cake', label: 'Bakery & Fast Food' },
  { text: 'vanilla cake', label: 'Bakery & Fast Food' },
  { text: 'strawberry cake', label: 'Bakery & Fast Food' },
  { text: 'carrot cake', label: 'Bakery & Fast Food' },
  { text: 'red velvet cake', label: 'Bakery & Fast Food' },
  { text: 'cheesecake', label: 'Bakery & Fast Food' },
  { text: 'pound cake', label: 'Bakery & Fast Food' },
  { text: 'sponge cake', label: 'Bakery & Fast Food' },
  { text: 'angel food cake', label: 'Bakery & Fast Food' },
  { text: 'devil food cake', label: 'Bakery & Fast Food' },
  { text: 'bundt cake', label: 'Bakery & Fast Food' },
  { text: 'layer cake', label: 'Bakery & Fast Food' },
  { text: 'sheet cake', label: 'Bakery & Fast Food' },
  { text: 'coffee cake', label: 'Bakery & Fast Food' },
  { text: 'fruitcake', label: 'Bakery & Fast Food' },
  { text: 'upside down cake', label: 'Bakery & Fast Food' },
  { text: 'pie', label: 'Bakery & Fast Food' },
  { text: 'apple pie', label: 'Bakery & Fast Food' },
  { text: 'cherry pie', label: 'Bakery & Fast Food' },
  { text: 'blueberry pie', label: 'Bakery & Fast Food' },
  { text: 'pumpkin pie', label: 'Bakery & Fast Food' },
  { text: 'pecan pie', label: 'Bakery & Fast Food' },
  { text: 'lemon meringue pie', label: 'Bakery & Fast Food' },
  { text: 'key lime pie', label: 'Bakery & Fast Food' },
  { text: 'coconut cream pie', label: 'Bakery & Fast Food' },
  { text: 'banana cream pie', label: 'Bakery & Fast Food' },
  { text: 'chocolate cream pie', label: 'Bakery & Fast Food' },
  { text: 'custard pie', label: 'Bakery & Fast Food' },
  { text: 'meat pie', label: 'Bakery & Fast Food' },
  { text: 'chicken pie', label: 'Bakery & Fast Food' },
  { text: 'beef pie', label: 'Bakery & Fast Food' },
  { text: 'shepherd pie', label: 'Bakery & Fast Food' },
  { text: 'pot pie', label: 'Bakery & Fast Food' },
  { text: 'quiche', label: 'Bakery & Fast Food' },
  { text: 'tart', label: 'Bakery & Fast Food' },
  { text: 'fruit tart', label: 'Bakery & Fast Food' },
  { text: 'custard tart', label: 'Bakery & Fast Food' },
  { text: 'egg tart', label: 'Bakery & Fast Food' },
  { text: 'lemon tart', label: 'Bakery & Fast Food' },
  { text: 'chocolate tart', label: 'Bakery &